ESPResSo: cells.hpp File Reference
cells.hpp File Reference
#include "Cell.hpp"
#include "CellStructure.hpp"
#include "DomainDecomposition.hpp"
#include "Particle.hpp"
#include <utility>
#include <vector>
Classes
class PairInfo
Enumerations
enum { CELL_NEIGHBOR_EXCHANGE = 0, CELL_GLOBAL_EXCHANGE = 1 }
Flags for particle exchange and resorting: whether to do a global exchange or assume that particles did not move much (faster, used during integration, where moving far is a catastrophe anyways).
Functions
void cells_re_init (int new_cs)
Reinitialize the cell structures.
void mpi_bcast_cell_structure (int cs)
Change the cell structure on all nodes.
void mpi_set_use_verlet_lists (bool use_verlet_lists)
Set cell_structure::use_verlet_list.
void cells_update_ghosts (unsigned data_parts)
Update ghost information.
std::vector< std::pair< int, int > > mpi_get_pairs (double distance)
Get pairs closer than distance from the cells.
std::vector< std::pair< int, int > > mpi_get_pairs_of_types (double distance, std::vector< int > const &types)
Get pairs closer than distance if both their types are in types.
void check_resort_particles ()
Check if a particle resorting is required.
std::vector< int > mpi_resort_particles (int global_flag)
Resort the particles.
Cell * find_current_cell (const Particle &p)
Find the cell in which a particle is stored.
const DomainDecomposition * get_domain_decomposition ()
Return a pointer to the global DomainDecomposition.
std::vector< PairInfo > mpi_non_bonded_loop_trace ()
Returns pairs of particle ids, positions and distance as seen by the non-bonded loop.
Variables
CellStructure cell_structure
Type of cell structure in use.
Detailed Description
This file contains everything related to the global cell structure / cell system.
The cell system (CellStructure) describes how particles are distributed on the cells and how particles of different cells (regardless if they reside on the same or different nodes) interact with each other. The following cell systems are implemented:
domain decomposition: The simulation box is divided spatially into cells (see DomainDecomposition.hpp). This is suitable for short range interactions.
nsquare: The particles are distributed equally on all nodes regardless their spatial position (see AtomDecomposition.hpp). This is suitable for long range interactions that cannot be treated by a special method like P3M.
Definition in file cells.hpp.
Enumeration Type Documentation
anonymous enum
anonymous enum
Flags for particle exchange and resorting: whether to do a global exchange or assume that particles did not move much (faster, used during integration, where moving far is a catastrophe anyways).
Enumerator
CELL_NEIGHBOR_EXCHANGE
Do neighbor exchange.
CELL_GLOBAL_EXCHANGE
Do global exchange.
Definition at line 53 of file cells.hpp.
Function Documentation
cells_re_init()
void cells_re_init (int new_cs)
Reinitialize the cell structures.
Parameters
new_cs The new topology to use afterwards.
Definition at line 209 of file cells.cpp.
References box_geo, cell_structure, CELL_STRUCTURE_DOMDEC, CELL_STRUCTURE_NSQUARE, comm_cart, interaction_range(), local_geo, on_cell_structure_change(), CellStructure::set_atom_decomposition(), and CellStructure::set_domain_decomposition().
Referenced by mpi_bcast_cell_structure(), on_boxl_change(), on_nodegrid_change(), on_program_start(), on_short_range_ia_change(), and on_skin_change().
cells_update_ghosts()
void cells_update_ghosts (unsigned data_parts)
Update ghost information.
If needed, the particles are also resorted.
Definition at line 243 of file cells.cpp.
References CELL_GLOBAL_EXCHANGE, CELL_NEIGHBOR_EXCHANGE, cell_structure, CellStructure::clear_resort_particles(), comm_cart, Cells::DATA_PART_BONDS, Cells::DATA_PART_PROPERTIES, CellStructure::get_local_particle(), CellStructure::get_resort_particles(), CellStructure::ghost_particles(), CellStructure::ghosts_count(), CellStructure::ghosts_update(), Cells::RESORT_GLOBAL, Cells::RESORT_NONE, CellStructure::resort_particles(), and CellStructure::update_particle_index().
Referenced by correct_position_shake(), handle_collisions(), integrate(), on_observable_calc(), and update_dependent_particles().
check_resort_particles()
void check_resort_particles ()
Check if a particle resorting is required.
Definition at line 229 of file cells.cpp.
References cell_structure, CellStructure::local_particles(), Cells::RESORT_LOCAL, Cells::RESORT_NONE, CellStructure::set_resort_particles(), skin, and Utils::sqr().
Referenced by correct_position_shake().
find_current_cell()
Cell* find_current_cell (const Particle & p)
Find the cell in which a particle is stored.
Uses position_to_cell on p.r.p. If this is not on the node's domain, uses position at last Verlet list rebuild (p.l.p_old).
Returns
pointer to the cell or nullptr if the particle is not on the node
Definition at line 278 of file cells.cpp.
References cell_structure, and CellStructure::find_current_cell().
Referenced by three_particle_binding_domain_decomposition().
get_domain_decomposition()
const DomainDecomposition* get_domain_decomposition ()
Return a pointer to the global DomainDecomposition.
Returns
Pointer to the decomposition if it is set, nullptr otherwise.
Definition at line 282 of file cells.cpp.
References Utils::as_const(), and cell_structure.
mpi_bcast_cell_structure()
void mpi_bcast_cell_structure (int cs)
Change the cell structure on all nodes.
Definition at line 227 of file cells.cpp.
References cells_re_init(), and mpi_call_all().
mpi_get_pairs()
std::vector<std::pair<int, int> > mpi_get_pairs (double distance)
Get pairs closer than distance from the cells.
Pairs are sorted so that first.id < second.id
Definition at line 155 of file cells.cpp.
mpi_get_pairs_of_types()
std::vector<std::pair<int, int> > mpi_get_pairs_of_types (double distance, std::vector< int > const & types)
Get pairs closer than distance if both their types are in types.
Pairs are sorted so that first.id < second.id
Definition at line 164 of file cells.cpp.
mpi_non_bonded_loop_trace()
std::vector<PairInfo> mpi_non_bonded_loop_trace ()
Returns pairs of particle ids, positions and distance as seen by the non-bonded loop.
Definition at line 179 of file cells.cpp.
References comm_cart, Utils::Mpi::gather_buffer(), mpi_call(), non_bonded_loop_trace(), and non_bonded_loop_trace_local().
mpi_resort_particles()
std::vector<int> mpi_resort_particles (int global_flag)
Resort the particles.
This function resorts the particles on the nodes.
Parameters
global_flag If true a global resort is done, if false particles are only exchanges between neighbors.
Returns
The number of particles on the nodes after the resort.
Definition at line 195 of file cells.cpp.
References cell_structure, clear_particle_node(), comm_cart, CellStructure::local_particles(), mpi_call(), mpi_resort_particles_local(), CellStructure::resort_particles(), and ParticleRange::size().
mpi_set_use_verlet_lists()
void mpi_set_use_verlet_lists (bool use_verlet_lists)
Set cell_structure::use_verlet_list.
Parameters
use_verlet_lists Should Verlet lists be used?
Definition at line 293 of file cells.cpp.
References mpi_call_all(), and mpi_set_use_verlet_lists_local().
Variable Documentation
cell_structure
CellStructure cell_structure
Type of cell structure in use.
Definition at line 52 of file cells.cpp.
Referenced by VirtualSitesRelative::back_transfer_forces_and_torques(), bind_at_poc_create_bond_between_vs(), brownian_dynamics_propagator(), calc_mu_max(), calculate_energy_local(), calculate_pressure_local(), cells_re_init(), cells_update_ghosts(), check_resort_particles(), correct_position_shake(), correct_velocity_shake(), ScriptInterface::MPIIO::MPIIOScript::do_call_method(), ScriptInterface::Constraints::ShapeBasedConstraint::do_call_method(), dp3m_count_magnetic_particles(), dp3m_sanity_checks(), dpd_viscous_stress_local(), find_current_cell(), force_calc(), force_calc_icc(), EspressoSystemInterface::gatherParticles(), get_domain_decomposition(), get_pairs_filtered(), anonymous_namespace{collision.cpp}::get_part(), get_particle_data(), get_particle_data_local(), anonymous_namespace{VirtualSitesRelative.cpp}::get_reference_particle(), handle_collisions(), IBM_ForcesIntoFluid_CPU(), IBM_UpdateParticlePositions(), icc_iteration(), init_forces(), integrate(), lb_sanity_checks(), local_change_exclusion(), local_galilei_transform(), local_particle_momentum(), local_place_particle(), local_rescale_particles(), local_rotate_system(), local_system_CMS(), local_system_CMS_velocity(), MMM1D_sanity_checks(), mpi_kill_particle_forces_local(), mpi_kill_particle_motion_local(), Mpiio::mpi_mpiio_common_read(), mpi_place_particle(), mpi_place_particle_local(), mpi_remove_particle_local(), mpi_resort_particles(), mpi_resort_particles_local(), mpi_rotate_system(), mpi_rotate_system_local(), mpi_set_use_verlet_lists_local(), mpi_who_has(), mpi_who_has_local(), non_bonded_loop_trace(), on_boxl_change(), on_integration_start(), on_nodegrid_change(), on_particle_change(), on_short_range_ia_change(), on_skin_change(), p3m_count_charged_particles(), p3m_sanity_checks_system(), ParticleVelocitiesFromLB_CPU(), place_vs_and_relate_to_particle(), VirtualSitesRelative::pressure_tensor(), python_integrate(), steepest_descent_step(), stokesian_dynamics_propagate_vel_pos(), three_particle_binding_domain_decomposition(), tune_skin(), VirtualSitesRelative::update(), update_dependent_particles(), Scafacos::ScafacosContextCoulomb::update_particle_data(), Scafacos::ScafacosContextDipoles::update_particle_data(), Scafacos::ScafacosContextCoulomb::update_particle_forces(), Scafacos::ScafacosContextDipoles::update_particle_forces(), Scafacos::ScafacosContext::update_system_params(), velocity_verlet_npt_propagate_pos(), and velocity_verlet_propagate_vel_pos().