ESPResSo: EspressoSystemInterface Class Reference
EspressoSystemInterface Class Reference
#include <EspressoSystemInterface.hpp>
Public Member Functions
void init () override
void update () override
float * rGpuBegin () override
float * rGpuEnd () override
bool hasRGpu () override
bool requestRGpu () override
float * dipGpuBegin () override
float * dipGpuEnd () override
bool hasDipGpu () override
bool requestDipGpu () override
float * vGpuBegin () override
float * vGpuEnd () override
bool hasVGpu () override
bool requestVGpu () override
float * qGpuBegin () override
float * qGpuEnd () override
bool hasQGpu () override
bool requestQGpu () override
float * directorGpuBegin () override
float * directorGpuEnd () override
bool hasDirectorGpu () override
bool requestDirectorGpu () override
bool requestParticleStructGpu ()
float * fGpuBegin () override
float * fGpuEnd () override
float * eGpu () override
float * torqueGpuBegin () override
float * torqueGpuEnd () override
bool hasFGpu () override
bool requestFGpu () override
bool hasTorqueGpu () override
bool requestTorqueGpu () override
Utils::Vector3d box () const override
std::size_t npart_gpu () const override
Public Member Functions inherited from SystemInterface
SystemInterface ()
virtual bool needsRGpu ()
virtual bool needsDipGpu ()
virtual bool needsQGpu ()
virtual bool needsDirectorGpu ()
virtual bool needsFGpu ()
virtual bool needsTorqueGpu ()
virtual ~SystemInterface ()=default
Static Public Member Functions
static EspressoSystemInterface & Instance ()
static EspressoSystemInterface * _Instance ()
Protected Member Functions
EspressoSystemInterface ()
~EspressoSystemInterface () override=default
void gatherParticles ()
void split_particle_struct ()
void enableParticleCommunication ()
void reallocDeviceMemory (std::size_t n)
Protected Attributes
std::size_t m_gpu_npart
bool m_gpu
float * m_r_gpu_begin
float * m_r_gpu_end
float * m_dip_gpu_begin
float * m_dip_gpu_end
float * m_v_gpu_begin
float * m_v_gpu_end
float * m_q_gpu_begin
float * m_q_gpu_end
float * m_director_gpu_begin
float * m_director_gpu_end
bool m_needsParticleStructGpu
bool m_splitParticleStructGpu
Protected Attributes inherited from SystemInterface
bool m_needsRGpu
bool m_needsVGpu
bool m_needsQGpu
bool m_needsDirectorGpu
bool m_needsFGpu
bool m_needsDipGpu
bool m_needsTorqueGpu
Static Protected Attributes
static EspressoSystemInterface * m_instance = nullptr
Additional Inherited Members
Public Types inherited from SystemInterface
typedef Utils::Vector3d Vector3
typedef double Real
Detailed Description
Definition at line 30 of file EspressoSystemInterface.hpp.
Constructor & Destructor Documentation
EspressoSystemInterface()
EspressoSystemInterface::EspressoSystemInterface () inline protected
Definition at line 167 of file EspressoSystemInterface.hpp.
Referenced by _Instance(), and Instance().
~EspressoSystemInterface()
EspressoSystemInterface::~EspressoSystemInterface () override protected default
Member Function Documentation
_Instance()
static EspressoSystemInterface* EspressoSystemInterface::_Instance () inline static
Definition at line 39 of file EspressoSystemInterface.hpp.
References EspressoSystemInterface(), and m_instance.
box()
Utils::Vector3d EspressoSystemInterface::box () const override virtual
Implements SystemInterface.
Definition at line 49 of file EspressoSystemInterface.cpp.
References box_geo, and BoxGeometry::length().
dipGpuBegin()
float* EspressoSystemInterface::dipGpuBegin () inline override virtual
Reimplemented from SystemInterface.
Definition at line 62 of file EspressoSystemInterface.hpp.
References m_dip_gpu_begin.
dipGpuEnd()
float* EspressoSystemInterface::dipGpuEnd () inline override virtual
Reimplemented from SystemInterface.
Definition at line 63 of file EspressoSystemInterface.hpp.
References m_dip_gpu_end.
directorGpuBegin()
float* EspressoSystemInterface::directorGpuBegin () inline override virtual
Reimplemented from SystemInterface.
Definition at line 98 of file EspressoSystemInterface.hpp.
References m_director_gpu_begin.
directorGpuEnd()
float* EspressoSystemInterface::directorGpuEnd () inline override virtual
Reimplemented from SystemInterface.
Definition at line 99 of file EspressoSystemInterface.hpp.
References m_director_gpu_end.
eGpu()
float* EspressoSystemInterface::eGpu () inline override virtual
Reimplemented from SystemInterface.
Definition at line 122 of file EspressoSystemInterface.hpp.
References gpu_get_energy_pointer().
enableParticleCommunication()
void EspressoSystemInterface::enableParticleCommunication () inline protected
Definition at line 179 of file EspressoSystemInterface.hpp.
References cuda_bcast_global_part_params(), gpu_get_global_particle_vars_pointer_host(), gpu_get_particle_pointer(), gpu_init_particle_comm(), and reallocDeviceMemory().
Referenced by requestDipGpu(), requestDirectorGpu(), requestFGpu(), requestParticleStructGpu(), requestQGpu(), requestRGpu(), requestTorqueGpu(), and requestVGpu().
fGpuBegin()
float* EspressoSystemInterface::fGpuBegin () inline override virtual
Reimplemented from SystemInterface.
Definition at line 118 of file EspressoSystemInterface.hpp.
References gpu_get_particle_force_pointer().
fGpuEnd()
float* EspressoSystemInterface::fGpuEnd () inline override virtual
Reimplemented from SystemInterface.
Definition at line 119 of file EspressoSystemInterface.hpp.
References gpu_get_particle_force_pointer(), and m_gpu_npart.
gatherParticles()
void EspressoSystemInterface::gatherParticles () protected
Definition at line 31 of file EspressoSystemInterface.cpp.
References cell_structure, copy_part_data_to_gpu(), gpu_get_global_particle_vars_pointer_host(), gpu_get_particle_pointer(), CellStructure::local_particles(), m_gpu, m_splitParticleStructGpu, reallocDeviceMemory(), split_particle_struct(), and this_node.
Referenced by init(), and update().
hasDipGpu()
bool EspressoSystemInterface::hasDipGpu () inline override virtual
Reimplemented from SystemInterface.
Definition at line 64 of file EspressoSystemInterface.hpp.
Referenced by requestDipGpu().
hasDirectorGpu()
bool EspressoSystemInterface::hasDirectorGpu () inline override virtual
Reimplemented from SystemInterface.
Definition at line 100 of file EspressoSystemInterface.hpp.
Referenced by requestDirectorGpu().
hasFGpu()
bool EspressoSystemInterface::hasFGpu () inline override virtual
Reimplemented from SystemInterface.
Definition at line 133 of file EspressoSystemInterface.hpp.
Referenced by requestFGpu().
hasQGpu()
bool EspressoSystemInterface::hasQGpu () inline override virtual
Reimplemented from SystemInterface.
Definition at line 88 of file EspressoSystemInterface.hpp.
Referenced by requestQGpu().
hasRGpu()
bool EspressoSystemInterface::hasRGpu () inline override virtual
Reimplemented from SystemInterface.
Definition at line 52 of file EspressoSystemInterface.hpp.
Referenced by requestRGpu().
hasTorqueGpu()
bool EspressoSystemInterface::hasTorqueGpu () inline override virtual
Reimplemented from SystemInterface.
Definition at line 143 of file EspressoSystemInterface.hpp.
Referenced by requestTorqueGpu().
hasVGpu()
bool EspressoSystemInterface::hasVGpu () inline override virtual
Reimplemented from SystemInterface.
Definition at line 76 of file EspressoSystemInterface.hpp.
Referenced by requestVGpu().
init()
void EspressoSystemInterface::init () override virtual
Implements SystemInterface.
Definition at line 45 of file EspressoSystemInterface.cpp.
References gatherParticles().
Instance()
static EspressoSystemInterface& EspressoSystemInterface::Instance () inline static
Definition at line 32 of file EspressoSystemInterface.hpp.
References EspressoSystemInterface(), and m_instance.
Referenced by calculate_energy_local().
npart_gpu()
std::size_t EspressoSystemInterface::npart_gpu () const inline override virtual
Reimplemented from SystemInterface.
Definition at line 157 of file EspressoSystemInterface.hpp.
References gpu_get_particle_pointer().
qGpuBegin()
float* EspressoSystemInterface::qGpuBegin () inline override virtual
Reimplemented from SystemInterface.
Definition at line 86 of file EspressoSystemInterface.hpp.
References m_q_gpu_begin.
qGpuEnd()
float* EspressoSystemInterface::qGpuEnd () inline override virtual
Reimplemented from SystemInterface.
Definition at line 87 of file EspressoSystemInterface.hpp.
References m_q_gpu_end.
reallocDeviceMemory()
void EspressoSystemInterface::reallocDeviceMemory (std::size_t n) protected
Definition at line 136 of file EspressoSystemInterface_cuda.cu.
References cuda_safe_mem, m_dip_gpu_begin, m_dip_gpu_end, m_director_gpu_begin, m_director_gpu_end, m_gpu_npart, SystemInterface::m_needsDipGpu, SystemInterface::m_needsDirectorGpu, SystemInterface::m_needsQGpu, SystemInterface::m_needsRGpu, SystemInterface::m_needsVGpu, m_q_gpu_begin, m_q_gpu_end, m_r_gpu_begin, m_r_gpu_end, m_v_gpu_begin, and m_v_gpu_end.
Referenced by enableParticleCommunication(), and gatherParticles().
requestDipGpu()
bool EspressoSystemInterface::requestDipGpu () inline override virtual
Reimplemented from SystemInterface.
Definition at line 65 of file EspressoSystemInterface.hpp.
References enableParticleCommunication(), hasDipGpu(), m_gpu, SystemInterface::m_needsDipGpu, SystemInterface::m_needsRGpu, and m_splitParticleStructGpu.
requestDirectorGpu()
bool EspressoSystemInterface::requestDirectorGpu () inline override virtual
Reimplemented from SystemInterface.
Definition at line 101 of file EspressoSystemInterface.hpp.
References enableParticleCommunication(), hasDirectorGpu(), m_gpu, SystemInterface::m_needsDirectorGpu, and m_splitParticleStructGpu.
requestFGpu()
bool EspressoSystemInterface::requestFGpu () inline override virtual
Reimplemented from SystemInterface.
Definition at line 134 of file EspressoSystemInterface.hpp.
References enableParticleCommunication(), hasFGpu(), m_gpu, and SystemInterface::m_needsFGpu.
requestParticleStructGpu()
bool EspressoSystemInterface::requestParticleStructGpu () inline
Definition at line 110 of file EspressoSystemInterface.hpp.
References enableParticleCommunication(), m_gpu, and m_needsParticleStructGpu.
requestQGpu()
bool EspressoSystemInterface::requestQGpu () inline override virtual
Reimplemented from SystemInterface.
Definition at line 89 of file EspressoSystemInterface.hpp.
References enableParticleCommunication(), hasQGpu(), m_gpu, SystemInterface::m_needsQGpu, and m_splitParticleStructGpu.
requestRGpu()
bool EspressoSystemInterface::requestRGpu () inline override virtual
Reimplemented from SystemInterface.
Definition at line 53 of file EspressoSystemInterface.hpp.
References enableParticleCommunication(), hasRGpu(), m_gpu, SystemInterface::m_needsRGpu, and m_splitParticleStructGpu.
requestTorqueGpu()
bool EspressoSystemInterface::requestTorqueGpu () inline override virtual
Reimplemented from SystemInterface.
Definition at line 144 of file EspressoSystemInterface.hpp.
References enableParticleCommunication(), hasTorqueGpu(), m_gpu, and SystemInterface::m_needsTorqueGpu.
requestVGpu()
bool EspressoSystemInterface::requestVGpu () inline override virtual
Reimplemented from SystemInterface.
Definition at line 77 of file EspressoSystemInterface.hpp.
References enableParticleCommunication(), hasVGpu(), m_gpu, SystemInterface::m_needsVGpu, and m_splitParticleStructGpu.
rGpuBegin()
float* EspressoSystemInterface::rGpuBegin () inline override virtual
Reimplemented from SystemInterface.
Definition at line 50 of file EspressoSystemInterface.hpp.
References m_r_gpu_begin.
rGpuEnd()
float* EspressoSystemInterface::rGpuEnd () inline override virtual
Reimplemented from SystemInterface.
Definition at line 51 of file EspressoSystemInterface.hpp.
References m_r_gpu_end.
split_particle_struct()
void EspressoSystemInterface::split_particle_struct () protected
Definition at line 176 of file EspressoSystemInterface_cuda.cu.
References block(), gpu_get_particle_pointer(), m_dip_gpu_begin, m_director_gpu_begin, SystemInterface::m_needsDipGpu, SystemInterface::m_needsDirectorGpu, SystemInterface::m_needsQGpu, SystemInterface::m_needsRGpu, SystemInterface::m_needsVGpu, m_q_gpu_begin, m_r_gpu_begin, m_v_gpu_begin, split_kernel_dip(), split_kernel_director(), split_kernel_q(), split_kernel_r(), split_kernel_rq(), and split_kernel_v().
Referenced by gatherParticles().
torqueGpuBegin()
float* EspressoSystemInterface::torqueGpuBegin () inline override virtual
Reimplemented from SystemInterface.
Definition at line 127 of file EspressoSystemInterface.hpp.
References gpu_get_particle_torque_pointer().
torqueGpuEnd()
float* EspressoSystemInterface::torqueGpuEnd () inline override virtual
Reimplemented from SystemInterface.
Definition at line 130 of file EspressoSystemInterface.hpp.
References gpu_get_particle_torque_pointer(), and m_gpu_npart.
update()
void EspressoSystemInterface::update () override virtual
Implements SystemInterface.
Definition at line 47 of file EspressoSystemInterface.cpp.
References gatherParticles().
Referenced by calculate_energy_local().
vGpuBegin()
float* EspressoSystemInterface::vGpuBegin () inline override virtual
Reimplemented from SystemInterface.
Definition at line 74 of file EspressoSystemInterface.hpp.
References m_v_gpu_begin.
vGpuEnd()
float* EspressoSystemInterface::vGpuEnd () inline override virtual
Reimplemented from SystemInterface.
Definition at line 75 of file EspressoSystemInterface.hpp.
References m_v_gpu_end.
Member Data Documentation
m_dip_gpu_begin
float* EspressoSystemInterface::m_dip_gpu_begin protected
Definition at line 195 of file EspressoSystemInterface.hpp.
Referenced by dipGpuBegin(), reallocDeviceMemory(), and split_particle_struct().
m_dip_gpu_end
float* EspressoSystemInterface::m_dip_gpu_end protected
Definition at line 196 of file EspressoSystemInterface.hpp.
Referenced by dipGpuEnd(), and reallocDeviceMemory().
m_director_gpu_begin
float* EspressoSystemInterface::m_director_gpu_begin protected
Definition at line 204 of file EspressoSystemInterface.hpp.
Referenced by directorGpuBegin(), reallocDeviceMemory(), and split_particle_struct().
m_director_gpu_end
float* EspressoSystemInterface::m_director_gpu_end protected
Definition at line 205 of file EspressoSystemInterface.hpp.
Referenced by directorGpuEnd(), and reallocDeviceMemory().
m_gpu
bool EspressoSystemInterface::m_gpu protected
Definition at line 190 of file EspressoSystemInterface.hpp.
Referenced by gatherParticles(), requestDipGpu(), requestDirectorGpu(), requestFGpu(), requestParticleStructGpu(), requestQGpu(), requestRGpu(), requestTorqueGpu(), and requestVGpu().
m_gpu_npart
std::size_t EspressoSystemInterface::m_gpu_npart protected
Definition at line 189 of file EspressoSystemInterface.hpp.
Referenced by fGpuEnd(), reallocDeviceMemory(), and torqueGpuEnd().
m_instance
EspressoSystemInterface * EspressoSystemInterface::m_instance = nullptr static protected
Definition at line 163 of file EspressoSystemInterface.hpp.
Referenced by _Instance(), and Instance().
m_needsParticleStructGpu
bool EspressoSystemInterface::m_needsParticleStructGpu protected
Definition at line 207 of file EspressoSystemInterface.hpp.
Referenced by requestParticleStructGpu().
m_q_gpu_begin
float* EspressoSystemInterface::m_q_gpu_begin protected
Definition at line 201 of file EspressoSystemInterface.hpp.
Referenced by qGpuBegin(), reallocDeviceMemory(), and split_particle_struct().
m_q_gpu_end
float* EspressoSystemInterface::m_q_gpu_end protected
Definition at line 202 of file EspressoSystemInterface.hpp.
Referenced by qGpuEnd(), and reallocDeviceMemory().
m_r_gpu_begin
float* EspressoSystemInterface::m_r_gpu_begin protected
Definition at line 192 of file EspressoSystemInterface.hpp.
Referenced by reallocDeviceMemory(), rGpuBegin(), and split_particle_struct().
m_r_gpu_end
float* EspressoSystemInterface::m_r_gpu_end protected
Definition at line 193 of file EspressoSystemInterface.hpp.
Referenced by reallocDeviceMemory(), and rGpuEnd().
m_splitParticleStructGpu
bool EspressoSystemInterface::m_splitParticleStructGpu protected
Definition at line 208 of file EspressoSystemInterface.hpp.
Referenced by gatherParticles(), requestDipGpu(), requestDirectorGpu(), requestQGpu(), requestRGpu(), and requestVGpu().
m_v_gpu_begin
float* EspressoSystemInterface::m_v_gpu_begin protected
Definition at line 198 of file EspressoSystemInterface.hpp.
Referenced by reallocDeviceMemory(), split_particle_struct(), and vGpuBegin().
m_v_gpu_end
float* EspressoSystemInterface::m_v_gpu_end protected
Definition at line 199 of file EspressoSystemInterface.hpp.
Referenced by reallocDeviceMemory(), and vGpuEnd().
The documentation for this class was generated from the following files:
EspressoSystemInterface.hpp
EspressoSystemInterface.cpp
EspressoSystemInterface_cuda.cu