ESPResSo: DipolarBarnesHut Class Reference
DipolarBarnesHut Class Reference
#include <DipolarBarnesHut.hpp>
Public Member Functions
DipolarBarnesHut (SystemInterface &s, float epssq, float itolsq)
void computeForces (SystemInterface &s) override
void computeEnergy (SystemInterface &s) override
Public Member Functions inherited from Actor
virtual void computeTorques (SystemInterface &s)
virtual ~Actor ()=default
Detailed Description
Definition at line 36 of file DipolarBarnesHut.hpp.
Constructor & Destructor Documentation
DipolarBarnesHut()
DipolarBarnesHut::DipolarBarnesHut (SystemInterface & s, float epssq, float itolsq) inline
Definition at line 38 of file DipolarBarnesHut.hpp.
References dipole, Dipole_parameters::prefactor, SystemInterface::requestDipGpu(), SystemInterface::requestFGpu(), SystemInterface::requestRGpu(), runtimeErrorMsg, and setBHPrecision().
Member Function Documentation
computeEnergy()
void DipolarBarnesHut::computeEnergy (SystemInterface & s) inline override virtual
Reimplemented from Actor.
Definition at line 71 of file DipolarBarnesHut.hpp.
References allocBHmemCopy(), BHData::blocks, buildBoxBH(), buildTreeBH(), SystemInterface::dipGpuBegin(), CUDA_energy::dipolar, SystemInterface::eGpu(), energyBH(), fillConstantPointers(), initBHgpu(), SystemInterface::npart_gpu(), SystemInterface::rGpuBegin(), runtimeErrorMsg, sortBH(), and summarizeBH().
computeForces()
void DipolarBarnesHut::computeForces (SystemInterface & s) inline override virtual
Reimplemented from Actor.
Definition at line 53 of file DipolarBarnesHut.hpp.
References allocBHmemCopy(), BHData::blocks, buildBoxBH(), buildTreeBH(), SystemInterface::dipGpuBegin(), SystemInterface::fGpuBegin(), fillConstantPointers(), forceBH(), initBHgpu(), SystemInterface::npart_gpu(), SystemInterface::rGpuBegin(), runtimeErrorMsg, sortBH(), summarizeBH(), and SystemInterface::torqueGpuBegin().
The documentation for this class was generated from the following file:
DipolarBarnesHut.hpp