ESPResSo: BoxGeometry Class Reference
BoxGeometry Class Reference
#include <BoxGeometry.hpp>
Public Member Functions
void set_periodic (unsigned coord, bool val)
Set periodicity for direction.
constexpr bool periodic (unsigned coord) const
Check periodicity in direction.
const Utils::Vector3d & length () const
Box length.
const Utils::Vector3d & length_inv () const
Inverse box length.
const Utils::Vector3d & length_half () const
Half box length.
void set_length (Utils::Vector3d const &box_l)
Set box side lengths.
double volume () const
Box volume.
template<typename T >
T get_mi_coord (T a, T b, unsigned coord) const
Get the minimum-image distance between two coordinates.
template<typename T >
Utils::Vector< T, 3 > get_mi_vector (const Utils::Vector< T, 3 > &a, const Utils::Vector< T, 3 > &b) const
Get the minimum-image vector between two coordinates.
Detailed Description
Definition at line 71 of file BoxGeometry.hpp.
Member Function Documentation
get_mi_coord()
template<typename T > T BoxGeometry::get_mi_coord (T a, T b, unsigned coord) const inline
Get the minimum-image distance between two coordinates.
Parameters
a Coordinate of the terminal point.
b Coordinate of the initial point.
coord Direction
Returns
Shortest distance from b to a across periodic images, i.e. a - b. Can be negative.
Definition at line 144 of file BoxGeometry.hpp.
Referenced by get_mi_vector().
get_mi_vector()
template<typename T > Utils::Vector<T, 3> BoxGeometry::get_mi_vector (const Utils::Vector< T, 3 > & a, const Utils::Vector< T, 3 > & b) const inline
Get the minimum-image vector between two coordinates.
Template Parameters
T Floating point type.
Parameters
a Coordinate of the terminal point.
b Coordinate of the initial point.
Returns
Vector from b to a that minimizes the distance across periodic images, i.e. a - b.
Definition at line 162 of file BoxGeometry.hpp.
References b, and get_mi_coord().
Referenced by add_bonded_two_body_force(), add_oif_global_forces(), bind_at_point_of_collision_calc_vs_pos(), calc_bonded_energy(), calc_bonded_three_body_pressure_tensor(), calc_bonded_virial_pressure_tensor(), calc_dihedral_angle(), calc_dipole_dipole_ia(), IBMTribend::calc_forces(), IBMTriel::calc_forces(), OifLocalForcesBond::calc_forces(), calc_oif_global(), calc_part_distribution(), calc_vectors_and_cosine(), calculate_positional_correction(), calculate_velocity_correction(), calculate_vs_relate_to_params(), ClusterAnalysis::Cluster::center_of_mass_subcluster(), coldet_do_three_particle_bond(), PairCriteria::DistanceCriterion::decide(), PairCriteria::EnergyCriterion::decide(), distto(), ELC_P3M_dielectric_layers_energy_contribution(), ELC_P3M_dielectric_layers_force_contribution(), Observables::BondAngles::evaluate(), Observables::ParticleDistances::evaluate(), Observables::CosPersistenceAngles::evaluate(), Observables::BondDihedrals::evaluate(), ClusterAnalysis::Cluster::fractal_dimension(), glue_to_surface_calc_vs_pos(), IBMTribend::IBMTribend(), IBMTriel::IBMTriel(), is_valid_position(), ClusterAnalysis::Cluster::longest_distance(), mindist(), nbhood(), ClusterAnalysis::Cluster::radius_of_gyration_subcluster(), and VirtualSitesRelative::update().
length()
const Utils::Vector3d& BoxGeometry::length () const inline
Box length.
Returns
Return vector of side-lengths of the box.
Definition at line 106 of file BoxGeometry.hpp.
Referenced by Constraints::Constraints< ParticleRange, Constraint >::add(), add_dipole_force(), add_mmm1d_coulomb_pair_force(), add_oif_global_forces(), EspressoSystemInterface::box(), OifLocalForcesBond::calc_forces(), calc_oif_global(), calc_part_distribution(), calc_re(), calc_rg(), calc_rh(), ClusterAnalysis::Cluster::center_of_mass_subcluster(), determine_minrad(), dipole_energy(), anonymous_namespace{p3m.cpp}::dipole_moment(), dp3m_adaptive_tune(), dp3m_average_dipolar_self_energy(), dp3m_calc_influence_function_energy(), dp3m_calc_influence_function_force(), dp3m_get_accuracy(), dp3m_mc_time(), dp3m_sanity_checks(), dp3m_sanity_checks_boxl(), dp3m_scaleby_box_l(), dp3m_set_params(), ELC_add_force(), ELC_energy(), ELC_init(), ELC_set_params(), ELC_tune_far_cut(), fetch_particles(), fold_position(), folded_position(), force_calc(), get_DLC_dipolar(), get_DLC_energy_dipolar(), ReactionMethods::ReactionAlgorithm::get_random_position_in_box(), image_sum_b(), image_sum_t(), lb_init(), lb_set_agrid_gpu(), magnetic_dipolar_direct_sum_calculations(), DomainDecomposition::max_cutoff(), mdlc_set_params(), mdlc_tune_far_cut(), mmm1d_coulomb_pair_energy(), MMM1D_init(), mmm1d_tune(), npt_ensemble_init(), p3m_adaptive_tune(), p3m_calc_influence_function_energy(), p3m_calc_influence_function_force(), p3m_get_accuracy(), p3m_gpu_init(), p3m_k_space_error(), p3m_mc_time(), p3m_mcr_time(), p3m_real_space_error(), p3m_sanity_checks_boxl(), p3m_scaleby_box_l(), p3m_set_params(), random_position(), recalc_long_range_cutoff(), recalc_maximal_cutoff(), regular_decomposition(), rescale_boxl(), ReactionMethods::ReactionAlgorithm::set_cyl_constraint(), ReactionMethods::ReactionAlgorithm::set_slab_constraint(), setup_PoQ(), setup_PQ(), anonymous_namespace{DomainDecomposition.cpp}::shift(), thole_pair_energy(), Scafacos::tune_r_cut(), tune_skin(), Scafacos::ScafacosContext::update_system_params(), velocity_verlet_npt_propagate_pos(), and Writer::H5md::write_box().
length_half()
const Utils::Vector3d& BoxGeometry::length_half () const inline
Half box length.
Returns
Return vector of half side-lengths of the box.
Definition at line 118 of file BoxGeometry.hpp.
Referenced by add_dipole_force(), dipole_energy(), dp3m_sanity_checks_boxl(), image_sum_b(), image_sum_t(), p3m_sanity_checks_boxl(), and z_energy().
length_inv()
const Utils::Vector3d& BoxGeometry::length_inv () const inline
Inverse box length.
Returns
Return vector of inverse side-lengths of the box.
Definition at line 112 of file BoxGeometry.hpp.
Referenced by add_dipole_force(), add_mmm1d_coulomb_pair_force(), add_PQ_force(), add_z_force(), calc_structurefactor(), dipole_energy(), dp3m_adaptive_tune(), dp3m_calc_kspace_forces(), dp3m_init_a_ai_cao_cut(), dp3m_scaleby_box_l(), dp3m_set_params(), dp3m_set_tune_params(), ELC_add_force(), ELC_energy(), ELC_tune_far_cut(), far_error(), get_DLC_dipolar(), get_DLC_energy_dipolar(), mmm1d_coulomb_pair_energy(), MMM1D_init(), p3m_adaptive_tune(), p3m_calc_kspace_forces(), p3m_init_a_ai_cao_cut(), p3m_mcr_time(), p3m_scaleby_box_l(), p3m_set_params(), p3m_set_tune_params(), rescale_boxl(), setup_PoQ(), setup_PQ(), velocity_verlet_npt_propagate_pos(), and z_energy().
periodic()
constexpr bool BoxGeometry::periodic (unsigned coord) const inline constexpr
Check periodicity in direction.
Parameters
coord Direction to check
Returns
true iff periodic in direction.
Definition at line 97 of file BoxGeometry.hpp.
Referenced by DipolarDirectSum::computeEnergy(), DipolarDirectSum::computeForces(), dp3m_sanity_checks(), ELC_sanity_checks(), fold_position(), folded_position(), integrate_set_sd(), lb_check_halo_regions(), magnetic_dipolar_direct_sum_calculations(), mdds_sanity_checks(), mdlc_sanity_checks(), MMM1D_sanity_checks(), on_periodicity_change(), p3m_sanity_checks_system(), prepare_halo_communication(), anonymous_namespace{DomainDecomposition.cpp}::shift(), and Scafacos::ScafacosContext::update_system_params().
set_length()
void BoxGeometry::set_length (Utils::Vector3d const & box_l) inline
Set box side lengths.
Parameters
box_l Length that should be set.
Definition at line 124 of file BoxGeometry.hpp.
Referenced by mpi_set_box_length_local(), and velocity_verlet_npt_propagate_pos().
set_periodic()
void BoxGeometry::set_periodic (unsigned coord, bool val) inline
Set periodicity for direction.
Parameters
coord The coordinate to set the periodicity for.
val True if this direction should be periodic.
Definition at line 89 of file BoxGeometry.hpp.
Referenced by mpi_set_periodicity_local().
volume()
double BoxGeometry::volume () const inline
Box volume.
Returns
Return the volume of the box.
Definition at line 134 of file BoxGeometry.hpp.
Referenced by anonymous_namespace{p3m.cpp}::add_dipole_correction(), add_mdlc_energy_corrections(), add_mdlc_force_corrections(), calc_surface_term(), calculate_pressure_local(), anonymous_namespace{p3m.cpp}::dipole_correction_energy(), dp3m_calc_kspace_forces(), dp3m_compute_constants_energy_dipolar(), dpd_stress(), p3m_adaptive_tune(), p3m_calc_kspace_forces(), p3m_real_space_error(), ReactionMethods::ReactionAlgorithm::set_cuboid_reaction_ensemble_volume(), and velocity_verlet_npt_propagate_pos().
The documentation for this class was generated from the following file:
BoxGeometry.hpp