ESPResSo: Mmm1dgpuForce Class Reference
Mmm1dgpuForce Class Reference
#include <Mmm1dgpuForce.hpp>
Public Member Functions
Mmm1dgpuForce (SystemInterface &s, float coulomb_prefactor, float maxPWerror, float far_switch_radius=-1, int bessel_cutoff=-1)
~Mmm1dgpuForce () override
void computeForces (SystemInterface &s) override
void computeEnergy (SystemInterface &s) override
void setup (SystemInterface &s)
void tune (SystemInterface &s, float _maxPWerror, float _far_switch_radius, int _bessel_cutoff)
void set_params (float _boxz, float _coulomb_prefactor, float _maxPWerror, float _far_switch_radius, int _bessel_cutoff, bool manual=false)
void activate ()
void deactivate ()
Public Member Functions inherited from Actor
virtual void computeTorques (SystemInterface &s)
virtual ~Actor ()=default
Detailed Description
Definition at line 29 of file Mmm1dgpuForce.hpp.
Constructor & Destructor Documentation
Mmm1dgpuForce()
Mmm1dgpuForce::Mmm1dgpuForce (SystemInterface & s, float coulomb_prefactor, float maxPWerror, float far_switch_radius = -1, int bessel_cutoff = -1)
Definition at line 136 of file Mmm1dgpuForce_cuda.cu.
References modpsi_init(), SystemInterface::requestFGpu(), SystemInterface::requestQGpu(), and SystemInterface::requestRGpu().
~Mmm1dgpuForce()
Mmm1dgpuForce::~Mmm1dgpuForce () override
Definition at line 211 of file Mmm1dgpuForce_cuda.cu.
Member Function Documentation
activate()
void Mmm1dgpuForce::activate ()
Definition at line 40 of file Mmm1dgpuForce.cpp.
References energyActors, and forceActors.
computeEnergy()
void Mmm1dgpuForce::computeEnergy (SystemInterface & s) override virtual
Reimplemented from Actor.
Definition at line 578 of file Mmm1dgpuForce_cuda.cu.
References coulomb, CUDA_energy::coulomb, COULOMB_MMM1D_GPU, SystemInterface::eGpu(), energiesKernel(), KERNELCALL, KERNELCALL_shared, Coulomb_parameters::method, SystemInterface::npart_gpu(), SystemInterface::qGpuBegin(), SystemInterface::rGpuBegin(), scaleAndAddKernel(), setup(), and sumKernel().
computeForces()
void Mmm1dgpuForce::computeForces (SystemInterface & s) override virtual
Reimplemented from Actor.
Definition at line 547 of file Mmm1dgpuForce_cuda.cu.
References coulomb, COULOMB_MMM1D_GPU, SystemInterface::fGpuBegin(), forcesKernel(), KERNELCALL, Coulomb_parameters::method, SystemInterface::npart_gpu(), SystemInterface::qGpuBegin(), SystemInterface::rGpuBegin(), setup(), and vectorReductionKernel().
deactivate()
void Mmm1dgpuForce::deactivate ()
Definition at line 45 of file Mmm1dgpuForce.cpp.
References energyActors, forceActors, and ActorList::remove().
set_params()
void Mmm1dgpuForce::set_params (float _boxz, float _coulomb_prefactor, float _maxPWerror, float _far_switch_radius, int _bessel_cutoff, bool manual = false)
Definition at line 313 of file Mmm1dgpuForce_cuda.cu.
References MMM1DParameters::bessel_cutoff, boxz, cuda_safe_mem, cudaSetDevice, deviceCount, MMM1DParameters::far_switch_radius_2, far_switch_radius_2, MMM1DParameters::maxPWerror, mmm1d_params, Utils::sqr(), and uz.
Referenced by setup(), and tune().
setup()
void Mmm1dgpuForce::setup (SystemInterface & s)
Definition at line 159 of file Mmm1dgpuForce_cuda.cu.
References SystemInterface::box(), coulomb, cuda_safe_mem, cudaSetDevice, deviceCount, SystemInterface::npart_gpu(), Coulomb_parameters::prefactor, set_params(), Utils::sqr(), and tune().
Referenced by computeEnergy(), and computeForces().
tune()
void Mmm1dgpuForce::tune (SystemInterface & s, float _maxPWerror, float _far_switch_radius, int _bessel_cutoff)
Definition at line 267 of file Mmm1dgpuForce_cuda.cu.
References bessel_cutoff, besselTuneKernel(), cuda_safe_mem, f, and set_params().
Referenced by setup().
The documentation for this class was generated from the following files:
Mmm1dgpuForce.hpp
Mmm1dgpuForce.cpp
Mmm1dgpuForce_cuda.cu