ESPResSo: ReactionMethods::WidomInsertion Class Reference
ReactionMethods::WidomInsertion Class Reference
Widom insertion method.
#include <WidomInsertion.hpp>
Public Member Functions
WidomInsertion (int seed)
std::pair< double, double > measure_excess_chemical_potential (SingleReaction &current_reaction)
Public Member Functions inherited from ReactionMethods::ReactionAlgorithm
ReactionAlgorithm (int seed)
virtual ~ReactionAlgorithm ()=default
double get_acceptance_rate_configurational_moves () const
void set_cuboid_reaction_ensemble_volume ()
Automatically sets the volume which is used by the reaction ensemble to the volume of a cuboid box, if not already initialized with another value.
virtual int do_reaction (int reaction_steps)
Performs a randomly selected reaction in the reaction ensemble.
void check_reaction_method () const
Checks whether all necessary variables for the reaction ensemble have been set.
void remove_constraint ()
void set_cyl_constraint (double center_x, double center_y, double radius)
void set_slab_constraint (double slab_start_z, double slab_end_z)
Utils::Vector2d get_slab_constraint_parameters () const
int delete_particle (int p_id)
Deletes the particle with the given p_id and stores the id if the deletion created a hole in the particle id range.
void add_reaction (double gamma, const std::vector< int > &reactant_types, const std::vector< int > &reactant_coefficients, const std::vector< int > &product_types, const std::vector< int > &product_coefficients)
Adds a reaction to the reaction system.
void delete_reaction (int reaction_id)
bool do_global_mc_move_for_particles_of_type (int type, int particle_number_of_type)
Performs a global MC move for a particle of the provided type.
Additional Inherited Members
Public Attributes inherited from ReactionMethods::ReactionAlgorithm
std::vector< SingleReaction > reactions
std::map< int, double > charges_of_types
double kT = -10.0
double exclusion_radius = 0.0
Hard sphere radius.
double volume = -10.0
int non_interacting_type = 100
int m_accepted_configurational_MC_moves = 0
int m_tried_configurational_MC_moves = 0
bool particle_inside_exclusion_radius_touched = false
Protected Member Functions inherited from ReactionMethods::ReactionAlgorithm
void generic_oneway_reaction (SingleReaction &current_reaction)
Generic one way reaction A+B+...+G +...
std::tuple< std::vector< StoredParticleProperty >, std::vector< int >, std::vector< StoredParticleProperty > > make_reaction_attempt (SingleReaction const &current_reaction)
Performs a trial reaction move.
std::vector< std::pair< int, Utils::Vector3d > > generate_new_particle_positions (int type, int n_particles)
void restore_properties (std::vector< StoredParticleProperty > const &property_list, int number_of_saved_properties)
Restores the previously stored particle properties.
int i_random (int maxint)
draws a random integer from the uniform distribution in the range [0,maxint-1]
bool all_reactant_particles_exist (SingleReaction const &current_reaction) const
Checks whether all particles exist for the provided reaction.
virtual double calculate_acceptance_probability (SingleReaction const &current_reaction, double E_pot_old, double E_pot_new, std::map< int, int > const &old_particle_numbers) const
Utils::Vector3d get_random_position_in_box ()
Writes a random position inside the central box into the provided array.
Protected Attributes inherited from ReactionMethods::ReactionAlgorithm
std::vector< int > m_empty_p_ids_smaller_than_max_seen_particle
Detailed Description
Widom insertion method.
Definition at line 29 of file WidomInsertion.hpp.
Constructor & Destructor Documentation
WidomInsertion()
ReactionMethods::WidomInsertion::WidomInsertion (int seed) inline
Definition at line 31 of file WidomInsertion.hpp.
Member Function Documentation
measure_excess_chemical_potential()
std::pair< double, double > ReactionMethods::WidomInsertion::measure_excess_chemical_potential (SingleReaction & current_reaction)
Definition at line 32 of file WidomInsertion.cpp.
References Utils::abs(), ReactionMethods::SingleReaction::accumulator_potential_energy_difference_exponential, ReactionMethods::ReactionAlgorithm::all_reactant_particles_exist(), calculate_current_potential_energy_of_system(), ReactionMethods::ReactionAlgorithm::delete_particle(), ReactionMethods::ReactionAlgorithm::kT, ReactionMethods::ReactionAlgorithm::make_reaction_attempt(), and ReactionMethods::ReactionAlgorithm::restore_properties().
The documentation for this class was generated from the following files:
WidomInsertion.hpp
WidomInsertion.cpp