ESPResSo: PairCriteria::EnergyCriterion Class Reference
PairCriteria::EnergyCriterion Class Reference
True if the short range energy is larger than a cut_off.
#include <pair_criteria.hpp>
Public Member Functions
bool decide (const Particle &p1, const Particle &p2) const override
double get_cut_off ()
void set_cut_off (double c)
Public Member Functions inherited from PairCriteria::PairCriterion
bool decide (int id1, int id2) const
Make a decision based on particle ids.
virtual ~PairCriterion ()=default
Detailed Description
True if the short range energy is larger than a cut_off.
Definition at line 61 of file core/pair_criteria/pair_criteria.hpp.
Member Function Documentation
decide()
bool PairCriteria::EnergyCriterion::decide (const Particle & p1, const Particle & p2) const inline override virtual
Implements PairCriteria::PairCriterion.
Definition at line 63 of file core/pair_criteria/pair_criteria.hpp.
References box_geo, calc_non_bonded_pair_energy(), get_ia_param(), BoxGeometry::get_mi_vector(), ia_params, Utils::Vector< T, N >::norm(), ParticlePosition::p, Particle::p, Particle::r, and ParticleProperties::type.
get_cut_off()
double PairCriteria::EnergyCriterion::get_cut_off () inline
Definition at line 74 of file core/pair_criteria/pair_criteria.hpp.
set_cut_off()
void PairCriteria::EnergyCriterion::set_cut_off (double c) inline
Definition at line 75 of file core/pair_criteria/pair_criteria.hpp.
References D3Q19::c.
The documentation for this class was generated from the following file:
core/pair_criteria/pair_criteria.hpp