ESPResSo: DipolarDirectSum Class Reference
DipolarDirectSum Class Reference
#include <DipolarDirectSum.hpp>
Public Member Functions
DipolarDirectSum (SystemInterface &s)
void computeForces (SystemInterface &s) override
void computeEnergy (SystemInterface &s) override
Public Member Functions inherited from Actor
virtual void computeTorques (SystemInterface &s)
virtual ~Actor ()=default
Detailed Description
Definition at line 42 of file DipolarDirectSum.hpp.
Constructor & Destructor Documentation
DipolarDirectSum()
DipolarDirectSum::DipolarDirectSum (SystemInterface & s) inline
Definition at line 44 of file DipolarDirectSum.hpp.
References dipole, Dipole_parameters::prefactor, SystemInterface::requestDipGpu(), SystemInterface::requestFGpu(), SystemInterface::requestRGpu(), and runtimeErrorMsg.
Member Function Documentation
computeEnergy()
void DipolarDirectSum::computeEnergy (SystemInterface & s) inline override virtual
Reimplemented from Actor.
Definition at line 68 of file DipolarDirectSum.hpp.
References SystemInterface::box(), box_geo, SystemInterface::dipGpuBegin(), CUDA_energy::dipolar, DipolarDirectSum_kernel_wrapper_energy(), SystemInterface::eGpu(), SystemInterface::npart_gpu(), BoxGeometry::periodic(), and SystemInterface::rGpuBegin().
computeForces()
void DipolarDirectSum::computeForces (SystemInterface & s) inline override virtual
Reimplemented from Actor.
Definition at line 57 of file DipolarDirectSum.hpp.
References SystemInterface::box(), box_geo, SystemInterface::dipGpuBegin(), DipolarDirectSum_kernel_wrapper_force(), SystemInterface::fGpuBegin(), SystemInterface::npart_gpu(), BoxGeometry::periodic(), SystemInterface::rGpuBegin(), and SystemInterface::torqueGpuBegin().
The documentation for this class was generated from the following file:
DipolarDirectSum.hpp