ESPResSo: collision.cpp File Reference
collision.cpp File Reference
#include "collision.hpp"
#include "Cell.hpp"
#include "Particle.hpp"
#include "bonded_interactions/bonded_interaction_data.hpp"
#include "cells.hpp"
#include "communication.hpp"
#include "errorhandling.hpp"
#include "event.hpp"
#include "grid.hpp"
#include "nonbonded_interactions/nonbonded_interaction_data.hpp"
#include "virtual_sites.hpp"
#include <utils/Vector.hpp>
#include <utils/constants.hpp>
#include <utils/math/sqr.hpp>
#include <utils/mpi/all_compare.hpp>
#include <utils/mpi/gather_buffer.hpp>
#include <boost/algorithm/clamp.hpp>
#include <boost/algorithm/cxx11/any_of.hpp>
#include <boost/mpi/collectives.hpp>
#include <boost/serialization/serialization.hpp>
#include <algorithm>
#include <array>
#include <cmath>
#include <stdexcept>
#include <string>
#include <utility>
#include <vector>
Namespaces
boost
boost::serialization
anonymous_namespace{collision.cpp}
Functions
template<typename Archive >
void boost::serialization::serialize (Archive &ar, CollisionPair &c, const unsigned int)
Particle & anonymous_namespace{collision.cpp}::get_part (int id)
bool bind_centers ()
Return true if a bond between the centers of the colliding particles needs to be placed.
int get_bond_num_partners (int bond_id)
bool validate_collision_parameters ()
Validates collision parameters and creates particle types if needed.
void prepare_local_collision_queue ()
void queue_collision (const int part1, const int part2)
Add the collision between the given particle ids to the collision queue.
const Particle & glue_to_surface_calc_vs_pos (const Particle &p1, const Particle &p2, Utils::Vector3d &pos)
Calculate position of vs for GLUE_TO_SURFACE mode.
void bind_at_point_of_collision_calc_vs_pos (const Particle *const p1, const Particle *const p2, Utils::Vector3d &pos1, Utils::Vector3d &pos2)
void coldet_do_three_particle_bond (Particle &p, Particle const &p1, Particle const &p2)
void place_vs_and_relate_to_particle (const int current_vs_pid, const Utils::Vector3d &pos, int relate_to)
void bind_at_poc_create_bond_between_vs (const int current_vs_pid, const CollisionPair &c)
void glue_to_surface_bind_part_to_vs (const Particle *const p1, const Particle *const p2, const int vs_pid_plus_one, const CollisionPair &c)
std::vector< CollisionPair > gather_global_collision_queue ()
static void three_particle_binding_do_search (Cell *basecell, Particle &p1, Particle &p2)
void three_particle_binding_domain_decomposition (const std::vector< CollisionPair > &gathered_queue)
void handle_collisions ()
Handle the collisions recorded in the queue.
Variables
static std::vector< CollisionPair > local_collision_queue
During force calculation, colliding particles are recorded in the queue. The queue is processed after force calculation, when it is safe to add particles.
Collision_parameters collision_params
Parameters for collision detection.
Function Documentation
bind_at_poc_create_bond_between_vs()
void bind_at_poc_create_bond_between_vs (const int current_vs_pid, const CollisionPair & c)
Definition at line 382 of file collision.cpp.
References Collision_parameters::bond_vs, Particle::bonds(), D3Q19::c, cell_structure, collision_params, get_bond_num_partners(), CellStructure::get_local_particle(), and anonymous_namespace{collision.cpp}::get_part().
Referenced by handle_collisions().
bind_at_point_of_collision_calc_vs_pos()
void bind_at_point_of_collision_calc_vs_pos (const Particle *const p1, const Particle *const p2, Utils::Vector3d & pos1, Utils::Vector3d & pos2)
Definition at line 293 of file collision.cpp.
References box_geo, collision_params, BoxGeometry::get_mi_vector(), ParticlePosition::p, Particle::r, and Collision_parameters::vs_placement.
Referenced by handle_collisions().
bind_centers()
bool bind_centers () inline
Return true if a bond between the centers of the colliding particles needs to be placed.
At this point, all modes need this.
Definition at line 93 of file collision.cpp.
References COLLISION_MODE_GLUE_TO_SURF, COLLISION_MODE_OFF, collision_params, and Collision_parameters::mode.
Referenced by handle_collisions().
coldet_do_three_particle_bond()
void coldet_do_three_particle_bond (Particle & p, Particle const & p1, Particle const & p2)
Definition at line 304 of file collision.cpp.
References Collision_parameters::bond_three_particles, Particle::bonds(), box_geo, collision_params, Collision_parameters::distance, BoxGeometry::get_mi_vector(), ParticleProperties::identity, Particle::identity(), Utils::Vector< T, N >::norm(), Utils::Vector< T, N >::normalize(), ParticlePosition::p, Particle::p, Utils::pi(), Particle::r, Collision_parameters::three_particle_angle_resolution, and TINY_COS_VALUE.
Referenced by three_particle_binding_do_search().
gather_global_collision_queue()
std::vector<CollisionPair> gather_global_collision_queue ()
Definition at line 428 of file collision.cpp.
References comm_cart, Utils::Mpi::gather_buffer(), local_collision_queue, and res.
Referenced by handle_collisions().
get_bond_num_partners()
int get_bond_num_partners (int bond_id) inline
Definition at line 102 of file collision.cpp.
References bonded_ia_params, and number_of_partners().
Referenced by bind_at_poc_create_bond_between_vs(), and validate_collision_parameters().
glue_to_surface_bind_part_to_vs()
void glue_to_surface_bind_part_to_vs (const Particle *const p1, const Particle *const p2, const int vs_pid_plus_one, const CollisionPair & c)
Definition at line 412 of file collision.cpp.
References Collision_parameters::bond_vs, Particle::bonds(), collision_params, anonymous_namespace{collision.cpp}::get_part(), ParticleProperties::identity, Particle::p, Collision_parameters::part_type_after_glueing, and ParticleProperties::type.
Referenced by handle_collisions().
glue_to_surface_calc_vs_pos()
const Particle& glue_to_surface_calc_vs_pos (const Particle & p1, const Particle & p2, Utils::Vector3d & pos)
Calculate position of vs for GLUE_TO_SURFACE mode.
Returns id of particle to bind vs to.
Definition at line 267 of file collision.cpp.
References box_geo, D3Q19::c, collision_params, Collision_parameters::dist_glued_part_to_vs, BoxGeometry::get_mi_vector(), Utils::Vector< T, N >::norm(), ParticlePosition::p, Particle::p, Collision_parameters::part_type_to_attach_vs_to, Collision_parameters::part_type_to_be_glued, pos, Particle::r, and ParticleProperties::type.
Referenced by handle_collisions().
handle_collisions()
void handle_collisions ()
Handle the collisions recorded in the queue.
Definition at line 499 of file collision.cpp.
References Utils::Mpi::all_compare(), bind_at_poc_create_bond_between_vs(), bind_at_point_of_collision_calc_vs_pos(), bind_centers(), Collision_parameters::bond_centers, Particle::bonds(), D3Q19::c, cell_structure, cells_update_ghosts(), COLLISION_MODE_BIND_THREE_PARTICLES, COLLISION_MODE_GLUE_TO_SURF, COLLISION_MODE_VS, collision_params, comm_cart, Cells::DATA_PART_BONDS, Cells::DATA_PART_PROPERTIES, Collision_parameters::exception_on_collision, gather_global_collision_queue(), CellStructure::get_local_particle(), CellStructure::get_max_local_particle_id(), anonymous_namespace{collision.cpp}::get_part(), ParticleLocal::ghost, glue_to_surface_bind_part_to_vs(), glue_to_surface_calc_vs_pos(), Particle::identity(), Particle::l, local_collision_queue, anonymous_namespace{Correlator.cpp}::min(), Collision_parameters::mode, Particle::p, Collision_parameters::part_type_after_glueing, Collision_parameters::part_type_to_be_glued, place_vs_and_relate_to_particle(), pos, Cells::RESORT_GLOBAL, ParticleProperties::rotation, ROTATION_X, ROTATION_Y, ROTATION_Z, runtimeWarningMsg, CellStructure::set_resort_particles(), three_particle_binding_domain_decomposition(), and ParticleProperties::type.
Referenced by integrate().
place_vs_and_relate_to_particle()
void place_vs_and_relate_to_particle (const int current_vs_pid, const Utils::Vector3d & pos, int relate_to)
Definition at line 368 of file collision.cpp.
References CellStructure::add_particle(), cell_structure, collision_params, anonymous_namespace{collision.cpp}::get_part(), ParticleProperties::identity, local_vs_relate_to(), ParticlePosition::p, Particle::p, pos, Particle::r, and Collision_parameters::vs_particle_type.
Referenced by handle_collisions().
prepare_local_collision_queue()
void prepare_local_collision_queue ()
Definition at line 258 of file collision.cpp.
References local_collision_queue.
Referenced by force_calc().
queue_collision()
void queue_collision (const int part1, const int part2)
Add the collision between the given particle ids to the collision queue.
Definition at line 260 of file collision.cpp.
References local_collision_queue.
Referenced by detect_collision().
three_particle_binding_do_search()
static void three_particle_binding_do_search (Cell * basecell, Particle & p1, Particle & p2) static
Definition at line 436 of file collision.cpp.
References Neighbors< CellRef >::all(), D3Q19::c, coldet_do_three_particle_bond(), ParticleLocal::ghost, ParticleProperties::identity, Particle::l, Cell::neighbors(), P, and Particle::p.
Referenced by three_particle_binding_domain_decomposition().
three_particle_binding_domain_decomposition()
void three_particle_binding_domain_decomposition (const std::vector< CollisionPair > & gathered_queue)
Definition at line 476 of file collision.cpp.
References D3Q19::c, cell_structure, find_current_cell(), CellStructure::get_local_particle(), and three_particle_binding_do_search().
Referenced by handle_collisions().
validate_collision_parameters()
bool validate_collision_parameters ()
Validates collision parameters and creates particle types if needed.
Definition at line 106 of file collision.cpp.
References Collision_parameters::bond_centers, Collision_parameters::bond_three_particles, Collision_parameters::bond_vs, bonded_ia_params, COLLISION_MODE_BIND_THREE_PARTICLES, COLLISION_MODE_BOND, COLLISION_MODE_GLUE_TO_SURF, COLLISION_MODE_OFF, COLLISION_MODE_VS, collision_params, Collision_parameters::distance, Collision_parameters::distance2, get_bond_num_partners(), make_particle_type_exist(), Collision_parameters::mode, on_short_range_ia_change(), Collision_parameters::part_type_after_glueing, Collision_parameters::part_type_to_attach_vs_to, Collision_parameters::part_type_to_be_glued, runtimeErrorMsg, Utils::sqr(), this_node, Collision_parameters::three_particle_angle_resolution, Collision_parameters::vs_particle_type, and Collision_parameters::vs_placement.
Referenced by ScriptInterface::CollisionDetection::CollisionDetection::do_call_method().
Variable Documentation
collision_params
Collision_parameters collision_params
Parameters for collision detection.
Definition at line 75 of file collision.cpp.
Referenced by bind_at_poc_create_bond_between_vs(), bind_at_point_of_collision_calc_vs_pos(), bind_centers(), coldet_do_three_particle_bond(), collision_detection_cutoff(), ScriptInterface::CollisionDetection::CollisionDetection::CollisionDetection(), detect_collision(), force_calc(), global_ghost_flags(), glue_to_surface_bind_part_to_vs(), glue_to_surface_calc_vs_pos(), glue_to_surface_criterion(), handle_collisions(), place_vs_and_relate_to_particle(), and validate_collision_parameters().
local_collision_queue
std::vector<CollisionPair> local_collision_queue static
During force calculation, colliding particles are recorded in the queue. The queue is processed after force calculation, when it is safe to add particles.
Definition at line 72 of file collision.cpp.
Referenced by gather_global_collision_queue(), handle_collisions(), prepare_local_collision_queue(), and queue_collision().