ESPResSo: collision.hpp File Reference
collision.hpp File Reference
#include "config.hpp"
#include "BondList.hpp"
#include "Particle.hpp"
Classes
class Collision_parameters
Macros
bits of possible modes for collision handling.
The modes can be combined by or-ing together, but not all combinations are possible.
#define COLLISION_MODE_OFF 0
#define COLLISION_MODE_BOND 2
Just create bond between centers of colliding particles.
#define COLLISION_MODE_VS 4
Create a bond between the centers of the colliding particles, plus two virtual sites at the point of collision and bind them together.
#define COLLISION_MODE_GLUE_TO_SURF 8
Glue a particle to a specific spot on the surface of an other.
#define COLLISION_MODE_BIND_THREE_PARTICLES 16
Three particle binding mode.
Functions
void prepare_local_collision_queue ()
void handle_collisions ()
Handle the collisions recorded in the queue.
bool validate_collision_parameters ()
Validates collision parameters and creates particle types if needed.
void queue_collision (int part1, int part2)
Add the collision between the given particle ids to the collision queue.
bool glue_to_surface_criterion (Particle const &p1, Particle const &p2)
Check additional criteria for the glue_to_surface collision mode.
void detect_collision (Particle const &p1, Particle const &p2, const double &dist_betw_part2)
Detect (and queue) a collision between the given particles.
double collision_detection_cutoff ()
Variables
Collision_parameters collision_params
Parameters for collision detection.
Macro Definition Documentation
COLLISION_MODE_BIND_THREE_PARTICLES
#define COLLISION_MODE_BIND_THREE_PARTICLES 16
Three particle binding mode.
Definition at line 44 of file collision.hpp.
COLLISION_MODE_BOND
#define COLLISION_MODE_BOND 2
Just create bond between centers of colliding particles.
Definition at line 34 of file collision.hpp.
COLLISION_MODE_GLUE_TO_SURF
#define COLLISION_MODE_GLUE_TO_SURF 8
Glue a particle to a specific spot on the surface of an other.
Definition at line 42 of file collision.hpp.
COLLISION_MODE_OFF
#define COLLISION_MODE_OFF 0
Definition at line 32 of file collision.hpp.
COLLISION_MODE_VS
#define COLLISION_MODE_VS 4
Create a bond between the centers of the colliding particles, plus two virtual sites at the point of collision and bind them together.
This prevents the particles from sliding against each other. Requires VIRTUAL_SITES_RELATIVE and COLLISION_MODE_BOND
Definition at line 40 of file collision.hpp.
Function Documentation
collision_detection_cutoff()
double collision_detection_cutoff () inline
Definition at line 159 of file collision.hpp.
References collision_params, Collision_parameters::distance, and Collision_parameters::mode.
Referenced by force_calc(), and maximal_cutoff().
detect_collision()
void detect_collision (Particle const & p1, Particle const & p2, const double & dist_betw_part2) inline
Detect (and queue) a collision between the given particles.
Definition at line 123 of file collision.hpp.
References Collision_parameters::bond_centers, Particle::bonds(), COLLISION_MODE_GLUE_TO_SURF, collision_params, Collision_parameters::distance2, ParticleLocal::ghost, glue_to_surface_criterion(), ParticleProperties::identity, Particle::identity(), ParticleProperties::is_virtual, Particle::l, Collision_parameters::mode, Particle::p, pair_bond_exists_on(), and queue_collision().
Referenced by force_calc().
glue_to_surface_criterion()
bool glue_to_surface_criterion (Particle const & p1, Particle const & p2) inline
Check additional criteria for the glue_to_surface collision mode.
Definition at line 115 of file collision.hpp.
References collision_params, Particle::p, Collision_parameters::part_type_to_attach_vs_to, Collision_parameters::part_type_to_be_glued, and ParticleProperties::type.
Referenced by detect_collision().
handle_collisions()
void handle_collisions ()
Handle the collisions recorded in the queue.
Definition at line 499 of file collision.cpp.
References Utils::Mpi::all_compare(), bind_at_poc_create_bond_between_vs(), bind_at_point_of_collision_calc_vs_pos(), bind_centers(), Collision_parameters::bond_centers, Particle::bonds(), D3Q19::c, cell_structure, cells_update_ghosts(), COLLISION_MODE_BIND_THREE_PARTICLES, COLLISION_MODE_GLUE_TO_SURF, COLLISION_MODE_VS, collision_params, comm_cart, Cells::DATA_PART_BONDS, Cells::DATA_PART_PROPERTIES, Collision_parameters::exception_on_collision, gather_global_collision_queue(), CellStructure::get_local_particle(), CellStructure::get_max_local_particle_id(), anonymous_namespace{collision.cpp}::get_part(), ParticleLocal::ghost, glue_to_surface_bind_part_to_vs(), glue_to_surface_calc_vs_pos(), Particle::identity(), Particle::l, local_collision_queue, anonymous_namespace{Correlator.cpp}::min(), Collision_parameters::mode, Particle::p, Collision_parameters::part_type_after_glueing, Collision_parameters::part_type_to_be_glued, place_vs_and_relate_to_particle(), pos, Cells::RESORT_GLOBAL, ParticleProperties::rotation, ROTATION_X, ROTATION_Y, ROTATION_Z, runtimeWarningMsg, CellStructure::set_resort_particles(), three_particle_binding_domain_decomposition(), and ParticleProperties::type.
Referenced by integrate().
prepare_local_collision_queue()
void prepare_local_collision_queue ()
Definition at line 258 of file collision.cpp.
References local_collision_queue.
Referenced by force_calc().
queue_collision()
void queue_collision (int part1, int part2)
Add the collision between the given particle ids to the collision queue.
Definition at line 260 of file collision.cpp.
References local_collision_queue.
Referenced by detect_collision().
validate_collision_parameters()
bool validate_collision_parameters ()
Validates collision parameters and creates particle types if needed.
Definition at line 106 of file collision.cpp.
References Collision_parameters::bond_centers, Collision_parameters::bond_three_particles, Collision_parameters::bond_vs, bonded_ia_params, COLLISION_MODE_BIND_THREE_PARTICLES, COLLISION_MODE_BOND, COLLISION_MODE_GLUE_TO_SURF, COLLISION_MODE_OFF, COLLISION_MODE_VS, collision_params, Collision_parameters::distance, Collision_parameters::distance2, get_bond_num_partners(), make_particle_type_exist(), Collision_parameters::mode, on_short_range_ia_change(), Collision_parameters::part_type_after_glueing, Collision_parameters::part_type_to_attach_vs_to, Collision_parameters::part_type_to_be_glued, runtimeErrorMsg, Utils::sqr(), this_node, Collision_parameters::three_particle_angle_resolution, Collision_parameters::vs_particle_type, and Collision_parameters::vs_placement.
Referenced by ScriptInterface::CollisionDetection::CollisionDetection::do_call_method().
Variable Documentation
collision_params
Collision_parameters collision_params
Parameters for collision detection.
Definition at line 75 of file collision.cpp.
Referenced by bind_at_poc_create_bond_between_vs(), bind_at_point_of_collision_calc_vs_pos(), bind_centers(), coldet_do_three_particle_bond(), collision_detection_cutoff(), ScriptInterface::CollisionDetection::CollisionDetection::CollisionDetection(), detect_collision(), force_calc(), global_ghost_flags(), glue_to_surface_bind_part_to_vs(), glue_to_surface_calc_vs_pos(), glue_to_surface_criterion(), handle_collisions(), place_vs_and_relate_to_particle(), and validate_collision_parameters().