ESPResSo: common.hpp File Reference
common.hpp File Reference
Functions
void mpi_bcast_coulomb_params ()
Send new Coulomb/Dipole parameters.
Function Documentation
mpi_bcast_coulomb_params()
void mpi_bcast_coulomb_params ()
Send new Coulomb/Dipole parameters.
Definition at line 52 of file common.cpp.
References mpi_bcast_coulomb_params_local(), and mpi_call_all().
Referenced by activate_dipolar_barnes_hut(), activate_dipolar_direct_sum_gpu(), dawaanr_set_params(), Coulomb::deactivate_method(), dh_set_params(), dp3m_adaptive_tune(), dp3m_mcr_time(), dp3m_set_eps(), dp3m_set_mesh_offset(), dp3m_set_params(), ELC_set_params(), mdds_set_params(), mdlc_set_params(), MMM1D_set_params(), mmm1d_tune(), p3m_adaptive_tune(), p3m_mcr_time(), p3m_set_eps(), p3m_set_mesh_offset(), p3m_set_params(), rf_set_params(), Dipole::set_Dprefactor(), and Coulomb::set_prefactor().