ESPResSo: communication.hpp File Reference
communication.hpp File Reference
#include "MpiCallbacks.hpp"
#include <boost/mpi/communicator.hpp>
#include <memory>
#include <utility>
Namespaces
Communication
Macros
#define SOME_TAG 42
Default MPI tag used by callbacks.
Functions
MpiCallbacks & Communication::mpiCallbacks ()
Returns a reference to the global callback class instance.
std::shared_ptr< boost::mpi::environment > mpi_init (int argc=0, char **argv=nullptr)
Initialize MPI.
template<class... Args, class... ArgRef>
void mpi_call (void(*fp)(Args...), ArgRef &&... args)
Call a slave function.
template<class... Args, class... ArgRef>
void mpi_call_all (void(*fp)(Args...), ArgRef &&... args)
Call a slave function.
template<class Tag , class R , class... Args, class... ArgRef>
auto mpi_call (Tag tag, R(*fp)(Args...), ArgRef &&... args)
Call a slave function.
template<class Tag , class TagArg , class R , class... Args, class... ArgRef>
auto mpi_call (Tag tag, TagArg &&tag_arg, R(*fp)(Args...), ArgRef &&... args)
Call a slave function.
void mpi_loop ()
Process requests from master node.
void Communication::init (std::shared_ptr< boost::mpi::environment > mpi_env)
Init globals for communication.
Variables
int this_node
The number of this node.
int n_nodes
The total number of nodes.
boost::mpi::communicator comm_cart
The communicator.
Detailed Description
This file contains the asynchronous MPI communication.
It is the header file for communication.cpp.
The asynchronous MPI communication is used during the script evaluation. Except for the master node that interprets the interface script, all other nodes wait in mpi_loop() for the master node to issue an action using mpi_call(). mpi_loop() immediately executes an MPI_Bcast and therefore waits for the master node to broadcast a command, which is done by mpi_call(). The request consists of a callback function and two arbitrary integers. If applicable, the first integer is the node number of the slave this request is dedicated to.
To add new actions (e.g. to implement new interface functionality), do the following:
write the mpi_* function that is executed on the master
write the mpi_*_slave function
register your slave function with one of the REGISTER_CALLBACK macros
After this, your procedure is free to do anything. However, it has to be in (MPI) sync with what your new mpi_*_slave does. This procedure is called immediately after the broadcast with the arbitrary integer as parameter.
Definition in file communication.hpp.
Macro Definition Documentation
SOME_TAG
#define SOME_TAG 42
Default MPI tag used by callbacks.
Definition at line 68 of file communication.hpp.
Function Documentation
mpi_call() [1/3]
template<class Tag , class R , class... Args, class... ArgRef> auto mpi_call (Tag tag, R(*)(Args...) fp, ArgRef &&... args)
Call a slave function.
Template Parameters
Tag Any tag type defined in Communication::Result
R Return type of the slave function
Args Slave function argument types
ArgRef Slave function argument types
Parameters
tag Reduction strategy
fp Slave function
args Slave function arguments
Definition at line 120 of file communication.hpp.
References Communication::mpiCallbacks().
mpi_call() [2/3]
template<class Tag , class TagArg , class R , class... Args, class... ArgRef> auto mpi_call (Tag tag, TagArg && tag_arg, R(*)(Args...) fp, ArgRef &&... args)
Call a slave function.
Template Parameters
Tag Any tag type defined in Communication::Result
TagArg Types of arguments to Tag
R Return type of the slave function
Args Slave function argument types
ArgRef Slave function argument types
Parameters
tag Reduction strategy
tag_arg Arguments to the reduction strategy
fp Slave function
args Slave function arguments
Definition at line 137 of file communication.hpp.
References Communication::mpiCallbacks().
mpi_call() [3/3]
template<class... Args, class... ArgRef> void mpi_call (void(*)(Args...) fp, ArgRef &&... args)
Call a slave function.
Template Parameters
Args Slave function argument types
ArgRef Slave function argument types
Parameters
fp Slave function
args Slave function arguments
Definition at line 95 of file communication.hpp.
References Communication::mpiCallbacks().
Referenced by calculate_energy(), calculate_pressure(), cuda_gather_gpus(), dpd_stress(), Scafacos::free_handle(), lb_fluid_set_rng_state(), lb_lbfluid_calc_fluid_momentum(), lb_lbfluid_get_interpolated_density(), lb_lbfluid_get_interpolated_velocity(), lb_lbfluid_save_checkpoint(), lb_lbnode_get_boundary(), lb_lbnode_get_pop(), lb_lbnode_get_pressure_tensor_neq(), LBBoundaries::lbboundary_get_force(), mdlc_tune_far_cut(), mpi_bcast_lb_params(), mpi_bcast_lb_particle_coupling(), mpi_get_particles(), mpi_icc_init(), mpi_integrate(), mpi_non_bonded_loop_trace(), mpi_place_new_particle(), mpi_place_particle(), mpi_rescale_particles(), mpi_resort_particles(), mpi_rotate_system(), mpi_send_update_message(), mpi_steepest_descent(), mpi_system_CMS(), mpi_system_CMS_velocity(), mpi_who_has(), and REGISTER_CALLBACK_REDUCTION().
mpi_call_all()
template<class... Args, class... ArgRef> void mpi_call_all (void(*)(Args...) fp, ArgRef &&... args)
Call a slave function.
Template Parameters
Args Slave function argument types
ArgRef Slave function argument types
Parameters
fp Slave function
args Slave function arguments
Definition at line 106 of file communication.hpp.
References Communication::MpiCallbacks::call_all(), and Communication::mpiCallbacks().
Referenced by cuda_bcast_global_part_params(), dp3m_adaptive_tune(), lb_lbinterpolation_set_interpolation_order(), lb_lbnode_set_density(), lb_lbnode_set_pop(), lb_lbnode_set_velocity(), mpi_bcast_all_ia_params(), mpi_bcast_cell_structure(), mpi_bcast_coulomb_params(), mpi_bcast_ia_params(), mpi_bcast_nptiso_geom_barostat(), mpi_bcast_steepest_descent(), mpi_galilei_transform(), mpi_kill_particle_forces(), mpi_kill_particle_motion(), mpi_realloc_ia_params(), mpi_remove_particle(), mpi_send_exclusion(), mpi_set_box_length(), mpi_set_brownian_gamma(), mpi_set_brownian_gamma_rot(), mpi_set_forcecap(), mpi_set_integ_switch(), mpi_set_langevin_gamma(), mpi_set_langevin_gamma_rot(), mpi_set_lattice_switch(), mpi_set_max_oif_objects(), mpi_set_min_global_cut(), mpi_set_n_ibm_volcons_bonds(), mpi_set_n_rigidbonds(), mpi_set_n_thermalized_bonds(), mpi_set_node_grid(), mpi_set_nptiso_gammas(), mpi_set_periodicity(), mpi_set_skin(), mpi_set_temperature(), mpi_set_thermo_switch(), mpi_set_thermo_virtual(), mpi_set_time(), mpi_set_time_step(), mpi_set_use_verlet_lists(), p3m_adaptive_tune(), Scafacos::set_parameters(), and Scafacos::time_r_cut().
mpi_init()
std::shared_ptr<boost::mpi::environment> mpi_init (int argc = 0, char ** argv = nullptr)
Initialize MPI.
Definition at line 142 of file communication.cpp.
Referenced by EspressoSystemStandAlone::EspressoSystemStandAlone().
mpi_loop()
void mpi_loop ()
Process requests from master node.
Slave nodes main loop.
Definition at line 151 of file communication.cpp.
References Communication::MpiCallbacks::loop(), Communication::mpiCallbacks(), and this_node.
Referenced by EspressoSystemStandAlone::EspressoSystemStandAlone().
Variable Documentation
comm_cart
boost::mpi::communicator comm_cart
The communicator.
Definition at line 47 of file communication.cpp.
Referenced by Coulomb::bcast_coulomb_params(), calc_mu_max(), calc_slab_dipole(), calc_surface_term(), cells_re_init(), cells_update_ghosts(), correct_position_shake(), correct_velocity_shake(), cuda_bcast_global_part_params_local(), cuda_mpi_get_particles(), cuda_mpi_send_forces(), distribute(), dp3m_average_dipolar_self_energy(), dp3m_calc_kspace_forces(), dp3m_count_magnetic_particles(), dp3m_init(), ELC_P3M_modify_p3m_sums_both(), ELC_P3M_modify_p3m_sums_image(), ELC_P3M_restore_p3m_sums(), force_calc(), gather_global_collision_queue(), get_DLC_dipolar(), get_DLC_energy_dipolar(), get_pairs_local(), get_pairs_of_types_local(), grid_changed_box_l(), grid_changed_n_nodes(), halo_communication(), halo_push_communication(), handle_collisions(), IBM_cuda_mpi_get_particles(), IBM_cuda_mpi_send_velocities(), icc_iteration(), Communication::init(), integrate(), lb_calc_fluid_momentum(), lb_check_halo_regions(), lb_collect_boundary_forces(), lb_init(), LBBoundaries::lb_init_boundaries(), local_rotate_system(), map_position_node_array(), mpi_bcast_all_ia_params_local(), mpi_bcast_coulomb_params_local(), mpi_bcast_ia_params_local(), mpi_bcast_lb_particle_coupling(), mpi_bcast_lb_particle_coupling_slave(), mpi_bcast_nptiso_geom_barostat_worker(), mpi_bcast_steepest_descent_worker(), mpi_get_particles(), mpi_get_particles_local(), mpi_icc_init(), mpi_icc_init_local(), mpi_non_bonded_loop_trace(), mpi_place_new_particle_local(), mpi_place_particle(), mpi_place_particle_local(), Observable_stat::mpi_reduce(), mpi_rescale_particles(), mpi_rescale_particles_local(), mpi_resort_particles(), mpi_resort_particles_local(), mpi_rotate_system(), mpi_rotate_system_local(), mpi_send_update_message(), mpi_send_update_message_local(), mpi_who_has(), mpi_who_has_local(), non_bonded_loop_trace(), non_bonded_loop_trace_local(), object_container_mpi_guard(), on_integration_start(), p3m_calc_kspace_forces(), p3m_calc_kspace_pressure_tensor(), p3m_count_charged_particles(), p3m_init(), prefetch_particle_data(), prepare_halo_communication(), Scafacos::set_parameters_coulomb_worker(), Scafacos::set_parameters_dipoles_worker(), steepest_descent_step(), stokesian_dynamics_propagate_vel_pos(), synchronize_npt_state(), Constraints::ShapeBasedConstraint::total_force(), Constraints::ShapeBasedConstraint::total_normal_force(), Scafacos::ScafacosContext::update_system_params(), velocity_verlet_npt_finalize_p_inst(), and velocity_verlet_npt_propagate_pos().
n_nodes
int n_nodes
The total number of nodes.
Definition at line 63 of file communication.cpp.
Referenced by calculate_vs_relate_to_params(), dawaanr_calculations(), dawaanr_set_params(), Communication::init(), lb_check_halo_regions(), magnetic_dipolar_direct_sum_calculations(), mdds_set_params(), mpi_cuda_gather_gpus_local(), mpi_rescale_particles(), and mpi_who_has().
this_node
int this_node
The number of this node.
Definition at line 62 of file communication.cpp.