ESPResSo: debye_hueckel.hpp File Reference
debye_hueckel.hpp File Reference
#include "config.hpp"
#include <utils/Vector.hpp>
#include <cmath>
Classes
struct DebyeHueckelParameters
Debye-H端ckel parameters.
Functions
void dh_set_params (double kappa, double r_cut)
void add_dh_coulomb_pair_force (double const q1q2, Utils::Vector3d const &d, double const dist, Utils::Vector3d &force)
Compute the Debye-Hueckel pair force.
double dh_coulomb_pair_energy (double const q1q2, double const dist)
Compute the Debye-Hueckel pair energy.
Variables
DebyeHueckelParameters dh_params
Global state of the Debye-H端ckel method.
Detailed Description
Routines to calculate the Debye-H端ckel energy and force for a particle pair.
Definition in file debye_hueckel.hpp.
Function Documentation
add_dh_coulomb_pair_force()
void add_dh_coulomb_pair_force (double const q1q2, Utils::Vector3d const & d, double const dist, Utils::Vector3d & force) inline
Compute the Debye-Hueckel pair force.
Parameters
[in] q1q2 Product of the charges on p1 and p2.
[in] d Vector pointing from p1 to p2.
[in] dist Distance between p1 and p2.
[out] force Calculated force on p1.
Definition at line 54 of file debye_hueckel.hpp.
References dh_params, force, DebyeHueckelParameters::kappa, and DebyeHueckelParameters::r_cut.
Referenced by Coulomb::central_force().
dh_coulomb_pair_energy()
double dh_coulomb_pair_energy (double const q1q2, double const dist) inline
Compute the Debye-Hueckel pair energy.
Parameters
q1q2 Product of the charges on p1 and p2.
dist Distance between p1 and p2.
Definition at line 74 of file debye_hueckel.hpp.
References dh_params, DebyeHueckelParameters::kappa, and DebyeHueckelParameters::r_cut.
Referenced by Coulomb::pair_energy().
dh_set_params()
void dh_set_params (double kappa, double r_cut)
Definition at line 35 of file debye_hueckel.cpp.
References dh_params, and mpi_bcast_coulomb_params().
Variable Documentation
dh_params
DebyeHueckelParameters dh_params
Global state of the Debye-H端ckel method.
Definition at line 33 of file debye_hueckel.cpp.
Referenced by add_dh_coulomb_pair_force(), Coulomb::bcast_coulomb_params(), Coulomb::cutoff(), Coulomb::deactivate(), dh_coulomb_pair_energy(), and dh_set_params().