ESPResSo: DipolarDirectSum.hpp File Reference
DipolarDirectSum.hpp File Reference
#include "config.hpp"
#include "Actor.hpp"
#include "SystemInterface.hpp"
#include "cuda_interface.hpp"
#include "electrostatics_magnetostatics/dipole.hpp"
#include "errorhandling.hpp"
#include "grid.hpp"
#include <memory>
Classes
class DipolarDirectSum
Functions
void DipolarDirectSum_kernel_wrapper_energy (float k, int n, float *pos, float *dip, float box_l[3], int periodic[3], float *E)
void DipolarDirectSum_kernel_wrapper_force (float k, int n, float *pos, float *dip, float *f, float *torque, float box_l[3], int periodic[3])
void activate_dipolar_direct_sum_gpu ()
void deactivate_dipolar_direct_sum_gpu ()
Variables
std::unique_ptr< DipolarDirectSum > dipolarDirectSum
Function Documentation
activate_dipolar_direct_sum_gpu()
void activate_dipolar_direct_sum_gpu ()
Definition at line 35 of file DipolarDirectSum.cpp.
References DIPOLAR_DS_GPU, dipolarDirectSum, dipole, energyActors, espressoSystemInterface, forceActors, Dipole_parameters::method, and mpi_bcast_coulomb_params().
deactivate_dipolar_direct_sum_gpu()
void deactivate_dipolar_direct_sum_gpu ()
Definition at line 46 of file DipolarDirectSum.cpp.
References dipolarDirectSum, energyActors, forceActors, and ActorList::remove().
Referenced by Dipole::set_method_local().
DipolarDirectSum_kernel_wrapper_energy()
void DipolarDirectSum_kernel_wrapper_energy (float k, int n, float * pos, float * dip, float box_l[3], int periodic[3], float * E)
Definition at line 286 of file DipolarDirectSum_cuda.cu.
References block(), cuda_safe_mem, DipolarDirectSum_kernel_energy(), energySum, KERNELCALL_shared, and pos.
Referenced by DipolarDirectSum::computeEnergy().
DipolarDirectSum_kernel_wrapper_force()
void DipolarDirectSum_kernel_wrapper_force (float k, int n, float * pos, float * dip, float * f, float * torque, float box_l[3], int periodic[3])
Definition at line 252 of file DipolarDirectSum_cuda.cu.
References block(), cuda_safe_mem, DipolarDirectSum_kernel_force(), f, KERNELCALL, pos, and torque.
Referenced by DipolarDirectSum::computeForces().
Variable Documentation
dipolarDirectSum
std::unique_ptr<DipolarDirectSum> dipolarDirectSum
Definition at line 33 of file DipolarDirectSum.cpp.
Referenced by activate_dipolar_direct_sum_gpu(), and deactivate_dipolar_direct_sum_gpu().