ESPResSo: DipolarDirectSum_cuda.cu File Reference
DipolarDirectSum_cuda.cu File Reference
#include "config.hpp"
#include "cuda_utils.cuh"
#include <thrust/device_ptr.h>
#include <thrust/reduce.h>
#include <cuda.h>
Macros
#define scalar(a, b) ((a)[0] * (b)[0] + (a)[1] * (b)[1] + (a)[2] * (b)[2])
Functions
__device__ void get_mi_vector_dds (float res[3], float const a[3], float const b[3], float const box_l[3], int const periodic[3])
__device__ void dipole_ia_force (int id, float pf, float const *r1, float const *r2, float const *dip1, float const *dip2, float *f1, float *torque1, float *torque2, float box_l[3], int periodic[3])
__device__ float dipole_ia_energy (int id, float pf, float const *r1, float const *r2, float const *dip1, float const *dip2, float box_l[3], int periodic[3])
__global__ void DipolarDirectSum_kernel_force (float pf, int n, float *pos, float *dip, float *f, float *torque, float box_l[3], int periodic[3])
__device__ void dds_sumReduction (float *input, float *sum)
__global__ void DipolarDirectSum_kernel_energy (float pf, int n, float *pos, float *dip, float box_l[3], int periodic[3], float *energySum)
void DipolarDirectSum_kernel_wrapper_force (float k, int n, float *pos, float *dip, float *f, float *torque, float box_l[3], int periodic[3])
void DipolarDirectSum_kernel_wrapper_energy (float k, int n, float *pos, float *dip, float box_l[3], int periodic[3], float *E)
Macro Definition Documentation
scalar
#define scalar (a, b) ((a)[0] * (b)[0] + (a)[1] * (b)[1] + (a)[2] * (b)[2])
Definition at line 45 of file DipolarDirectSum_cuda.cu.
Function Documentation
dds_sumReduction()
__device__ void dds_sumReduction (float * input, float * sum)
Definition at line 206 of file DipolarDirectSum_cuda.cu.
References __syncthreads(), and sum.
Referenced by DipolarDirectSum_kernel_energy().
DipolarDirectSum_kernel_energy()
__global__ void DipolarDirectSum_kernel_energy (float pf, int n, float * pos, float * dip, float box_l[3], int periodic[3], float * energySum)
Definition at line 221 of file DipolarDirectSum_cuda.cu.
References __syncthreads(), dds_sumReduction(), dipole_ia_energy(), energySum, pos, res, and sum.
Referenced by DipolarDirectSum_kernel_wrapper_energy().
DipolarDirectSum_kernel_force()
__global__ void DipolarDirectSum_kernel_force (float pf, int n, float * pos, float * dip, float * f, float * torque, float box_l[3], int periodic[3])
Definition at line 155 of file DipolarDirectSum_cuda.cu.
References dipole_ia_force(), f, pos, and torque.
Referenced by DipolarDirectSum_kernel_wrapper_force().
DipolarDirectSum_kernel_wrapper_energy()
void DipolarDirectSum_kernel_wrapper_energy (float k, int n, float * pos, float * dip, float box_l[3], int periodic[3], float * E)
Definition at line 286 of file DipolarDirectSum_cuda.cu.
References block(), cuda_safe_mem, DipolarDirectSum_kernel_energy(), energySum, KERNELCALL_shared, and pos.
Referenced by DipolarDirectSum::computeEnergy().
DipolarDirectSum_kernel_wrapper_force()
void DipolarDirectSum_kernel_wrapper_force (float k, int n, float * pos, float * dip, float * f, float * torque, float box_l[3], int periodic[3])
Definition at line 252 of file DipolarDirectSum_cuda.cu.
References block(), cuda_safe_mem, DipolarDirectSum_kernel_force(), f, KERNELCALL, pos, and torque.
Referenced by DipolarDirectSum::computeForces().
dipole_ia_energy()
__device__ float dipole_ia_energy (int id, float pf, float const * r1, float const * r2, float const * dip1, float const * dip2, float box_l[3], int periodic[3])
Definition at line 120 of file DipolarDirectSum_cuda.cu.
References dr, get_mi_vector_dds(), and scalar.
Referenced by DipolarDirectSum_kernel_energy().
dipole_ia_force()
__device__ void dipole_ia_force (int id, float pf, float const * r1, float const * r2, float const * dip1, float const * dip2, float * f1, float * torque1, float * torque2, float box_l[3], int periodic[3])
Definition at line 47 of file DipolarDirectSum_cuda.cu.
References b, dr, get_mi_vector_dds(), and scalar.
Referenced by DipolarDirectSum_kernel_force().
get_mi_vector_dds()
__device__ void get_mi_vector_dds (float res[3], float const a[3], float const b[3], float const box_l[3], int const periodic[3]) inline
Definition at line 35 of file DipolarDirectSum_cuda.cu.
References b, f, and res.
Referenced by dipole_ia_energy(), and dipole_ia_force().