ESPResSo: elc.cpp File Reference
elc.cpp File Reference
#include "config.hpp"
#include "electrostatics_magnetostatics/elc.hpp"
#include "electrostatics_magnetostatics/common.hpp"
#include "electrostatics_magnetostatics/coulomb.hpp"
#include "electrostatics_magnetostatics/mmm-common.hpp"
#include "electrostatics_magnetostatics/p3m.hpp"
#include "Particle.hpp"
#include "ParticleRange.hpp"
#include "communication.hpp"
#include "errorhandling.hpp"
#include "grid.hpp"
#include <utils/Vector.hpp>
#include <utils/constants.hpp>
#include <utils/math/sqr.hpp>
#include <mpi.h>
#include <cassert>
#include <cmath>
#include <cstddef>
#include <vector>
Namespaces
anonymous_namespace{elc.cpp}
Macros
Product decomposition data organization
For the cell blocks it is assumed that the lower blocks part is in the lower half.
This has to have positive sign, so that has to be first.
#define POQESP 0
#define POQECP 1
#define POQESM 2
#define POQECM 3
#define PQESSP 0
#define PQESCP 1
#define PQECSP 2
#define PQECCP 3
#define PQESSM 4
#define PQESCM 5
#define PQECSM 6
#define PQECCM 7
Enumerations
enum PoQ : int { PoQ::P, PoQ::Q }
ELC axes (x and y directions)
Functions
static void distribute (std::size_t size)
static void add_dipole_force (const ParticleRange &particles)
Calculate the dipole force.
static double dipole_energy (const ParticleRange &particles)
Calculate the dipole energy.
static double z_energy (const ParticleRange &particles)
static void add_z_force (const ParticleRange &particles)
template<std::size_t dir>
static std::vector< SCCache > calc_sc_cache (const ParticleRange &particles, std::size_t n_freq, double u)
Calculate cached sin/cos values for one direction.
static void prepare_sc_cache (const ParticleRange &particles, std::size_t n_freq_x, double u_x, std::size_t n_freq_y, double u_y)
void clear_vec (double *pdc, std::size_t size)
void copy_vec (double *pdc_d, double const *pdc_s, std::size_t size)
void add_vec (double *pdc_d, double const *pdc_s1, double const *pdc_s2, std::size_t size)
void addscale_vec (double *pdc_d, double scale, double const *pdc_s1, double const *pdc_s2, std::size_t size)
void scale_vec (double scale, double *pdc, std::size_t size)
double * block (double *p, std::size_t index, std::size_t size)
void check_gap_elc (const Particle &p)
Checks if a charged particle is in the forbidden gap region.
double image_sum_b (double q, double z)
double image_sum_t (double q, double z)
void ELC_add_force (const ParticleRange &particles)
the force calculation
double ELC_energy (const ParticleRange &particles)
the energy calculation
double ELC_tune_far_cut (ELCParameters const &params)
void ELC_sanity_checks (ELCParameters const &params)
check the ELC parameters
void ELC_init ()
initialize the ELC constants
void ELC_set_params (double maxPWerror, double gap_size, double far_cut, bool neutralize, double delta_top, double delta_bot, bool const_pot, double pot_diff)
Set parameters for ELC.
void ELC_P3M_self_forces (const ParticleRange &particles)
forces of particles in border layers with themselves
void anonymous_namespace{elc.cpp}::assign_image_charge (const Particle &p)
void ELC_p3m_charge_assign_both (const ParticleRange &particles)
assign the additional, virtual charges, used only in energy.cpp
void ELC_p3m_charge_assign_image (const ParticleRange &particles)
assign the additional, virtual charges, used only in energy.cpp
Utils::Vector3d ELC_P3M_dielectric_layers_force_contribution (const Utils::Vector3d &pos1, const Utils::Vector3d &pos2, double q1q2)
pairwise contributions from the lowest and top layers to the force
double ELC_P3M_dielectric_layers_energy_contribution (Utils::Vector3d const &pos1, Utils::Vector3d const &pos2, double q1q2)
double ELC_P3M_dielectric_layers_energy_contribution (Particle const &p1, Particle const &p2)
pairwise contributions from the lowest and top layers to the energy
double ELC_P3M_dielectric_layers_energy_self (ParticleRange const &particles)
self energies of top and bottom layers with their virtual images
void ELC_P3M_modify_p3m_sums_both (ParticleRange const &particles)
take into account the virtual charges in the charge sums, used in energy.cpp
void ELC_P3M_modify_p3m_sums_image (ParticleRange const &particles)
take into account the virtual charges in the charge sums, used in energy.cpp
void ELC_P3M_restore_p3m_sums (ParticleRange const &particles)
assign the additional, virtual charges, used only in energy.cpp
q=0 or p=0 per frequency code
template<PoQ axis>
void setup_PoQ (std::size_t index, double omega, const ParticleRange &particles)
template<PoQ axis>
void add_PoQ_force (const ParticleRange &particles)
static double PoQ_energy (double omega, std::size_t n_part)
p,q <> 0 per frequency code
static void setup_PQ (std::size_t index_p, std::size_t index_q, double omega, const ParticleRange &particles)
static void add_PQ_force (std::size_t index_p, std::size_t index_q, double omega, const ParticleRange &particles)
static double PQ_energy (double omega, std::size_t n_part)
Variables
ELCParameters elc_params
static std::vector< double > partblk
temporary buffers for product decomposition
static double gblcblk [8]
collected data from the other cells
static std::vector< SCCache > scxcache
Cached sin/cos values along the x-axis and y-axis.
static std::vector< SCCache > scycache
Detailed Description
Implementation of elc.hpp.
Definition in file elc.cpp.
Macro Definition Documentation
POQECM
#define POQECM 3
Definition at line 64 of file elc.cpp.
POQECP
#define POQECP 1
Definition at line 62 of file elc.cpp.
POQESM
#define POQESM 2
Definition at line 63 of file elc.cpp.
POQESP
#define POQESP 0
Definition at line 61 of file elc.cpp.
PQECCM
#define PQECCM 7
Definition at line 73 of file elc.cpp.
PQECCP
#define PQECCP 3
Definition at line 69 of file elc.cpp.
PQECSM
#define PQECSM 6
Definition at line 72 of file elc.cpp.
PQECSP
#define PQECSP 2
Definition at line 68 of file elc.cpp.
PQESCM
#define PQESCM 5
Definition at line 71 of file elc.cpp.
PQESCP
#define PQESCP 1
Definition at line 67 of file elc.cpp.
PQESSM
#define PQESSM 4
Definition at line 70 of file elc.cpp.
PQESSP
#define PQESSP 0
Definition at line 66 of file elc.cpp.
Enumeration Type Documentation
PoQ
enum PoQ : int strong
ELC axes (x and y directions)
Enumerator
P
Q
Definition at line 77 of file elc.cpp.
Function Documentation
add_dipole_force()
static void add_dipole_force (const ParticleRange & particles) static
Calculate the dipole force.
See [53].
Definition at line 206 of file elc.cpp.
References box_geo, check_gap_elc(), ELCParameters::const_pot, coulomb, ELCParameters::delta_mid_bot, ELCParameters::delta_mid_top, ELCParameters::dielectric_contrast_on, distribute(), elc_params, Coulomb_parameters::field_applied, Coulomb_parameters::field_induced, gblcblk, ELCParameters::h, BoxGeometry::length(), BoxGeometry::length_half(), BoxGeometry::length_inv(), ELCParameters::neutralize, Cells::particles(), Utils::pi(), ELCParameters::pot_diff, Coulomb_parameters::prefactor, anonymous_namespace{DomainDecomposition.cpp}::shift(), and ELCParameters::space_layer.
Referenced by ELC_add_force().
add_PoQ_force()
template<PoQ axis> void add_PoQ_force (const ParticleRange & particles)
Definition at line 616 of file elc.cpp.
References gblcblk, partblk, Cells::particles(), POQECM, POQECP, POQESM, and POQESP.
add_PQ_force()
static void add_PQ_force (std::size_t index_p, std::size_t index_q, double omega, const ParticleRange & particles) static
Definition at line 787 of file elc.cpp.
References box_geo, gblcblk, BoxGeometry::length_inv(), partblk, Cells::particles(), Utils::pi(), PQECCM, PQECCP, PQECSM, PQECSP, PQESCM, PQESCP, PQESSM, and PQESSP.
Referenced by ELC_add_force().
add_vec()
void add_vec (double * pdc_d, double const * pdc_s1, double const * pdc_s2, std::size_t size) inline
Definition at line 156 of file elc.cpp.
Referenced by setup_PoQ(), and setup_PQ().
add_z_force()
static void add_z_force (const ParticleRange & particles) static
Definition at line 449 of file elc.cpp.
References box_geo, clear_vec(), ELCParameters::const_pot, coulomb, ELCParameters::delta_mid_bot, ELCParameters::delta_mid_top, ELCParameters::dielectric_contrast_on, distribute(), elc_params, gblcblk, ELCParameters::h, BoxGeometry::length_inv(), Cells::particles(), Utils::pi(), Coulomb_parameters::prefactor, and ELCParameters::space_layer.
Referenced by ELC_add_force().
addscale_vec()
void addscale_vec (double * pdc_d, double scale, double const * pdc_s1, double const * pdc_s2, std::size_t size) inline
Definition at line 162 of file elc.cpp.
Referenced by setup_PoQ(), and setup_PQ().
block()
double* block (double * p, std::size_t index, std::size_t size) inline
Definition at line 173 of file elc.cpp.
Referenced by assign_charges(), assign_forces(), Utils::Interpolation::bspline_3d(), Utils::Interpolation::bspline_3d_gradient(), buildBoxBH(), buildTreeBH(), anonymous_namespace{fft.cpp}::calc_send_block(), cuda_check_errors_exit(), DipolarDirectSum_kernel_wrapper_energy(), DipolarDirectSum_kernel_wrapper_force(), energyBH(), forceBH(), initBHgpu(), p3m_gpu_init(), p3m_k_space_error_gpu(), setup_PoQ(), setup_PQ(), sortBH(), EspressoSystemInterface::split_particle_struct(), and summarizeBH().
calc_sc_cache()
template<std::size_t dir> static std::vector<SCCache> calc_sc_cache (const ParticleRange & particles, std::size_t n_freq, double u) static
Calculate cached sin/cos values for one direction.
Template Parameters
dir Index of the dimension to consider (e.g. 0 for x ...).
Parameters
particles Particle to calculate values for
n_freq Number of frequencies to calculate per particle
u Inverse box length
Returns
Calculated values.
Definition at line 116 of file elc.cpp.
References Cells::particles(), Utils::pi(), ParticleRange::size(), and u.
check_gap_elc()
void check_gap_elc (const Particle & p) inline
Checks if a charged particle is in the forbidden gap region.
Definition at line 187 of file elc.cpp.
References elc_params, ELCParameters::h, ParticleProperties::identity, ParticlePosition::p, Particle::p, ParticleProperties::q, Particle::r, and runtimeErrorMsg.
Referenced by add_dipole_force(), and dipole_energy().
clear_vec()
void clear_vec (double * pdc, std::size_t size) inline
Definition at line 146 of file elc.cpp.
Referenced by add_z_force(), setup_PoQ(), setup_PQ(), and z_energy().
copy_vec()
void copy_vec (double * pdc_d, double const * pdc_s, std::size_t size) inline
Definition at line 151 of file elc.cpp.
Referenced by distribute().
dipole_energy()
static double dipole_energy (const ParticleRange & particles) static
Calculate the dipole energy.
See [53].
Definition at line 273 of file elc.cpp.
References box_geo, check_gap_elc(), ELCParameters::const_pot, coulomb, ELCParameters::delta_mid_bot, ELCParameters::delta_mid_top, ELCParameters::dielectric_contrast_on, distribute(), elc_params, gblcblk, ELCParameters::h, BoxGeometry::length(), BoxGeometry::length_half(), BoxGeometry::length_inv(), ELCParameters::neutralize, Cells::particles(), Utils::pi(), ELCParameters::pot_diff, Coulomb_parameters::prefactor, anonymous_namespace{DomainDecomposition.cpp}::shift(), ELCParameters::space_layer, Utils::sqr(), and this_node.
Referenced by ELC_energy().
distribute()
void distribute (std::size_t size) static
Definition at line 177 of file elc.cpp.
References comm_cart, copy_vec(), and gblcblk.
Referenced by add_dipole_force(), add_z_force(), dipole_energy(), ELC_add_force(), ELC_energy(), and z_energy().
ELC_add_force()
void ELC_add_force (const ParticleRange & particles)
the force calculation
Definition at line 848 of file elc.cpp.
References add_dipole_force(), add_PQ_force(), add_z_force(), box_geo, distribute(), elc_params, ELCParameters::far_cut, ELCParameters::far_cut2, BoxGeometry::length(), BoxGeometry::length_inv(), partblk, Cells::particles(), Utils::pi(), prepare_sc_cache(), setup_PQ(), ParticleRange::size(), Utils::sqr(), and Utils::sqrt().
Referenced by Coulomb::calc_long_range_force().
ELC_energy()
double ELC_energy (const ParticleRange & particles)
the energy calculation
Definition at line 905 of file elc.cpp.
References box_geo, dipole_energy(), distribute(), elc_params, ELCParameters::far_cut, ELCParameters::far_cut2, BoxGeometry::length(), BoxGeometry::length_inv(), partblk, Cells::particles(), Utils::pi(), PoQ_energy(), PQ_energy(), prepare_sc_cache(), setup_PQ(), ParticleRange::size(), Utils::sqr(), Utils::sqrt(), and z_energy().
Referenced by Coulomb::calc_energy_long_range().
ELC_init()
void ELC_init ()
initialize the ELC constants
Definition at line 1040 of file elc.cpp.
References box_geo, ELCParameters::dielectric_contrast_on, elc_params, ELC_tune_far_cut(), ELCParameters::far_calculated, ELCParameters::far_cut, ELCParameters::far_cut2, ELCParameters::gap_size, ELCParameters::h, BoxGeometry::length(), anonymous_namespace{Correlator.cpp}::min(), ELCParameters::minimal_dist, p3m, p3m_data_struct_base::params, P3MParameters::r_cut, runtimeErrorMsg, ELCParameters::space_box, ELCParameters::space_layer, and Utils::sqr().
Referenced by Coulomb::init(), Coulomb::on_boxl_change(), and on_coulomb_change().
ELC_p3m_charge_assign_both()
void ELC_p3m_charge_assign_both (const ParticleRange & particles)
assign the additional, virtual charges, used only in energy.cpp
Definition at line 1171 of file elc.cpp.
References anonymous_namespace{elc.cpp}::assign_image_charge(), P3MParameters::cao, p3m_data_struct::inter_weights, p3m_data_struct::local_mesh, p3m, p3m_assign_charge(), p3m_data_struct_base::params, Cells::particles(), p3m_interpolation_cache::reset(), p3m_data_struct::rs_mesh, and P3MLocalMesh::size.
Referenced by Coulomb::calc_energy_long_range(), and Coulomb::calc_long_range_force().
ELC_p3m_charge_assign_image()
void ELC_p3m_charge_assign_image (const ParticleRange & particles)
assign the additional, virtual charges, used only in energy.cpp
Definition at line 1186 of file elc.cpp.
References anonymous_namespace{elc.cpp}::assign_image_charge(), p3m_data_struct::local_mesh, p3m, Cells::particles(), p3m_data_struct::rs_mesh, and P3MLocalMesh::size.
Referenced by Coulomb::calc_energy_long_range().
ELC_P3M_dielectric_layers_energy_contribution() [1/2]
double ELC_P3M_dielectric_layers_energy_contribution (Particle const & p1, Particle const & p2)
pairwise contributions from the lowest and top layers to the energy
Definition at line 1247 of file elc.cpp.
References ELC_P3M_dielectric_layers_energy_contribution(), ParticlePosition::p, Particle::p, ParticleProperties::q, and Particle::r.
ELC_P3M_dielectric_layers_energy_contribution() [2/2]
double ELC_P3M_dielectric_layers_energy_contribution (Utils::Vector3d const & pos1, Utils::Vector3d const & pos2, double q1q2)
Definition at line 1224 of file elc.cpp.
References box_geo, ELCParameters::delta_mid_bot, ELCParameters::delta_mid_top, elc_params, BoxGeometry::get_mi_vector(), ELCParameters::h, Utils::Vector< T, N >::norm(), p3m_pair_energy(), and ELCParameters::space_layer.
Referenced by ELC_P3M_dielectric_layers_energy_contribution(), ELC_P3M_dielectric_layers_energy_self(), and Coulomb::pair_energy().
ELC_P3M_dielectric_layers_energy_self()
double ELC_P3M_dielectric_layers_energy_self (ParticleRange const & particles)
self energies of top and bottom layers with their virtual images
Definition at line 1263 of file elc.cpp.
References ELC_P3M_dielectric_layers_energy_contribution(), and Cells::particles().
Referenced by Coulomb::calc_energy_long_range().
ELC_P3M_dielectric_layers_force_contribution()
Utils::Vector3d ELC_P3M_dielectric_layers_force_contribution (const Utils::Vector3d & pos1, const Utils::Vector3d & pos2, double q1q2)
pairwise contributions from the lowest and top layers to the force
Definition at line 1200 of file elc.cpp.
References box_geo, ELCParameters::delta_mid_bot, ELCParameters::delta_mid_top, elc_params, force, BoxGeometry::get_mi_vector(), ELCParameters::h, p3m_add_pair_force(), and ELCParameters::space_layer.
Referenced by ELC_P3M_self_forces(), and Coulomb::pair_force().
ELC_P3M_modify_p3m_sums_both()
void ELC_P3M_modify_p3m_sums_both (ParticleRange const & particles)
take into account the virtual charges in the charge sums, used in energy.cpp
Definition at line 1277 of file elc.cpp.
References comm_cart, ELCParameters::delta_mid_bot, ELCParameters::delta_mid_top, elc_params, ELCParameters::h, p3m, Cells::particles(), ELCParameters::space_layer, Utils::sqr(), p3m_data_struct::square_sum_q, p3m_data_struct::sum_q2, and p3m_data_struct::sum_qpart.
Referenced by Coulomb::calc_energy_long_range(), and Coulomb::calc_long_range_force().
ELC_P3M_modify_p3m_sums_image()
void ELC_P3M_modify_p3m_sums_image (ParticleRange const & particles)
take into account the virtual charges in the charge sums, used in energy.cpp
Definition at line 1313 of file elc.cpp.
References comm_cart, ELCParameters::delta_mid_bot, ELCParameters::delta_mid_top, elc_params, ELCParameters::h, p3m, Cells::particles(), ELCParameters::space_layer, Utils::sqr(), p3m_data_struct::square_sum_q, p3m_data_struct::sum_q2, and p3m_data_struct::sum_qpart.
Referenced by Coulomb::calc_energy_long_range().
ELC_P3M_restore_p3m_sums()
void ELC_P3M_restore_p3m_sums (ParticleRange const & particles)
assign the additional, virtual charges, used only in energy.cpp
Definition at line 1347 of file elc.cpp.
References comm_cart, p3m, Cells::particles(), Utils::sqr(), p3m_data_struct::square_sum_q, p3m_data_struct::sum_q2, and p3m_data_struct::sum_qpart.
Referenced by Coulomb::calc_energy_long_range(), and Coulomb::calc_long_range_force().
ELC_P3M_self_forces()
void ELC_P3M_self_forces (const ParticleRange & particles)
forces of particles in border layers with themselves
Definition at line 1143 of file elc.cpp.
References coulomb, ELC_P3M_dielectric_layers_force_contribution(), Cells::particles(), and Coulomb_parameters::prefactor.
Referenced by Coulomb::calc_long_range_force().
ELC_sanity_checks()
void ELC_sanity_checks (ELCParameters const & params)
check the ELC parameters
Definition at line 1009 of file elc.cpp.
References box_geo, p3m, params, BoxGeometry::periodic(), ROUND_ERROR_PREC, and p3m_data_struct::square_sum_q.
Referenced by ELC_set_params(), and Coulomb::sanity_checks().
ELC_set_params()
void ELC_set_params (double maxPWerror, double min_dist, double far_cut, bool neutralize, double delta_mid_top, double delta_mid_bot, bool const_pot, double pot_diff)
Set parameters for ELC.
Parameters
maxPWerror Maximal allowed pairwise error for the potential and force. Note that this counts for the plain 1/r contribution alone, without the prefactor and the charge prefactor.
min_dist Minimal distance of two charges for which the far formula is used.
far_cut Cutoff of the exponential sum. If -1, the cutoff is automatically calculated using the error formulas.
neutralize whether to add a neutralizing background. WARNING: This background exerts forces, which are dependent on the simulation box; especially the gap size enters into the value of the forces.
delta_mid_top dielectric contrast in the upper part of the simulation cell.
delta_mid_bot dielectric contrast in the lower part of the simulation cell.
const_pot Flag whether a const. potential is applied.
pot_diff Const. potential.
Definition at line 1079 of file elc.cpp.
References box_geo, coulomb, COULOMB_ELC_P3M, COULOMB_P3M, elc_params, ELC_sanity_checks(), ELC_tune_far_cut(), P3MParameters::epsilon, ELCParameters::far_calculated, ELCParameters::far_cut, ELCParameters::far_cut2, h, BoxGeometry::length(), maxPWerror, Coulomb_parameters::method, anonymous_namespace{Correlator.cpp}::min(), mpi_bcast_coulomb_params(), p3m, P3M_EPSILON_METALLIC, p3m_data_struct_base::params, and Utils::sqr().
ELC_tune_far_cut()
double ELC_tune_far_cut (ELCParameters const & params)
Definition at line 965 of file elc.cpp.
References box_geo, h, BoxGeometry::length(), BoxGeometry::length_inv(), anonymous_namespace{Correlator.cpp}::min(), params, Utils::pi(), and sum.
Referenced by ELC_init(), and ELC_set_params().
image_sum_b()
double image_sum_b (double q, double z) inline
Definition at line 351 of file elc.cpp.
References box_geo, ELCParameters::delta_mid_bot, ELCParameters::delta_mid_top, elc_params, BoxGeometry::length(), BoxGeometry::length_half(), and anonymous_namespace{DomainDecomposition.cpp}::shift().
Referenced by z_energy().
image_sum_t()
double image_sum_t (double q, double z) inline
Definition at line 360 of file elc.cpp.
References box_geo, ELCParameters::delta_mid_bot, ELCParameters::delta_mid_top, elc_params, BoxGeometry::length(), BoxGeometry::length_half(), and anonymous_namespace{DomainDecomposition.cpp}::shift().
Referenced by z_energy().
PoQ_energy()
static double PoQ_energy (double omega, std::size_t n_part) static
Definition at line 634 of file elc.cpp.
References gblcblk, partblk, POQECM, POQECP, POQESM, and POQESP.
Referenced by ELC_energy().
PQ_energy()
static double PQ_energy (double omega, std::size_t n_part) static
Definition at line 826 of file elc.cpp.
References gblcblk, partblk, PQECCM, PQECCP, PQECSM, PQECSP, PQESCM, PQESCP, PQESSM, and PQESSP.
Referenced by ELC_energy().
prepare_sc_cache()
static void prepare_sc_cache (const ParticleRange & particles, std::size_t n_freq_x, double u_x, std::size_t n_freq_y, double u_y) static
Definition at line 135 of file elc.cpp.
References Cells::particles(), scxcache, and scycache.
Referenced by ELC_add_force(), and ELC_energy().
scale_vec()
void scale_vec (double scale, double * pdc, std::size_t size) inline
Definition at line 168 of file elc.cpp.
Referenced by setup_PoQ(), and setup_PQ().
setup_PoQ()
template<PoQ axis> void setup_PoQ (std::size_t index, double omega, const ParticleRange & particles)
Definition at line 508 of file elc.cpp.
References add_vec(), addscale_vec(), block(), box_geo, clear_vec(), coulomb, ELCParameters::delta_mid_bot, ELCParameters::delta_mid_top, ELCParameters::dielectric_contrast_on, elc_params, gblcblk, ELCParameters::h, BoxGeometry::length(), BoxGeometry::length_inv(), P, partblk, Cells::particles(), Utils::pi(), POQECM, POQECP, POQESM, POQESP, Coulomb_parameters::prefactor, scale_vec(), scxcache, scycache, ParticleRange::size(), and ELCParameters::space_layer.
setup_PQ()
static void setup_PQ (std::size_t index_p, std::size_t index_q, double omega, const ParticleRange & particles) static
Definition at line 655 of file elc.cpp.
References add_vec(), addscale_vec(), block(), box_geo, clear_vec(), coulomb, ELCParameters::delta_mid_bot, ELCParameters::delta_mid_top, ELCParameters::dielectric_contrast_on, elc_params, gblcblk, ELCParameters::h, BoxGeometry::length(), BoxGeometry::length_inv(), partblk, Cells::particles(), Utils::pi(), PQECCM, PQECCP, PQECSM, PQECSP, PQESCM, PQESCP, PQESSM, PQESSP, Coulomb_parameters::prefactor, scale_vec(), scxcache, scycache, ParticleRange::size(), and ELCParameters::space_layer.
Referenced by ELC_add_force(), and ELC_energy().
z_energy()
static double z_energy (const ParticleRange & particles) static
Definition at line 370 of file elc.cpp.
References box_geo, clear_vec(), ELCParameters::const_pot, coulomb, ELCParameters::delta_mid_bot, ELCParameters::delta_mid_top, ELCParameters::dielectric_contrast_on, distribute(), elc_params, gblcblk, ELCParameters::h, image_sum_b(), image_sum_t(), BoxGeometry::length_half(), BoxGeometry::length_inv(), Cells::particles(), Utils::pi(), Coulomb_parameters::prefactor, anonymous_namespace{DomainDecomposition.cpp}::shift(), ELCParameters::space_layer, and this_node.
Referenced by ELC_energy().
Variable Documentation
elc_params
ELCParameters elc_params
Initial value:
= {1e100, 10,    1, 0, true, true, false, 1,
                            1,     false, 0, 0, 0,    0,    0.0}
Definition at line 53 of file elc.cpp.
Referenced by add_dipole_force(), add_z_force(), anonymous_namespace{elc.cpp}::assign_image_charge(), Coulomb::bcast_coulomb_params(), Coulomb::calc_energy_long_range(), Coulomb::calc_long_range_force(), check_gap_elc(), Coulomb::cutoff(), dipole_energy(), ELC_add_force(), ELC_energy(), ELC_init(), ELC_P3M_dielectric_layers_energy_contribution(), ELC_P3M_dielectric_layers_force_contribution(), ELC_P3M_modify_p3m_sums_both(), ELC_P3M_modify_p3m_sums_image(), ELC_set_params(), Coulomb::icc_sanity_check(), image_sum_b(), image_sum_t(), p3m_init(), p3m_mc_time(), Coulomb::pair_energy(), Coulomb::pair_force(), Coulomb::sanity_checks(), setup_PoQ(), setup_PQ(), and z_energy().
gblcblk
double gblcblk[8] static
collected data from the other cells
Definition at line 82 of file elc.cpp.
Referenced by add_dipole_force(), add_PoQ_force(), add_PQ_force(), add_z_force(), dipole_energy(), distribute(), PoQ_energy(), PQ_energy(), setup_PoQ(), setup_PQ(), and z_energy().
partblk
std::vector<double> partblk static
temporary buffers for product decomposition
Definition at line 80 of file elc.cpp.
Referenced by add_PoQ_force(), add_PQ_force(), ELC_add_force(), ELC_energy(), PoQ_energy(), PQ_energy(), setup_PoQ(), and setup_PQ().
scxcache
std::vector<SCCache> scxcache static
Cached sin/cos values along the x-axis and y-axis.
Definition at line 91 of file elc.cpp.
Referenced by prepare_sc_cache(), setup_PoQ(), and setup_PQ().
scycache
std::vector<SCCache> scycache static
Definition at line 92 of file elc.cpp.
Referenced by prepare_sc_cache(), setup_PoQ(), and setup_PQ().