ESPResSo: elc.hpp File Reference
elc.hpp File Reference
ELC algorithm for long-range Coulomb interactions.
#include "config.hpp"
#include "Particle.hpp"
#include "ParticleRange.hpp"
#include <utils/Vector.hpp>
Classes
struct ELCParameters
Parameters for the ELC method.
Functions
void ELC_set_params (double maxPWerror, double min_dist, double far_cut, bool neutralize, double delta_mid_top, double delta_mid_bot, bool const_pot, double pot_diff)
Set parameters for ELC.
void ELC_add_force (const ParticleRange &particles)
the force calculation
double ELC_energy (const ParticleRange &particles)
the energy calculation
void ELC_sanity_checks (ELCParameters const &params)
check the ELC parameters
void ELC_init ()
initialize the ELC constants
double ELC_P3M_dielectric_layers_energy_contribution (Particle const &p1, Particle const &p2)
pairwise contributions from the lowest and top layers to the energy
Utils::Vector3d ELC_P3M_dielectric_layers_force_contribution (const Utils::Vector3d &pos1, const Utils::Vector3d &pos2, double q1q2)
pairwise contributions from the lowest and top layers to the force
double ELC_P3M_dielectric_layers_energy_self (const ParticleRange &particles)
self energies of top and bottom layers with their virtual images
void ELC_P3M_self_forces (const ParticleRange &particles)
forces of particles in border layers with themselves
void ELC_p3m_charge_assign_both (const ParticleRange &particles)
assign the additional, virtual charges, used only in energy.cpp
void ELC_p3m_charge_assign_image (const ParticleRange &particles)
assign the additional, virtual charges, used only in energy.cpp
void ELC_P3M_modify_p3m_sums_both (const ParticleRange &particles)
take into account the virtual charges in the charge sums, used in energy.cpp
void ELC_P3M_modify_p3m_sums_image (const ParticleRange &particles)
take into account the virtual charges in the charge sums, used in energy.cpp
void ELC_P3M_restore_p3m_sums (const ParticleRange &particles)
assign the additional, virtual charges, used only in energy.cpp
Variables
ELCParameters elc_params
Detailed Description
ELC algorithm for long-range Coulomb interactions.
Implementation of the ELC method for the calculation of the electrostatic interaction in two dimensional periodic systems. For details on the method see MMM in general. The ELC method works together with any three-dimensional method, for example P3M, with metallic boundary conditions.
Definition in file elc.hpp.
Function Documentation
ELC_add_force()
void ELC_add_force (const ParticleRange & particles)
the force calculation
Definition at line 848 of file elc.cpp.
References add_dipole_force(), add_PQ_force(), add_z_force(), box_geo, distribute(), elc_params, ELCParameters::far_cut, ELCParameters::far_cut2, BoxGeometry::length(), BoxGeometry::length_inv(), partblk, Cells::particles(), Utils::pi(), prepare_sc_cache(), setup_PQ(), ParticleRange::size(), Utils::sqr(), and Utils::sqrt().
Referenced by Coulomb::calc_long_range_force().
ELC_energy()
double ELC_energy (const ParticleRange & particles)
the energy calculation
Definition at line 905 of file elc.cpp.
References box_geo, dipole_energy(), distribute(), elc_params, ELCParameters::far_cut, ELCParameters::far_cut2, BoxGeometry::length(), BoxGeometry::length_inv(), partblk, Cells::particles(), Utils::pi(), PoQ_energy(), PQ_energy(), prepare_sc_cache(), setup_PQ(), ParticleRange::size(), Utils::sqr(), Utils::sqrt(), and z_energy().
Referenced by Coulomb::calc_energy_long_range().
ELC_init()
void ELC_init ()
initialize the ELC constants
Definition at line 1040 of file elc.cpp.
References box_geo, ELCParameters::dielectric_contrast_on, elc_params, ELC_tune_far_cut(), ELCParameters::far_calculated, ELCParameters::far_cut, ELCParameters::far_cut2, ELCParameters::gap_size, ELCParameters::h, BoxGeometry::length(), anonymous_namespace{Correlator.cpp}::min(), ELCParameters::minimal_dist, p3m, p3m_data_struct_base::params, P3MParameters::r_cut, runtimeErrorMsg, ELCParameters::space_box, ELCParameters::space_layer, and Utils::sqr().
Referenced by Coulomb::init(), Coulomb::on_boxl_change(), and on_coulomb_change().
ELC_p3m_charge_assign_both()
void ELC_p3m_charge_assign_both (const ParticleRange & particles)
assign the additional, virtual charges, used only in energy.cpp
Definition at line 1171 of file elc.cpp.
References anonymous_namespace{elc.cpp}::assign_image_charge(), P3MParameters::cao, p3m_data_struct::inter_weights, p3m_data_struct::local_mesh, p3m, p3m_assign_charge(), p3m_data_struct_base::params, Cells::particles(), p3m_interpolation_cache::reset(), p3m_data_struct::rs_mesh, and P3MLocalMesh::size.
Referenced by Coulomb::calc_energy_long_range(), and Coulomb::calc_long_range_force().
ELC_p3m_charge_assign_image()
void ELC_p3m_charge_assign_image (const ParticleRange & particles)
assign the additional, virtual charges, used only in energy.cpp
Definition at line 1186 of file elc.cpp.
References anonymous_namespace{elc.cpp}::assign_image_charge(), p3m_data_struct::local_mesh, p3m, Cells::particles(), p3m_data_struct::rs_mesh, and P3MLocalMesh::size.
Referenced by Coulomb::calc_energy_long_range().
ELC_P3M_dielectric_layers_energy_contribution()
double ELC_P3M_dielectric_layers_energy_contribution (Particle const & p1, Particle const & p2)
pairwise contributions from the lowest and top layers to the energy
Definition at line 1247 of file elc.cpp.
References ELC_P3M_dielectric_layers_energy_contribution(), ParticlePosition::p, Particle::p, ParticleProperties::q, and Particle::r.
ELC_P3M_dielectric_layers_energy_self()
double ELC_P3M_dielectric_layers_energy_self (const ParticleRange & particles)
self energies of top and bottom layers with their virtual images
Definition at line 1263 of file elc.cpp.
References ELC_P3M_dielectric_layers_energy_contribution(), and Cells::particles().
Referenced by Coulomb::calc_energy_long_range().
ELC_P3M_dielectric_layers_force_contribution()
Utils::Vector3d ELC_P3M_dielectric_layers_force_contribution (const Utils::Vector3d & pos1, const Utils::Vector3d & pos2, double q1q2)
pairwise contributions from the lowest and top layers to the force
Definition at line 1200 of file elc.cpp.
References box_geo, ELCParameters::delta_mid_bot, ELCParameters::delta_mid_top, elc_params, force, BoxGeometry::get_mi_vector(), ELCParameters::h, p3m_add_pair_force(), and ELCParameters::space_layer.
Referenced by ELC_P3M_self_forces(), and Coulomb::pair_force().
ELC_P3M_modify_p3m_sums_both()
void ELC_P3M_modify_p3m_sums_both (const ParticleRange & particles)
take into account the virtual charges in the charge sums, used in energy.cpp
Definition at line 1277 of file elc.cpp.
References comm_cart, ELCParameters::delta_mid_bot, ELCParameters::delta_mid_top, elc_params, ELCParameters::h, p3m, Cells::particles(), ELCParameters::space_layer, Utils::sqr(), p3m_data_struct::square_sum_q, p3m_data_struct::sum_q2, and p3m_data_struct::sum_qpart.
Referenced by Coulomb::calc_energy_long_range(), and Coulomb::calc_long_range_force().
ELC_P3M_modify_p3m_sums_image()
void ELC_P3M_modify_p3m_sums_image (const ParticleRange & particles)
take into account the virtual charges in the charge sums, used in energy.cpp
Definition at line 1313 of file elc.cpp.
References comm_cart, ELCParameters::delta_mid_bot, ELCParameters::delta_mid_top, elc_params, ELCParameters::h, p3m, Cells::particles(), ELCParameters::space_layer, Utils::sqr(), p3m_data_struct::square_sum_q, p3m_data_struct::sum_q2, and p3m_data_struct::sum_qpart.
Referenced by Coulomb::calc_energy_long_range().
ELC_P3M_restore_p3m_sums()
void ELC_P3M_restore_p3m_sums (const ParticleRange & particles)
assign the additional, virtual charges, used only in energy.cpp
Definition at line 1347 of file elc.cpp.
References comm_cart, p3m, Cells::particles(), Utils::sqr(), p3m_data_struct::square_sum_q, p3m_data_struct::sum_q2, and p3m_data_struct::sum_qpart.
Referenced by Coulomb::calc_energy_long_range(), and Coulomb::calc_long_range_force().
ELC_P3M_self_forces()
void ELC_P3M_self_forces (const ParticleRange & particles)
forces of particles in border layers with themselves
Definition at line 1143 of file elc.cpp.
References coulomb, ELC_P3M_dielectric_layers_force_contribution(), Cells::particles(), and Coulomb_parameters::prefactor.
Referenced by Coulomb::calc_long_range_force().
ELC_sanity_checks()
void ELC_sanity_checks (ELCParameters const & params)
check the ELC parameters
Definition at line 1009 of file elc.cpp.
References box_geo, p3m, params, BoxGeometry::periodic(), ROUND_ERROR_PREC, and p3m_data_struct::square_sum_q.
Referenced by ELC_set_params(), and Coulomb::sanity_checks().
ELC_set_params()
void ELC_set_params (double maxPWerror, double min_dist, double far_cut, bool neutralize, double delta_mid_top, double delta_mid_bot, bool const_pot, double pot_diff)
Set parameters for ELC.
Parameters
maxPWerror Maximal allowed pairwise error for the potential and force. Note that this counts for the plain 1/r contribution alone, without the prefactor and the charge prefactor.
min_dist Minimal distance of two charges for which the far formula is used.
far_cut Cutoff of the exponential sum. If -1, the cutoff is automatically calculated using the error formulas.
neutralize whether to add a neutralizing background. WARNING: This background exerts forces, which are dependent on the simulation box; especially the gap size enters into the value of the forces.
delta_mid_top dielectric contrast in the upper part of the simulation cell.
delta_mid_bot dielectric contrast in the lower part of the simulation cell.
const_pot Flag whether a const. potential is applied.
pot_diff Const. potential.
Definition at line 1079 of file elc.cpp.
References box_geo, coulomb, COULOMB_ELC_P3M, COULOMB_P3M, elc_params, ELC_sanity_checks(), ELC_tune_far_cut(), P3MParameters::epsilon, ELCParameters::far_calculated, ELCParameters::far_cut, ELCParameters::far_cut2, h, BoxGeometry::length(), maxPWerror, Coulomb_parameters::method, anonymous_namespace{Correlator.cpp}::min(), mpi_bcast_coulomb_params(), p3m, P3M_EPSILON_METALLIC, p3m_data_struct_base::params, and Utils::sqr().
Variable Documentation
elc_params
ELCParameters elc_params
Definition at line 53 of file elc.cpp.
Referenced by add_dipole_force(), add_z_force(), anonymous_namespace{elc.cpp}::assign_image_charge(), Coulomb::bcast_coulomb_params(), Coulomb::calc_energy_long_range(), Coulomb::calc_long_range_force(), check_gap_elc(), Coulomb::cutoff(), dipole_energy(), ELC_add_force(), ELC_energy(), ELC_init(), ELC_P3M_dielectric_layers_energy_contribution(), ELC_P3M_dielectric_layers_force_contribution(), ELC_P3M_modify_p3m_sums_both(), ELC_P3M_modify_p3m_sums_image(), ELC_set_params(), Coulomb::icc_sanity_check(), image_sum_b(), image_sum_t(), p3m_init(), p3m_mc_time(), Coulomb::pair_energy(), Coulomb::pair_force(), Coulomb::sanity_checks(), setup_PoQ(), setup_PQ(), and z_energy().