ESPResSo: energy.cpp File Reference
energy.cpp File Reference
#include "EspressoSystemInterface.hpp"
#include "Observable_stat.hpp"
#include "communication.hpp"
#include "constraints.hpp"
#include "cuda_interface.hpp"
#include "electrostatics_magnetostatics/magnetic_non_p3m_methods.hpp"
#include "energy_inline.hpp"
#include "event.hpp"
#include "forces.hpp"
#include "integrate.hpp"
#include "nonbonded_interactions/nonbonded_interaction_data.hpp"
#include "short_range_loop.hpp"
#include "electrostatics_magnetostatics/coulomb.hpp"
#include "electrostatics_magnetostatics/dipole.hpp"
#include <memory>
Functions
static std::shared_ptr< Observable_stat > calculate_energy_local ()
std::shared_ptr< Observable_stat > calculate_energy ()
Parallel energy calculation.
double calculate_current_potential_energy_of_system ()
Calculate the total energy of the system.
double observable_compute_energy ()
Helper function for Observables::Energy.
Variables
ActorList energyActors
Detailed Description
Energy calculation.
Definition in file energy.cpp.
Function Documentation
calculate_current_potential_energy_of_system()
double calculate_current_potential_energy_of_system ()
Calculate the total energy of the system.
Definition at line 120 of file energy.cpp.
References calculate_energy().
Referenced by ReactionMethods::ReactionAlgorithm::do_global_mc_move_for_particles_of_type(), ReactionMethods::ReactionAlgorithm::generic_oneway_reaction(), and ReactionMethods::WidomInsertion::measure_excess_chemical_potential().
calculate_energy()
std::shared_ptr<Observable_stat> calculate_energy ()
Parallel energy calculation.
Definition at line 116 of file energy.cpp.
References calculate_energy_local(), Communication::Result::master_rank, and mpi_call().
Referenced by calculate_current_potential_energy_of_system(), and observable_compute_energy().
calculate_energy_local()
static std::shared_ptr<Observable_stat> calculate_energy_local () static
Definition at line 46 of file energy.cpp.
References add_non_bonded_pair_energy(), bonded_ia_params, calc_bonded_energy(), Dipole::calc_energy_long_range(), Coulomb::calc_energy_long_range(), calc_kinetic_energy(), cell_structure, clear_energy_on_GPU(), Constraints::constraints, copy_energy_from_GPU(), CUDA_energy::coulomb, CUDA_energy::dipolar, energy_host, energyActors, espressoSystemInterface, get_sim_time(), EspressoSystemInterface::Instance(), interactions_sanity_checks(), CellStructure::local_particles(), maximal_cutoff(), maximal_cutoff_bonded(), Coulomb::on_observable_calc(), short_range_loop(), Utils::sqrt(), and EspressoSystemInterface::update().
Referenced by calculate_energy().
observable_compute_energy()
double observable_compute_energy ()
Helper function for Observables::Energy.
Definition at line 125 of file energy.cpp.
References calculate_energy().
Referenced by Observables::Energy::operator()().
Variable Documentation
energyActors
ActorList energyActors
Definition at line 44 of file energy.cpp.
Referenced by Mmm1dgpuForce::activate(), activate_dipolar_barnes_hut(), activate_dipolar_direct_sum_gpu(), calculate_energy_local(), Mmm1dgpuForce::deactivate(), deactivate_dipolar_barnes_hut(), and deactivate_dipolar_direct_sum_gpu().