ESPResSo: event.hpp File Reference
event.hpp File Reference
Functions
Hook procedures
These procedures are called if several significant changes to the system happen which may make a reinitialization of subsystems necessary.
void on_program_start ()
called once at the very beginning of the program start.
void on_integration_start (double time_step)
called every time the simulation is continued/started, i.e.
void on_observable_calc ()
called before calculating observables, i.e.
void on_particle_change ()
called every time a particle property is changed via the script interface.
void on_particle_charge_change ()
called every time the charge of a particle has changed.
void on_coulomb_change ()
called every time the Coulomb parameters are changed.
void on_short_range_ia_change ()
called every time short ranged interaction parameters are changed.
void on_constraint_change ()
called every time a constraint is changed.
void on_boxl_change (bool skip_method_adaption=false)
Called when the box length has changed.
void on_cell_structure_change ()
called every time a major change to the cell structure has happened, like the skin or grid have changed.
void on_temperature_change ()
called every time the temperature changes.
void on_periodicity_change ()
Called when the periodicity changes.
void on_skin_change ()
Called when the skin is changed.
void on_thermostat_param_change ()
Called when parameters of thermostats are changed.
void on_timestep_change ()
Called when the timestep changed.
void on_simtime_change ()
Called when the simulation time changed.
void on_forcecap_change ()
Called when the force cap changed.
void on_nodegrid_change ()
Called when the node_grid changed.
unsigned global_ghost_flags ()
Returns the ghost flags required for running pair kernels for the global state, e.g.
void on_lbboundary_change ()
called every time the walls for the lb fluid are changed
void update_dependent_particles ()
Update particles with properties depending on other particles, namely virtual sites and ICC charges.
Detailed Description
This file contains the hook procedures. These are the ones with names on_* and are called whenever something is changed in ESPResSo which might influence other parts. For example, the P3M code has to be reinitialized whenever the box size changes. The hooking mechanism allows to keep track of such changes.
For this mechanism to work, two things have to be fulfilled. If some part of the code changes some property, it has to call the corresponding hook, i.e. on_particle_change() if a particle property has been changed or on_short_range_ia_change(), if a short ranged interaction has been changed. In turn procedures that depend on particle properties or the box size, should react to such changes in the corresponding hook procedure.
Implementation in event.cpp.
Definition in file event.hpp.
Function Documentation
global_ghost_flags()
unsigned global_ghost_flags ()
Returns the ghost flags required for running pair kernels for the global state, e.g.
the force calculation.
Returns
Required data parts;
Definition at line 331 of file event.cpp.
References collision_params, CPU, Cells::DATA_PART_BONDS, Cells::DATA_PART_MOMENTUM, Cells::DATA_PART_POSITION, Cells::DATA_PART_PROPERTIES, lattice_switch, Collision_parameters::mode, n_thermalized_bonds, THERMO_DPD, and thermo_switch.
Referenced by integrate(), on_observable_calc(), and update_dependent_particles().
on_boxl_change()
void on_boxl_change (bool skip_method_adaption = false)
Called when the box length has changed.
This routine is relatively fast, and changing the box length every time step as for example necessary for NpT is more or less ok.
Parameters
skip_method_adaption skip the long-range methods adaptions
Definition at line 240 of file event.cpp.
References box_geo, cell_structure, cells_re_init(), CellStructure::decomposition_type(), grid_changed_box_l(), LBBoundaries::lb_init_boundaries(), lb_lbfluid_init(), Dipole::on_boxl_change(), and Coulomb::on_boxl_change().
on_cell_structure_change()
void on_cell_structure_change ()
called every time a major change to the cell structure has happened, like the skin or grid have changed.
This one is potentially slow.
Definition at line 263 of file event.cpp.
References clear_particle_node(), Dipole::init(), and Coulomb::init().
Referenced by cells_re_init().
on_constraint_change()
void on_constraint_change ()
called every time a constraint is changed.
Definition at line 230 of file event.cpp.
References recalc_forces.
on_coulomb_change()
void on_coulomb_change ()
called every time the Coulomb parameters are changed.
Definition at line 179 of file coulomb.cpp.
References P3MParameters::alpha, P3MParameters::cao, coulomb, COULOMB_DH, COULOMB_ELC_P3M, COULOMB_MMM1D, COULOMB_P3M, COULOMB_P3M_GPU, DIPOLAR_MDLC_P3M, DIPOLAR_P3M, dipole, dp3m_init(), ELC_init(), P3MParameters::mesh, Coulomb_parameters::method, Dipole_parameters::method, MMM1D_init(), Dipole::on_coulomb_change(), Coulomb::on_coulomb_change(), on_short_range_ia_change(), p3m, p3m_gpu_init(), p3m_init(), p3m_data_struct_base::params, recalc_forces, runtimeErrorMsg, and this_node.
Referenced by mpi_bcast_coulomb_params_local(), on_coulomb_change(), on_skin_change(), Scafacos::set_parameters_coulomb_worker(), and Scafacos::set_parameters_dipoles_worker().
on_forcecap_change()
void on_forcecap_change ()
Called when the force cap changed.
Definition at line 319 of file event.cpp.
References recalc_forces.
Referenced by mpi_set_forcecap_local().
on_integration_start()
void on_integration_start (double time_step)
called every time the simulation is continued/started, i.e.
when switching from the script interface to the simulation core.
Definition at line 102 of file event.cpp.
References Utils::Mpi::all_compare(), box_geo, cell_structure, comm_cart, coulomb, dipole, gpu_get_global_particle_vars_pointer_host(), integrator_npt_sanity_checks(), integrator_sanity_checks(), interactions_sanity_checks(), PartCfg::invalidate(), invalidate_fetch_cache(), lb_lbfluid_on_integration_start(), lb_lbfluid_sanity_checks(), Coulomb_parameters::method, Dipole_parameters::method, npt_ensemble_init(), on_observable_calc(), partCfg(), recalc_forces, reinit_thermo, runtimeErrorMsg, thermo_init(), time_step, and CellStructure::use_verlet_list.
Referenced by integrate().
on_lbboundary_change()
void on_lbboundary_change ()
called every time the walls for the lb fluid are changed
Definition at line 232 of file event.cpp.
References LBBoundaries::lb_init_boundaries(), and recalc_forces.
Referenced by LBBoundaries::add(), and LBBoundaries::remove().
on_nodegrid_change()
void on_nodegrid_change ()
Called when the node_grid changed.
Definition at line 321 of file event.cpp.
References cell_structure, cells_re_init(), CellStructure::decomposition_type(), and grid_changed_n_nodes().
Referenced by mpi_set_node_grid_local().
on_observable_calc()
void on_observable_calc ()
called before calculating observables, i.e.
energy, pressure or the integrator (forces). Initialize any methods here which are not initialized immediately (P3M etc.).
Definition at line 165 of file coulomb.cpp.
References cells_update_ghosts(), clear_particle_node(), coulomb, COULOMB_ELC_P3M, COULOMB_P3M, COULOMB_P3M_GPU, DIPOLAR_MDLC_P3M, DIPOLAR_P3M, dipole, dp3m_count_magnetic_particles(), ek_initialized, ek_integrate_electrostatics(), global_ghost_flags(), Coulomb_parameters::method, Dipole_parameters::method, Dipole::on_observable_calc(), Coulomb::on_observable_calc(), p3m_count_charged_particles(), reinit_electrostatics, reinit_magnetostatics, and update_dependent_particles().
Referenced by calculate_energy_local(), calculate_pressure_local(), dpd_viscous_stress_local(), get_pairs_filtered(), on_integration_start(), and on_observable_calc().
on_particle_change()
void on_particle_change ()
called every time a particle property is changed via the script interface.
Definition at line 193 of file event.cpp.
References cell_structure, PartCfg::invalidate(), invalidate_fetch_cache(), partCfg(), recalc_forces, reinit_electrostatics, reinit_magnetostatics, Cells::RESORT_LOCAL, and CellStructure::set_resort_particles().
Referenced by local_rotate_system(), mpi_galilei_transform_local(), mpi_kill_particle_forces_local(), mpi_kill_particle_motion_local(), mpi_place_new_particle_local(), mpi_place_particle(), mpi_place_particle_local(), mpi_remove_particle_local(), mpi_rescale_particles(), mpi_rescale_particles_local(), mpi_send_exclusion_local(), mpi_send_update_message(), and mpi_send_update_message_local().
on_particle_charge_change()
void on_particle_charge_change ()
called every time the charge of a particle has changed.
Definition at line 186 of file event.cpp.
References PartCfg::invalidate(), partCfg(), and reinit_electrostatics.
Referenced by icc_iteration(), mpi_icc_init(), and mpi_icc_init_local().
on_periodicity_change()
void on_periodicity_change ()
Called when the periodicity changes.
Internally calls on_skin_change.
Definition at line 280 of file event.cpp.
References box_geo, coulomb, COULOMB_SCAFACOS, DIPOLAR_SCAFACOS, dipole, Scafacos::fcs_coulomb(), Scafacos::fcs_dipoles(), INTEG_METHOD_SD, integ_switch, Coulomb_parameters::method, Dipole_parameters::method, on_skin_change(), BoxGeometry::periodic(), runtimeErrorMsg, and Scafacos::ScafacosContextBase::update_system_params().
Referenced by mpi_set_periodicity_local().
on_program_start()
void on_program_start ()
called once at the very beginning of the program start.
Definition at line 80 of file event.cpp.
References CELL_STRUCTURE_DOMDEC, cells_re_init(), cuda_init(), init_node_grid(), make_particle_type_exist(), and this_node.
Referenced by Communication::init().
on_short_range_ia_change()
void on_short_range_ia_change ()
called every time short ranged interaction parameters are changed.
Definition at line 224 of file event.cpp.
References cell_structure, cells_re_init(), CellStructure::decomposition_type(), and recalc_forces.
Referenced by mpi_bcast_ia_params_local(), on_coulomb_change(), and validate_collision_parameters().
on_simtime_change()
void on_simtime_change ()
Called when the simulation time changed.
Definition at line 317 of file event.cpp.
References recalc_forces.
Referenced by mpi_set_time_local().
on_skin_change()
void on_skin_change ()
Called when the skin is changed.
Definition at line 305 of file event.cpp.
References cell_structure, cells_re_init(), CellStructure::decomposition_type(), and on_coulomb_change().
Referenced by mpi_set_min_global_cut_local(), mpi_set_skin_local(), and on_periodicity_change().
on_temperature_change()
void on_temperature_change ()
called every time the temperature changes.
This one is potentially slow.
Definition at line 278 of file event.cpp.
References lb_lbfluid_reinit_parameters().
Referenced by mpi_set_temperature_local().
on_thermostat_param_change()
void on_thermostat_param_change ()
Called when parameters of thermostats are changed.
Definition at line 310 of file event.cpp.
References reinit_thermo.
Referenced by mpi_bcast_nptiso_geom_barostat_worker(), mpi_set_langevin_gamma_local(), mpi_set_langevin_gamma_rot_local(), mpi_set_n_thermalized_bonds_local(), mpi_set_nptiso_gammas_local(), mpi_set_temperature_local(), and on_timestep_change().
on_timestep_change()
void on_timestep_change ()
Called when the timestep changed.
Internally calls on_thermostat_param_change.
Definition at line 312 of file event.cpp.
References lb_lbfluid_reinit_parameters(), and on_thermostat_param_change().
Referenced by mpi_set_time_step_local().
update_dependent_particles()
void update_dependent_particles ()
Update particles with properties depending on other particles, namely virtual sites and ICC charges.
Update particles with properties depending on other particles, namely virtual sites and ICC charges.
Definition at line 160 of file coulomb.cpp.
References cell_structure, cells_update_ghosts(), CellStructure::ghost_particles(), global_ghost_flags(), icc_iteration(), immersed_boundaries, ImmersedBoundaries::init_volume_conservation(), CellStructure::local_particles(), Coulomb::update_dependent_particles(), and virtual_sites().
Referenced by local_rotate_system(), on_observable_calc(), and update_dependent_particles().