ESPResSo: exclusions.hpp File Reference
exclusions.hpp File Reference
#include "config.hpp"
#include "Particle.hpp"
#include <algorithm>
Functions
bool do_nonbonded (Particle const &p1, Particle const &p2)
Determine if the non-bonded interactions between p1 and p2 should be calculated.
void delete_exclusion (Particle *part, int part2)
Remove exclusion from particle if possible.
void add_exclusion (Particle *part, int part2)
Insert an exclusion if not already set.
Function Documentation
add_exclusion()
void add_exclusion (Particle * part, int part2)
Insert an exclusion if not already set.
Definition at line 32 of file exclusions.cpp.
delete_exclusion()
void delete_exclusion (Particle * part, int part2)
Remove exclusion from particle if possible.
Definition at line 39 of file exclusions.cpp.
do_nonbonded()
bool do_nonbonded (Particle const & p1, Particle const & p2) inline
Determine if the non-bonded interactions between p1 and p2 should be calculated.
Definition at line 34 of file exclusions.hpp.
References Particle::exclusions().
Referenced by add_non_bonded_pair_energy(), add_non_bonded_pair_force(), and add_non_bonded_pair_virials().