ESPResSo: forces.cpp File Reference
forces.cpp File Reference
#include "EspressoSystemInterface.hpp"
#include "collision.hpp"
#include "comfixed_global.hpp"
#include "communication.hpp"
#include "constraints.hpp"
#include "electrostatics_magnetostatics/dipole.hpp"
#include "electrostatics_magnetostatics/icc.hpp"
#include "electrostatics_magnetostatics/p3m_gpu.hpp"
#include "forcecap.hpp"
#include "forces_inline.hpp"
#include "grid_based_algorithms/electrokinetics.hpp"
#include "grid_based_algorithms/lb_interface.hpp"
#include "grid_based_algorithms/lb_particle_coupling.hpp"
#include "immersed_boundaries.hpp"
#include "integrate.hpp"
#include "nonbonded_interactions/VerletCriterion.hpp"
#include "nonbonded_interactions/nonbonded_interaction_data.hpp"
#include "npt.hpp"
#include "short_range_loop.hpp"
#include "virtual_sites.hpp"
#include <profiler/profiler.hpp>
#include <cassert>
Functions
void init_forces (const ParticleRange &particles, double time_step, double kT)
void init_forces_ghosts (const ParticleRange &particles)
Set forces of all ghosts to zero.
void force_calc (CellStructure &cell_structure, double time_step, double kT)
Calculate forces.
void calc_long_range_forces (const ParticleRange &particles)
Calculate long range forces (P3M, ...).
void npt_add_virial_force_contribution (const Utils::Vector3d &force, const Utils::Vector3d &d)
Update the NpT virial.
Variables
ActorList forceActors
Detailed Description
Force calculation.
The corresponding header file is forces.hpp.
Definition in file forces.cpp.
Function Documentation
calc_long_range_forces()
void calc_long_range_forces (const ParticleRange & particles)
Calculate long range forces (P3M, ...).
Definition at line 182 of file forces.cpp.
References Dipole::calc_long_range_force(), Coulomb::calc_long_range_force(), ESPRESSO_PROFILER_CXX_MARK_FUNCTION, and Cells::particles().
Referenced by force_calc().
force_calc()
void force_calc (CellStructure & cell_structure, double time_step, double kT)
Calculate forces.
A short list, what the function is doing:
Initialize forces
Calculate bonded interaction forces
Calculate non-bonded short range interaction forces
Calculate long range interaction forces
Definition at line 87 of file forces.cpp.
References add_bonded_force(), add_non_bonded_pair_force(), add_oif_global_forces(), box_geo, calc_long_range_forces(), calc_oif_global(), cell_structure, collision_detection_cutoff(), COLLISION_MODE_OFF, collision_params, comfixed, comm_cart, Constraints::constraints, copy_forces_from_GPU(), Dipole::cutoff(), Coulomb::cutoff(), detect_collision(), Distance::dist2, ESPRESSO_PROFILER_CXX_MARK_FUNCTION, espressoSystemInterface, forceActors, forcecap_cap(), get_sim_time(), CellStructure::ghost_particles(), CellStructure::ghosts_reduce_forces(), icc_iteration(), immersed_boundaries, INACTIVE_CUTOFF, init_forces(), interaction_range(), lb_lbcoupling_calc_particle_lattice_ia(), BoxGeometry::length(), CellStructure::local_particles(), max_oif_objects, maximal_cutoff(), maximal_cutoff_bonded(), Collision_parameters::mode, Cells::particles(), prepare_local_collision_queue(), recalc_forces, short_range_loop(), skin, Utils::sqrt(), thermo_virtual, time_step, Distance::vec21, virtual_sites(), and ImmersedBoundaries::volume_conservation().
Referenced by integrate().
init_forces()
void init_forces (const ParticleRange & particles, double time_step, double kT)
Definition at line 56 of file forces.cpp.
References cell_structure, ESPRESSO_PROFILER_CXX_MARK_FUNCTION, CellStructure::ghost_particles(), init_ghost_force(), init_local_particle_force(), npt_reset_instantaneous_virials(), Cells::particles(), and time_step.
Referenced by force_calc().
init_forces_ghosts()
void init_forces_ghosts (const ParticleRange & particles)
Set forces of all ghosts to zero.
Definition at line 81 of file forces.cpp.
References init_ghost_force(), and Cells::particles().
Referenced by VirtualSitesRelative::back_transfer_forces_and_torques().
npt_add_virial_force_contribution()
void npt_add_virial_force_contribution (const Utils::Vector3d & force, const Utils::Vector3d & d)
Update the NpT virial.
Definition at line 197 of file forces.cpp.
References force, and npt_add_virial_contribution().
Referenced by add_bonded_two_body_force(), and add_non_bonded_pair_force().
Variable Documentation
forceActors
ActorList forceActors
Definition at line 54 of file forces.cpp.
Referenced by Mmm1dgpuForce::activate(), activate_dipolar_barnes_hut(), activate_dipolar_direct_sum_gpu(), Mmm1dgpuForce::deactivate(), deactivate_dipolar_barnes_hut(), deactivate_dipolar_direct_sum_gpu(), and force_calc().