ESPResSo: forces_inline.hpp File Reference
forces_inline.hpp File Reference
#include "config.hpp"
#include "forces.hpp"
#include "bonded_interactions/bonded_interaction_data.hpp"
#include "immersed_boundary/ibm_tribend.hpp"
#include "immersed_boundary/ibm_triel.hpp"
#include "nonbonded_interactions/bmhtf-nacl.hpp"
#include "nonbonded_interactions/buckingham.hpp"
#include "nonbonded_interactions/gaussian.hpp"
#include "nonbonded_interactions/gay_berne.hpp"
#include "nonbonded_interactions/hat.hpp"
#include "nonbonded_interactions/hertzian.hpp"
#include "nonbonded_interactions/lj.hpp"
#include "nonbonded_interactions/ljcos.hpp"
#include "nonbonded_interactions/ljcos2.hpp"
#include "nonbonded_interactions/ljgen.hpp"
#include "nonbonded_interactions/morse.hpp"
#include "nonbonded_interactions/nonbonded_interaction_data.hpp"
#include "nonbonded_interactions/nonbonded_tab.hpp"
#include "nonbonded_interactions/smooth_step.hpp"
#include "nonbonded_interactions/soft_sphere.hpp"
#include "nonbonded_interactions/thole.hpp"
#include "nonbonded_interactions/wca.hpp"
#include "object-in-fluid/oif_global_forces.hpp"
#include "object-in-fluid/oif_local_forces.hpp"
#include "electrostatics_magnetostatics/dipole_inline.hpp"
#include "electrostatics_magnetostatics/coulomb_inline.hpp"
#include "dpd.hpp"
#include "Particle.hpp"
#include "errorhandling.hpp"
#include "exclusions.hpp"
#include "rotation.hpp"
#include "thermostat.hpp"
#include "thermostats/langevin_inline.hpp"
#include <utils/Span.hpp>
#include <utils/Vector.hpp>
#include <boost/optional.hpp>
#include <boost/variant.hpp>
#include <tuple>
Functions
ParticleForce init_ghost_force (Particle const &)
Initialize the forces for a ghost particle.
ParticleForce external_force (Particle const &p)
External particle forces.
ParticleForce thermostat_force (Particle const &p, double time_step, double kT)
ParticleForce init_local_particle_force (Particle const &part, double time_step, double kT)
Initialize the forces for a real particle.
ParticleForce calc_non_bonded_pair_force (Particle const &p1, Particle const &p2, IA_parameters const &ia_params, Utils::Vector3d const &d, double const dist)
ParticleForce calc_opposing_force (ParticleForce const &pf, Utils::Vector3d const &d)
void add_non_bonded_pair_force (Particle &p1, Particle &p2, Utils::Vector3d const &d, double dist, double dist2)
Calculate non-bonded forces between a pair of particles and update their forces and torques.
boost::optional< Utils::Vector3d > calc_bond_pair_force (Particle const &p1, Particle const &p2, Bonded_IA_Parameters const &iaparams, Utils::Vector3d const &dx)
Compute the bonded interaction force between particle pairs.
bool add_bonded_two_body_force (Bonded_IA_Parameters const &iaparams, Particle &p1, Particle &p2)
boost::optional< std::tuple< Utils::Vector3d, Utils::Vector3d, Utils::Vector3d > > calc_bonded_three_body_force (Bonded_IA_Parameters const &iaparams, Particle const &p1, Particle const &p2, Particle const &p3)
bool add_bonded_three_body_force (Bonded_IA_Parameters const &iaparams, Particle &p1, Particle &p2, Particle &p3)
boost::optional< std::tuple< Utils::Vector3d, Utils::Vector3d, Utils::Vector3d, Utils::Vector3d > > calc_bonded_four_body_force (Bonded_IA_Parameters const &iaparams, Particle const &p1, Particle const &p2, Particle const &p3, Particle const &p4)
bool add_bonded_four_body_force (Bonded_IA_Parameters const &iaparams, Particle &p1, Particle &p2, Particle &p3, Particle &p4)
bool add_bonded_force (Particle &p1, int bond_id, Utils::Span< Particle * > partners)
Function Documentation
add_bonded_force()
bool add_bonded_force (Particle & p1, int bond_id, Utils::Span< Particle * > partners) inline
Definition at line 453 of file forces_inline.hpp.
References add_bonded_four_body_force(), add_bonded_three_body_force(), add_bonded_two_body_force(), bonded_ia_params, and number_of_partners().
Referenced by force_calc().
add_bonded_four_body_force()
bool add_bonded_four_body_force (Bonded_IA_Parameters const & iaparams, Particle & p1, Particle & p2, Particle & p3, Particle & p4) inline
Definition at line 434 of file forces_inline.hpp.
References calc_bonded_four_body_force(), ParticleForce::f, Particle::f, and Utils::get().
Referenced by add_bonded_force().
add_bonded_three_body_force()
bool add_bonded_three_body_force (Bonded_IA_Parameters const & iaparams, Particle & p1, Particle & p2, Particle & p3) inline
Definition at line 392 of file forces_inline.hpp.
References calc_bonded_three_body_force(), ParticleForce::f, Particle::f, and Utils::get().
Referenced by add_bonded_force().
add_bonded_two_body_force()
bool add_bonded_two_body_force (Bonded_IA_Parameters const & iaparams, Particle & p1, Particle & p2) inline
Definition at line 339 of file forces_inline.hpp.
References box_geo, calc_bond_pair_force(), ParticleForce::f, Particle::f, Utils::get(), BoxGeometry::get_mi_vector(), npt_add_virial_force_contribution(), ParticlePosition::p, and Particle::r.
Referenced by add_bonded_force().
add_non_bonded_pair_force()
void add_non_bonded_pair_force (Particle & p1, Particle & p2, Utils::Vector3d const & d, double dist, double dist2) inline
Calculate non-bonded forces between a pair of particles and update their forces and torques.
Parameters
[in,out] p1 particle 1.
[in,out] p2 particle 2.
[in] d vector between p1 and p2.
dist distance between p1 and p2.
dist2 distance squared between p1 and p2.
Definition at line 229 of file forces_inline.hpp.
References calc_non_bonded_pair_force(), calc_opposing_force(), do_nonbonded(), dpd_pair_force(), ParticleForce::f, Particle::f, force, get_ia_param(), ia_params, npt_add_virial_force_contribution(), Particle::p, Dipole::pair_force(), Coulomb::pair_force(), THERMO_DPD, thermo_switch, and ParticleProperties::type.
Referenced by force_calc().
calc_bond_pair_force()
boost::optional<Utils::Vector3d> calc_bond_pair_force (Particle const & p1, Particle const & p2, Bonded_IA_Parameters const & iaparams, Utils::Vector3d const & dx) inline
Compute the bonded interaction force between particle pairs.
Parameters
[in] p1 First particle.
[in] p2 Second particle.
[in] iaparams Bonded parameters for the interaction.
[in] dx Vector between p1 and p2.
Definition at line 308 of file forces_inline.hpp.
References Particle::p, and ParticleProperties::q.
Referenced by add_bonded_two_body_force(), and calc_bonded_virial_pressure_tensor().
calc_bonded_four_body_force()
boost::optional<std::tuple<Utils::Vector3d, Utils::Vector3d, Utils::Vector3d, Utils::Vector3d> > calc_bonded_four_body_force (Bonded_IA_Parameters const & iaparams, Particle const & p1, Particle const & p2, Particle const & p3, Particle const & p4) inline
Definition at line 414 of file forces_inline.hpp.
References ParticlePosition::p, and Particle::r.
Referenced by add_bonded_four_body_force().
calc_bonded_three_body_force()
boost::optional< std::tuple<Utils::Vector3d, Utils::Vector3d, Utils::Vector3d> > calc_bonded_three_body_force (Bonded_IA_Parameters const & iaparams, Particle const & p1, Particle const & p2, Particle const & p3) inline
Definition at line 369 of file forces_inline.hpp.
References ParticlePosition::p, and Particle::r.
Referenced by add_bonded_three_body_force(), and calc_bonded_three_body_pressure_tensor().
calc_non_bonded_pair_force()
ParticleForce calc_non_bonded_pair_force (Particle const & p1, Particle const & p2, IA_parameters const & ia_params, Utils::Vector3d const & d, double const dist) inline
Definition at line 127 of file forces_inline.hpp.
References BMHTF_pair_force_factor(), buck_pair_force_factor(), ParticlePosition::calc_director(), gaussian_pair_force_factor(), gb_pair_force(), hat_pair_force_factor(), hertzian_pair_force_factor(), ia_params, lj_pair_force_factor(), ljcos2_pair_force_factor(), ljcos_pair_force_factor(), ljgen_pair_force_factor(), morse_pair_force_factor(), Particle::r, SmSt_pair_force_factor(), soft_pair_force_factor(), tabulated_pair_force_factor(), thole_pair_force(), and wca_pair_force_factor().
Referenced by add_non_bonded_pair_force(), add_non_bonded_pair_virials(), and Constraints::ShapeBasedConstraint::force().
calc_opposing_force()
ParticleForce calc_opposing_force (ParticleForce const & pf, Utils::Vector3d const & d) inline
Definition at line 207 of file forces_inline.hpp.
References ParticleForce::f, ParticleForce::torque, and Utils::vector_product().
Referenced by add_non_bonded_pair_force(), and Constraints::ShapeBasedConstraint::force().
external_force()
ParticleForce external_force (Particle const & p) inline
External particle forces.
Definition at line 82 of file forces_inline.hpp.
References ParticlePosition::calc_director(), ParticleProperties::ext_force, ParticleProperties::ext_torque, f, ParticleParametersSwimming::f_swim, Particle::p, Particle::r, ParticleProperties::swim, and ParticleParametersSwimming::swimming.
Referenced by init_local_particle_force().
init_ghost_force()
ParticleForce init_ghost_force (Particle const &) inline
Initialize the forces for a ghost particle.
Definition at line 79 of file forces_inline.hpp.
Referenced by init_forces(), and init_forces_ghosts().
init_local_particle_force()
ParticleForce init_local_particle_force (Particle const & part, double time_step, double kT) inline
Initialize the forces for a real particle.
Definition at line 122 of file forces_inline.hpp.
References external_force(), thermostat_force(), and time_step.
Referenced by init_forces().
thermostat_force()
ParticleForce thermostat_force (Particle const & p, double time_step, double kT) inline
Definition at line 103 of file forces_inline.hpp.
References convert_vector_body_to_space(), friction_thermo_langevin(), friction_thermo_langevin_rotation(), langevin, Particle::p, ParticleProperties::rotation, THERMO_LANGEVIN, thermo_switch, and time_step.
Referenced by init_local_particle_force().