ESPResSo: ghosts.cpp File Reference
ghosts.cpp File Reference
#include "ghosts.hpp"
#include "Particle.hpp"
#include <utils/Span.hpp>
#include <utils/serialization/memcpy_archive.hpp>
#include <boost/archive/binary_iarchive.hpp>
#include <boost/archive/binary_oarchive.hpp>
#include <boost/iostreams/device/array.hpp>
#include <boost/iostreams/device/back_inserter.hpp>
#include <boost/iostreams/stream.hpp>
#include <boost/mpi/collectives.hpp>
#include <boost/range/numeric.hpp>
#include <boost/serialization/vector.hpp>
#include <algorithm>
#include <cassert>
#include <cstddef>
#include <functional>
#include <iterator>
#include <vector>
Macros
#define REQ_GHOST_SEND 100
Tag for ghosts communications.
Functions
static std::size_t calc_transmit_size (unsigned data_parts)
static std::size_t calc_transmit_size (const GhostCommunication &ghost_comm, unsigned int data_parts)
static void prepare_send_buffer (CommBuf &send_buffer, const GhostCommunication &ghost_comm, unsigned int data_parts)
static void prepare_ghost_cell (ParticleList *cell, int size)
static void prepare_recv_buffer (CommBuf &recv_buffer, const GhostCommunication &ghost_comm, unsigned int data_parts)
static void put_recv_buffer (CommBuf &recv_buffer, const GhostCommunication &ghost_comm, unsigned int data_parts)
static void add_rattle_correction_from_recv_buffer (CommBuf &recv_buffer, const GhostCommunication &ghost_comm)
static void add_forces_from_recv_buffer (CommBuf &recv_buffer, const GhostCommunication &ghost_comm)
static void cell_cell_transfer (const GhostCommunication &ghost_comm, unsigned int data_parts)
static bool is_send_op (int comm_type, int node, int this_node)
static bool is_recv_op (int comm_type, int node, int this_node)
static bool is_prefetchable (GhostCommunication const &ghost_comm, int this_node)
static bool is_poststorable (GhostCommunication const &ghost_comm, int this_node)
void ghost_communicator (const GhostCommunicator &gcr, unsigned int data_parts)
Do a ghost communication with caller specified data parts.
Detailed Description
Ghost particles and particle exchange.
For more information on ghosts, see ghosts.hpp
Note on variable naming:
a "GhostCommunicator" is always named "gcr",
a "GhostCommunication" is always named "ghost_comm".
Definition in file ghosts.cpp.
Macro Definition Documentation
REQ_GHOST_SEND
#define REQ_GHOST_SEND 100
Tag for ghosts communications.
Definition at line 54 of file ghosts.cpp.
Function Documentation
add_forces_from_recv_buffer()
static void add_forces_from_recv_buffer (CommBuf & recv_buffer, const GhostCommunication & ghost_comm) static
Definition at line 257 of file ghosts.cpp.
References ParticleForce::f, Utils::make_span(), and GhostCommunication::part_lists.
Referenced by ghost_communicator().
add_rattle_correction_from_recv_buffer()
static void add_rattle_correction_from_recv_buffer (CommBuf & recv_buffer, const GhostCommunication & ghost_comm) static
Definition at line 243 of file ghosts.cpp.
References Utils::make_span(), and GhostCommunication::part_lists.
Referenced by ghost_communicator().
calc_transmit_size() [1/2]
static std::size_t calc_transmit_size (const GhostCommunication & ghost_comm, unsigned int data_parts) static
Definition at line 105 of file ghosts.cpp.
References calc_transmit_size(), GHOSTTRANS_PARTNUM, GhostCommunication::part_lists, and sum.
calc_transmit_size() [2/2]
static std::size_t calc_transmit_size (unsigned data_parts) static
Definition at line 87 of file ghosts.cpp.
References GHOSTTRANS_FORCE, GHOSTTRANS_MOMENTUM, GHOSTTRANS_POSITION, GHOSTTRANS_PROPRTS, and GHOSTTRANS_RATTLE.
Referenced by calc_transmit_size(), ghost_communicator(), prepare_recv_buffer(), and prepare_send_buffer().
cell_cell_transfer()
static void cell_cell_transfer (const GhostCommunication & ghost_comm, unsigned int data_parts) static
Definition at line 270 of file ghosts.cpp.
References GHOSTTRANS_BONDS, GHOSTTRANS_FORCE, GHOSTTRANS_MOMENTUM, GHOSTTRANS_PARTNUM, GHOSTTRANS_POSITION, GHOSTTRANS_PROPRTS, GHOSTTRANS_RATTLE, GhostCommunication::part_lists, prepare_ghost_cell(), and GhostCommunication::shift.
Referenced by ghost_communicator().
ghost_communicator()
void ghost_communicator (const GhostCommunicator & gcr, unsigned int data_parts)
Do a ghost communication with caller specified data parts.
Definition at line 341 of file ghosts.cpp.
References add_forces_from_recv_buffer(), add_rattle_correction_from_recv_buffer(), calc_transmit_size(), cell_cell_transfer(), GhostCommunicator::communications, Utils::find_if(), GHOST_BCST, GHOST_JOBMASK, GHOST_LOCL, GHOST_PREFETCH, GHOST_PSTSTORE, GHOST_RDCE, GHOST_RECV, GHOST_SEND, GHOSTTRANS_FORCE, GHOSTTRANS_NONE, GHOSTTRANS_RATTLE, is_recv_op(), is_send_op(), GhostCommunicator::mpi_comm, GhostCommunication::node, node, prepare_recv_buffer(), prepare_send_buffer(), put_recv_buffer(), REQ_GHOST_SEND, this_node, and GhostCommunication::type.
Referenced by CellStructure::ghosts_count(), CellStructure::ghosts_reduce_forces(), CellStructure::ghosts_reduce_rattle_correction(), and CellStructure::ghosts_update().
is_poststorable()
static bool is_poststorable (GhostCommunication const & ghost_comm, int this_node) static
Definition at line 333 of file ghosts.cpp.
References GHOST_JOBMASK, GHOST_PSTSTORE, is_recv_op(), GhostCommunication::node, node, this_node, and GhostCommunication::type.
is_prefetchable()
static bool is_prefetchable (GhostCommunication const & ghost_comm, int this_node) static
Definition at line 325 of file ghosts.cpp.
References GHOST_JOBMASK, GHOST_PREFETCH, is_send_op(), GhostCommunication::node, node, this_node, and GhostCommunication::type.
is_recv_op()
static bool is_recv_op (int comm_type, int node, int this_node) static
Definition at line 319 of file ghosts.cpp.
References GHOST_BCST, GHOST_RDCE, GHOST_RECV, node, and this_node.
Referenced by ghost_communicator(), and is_poststorable().
is_send_op()
static bool is_send_op (int comm_type, int node, int this_node) static
Definition at line 314 of file ghosts.cpp.
References GHOST_BCST, GHOST_RDCE, GHOST_SEND, node, and this_node.
Referenced by ghost_communicator(), and is_prefetchable().
prepare_ghost_cell()
static void prepare_ghost_cell (ParticleList * cell, int size) static
Definition at line 169 of file ghosts.cpp.
References Utils::Bag< T >::resize().
Referenced by cell_cell_transfer(), and put_recv_buffer().
prepare_recv_buffer()
static void prepare_recv_buffer (CommBuf & recv_buffer, const GhostCommunication & ghost_comm, unsigned int data_parts) static
Definition at line 179 of file ghosts.cpp.
References calc_transmit_size().
Referenced by ghost_communicator().
prepare_send_buffer()
static void prepare_send_buffer (CommBuf & send_buffer, const GhostCommunication & ghost_comm, unsigned int data_parts) static
Definition at line 117 of file ghosts.cpp.
References calc_transmit_size(), GHOSTTRANS_BONDS, GHOSTTRANS_FORCE, GHOSTTRANS_MOMENTUM, GHOSTTRANS_PARTNUM, GHOSTTRANS_POSITION, GHOSTTRANS_PROPRTS, GHOSTTRANS_RATTLE, Utils::make_span(), GhostCommunication::part_lists, and GhostCommunication::shift.
Referenced by ghost_communicator().
put_recv_buffer()
static void put_recv_buffer (CommBuf & recv_buffer, const GhostCommunication & ghost_comm, unsigned int data_parts) static
Definition at line 188 of file ghosts.cpp.
References GHOSTTRANS_BONDS, GHOSTTRANS_FORCE, GHOSTTRANS_MOMENTUM, GHOSTTRANS_PARTNUM, GHOSTTRANS_POSITION, GHOSTTRANS_PROPRTS, GHOSTTRANS_RATTLE, Utils::make_span(), GhostCommunication::part_lists, and prepare_ghost_cell().
Referenced by ghost_communicator().