ESPResSo: grid.hpp File Reference
grid.hpp File Reference
#include "BoxGeometry.hpp"
#include "LocalBox.hpp"
#include <utils/Vector.hpp>
#include <boost/mpi/communicator.hpp>
Functions
void init_node_grid ()
Make sure that the node grid is set, eventually determine one automatically.
int map_position_node_array (const Utils::Vector3d &pos)
Map a spatial position to the node grid.
Utils::Vector< int, 6 > calc_node_neighbors (const boost::mpi::communicator &comm)
Fill neighbor lists of node.
Utils::Vector3i calc_node_pos (const boost::mpi::communicator &comm)
Calculate the position of node in topology.
void grid_changed_n_nodes ()
void grid_changed_box_l (const BoxGeometry &box)
void rescale_boxl (int dir, double d_new)
Rescale box in dimension dir to the new value d_new and rescale the particles accordingly.
Utils::Vector3d image_shift (const Utils::Vector3i &image_box, const Utils::Vector3d &box)
Calculate image box shift vector.
Utils::Vector3d unfolded_position (const Utils::Vector3d &pos, const Utils::Vector3i &image_box, const Utils::Vector3d &box)
Unfold particle coordinates to image box.
LocalBox< double > regular_decomposition (const BoxGeometry &box, Utils::Vector3i const &node_pos, Utils::Vector3i const &node_grid)
Composition of the simulation box into equal parts for each node.
void mpi_set_box_length (const Utils::Vector3d &length)
Set and broadcast the box length.
void mpi_set_periodicity (bool x, bool y, bool z)
Set and broadcast the periodicity.
void mpi_set_node_grid (const Utils::Vector3i &node_grid)
Variables
BoxGeometry box_geo
LocalBox< double > local_geo
Utils::Vector3i node_grid
The number of nodes in each spatial dimension.
Detailed Description
Domain decomposition for parallel computing.
The primary simulation box is divided into orthogonal rectangular subboxes which are assigned to the different nodes (or processes or threads if you want). This grid is described in node_grid.
Implementation in grid.cpp.
Definition in file grid.hpp.
Function Documentation
calc_node_neighbors()
Utils::Vector<int, 6> calc_node_neighbors (const boost::mpi::communicator & comm)
Fill neighbor lists of node.
Calculates the numbers of the nearest neighbors for a node.
Returns
Ranks of neighbors
Definition at line 72 of file grid.cpp.
Referenced by grid_changed_n_nodes(), halo_push_communication(), lb_check_halo_regions(), and prepare_halo_communication().
calc_node_pos()
Utils::Vector3i calc_node_pos (const boost::mpi::communicator & comm)
Calculate the position of node in topology.
Parameters
comm Cartesian communicator
Returns
Index of node in grid.
Definition at line 67 of file grid.cpp.
Referenced by grid_changed_box_l(), lb_init(), and LBBoundaries::lb_init_boundaries().
grid_changed_box_l()
void grid_changed_box_l (const BoxGeometry & box)
Definition at line 98 of file grid.cpp.
References calc_node_pos(), comm_cart, local_geo, node_grid, and regular_decomposition().
Referenced by grid_changed_n_nodes(), and on_boxl_change().
grid_changed_n_nodes()
void grid_changed_n_nodes ()
Definition at line 102 of file grid.cpp.
References box_geo, calc_node_neighbors(), Utils::Mpi::cart_create(), comm_cart, grid_changed_box_l(), node_grid, and this_node.
Referenced by init_node_grid(), and on_nodegrid_change().
image_shift()
Utils::Vector3d image_shift (const Utils::Vector3i & image_box, const Utils::Vector3d & box) inline
Calculate image box shift vector.
Parameters
image_box image box offset
box box parameters (side lengths)
Returns
Image box coordinates.
Definition at line 85 of file grid.hpp.
References Utils::hadamard_product().
Referenced by fetch_particles(), and unfolded_position().
init_node_grid()
void init_node_grid ()
Make sure that the node grid is set, eventually determine one automatically.
Definition at line 53 of file grid.cpp.
References grid_changed_n_nodes().
Referenced by on_program_start().
map_position_node_array()
int map_position_node_array (const Utils::Vector3d & pos)
Map a spatial position to the node grid.
Definition at line 55 of file grid.cpp.
References box_geo, Utils::Mpi::cart_rank(), comm_cart, folded_position(), LocalBox< T >::length(), local_geo, node_grid, and pos.
mpi_set_box_length()
void mpi_set_box_length (const Utils::Vector3d & length)
Set and broadcast the box length.
Parameters
length new box length
Definition at line 142 of file grid.cpp.
References mpi_call_all(), and mpi_set_box_length_local().
Referenced by rescale_boxl(), and EspressoSystemStandAlone::set_box_l().
mpi_set_node_grid()
void mpi_set_node_grid (const Utils::Vector3i & node_grid)
Definition at line 172 of file grid.cpp.
References mpi_call_all(), mpi_set_node_grid_local(), and node_grid.
mpi_set_periodicity()
void mpi_set_periodicity (bool x, bool y, bool z)
Set and broadcast the periodicity.
Parameters
x periodicity in x direction
y periodicity in y direction
z periodicity in z direction
Definition at line 161 of file grid.cpp.
References mpi_call_all(), and mpi_set_periodicity_local().
regular_decomposition()
LocalBox<double> regular_decomposition (const BoxGeometry & box, Utils::Vector3i const & node_pos, Utils::Vector3i const & node_grid)
Composition of the simulation box into equal parts for each node.
Parameters
box Geometry of the simulation box
node_pos Position of node in the node grid
node_grid Nodes in each direction
Returns
Geometry for the node
Definition at line 76 of file grid.cpp.
References boundaries, and BoxGeometry::length().
Referenced by grid_changed_box_l().
rescale_boxl()
void rescale_boxl (int dir, double d_new)
Rescale box in dimension dir to the new value d_new and rescale the particles accordingly.
Definition at line 113 of file grid.cpp.
References box_geo, BoxGeometry::length(), BoxGeometry::length_inv(), mpi_rescale_particles(), and mpi_set_box_length().
unfolded_position()
Utils::Vector3d unfolded_position (const Utils::Vector3d & pos, const Utils::Vector3i & image_box, const Utils::Vector3d & box) inline
Unfold particle coordinates to image box.
Parameters
pos coordinate to unfold
image_box image box offset
box box parameters (side lengths, periodicity)
Returns
Unfolded coordinates.
Definition at line 96 of file grid.hpp.
References image_shift(), and pos.
Referenced by add_oif_global_forces(), OifLocalForcesBond::calc_forces(), calc_oif_global(), calc_re(), calc_rg(), calc_rh(), and anonymous_namespace{p3m.cpp}::dipole_moment().
Variable Documentation
box_geo
BoxGeometry box_geo
Definition at line 46 of file grid.cpp.
Referenced by grid_changed_n_nodes(), map_position_node_array(), mpi_set_box_length_local(), mpi_set_periodicity_local(), and rescale_boxl().
local_geo
LocalBox<double> local_geo
Definition at line 47 of file grid.cpp.
Referenced by cells_re_init(), dp3m_adaptive_tune(), dp3m_init(), dp3m_mc_time(), dp3m_sanity_checks_boxl(), grid_changed_box_l(), anonymous_namespace{lb_inertialess_tracers.cpp}::in_local_domain(), anonymous_namespace{lb_particle_coupling.cpp}::in_local_halo(), lb_init(), lb_lbcoupling_calc_particle_lattice_ia(), map_position_node_array(), p3m_adaptive_tune(), p3m_calc_local_ca_mesh(), p3m_init(), p3m_mc_time(), p3m_sanity_checks_boxl(), prepare_halo_communication(), CellStructure::set_domain_decomposition(), and Scafacos::tune_r_cut().
node_grid
Utils::Vector3i node_grid
The number of nodes in each spatial dimension.
Definition at line 49 of file grid.cpp.
Referenced by dp3m_init(), grid_changed_box_l(), grid_changed_n_nodes(), Communication::init(), lb_init(), lb_prepare_communication(), map_position_node_array(), mpi_set_node_grid(), mpi_set_node_grid_local(), Dipole::nonbonded_sanity_check(), p3m_adaptive_tune(), p3m_init(), and p3m_sanity_checks().