ESPResSo: icc.hpp File Reference
icc.hpp File Reference
#include "config.hpp"
#include <ParticleRange.hpp>
#include <utils/Vector.hpp>
#include <algorithm>
#include <vector>
Classes
struct icc_struct
ICC data structure.
Functions
void icc_iteration (const ParticleRange &particles, const ParticleRange &ghost_particles)
The main iterative scheme, where the surface element charges are calculated self-consistently.
int mpi_icc_init ()
Perform ICC initialization.
void icc_set_params (int n_ic, double convergence, double relaxation, Utils::Vector3d &ext_field, int max_iterations, int first_id, double eps_out, std::vector< double > &areas, std::vector< double > &e_in, std::vector< double > &sigma, std::vector< Utils::Vector3d > &normals)
Set ICC parameters.
void icc_deactivate ()
clear ICC vector allocations
Variables
icc_struct icc_cfg
ICC parameters.
Detailed Description
ICC is a method that allows to take into account the influence of arbitrarily shaped dielectric interfaces. The dielectric properties of a dielectric medium in the bulk of the simulation box are taken into account by reproducing the jump in the electric field at the interface with charge surface segments. The charge density of the surface segments have to be determined self-consistently using an iterative scheme. It can at present be used with P3M, ELCP3M and MMM1D. For details see: [50]
To set up ICC, first the dielectric boundary has to be modeled by ESPResSo particles n_0...n_0+n where n_0 and n have to be passed as a parameter to ICC.
For the determination of the induced charges only the forces acting on the induced charges has to be determined. As P3M and the other Coulomb solvers calculate all mutual forces, the force calculation was modified to avoid the calculation of the short range part of the source-source force calculation. For different particle data organisation schemes this is performed differently.
Definition in file icc.hpp.
Function Documentation
icc_deactivate()
void icc_deactivate ()
clear ICC vector allocations
Definition at line 268 of file icc.cpp.
References icc_struct::areas, icc_struct::ein, icc_cfg, mpi_icc_init(), icc_struct::n_icc, icc_struct::normals, and icc_struct::sigma.
icc_iteration()
void icc_iteration (const ParticleRange & particles, const ParticleRange & ghost_particles)
The main iterative scheme, where the surface element charges are calculated self-consistently.
Definition at line 84 of file icc.cpp.
References Utils::abs(), icc_struct::areas, cell_structure, icc_struct::citeration, comm_cart, icc_struct::convergence, coulomb, Cells::DATA_PART_PROPERTIES, icc_struct::ein, icc_struct::eout, icc_struct::ext_field, icc_struct::first_id, force_calc_icc(), CellStructure::ghosts_reduce_forces(), CellStructure::ghosts_update(), icc_cfg, Coulomb::icc_sanity_check(), icc_struct::n_icc, icc_struct::normals, icc_struct::num_iteration, on_particle_charge_change(), Cells::particles(), Utils::pi(), Coulomb_parameters::prefactor, icc_struct::relax, runtimeErrorMsg, and icc_struct::sigma.
Referenced by force_calc(), and update_dependent_particles().
icc_set_params()
void icc_set_params (int n_ic, double convergence, double relaxation, Utils::Vector3d & ext_field, int max_iterations, int first_id, double eps_out, std::vector< double > & areas, std::vector< double > & e_in, std::vector< double > & sigma, std::vector< Utils::Vector3d > & normals)
Set ICC parameters.
Definition at line 220 of file icc.cpp.
References icc_struct::areas, icc_struct::convergence, icc_struct::ein, icc_struct::eout, icc_struct::ext_field, icc_struct::first_id, icc_cfg, mpi_icc_init(), icc_struct::n_icc, icc_struct::normals, icc_struct::num_iteration, icc_struct::relax, and icc_struct::sigma.
mpi_icc_init()
int mpi_icc_init ()
Perform ICC initialization.
Returns
non-zero value on error
Definition at line 213 of file icc.cpp.
References check_runtime_errors(), comm_cart, icc_cfg, mpi_call(), mpi_icc_init_local(), and on_particle_charge_change().
Referenced by icc_deactivate(), and icc_set_params().
Variable Documentation
icc_cfg
icc_struct icc_cfg
ICC parameters.
Definition at line 55 of file icc.cpp.
Referenced by icc_deactivate(), icc_iteration(), icc_set_params(), mpi_icc_init(), and mpi_icc_init_local().