ESPResSo: icc.cpp File Reference
icc.cpp File Reference
#include "config.hpp"
#include "icc.hpp"
#include "Particle.hpp"
#include "ParticleRange.hpp"
#include "cells.hpp"
#include "communication.hpp"
#include "electrostatics_magnetostatics/coulomb.hpp"
#include "electrostatics_magnetostatics/coulomb_inline.hpp"
#include "errorhandling.hpp"
#include "event.hpp"
#include <utils/Vector.hpp>
#include <utils/constants.hpp>
#include <mpi.h>
#include <cmath>
#include <cstdlib>
#include <stdexcept>
#include <tuple>
#include <vector>
Functions
void init_forces_icc (const ParticleRange &particles, const ParticleRange &ghosts_particles)
void force_calc_icc (const ParticleRange &particles, const ParticleRange &ghost_particles)
Calculate the electrostatic forces between source charges (= real charges) and wall charges.
void add_non_bonded_pair_force_icc (Particle &p1, Particle &p2, Utils::Vector3d const &d, double dist, double dist2)
Variant of add_non_bonded_pair_force where only Coulomb contributions are calculated.
void icc_iteration (const ParticleRange &particles, const ParticleRange &ghost_particles)
The main iterative scheme, where the surface element charges are calculated self-consistently.
void mpi_icc_init_local (const icc_struct &icc_cfg_)
int mpi_icc_init ()
Perform ICC initialization.
void icc_set_params (int n_icc, double convergence, double relaxation, Utils::Vector3d &ext_field, int max_iterations, int first_id, double eps_out, std::vector< double > &areas, std::vector< double > &e_in, std::vector< double > &sigma, std::vector< Utils::Vector3d > &normals)
Set ICC parameters.
void icc_deactivate ()
clear ICC vector allocations
Variables
icc_struct icc_cfg
ICC parameters.
Detailed Description
Functions to compute the electric field acting on the induced charges, excluding forces other than the electrostatic ones. Detailed information about the ICC* method is included in the corresponding header file icc.hpp.
Definition in file icc.cpp.
Function Documentation
add_non_bonded_pair_force_icc()
void add_non_bonded_pair_force_icc (Particle & p1, Particle & p2, Utils::Vector3d const & d, double dist, double dist2) inline
Variant of add_non_bonded_pair_force where only Coulomb contributions are calculated.
Definition at line 72 of file icc.cpp.
References ParticleForce::f, Particle::f, and Coulomb::pair_force().
Referenced by force_calc_icc().
force_calc_icc()
void force_calc_icc (const ParticleRange & particles, const ParticleRange & ghost_particles)
Calculate the electrostatic forces between source charges (= real charges) and wall charges.
For each electrostatic method, the proper functions for short- and long-range parts are called. Long-range parts are calculated directly, short-range parts need helper functions according to the particle data organisation. This is a modified version of force_calc.
Definition at line 180 of file icc.cpp.
References add_non_bonded_pair_force_icc(), Coulomb::calc_long_range_force(), cell_structure, Distance::dist2, init_forces_icc(), CellStructure::non_bonded_loop(), Cells::particles(), Utils::sqrt(), and Distance::vec21.
Referenced by icc_iteration().
icc_deactivate()
void icc_deactivate ()
clear ICC vector allocations
Definition at line 268 of file icc.cpp.
References icc_struct::areas, icc_struct::ein, icc_cfg, mpi_icc_init(), icc_struct::n_icc, icc_struct::normals, and icc_struct::sigma.
icc_iteration()
void icc_iteration (const ParticleRange & particles, const ParticleRange & ghost_particles)
The main iterative scheme, where the surface element charges are calculated self-consistently.
Definition at line 84 of file icc.cpp.
References Utils::abs(), icc_struct::areas, cell_structure, icc_struct::citeration, comm_cart, icc_struct::convergence, coulomb, Cells::DATA_PART_PROPERTIES, icc_struct::ein, icc_struct::eout, icc_struct::ext_field, icc_struct::first_id, force_calc_icc(), CellStructure::ghosts_reduce_forces(), CellStructure::ghosts_update(), icc_cfg, Coulomb::icc_sanity_check(), icc_struct::n_icc, icc_struct::normals, icc_struct::num_iteration, on_particle_charge_change(), Cells::particles(), Utils::pi(), Coulomb_parameters::prefactor, icc_struct::relax, runtimeErrorMsg, and icc_struct::sigma.
Referenced by force_calc(), and update_dependent_particles().
icc_set_params()
void icc_set_params (int n_icc, double convergence, double relaxation, Utils::Vector3d & ext_field, int max_iterations, int first_id, double eps_out, std::vector< double > & areas, std::vector< double > & e_in, std::vector< double > & sigma, std::vector< Utils::Vector3d > & normals)
Set ICC parameters.
Definition at line 220 of file icc.cpp.
References icc_struct::areas, icc_struct::convergence, icc_struct::ein, icc_struct::eout, icc_struct::ext_field, icc_struct::first_id, icc_cfg, mpi_icc_init(), icc_struct::n_icc, icc_struct::normals, icc_struct::num_iteration, icc_struct::relax, and icc_struct::sigma.
init_forces_icc()
void init_forces_icc (const ParticleRange & particles, const ParticleRange & ghosts_particles)
Definition at line 193 of file icc.cpp.
References Cells::particles().
Referenced by force_calc_icc().
mpi_icc_init()
int mpi_icc_init ()
Perform ICC initialization.
Returns
non-zero value on error
Definition at line 213 of file icc.cpp.
References check_runtime_errors(), comm_cart, icc_cfg, mpi_call(), mpi_icc_init_local(), and on_particle_charge_change().
Referenced by icc_deactivate(), and icc_set_params().
mpi_icc_init_local()
void mpi_icc_init_local (const icc_struct & icc_cfg_)
Definition at line 204 of file icc.cpp.
References check_runtime_errors(), comm_cart, icc_cfg, and on_particle_charge_change().
Referenced by mpi_icc_init().
Variable Documentation
icc_cfg
icc_struct icc_cfg
ICC parameters.
Definition at line 55 of file icc.cpp.
Referenced by icc_deactivate(), icc_iteration(), icc_set_params(), mpi_icc_init(), and mpi_icc_init_local().