ESPResSo: interactions.hpp File Reference
interactions.hpp File Reference
Functions
void mpi_bcast_all_ia_params ()
Broadcast ia_params to all nodes.
void mpi_bcast_ia_params (int i, int j)
Send new IA params.
void mpi_realloc_ia_params (int s)
Resize ia_params.
Detailed Description
This file contains the asynchronous MPI communication for interactions.
Definition in file interactions.hpp.
Function Documentation
mpi_bcast_all_ia_params()
void mpi_bcast_all_ia_params ()
Broadcast ia_params to all nodes.
Definition at line 42 of file interactions.cpp.
References mpi_bcast_all_ia_params_local(), and mpi_call_all().
Referenced by ia_params_set_state(), and reset_ia_params().
mpi_bcast_ia_params()
void mpi_bcast_ia_params (int i, int j)
Send new IA params.
Also calls on_short_range_ia_change.
Used for both bonded and non-bonded interaction parameters. Therefore i and j are used depending on their value:
Parameters
i particle type for non-bonded interaction parameters / bonded interaction type number.
j if not negative: particle type for non-bonded interaction parameters / if negative: flag for bonded interaction
Definition at line 62 of file interactions.cpp.
References mpi_bcast_ia_params_local(), and mpi_call_all().
Referenced by BMHTF_set_params(), buckingham_set_params(), dpd_set_params(), gaussian_set_params(), gay_berne_set_params(), hat_set_params(), hertzian_set_params(), lennard_jones_set_params(), ljcos2_set_params(), ljcos_set_params(), ljgen_set_params(), morse_set_params(), set_bonded_ia_params(), smooth_step_set_params(), soft_sphere_set_params(), tabulated_set_params(), thole_set_params(), and wca_set_params().
mpi_realloc_ia_params()
void mpi_realloc_ia_params (int s)
Resize ia_params.
Parameters
s the new size.
Definition at line 68 of file interactions.cpp.
References mpi_call_all(), and realloc_ia_params().
Referenced by ia_params_set_state(), and make_particle_type_exist().