ESPResSo: lb_particle_coupling.cpp File Reference
lb_particle_coupling.cpp File Reference
#include "lb_particle_coupling.hpp"
#include "LocalBox.hpp"
#include "Particle.hpp"
#include "communication.hpp"
#include "config.hpp"
#include "errorhandling.hpp"
#include "grid.hpp"
#include "grid_based_algorithms/OptionalCounter.hpp"
#include "integrate.hpp"
#include "lb_interface.hpp"
#include "lb_interpolation.hpp"
#include "lbgpu.hpp"
#include "random.hpp"
#include <profiler/profiler.hpp>
#include <utils/Counter.hpp>
#include <utils/Vector.hpp>
#include <boost/mpi.hpp>
#include <algorithm>
#include <cmath>
#include <cstddef>
#include <stdexcept>
#include <utility>
Namespaces
anonymous_namespace{lb_particle_coupling.cpp}
Typedefs
template<class T , std::size_t N>
using anonymous_namespace{lb_particle_coupling.cpp}::Box = std::pair< Vector< T, N >, Vector< T, N > >
Functions
void mpi_bcast_lb_particle_coupling_slave ()
void mpi_bcast_lb_particle_coupling ()
void lb_lbcoupling_activate ()
void lb_lbcoupling_deactivate ()
void lb_lbcoupling_set_gamma (double gamma)
double lb_lbcoupling_get_gamma ()
bool lb_lbcoupling_is_seed_required ()
uint64_t lb_coupling_get_rng_state_cpu ()
uint64_t lb_lbcoupling_get_rng_state ()
void lb_lbcoupling_set_rng_state (uint64_t counter)
void anonymous_namespace{lb_particle_coupling.cpp}::add_md_force (Utils::Vector3d const &pos, Utils::Vector3d const &force, double time_step)
Add a force to the lattice force density.
Utils::Vector3d lb_viscous_coupling (Particle const &p, Utils::Vector3d const &f_random, double time_step)
Coupling of a single particle to viscous fluid with Stokesian friction.
template<class T , std::size_t N>
bool anonymous_namespace{lb_particle_coupling.cpp}::in_box (Vector< T, N > const &pos, Box< T, N > const &box)
Check if a position is in a box.
template<class T >
bool anonymous_namespace{lb_particle_coupling.cpp}::in_local_domain (Vector< T, 3 > const &pos, LocalBox< T > const &local_box, T const &halo={})
Check if a position is within the local box + halo.
bool anonymous_namespace{lb_particle_coupling.cpp}::in_local_halo (Vector3d const &pos)
Check if a position is within the local LB domain plus halo.
void anonymous_namespace{lb_particle_coupling.cpp}::add_swimmer_force (Particle const &p, double time_step)
void lb_lbcoupling_calc_particle_lattice_ia (bool couple_virtual, const ParticleRange &particles, const ParticleRange &more_particles, double time_step)
Calculate particle lattice interactions.
void lb_lbcoupling_propagate ()
Variables
LB_Particle_Coupling lb_particle_coupling
Function Documentation
lb_coupling_get_rng_state_cpu()
uint64_t lb_coupling_get_rng_state_cpu ()
Definition at line 92 of file lb_particle_coupling.cpp.
References lb_particle_coupling, LB_Particle_Coupling::rng_counter_coupling, and Utils::Counter< T >::value().
Referenced by lb_lbcoupling_get_rng_state().
lb_lbcoupling_activate()
void lb_lbcoupling_activate ()
Definition at line 58 of file lb_particle_coupling.cpp.
References LB_Particle_Coupling::couple_to_md, and lb_particle_coupling.
Referenced by integrate().
lb_lbcoupling_calc_particle_lattice_ia()
void lb_lbcoupling_calc_particle_lattice_ia (bool couple_virtual, const ParticleRange & particles, const ParticleRange & more_particles, double time_step)
Calculate particle lattice interactions.
So far, only viscous coupling with Stokesian friction is implemented. Include all particle-lattice forces in this function. The function is called from force_calc.
Definition at line 250 of file lb_particle_coupling.cpp.
References anonymous_namespace{lb_particle_coupling.cpp}::add_swimmer_force(), LB_Particle_Coupling::couple_to_md, CPU, ESPRESSO_PROFILER_CXX_MARK_FUNCTION, force, GPU, anonymous_namespace{lb_particle_coupling.cpp}::in_local_domain(), anonymous_namespace{lb_particle_coupling.cpp}::in_local_halo(), lattice_switch, lb_calc_particle_lattice_ia_gpu< 27 >(), lb_calc_particle_lattice_ia_gpu< 8 >(), lb_lbcoupling_get_gamma(), lb_lbfluid_get_kT(), lb_lbinterpolation_get_interpolation_order(), lb_particle_coupling, lb_viscous_coupling(), linear, local_geo, Cells::particles(), quadratic, LB_Particle_Coupling::rng_counter_coupling, Utils::sqrt(), this_node, time_step, and Utils::Counter< T >::value().
Referenced by force_calc().
lb_lbcoupling_deactivate()
void lb_lbcoupling_deactivate ()
Definition at line 60 of file lb_particle_coupling.cpp.
References LB_Particle_Coupling::couple_to_md, LB_Particle_Coupling::gamma, lattice_switch, lb_particle_coupling, NONE, runtimeWarningMsg, and this_node.
Referenced by integrate().
lb_lbcoupling_get_gamma()
double lb_lbcoupling_get_gamma ()
Definition at line 78 of file lb_particle_coupling.cpp.
References LB_Particle_Coupling::gamma, and lb_particle_coupling.
Referenced by ek_init(), lb_lbcoupling_calc_particle_lattice_ia(), and lb_viscous_coupling().
lb_lbcoupling_get_rng_state()
uint64_t lb_lbcoupling_get_rng_state ()
Definition at line 96 of file lb_particle_coupling.cpp.
References CPU, GPU, lattice_switch, lb_coupling_get_rng_state_cpu(), and lb_coupling_get_rng_state_gpu().
lb_lbcoupling_is_seed_required()
bool lb_lbcoupling_is_seed_required ()
Definition at line 80 of file lb_particle_coupling.cpp.
References CPU, GPU, OptionalCounter::is_initialized(), lattice_switch, lb_particle_coupling, LB_Particle_Coupling::rng_counter_coupling, and rng_counter_coupling_gpu.
lb_lbcoupling_propagate()
void lb_lbcoupling_propagate ()
Definition at line 336 of file lb_particle_coupling.cpp.
References CPU, GPU, Utils::Counter< T >::increment(), lattice_switch, lb_lbfluid_get_kT(), lb_particle_coupling, NONE, LB_Particle_Coupling::rng_counter_coupling, and rng_counter_coupling_gpu.
Referenced by integrate().
lb_lbcoupling_set_gamma()
void lb_lbcoupling_set_gamma (double gamma)
Definition at line 73 of file lb_particle_coupling.cpp.
References Utils::gamma(), LB_Particle_Coupling::gamma, lb_particle_coupling, and mpi_bcast_lb_particle_coupling().
Referenced by ek_init().
lb_lbcoupling_set_rng_state()
void lb_lbcoupling_set_rng_state (uint64_t counter)
Definition at line 108 of file lb_particle_coupling.cpp.
References CPU, GPU, lattice_switch, lb_coupling_set_rng_state_gpu(), lb_particle_coupling, mpi_bcast_lb_particle_coupling(), and LB_Particle_Coupling::rng_counter_coupling.
lb_viscous_coupling()
Utils::Vector3d lb_viscous_coupling (Particle const & p, Utils::Vector3d const & f_random, double time_step)
Coupling of a single particle to viscous fluid with Stokesian friction.
Section II.C. [2]
Parameters
[in] p The coupled particle.
[in] f_random Additional force to be included.
[in] time_step MD time step.
Returns
The viscous coupling force plus f_random.
Definition at line 146 of file lb_particle_coupling.cpp.
References anonymous_namespace{lb_particle_coupling.cpp}::add_md_force(), ParticlePosition::calc_director(), force, lb_lbcoupling_get_gamma(), lb_lbfluid_get_lattice_speed(), lb_lbinterpolation_get_interpolated_velocity(), Particle::m, ParticleProperties::mu_E, ParticlePosition::p, Particle::p, Particle::r, ParticleProperties::swim, ParticleParametersSwimming::swimming, time_step, ParticleMomentum::v, and ParticleParametersSwimming::v_swim.
Referenced by lb_lbcoupling_calc_particle_lattice_ia().
mpi_bcast_lb_particle_coupling()
void mpi_bcast_lb_particle_coupling ()
Definition at line 53 of file lb_particle_coupling.cpp.
References comm_cart, lb_particle_coupling, mpi_bcast_lb_particle_coupling_slave(), and mpi_call().
Referenced by lb_lbcoupling_set_gamma(), and lb_lbcoupling_set_rng_state().
mpi_bcast_lb_particle_coupling_slave()
void mpi_bcast_lb_particle_coupling_slave ()
Definition at line 47 of file lb_particle_coupling.cpp.
References comm_cart, and lb_particle_coupling.
Referenced by mpi_bcast_lb_particle_coupling().
Variable Documentation
lb_particle_coupling
LB_Particle_Coupling lb_particle_coupling
Definition at line 45 of file lb_particle_coupling.cpp.
Referenced by lb_coupling_get_rng_state_cpu(), lb_lbcoupling_activate(), lb_lbcoupling_calc_particle_lattice_ia(), lb_lbcoupling_deactivate(), lb_lbcoupling_get_gamma(), lb_lbcoupling_is_seed_required(), lb_lbcoupling_propagate(), lb_lbcoupling_set_gamma(), lb_lbcoupling_set_rng_state(), mpi_bcast_lb_particle_coupling(), and mpi_bcast_lb_particle_coupling_slave().