ESPResSo: lb_inertialess_tracers.hpp File Reference
lb_inertialess_tracers.hpp File Reference
Main of the Bayreuth Immersed-Boundary implementation.
#include "config.hpp"
#include "ParticleRange.hpp"
Functions
void IBM_UpdateParticlePositions (ParticleRange const &particles, double time_step)
Interpolate LB velocity at the particle positions and propagate the particles.
void IBM_ForcesIntoFluid_CPU ()
Put the calculated force stored on the ibm particles into the fluid by updating the lbfields structure.
void IBM_ForcesIntoFluid_GPU (ParticleRange const &particles)
Transfer particle forces into the LB fluid.
void IBM_ResetLBForces_GPU ()
Call a kernel to reset the forces on the LB nodes to the external force.
Detailed Description
Main of the Bayreuth Immersed-Boundary implementation.
Definition in file lb_inertialess_tracers.hpp.
Function Documentation
IBM_ForcesIntoFluid_CPU()
void IBM_ForcesIntoFluid_CPU ()
Put the calculated force stored on the ibm particles into the fluid by updating the lbfields structure.
Called from the integration loop right after the forces have been calculated.
Definition at line 69 of file lb_inertialess_tracers.cpp.
References cell_structure, CoupleIBMParticleToFluid(), Cells::DATA_PART_FORCE, CellStructure::ghost_particles(), CellStructure::ghosts_update(), anonymous_namespace{lb_inertialess_tracers.cpp}::in_local_domain(), and CellStructure::local_particles().
IBM_ForcesIntoFluid_GPU()
void IBM_ForcesIntoFluid_GPU (ParticleRange const & particles)
Transfer particle forces into the LB fluid.
Called from integrate. This must be the first CUDA-IBM function to be called because it also does some initialization.
Definition at line 299 of file lb_inertialess_tracers_cuda.cu.
References calculate_dim_grid(), cuda_safe_mem, ForcesIntoFluid_Kernel(), gpu_get_particle_pointer(), IBM_cuda_mpi_get_particles(), IBM_initialized, IBM_numParticlesCache, IBM_ParticleDataInput_device, IBM_ParticleDataInput_host, InitCUDA_IBM(), KERNELCALL, node_f, para_gpu, Cells::particles(), this_node, and threads_per_block.
IBM_ResetLBForces_GPU()
void IBM_ResetLBForces_GPU ()
Call a kernel to reset the forces on the LB nodes to the external force.
Definition at line 284 of file lb_inertialess_tracers_cuda.cu.
References calculate_dim_grid(), KERNELCALL, lbpar_gpu, node_f, LB_parameters_gpu::number_of_nodes, para_gpu, ResetLBForces_Kernel(), this_node, and threads_per_block.
IBM_UpdateParticlePositions()
void IBM_UpdateParticlePositions (ParticleRange const & particles, double time_step)
Interpolate LB velocity at the particle positions and propagate the particles.
Called from the integration loop right after the LB update.
Definition at line 93 of file lb_inertialess_tracers.cpp.
References cell_structure, CPU, GPU, lattice_switch, Cells::particles(), ParticleVelocitiesFromLB_CPU(), ParticleVelocitiesFromLB_GPU(), Cells::RESORT_LOCAL, CellStructure::set_resort_particles(), skin, Utils::sqr(), and time_step.