ESPResSo: magnetic_non_p3m_methods.hpp File Reference
magnetic_non_p3m_methods.hpp File Reference
#include "config.hpp"
#include "Particle.hpp"
#include "ParticleRange.hpp"
Functions
double dawaanr_calculations (bool force_flag, bool energy_flag, ParticleRange const &particles)
Core of the DAWAANR method: here you compute all the magnetic forces, torques and the magnetic energy for the whole system.
void dawaanr_set_params ()
Switch on DAWAANR magnetostatics.
void mdds_sanity_checks (int n_replica)
Sanity checks for the magnetic dipolar direct sum.
double magnetic_dipolar_direct_sum_calculations (bool force_flag, bool energy_flag, ParticleRange const &particles)
Core of the method: here you compute all the magnetic forces, torques and the energy for the whole system using direct sum.
void mdds_set_params (int n_replica)
Switch on direct sum magnetostatics.
Variables
int mdds_n_replica
Detailed Description
All 3d non-P3M methods to deal with the magnetic dipoles
DAWAANR => Dipolar All With All And No Replica Handling of a system of dipoles where no replicas exist. Assumes minimum image convention for those axis in which the system is periodic.
MDDS => Magnetic Dipoles Direct Sum Calculate dipole-dipole interaction of a periodic system by explicitly summing the dipole-dipole interaction over several copies of the system. Uses spherical summation order.
Definition in file magnetic_non_p3m_methods.hpp.
Function Documentation
dawaanr_calculations()
double dawaanr_calculations (bool force_flag, bool energy_flag, ParticleRange const & particles)
Core of the DAWAANR method: here you compute all the magnetic forces, torques and the magnetic energy for the whole system.
Definition at line 106 of file magnetic_non_p3m_methods.cpp.
References calc_dipole_dipole_ia(), n_nodes, and Cells::particles().
Referenced by Dipole::calc_energy_long_range(), and Dipole::calc_long_range_force().
dawaanr_set_params()
void dawaanr_set_params ()
Switch on DAWAANR magnetostatics.
Definition at line 303 of file magnetic_non_p3m_methods.cpp.
References DIPOLAR_ALL_WITH_ALL_AND_NO_REPLICA, dipole, Dipole_parameters::method, mpi_bcast_coulomb_params(), n_nodes, and Dipole::set_method_local().
magnetic_dipolar_direct_sum_calculations()
double magnetic_dipolar_direct_sum_calculations (bool force_flag, bool energy_flag, ParticleRange const & particles)
Core of the method: here you compute all the magnetic forces, torques and the energy for the whole system using direct sum.
Definition at line 151 of file magnetic_non_p3m_methods.cpp.
References b, box_geo, D3Q19::c, dipole, folded_position(), BoxGeometry::length(), mdds_n_replica, n_nodes, Cells::particles(), BoxGeometry::periodic(), Dipole_parameters::prefactor, ParticleRange::size(), Utils::sqr(), and Utils::sqrt().
Referenced by Dipole::calc_energy_long_range(), and Dipole::calc_long_range_force().
mdds_sanity_checks()
void mdds_sanity_checks (int n_replica)
Sanity checks for the magnetic dipolar direct sum.
Definition at line 142 of file magnetic_non_p3m_methods.cpp.
References box_geo, and BoxGeometry::periodic().
Referenced by mdds_set_params(), and Dipole::nonbonded_sanity_check().
mdds_set_params()
void mdds_set_params (int n_replica)
Switch on direct sum magnetostatics.
Parameters
n_replica Number of replicas to be taken for the explicit summation
Definition at line 315 of file magnetic_non_p3m_methods.cpp.
References DIPOLAR_DS, DIPOLAR_MDLC_DS, dipole, mdds_n_replica, mdds_sanity_checks(), Dipole_parameters::method, mpi_bcast_coulomb_params(), n_nodes, and Dipole::set_method_local().
Variable Documentation
mdds_n_replica
int mdds_n_replica
Definition at line 140 of file magnetic_non_p3m_methods.cpp.
Referenced by magnetic_dipolar_direct_sum_calculations(), mdds_set_params(), and Dipole::nonbonded_sanity_check().