ESPResSo: mdlc_correction.hpp File Reference
mdlc_correction.hpp File Reference
#include "config.hpp"
#include <ParticleRange.hpp>
Classes
struct DLC_struct
parameters for the MDLC method
Functions
void mdlc_set_params (double maxPWerror, double gap_size, double far_cut)
void mdlc_sanity_checks ()
void add_mdlc_force_corrections (const ParticleRange &particles)
Compute and add the terms needed to correct the 3D dipolar methods when we have a slab geometry.
double add_mdlc_energy_corrections (const ParticleRange &particles)
Compute and add the terms needed to correct the energy of 3D dipolar methods when we have a slab geometry.
Variables
DLC_struct dlc_params
Detailed Description
main header-file for MDLC (magnetic dipolar layer correction).
Developer: Joan J. Cerda.
Purpose: get the corrections for dipolar 3D algorithms when applied to a slab geometry and dipolar particles. DLC & co
Article: [8]
We also include a tuning function that returns the cut-off necessary to attend a certain accuracy.
Restrictions: the slab must be such that the z is the short direction. Otherwise we get trash.
Limitations: at this moment it is restricted to work with 1 cpu
Definition in file mdlc_correction.hpp.
Function Documentation
add_mdlc_energy_corrections()
double add_mdlc_energy_corrections (const ParticleRange & particles)
Compute and add the terms needed to correct the energy of 3D dipolar methods when we have a slab geometry.
Definition at line 380 of file mdlc_correction.cpp.
References box_geo, calc_slab_dipole(), check_gap_mdlc(), DIPOLAR_MDLC_P3M, dipole, dlc_params, dp3m, P3MParameters::epsilon, DLC_struct::far_cut, get_DLC_energy_dipolar(), Dipole_parameters::method, P3M_EPSILON_METALLIC, p3m_data_struct_base::params, Cells::particles(), Utils::pi(), Dipole_parameters::prefactor, Utils::sqr(), this_node, and BoxGeometry::volume().
Referenced by Dipole::calc_energy_long_range().
add_mdlc_force_corrections()
void add_mdlc_force_corrections (const ParticleRange & particles)
Compute and add the terms needed to correct the 3D dipolar methods when we have a slab geometry.
Definition at line 326 of file mdlc_correction.cpp.
References box_geo, calc_slab_dipole(), check_gap_mdlc(), DIPOLAR_MDLC_P3M, dipole, dlc_params, dp3m, P3MParameters::epsilon, DLC_struct::far_cut, get_DLC_dipolar(), Dipole_parameters::method, P3M_EPSILON_METALLIC, p3m_data_struct_base::params, Cells::particles(), Utils::pi(), Dipole_parameters::prefactor, ParticleRange::size(), Utils::vector_product(), and BoxGeometry::volume().
Referenced by Dipole::calc_long_range_force().
mdlc_sanity_checks()
void mdlc_sanity_checks ()
Definition at line 469 of file mdlc_correction.cpp.
References box_geo, and BoxGeometry::periodic().
Referenced by mdlc_set_params(), and Dipole::nonbonded_sanity_check().
mdlc_set_params()
void mdlc_set_params (double maxPWerror, double gap_size, double far_cut)
Definition at line 475 of file mdlc_correction.cpp.
References box_geo, DIPOLAR_DS, DIPOLAR_MDLC_DS, DIPOLAR_MDLC_P3M, DIPOLAR_P3M, dipole, dlc_params, h, BoxGeometry::length(), maxPWerror, mdlc_sanity_checks(), mdlc_tune_far_cut(), Dipole_parameters::method, mpi_bcast_coulomb_params(), and Dipole::set_method_local().
Variable Documentation
dlc_params
DLC_struct dlc_params
Definition at line 52 of file mdlc_correction.cpp.
Referenced by add_mdlc_energy_corrections(), add_mdlc_force_corrections(), Dipole::bcast_params(), check_gap_mdlc(), and mdlc_set_params().