ESPResSo: mdlc_correction.cpp File Reference
mdlc_correction.cpp File Reference
#include "electrostatics_magnetostatics/mdlc_correction.hpp"
#include "Particle.hpp"
#include "cells.hpp"
#include "communication.hpp"
#include "electrostatics_magnetostatics/common.hpp"
#include "electrostatics_magnetostatics/dipole.hpp"
#include "electrostatics_magnetostatics/p3m-dipolar.hpp"
#include "errorhandling.hpp"
#include "grid.hpp"
#include "particle_data.hpp"
#include <utils/constants.hpp>
#include <utils/math/sqr.hpp>
#include <boost/mpi.hpp>
#include <boost/mpi/collectives/all_reduce.hpp>
#include <boost/mpi/operations.hpp>
#include <algorithm>
#include <cmath>
#include <cstdio>
#include <functional>
#include <numeric>
#include <stdexcept>
#include <vector>
Functions
void check_gap_mdlc (const Particle &p)
Checks if a magnetic particle is in the forbidden gap region.
double calc_mu_max ()
Calculate the maximal dipole moment in the system.
double g1_DLC_dip (double g, double x)
double g2_DLC_dip (double g, double x)
Utils::Vector3d calc_slab_dipole (const ParticleRange &particles)
Compute the box magnetic dipole.
double get_DLC_dipolar (int kcut, std::vector< Utils::Vector3d > &fs, std::vector< Utils::Vector3d > &ts, const ParticleRange &particles)
Compute the dipolar DLC corrections for forces and torques.
double get_DLC_energy_dipolar (int kcut, const ParticleRange &particles)
Compute the dipolar DLC corrections Algorithm implemented accordingly to [8].
void add_mdlc_force_corrections (const ParticleRange &particles)
Compute and add the terms needed to correct the 3D dipolar methods when we have a slab geometry.
double add_mdlc_energy_corrections (const ParticleRange &particles)
Compute and add the terms needed to correct the energy of 3D dipolar methods when we have a slab geometry.
double mdlc_tune_far_cut (DLC_struct const &params)
Compute the cut-off in the DLC dipolar part to get a certain accuracy.
void mdlc_sanity_checks ()
void mdlc_set_params (double maxPWerror, double gap_size, double far_cut)
Variables
DLC_struct dlc_params = {1e100, 0., 0., false, 0.}
Function Documentation
add_mdlc_energy_corrections()
double add_mdlc_energy_corrections (const ParticleRange & particles)
Compute and add the terms needed to correct the energy of 3D dipolar methods when we have a slab geometry.
Definition at line 380 of file mdlc_correction.cpp.
References box_geo, calc_slab_dipole(), check_gap_mdlc(), DIPOLAR_MDLC_P3M, dipole, dlc_params, dp3m, P3MParameters::epsilon, DLC_struct::far_cut, get_DLC_energy_dipolar(), Dipole_parameters::method, P3M_EPSILON_METALLIC, p3m_data_struct_base::params, Cells::particles(), Utils::pi(), Dipole_parameters::prefactor, Utils::sqr(), this_node, and BoxGeometry::volume().
Referenced by Dipole::calc_energy_long_range().
add_mdlc_force_corrections()
void add_mdlc_force_corrections (const ParticleRange & particles)
Compute and add the terms needed to correct the 3D dipolar methods when we have a slab geometry.
Definition at line 326 of file mdlc_correction.cpp.
References box_geo, calc_slab_dipole(), check_gap_mdlc(), DIPOLAR_MDLC_P3M, dipole, dlc_params, dp3m, P3MParameters::epsilon, DLC_struct::far_cut, get_DLC_dipolar(), Dipole_parameters::method, P3M_EPSILON_METALLIC, p3m_data_struct_base::params, Cells::particles(), Utils::pi(), Dipole_parameters::prefactor, ParticleRange::size(), Utils::vector_product(), and BoxGeometry::volume().
Referenced by Dipole::calc_long_range_force().
calc_mu_max()
double calc_mu_max ()
Calculate the maximal dipole moment in the system.
Definition at line 69 of file mdlc_correction.cpp.
References cell_structure, comm_cart, and CellStructure::local_particles().
Referenced by mdlc_tune_far_cut().
calc_slab_dipole()
Utils::Vector3d calc_slab_dipole (const ParticleRange & particles) inline
Compute the box magnetic dipole.
Definition at line 98 of file mdlc_correction.cpp.
References comm_cart, and Cells::particles().
Referenced by add_mdlc_energy_corrections(), and add_mdlc_force_corrections().
check_gap_mdlc()
void check_gap_mdlc (const Particle & p) inline
Checks if a magnetic particle is in the forbidden gap region.
Definition at line 56 of file mdlc_correction.cpp.
References ParticleProperties::dipm, dlc_params, DLC_struct::h, ParticleProperties::identity, ParticlePosition::p, Particle::p, Particle::r, and runtimeErrorMsg.
Referenced by add_mdlc_energy_corrections(), and add_mdlc_force_corrections().
g1_DLC_dip()
double g1_DLC_dip (double g, double x) inline
Definition at line 83 of file mdlc_correction.cpp.
References D3Q19::c.
Referenced by mdlc_tune_far_cut().
g2_DLC_dip()
double g2_DLC_dip (double g, double x) inline
Definition at line 91 of file mdlc_correction.cpp.
Referenced by mdlc_tune_far_cut().
get_DLC_dipolar()
double get_DLC_dipolar (int kcut, std::vector< Utils::Vector3d > & fs, std::vector< Utils::Vector3d > & ts, const ParticleRange & particles)
Compute the dipolar DLC corrections for forces and torques.
Algorithm implemented accordingly to [8].
Definition at line 113 of file mdlc_correction.cpp.
References b, box_geo, D3Q19::c, comm_cart, f, BoxGeometry::length(), BoxGeometry::length_inv(), Cells::particles(), Utils::pi(), ParticleRange::size(), Utils::sqrt(), and Utils::vector_product().
Referenced by add_mdlc_force_corrections().
get_DLC_energy_dipolar()
double get_DLC_energy_dipolar (int kcut, const ParticleRange & particles)
Compute the dipolar DLC corrections Algorithm implemented accordingly to [8].
Definition at line 261 of file mdlc_correction.cpp.
References b, box_geo, D3Q19::c, comm_cart, f, BoxGeometry::length(), BoxGeometry::length_inv(), Cells::particles(), Utils::pi(), Utils::sqrt(), and this_node.
Referenced by add_mdlc_energy_corrections().
mdlc_sanity_checks()
void mdlc_sanity_checks ()
Definition at line 469 of file mdlc_correction.cpp.
References box_geo, and BoxGeometry::periodic().
Referenced by mdlc_set_params(), and Dipole::nonbonded_sanity_check().
mdlc_set_params()
void mdlc_set_params (double maxPWerror, double gap_size, double far_cut)
Definition at line 475 of file mdlc_correction.cpp.
References box_geo, DIPOLAR_DS, DIPOLAR_MDLC_DS, DIPOLAR_MDLC_P3M, DIPOLAR_P3M, dipole, dlc_params, h, BoxGeometry::length(), maxPWerror, mdlc_sanity_checks(), mdlc_tune_far_cut(), Dipole_parameters::method, mpi_bcast_coulomb_params(), and Dipole::set_method_local().
mdlc_tune_far_cut()
double mdlc_tune_far_cut (DLC_struct const & params)
Compute the cut-off in the DLC dipolar part to get a certain accuracy.
We assume particles to have all the same value of the dipolar momentum modulus, which is taken as the largest value of mu inside the system. If we assume the gap has a width gap_size (within which there is no particles): Lz = h + gap_size
BE CAREFUL:
We assume the short distance for the slab to be in the z-direction
You must also tune the other 3D method to the same accuracy, otherwise it makes no sense to have an accurate result for DLC-dipolar.
Definition at line 433 of file mdlc_correction.cpp.
References Utils::abs(), box_geo, calc_mu_max(), g1_DLC_dip(), g2_DLC_dip(), get_n_part(), h, BoxGeometry::length(), Communication::Result::master_rank, mpi_call(), params, Utils::pi(), and Utils::sqrt().
Referenced by mdlc_set_params().
Variable Documentation
dlc_params
DLC_struct dlc_params = {1e100, 0., 0., false, 0.}
Definition at line 52 of file mdlc_correction.cpp.
Referenced by add_mdlc_energy_corrections(), add_mdlc_force_corrections(), Dipole::bcast_params(), check_gap_mdlc(), and mdlc_set_params().