ESPResSo: Mmm1dgpuForce_cuda.cu File Reference
Mmm1dgpuForce_cuda.cu File Reference
#include "config.hpp"
#include "EspressoSystemInterface.hpp"
#include "actor/Mmm1dgpuForce.hpp"
#include "actor/specfunc_cuda.hpp"
#include "cuda_utils.cuh"
#include "electrostatics_magnetostatics/coulomb.hpp"
#include "electrostatics_magnetostatics/mmm-modpsi.hpp"
#include "electrostatics_magnetostatics/mmm1d.hpp"
#include <utils/constants.hpp>
#include <utils/math/sqr.hpp>
#include <cuda.h>
#include <cassert>
#include <cmath>
#include <cstddef>
#include <cstdio>
#include <stdexcept>
#include <vector>
Macros
#define cudaSetDevice(d)
Functions
__device__ float dev_mod_psi_even (int n, float x)
__device__ float dev_mod_psi_odd (int n, float x)
int modpsi_init ()
__forceinline__ __device__ float sqpow (float x)
__forceinline__ __device__ float cbpow (float x)
__device__ void sumReduction (float *input, float *sum)
__global__ void sumKernel (float *data, std::size_t N)
__global__ void besselTuneKernel (int *result, float far_switch_radius, int maxCut)
__global__ void forcesKernel (const float *__restrict__ r, const float *__restrict__ q, float *__restrict__ force, std::size_t N, int pairs, std::size_t tStart)
__global__ void energiesKernel (const float *__restrict__ r, const float *__restrict__ q, float *__restrict__ energy, std::size_t N, int pairs, std::size_t tStart)
__global__ void vectorReductionKernel (float const *src, float *dst, std::size_t N, std::size_t tStart)
__global__ void scaleAndAddKernel (float *dst, float const *src, std::size_t N, float factor)
Variables
constexpr int deviceCount = 1
__constant__ float far_switch_radius_2 [1] = {0.05f * 0.05f}
__constant__ float boxz [1]
__constant__ float uz [1]
__constant__ float coulomb_prefactor [1] = {1.0f}
__constant__ int bessel_cutoff [1] = {5}
__constant__ float maxPWerror [1] = {1e-5f}
constexpr int modpsi_order = 30
constexpr int modpsi_constant_size = modpsi_order * modpsi_order * 2
__constant__ int device_n_modPsi [1] = {0}
__constant__ unsigned int device_linModPsi_offsets [2 *modpsi_order]
__constant__ unsigned int device_linModPsi_lengths [2 *modpsi_order]
__constant__ float device_linModPsi [modpsi_constant_size]
Detailed Description
This file contains the code for the polygamma expansions used for the near formulas of MMM1D on GPU, as well as the force kernels.
Definition in file Mmm1dgpuForce_cuda.cu.
Macro Definition Documentation
cudaSetDevice
#define cudaSetDevice (d)
Definition at line 56 of file Mmm1dgpuForce_cuda.cu.
Function Documentation
besselTuneKernel()
__global__ void besselTuneKernel (int * result, float far_switch_radius, int maxCut)
Definition at line 250 of file Mmm1dgpuForce_cuda.cu.
References dev_K1(), f, maxPWerror, P, and uz.
Referenced by Mmm1dgpuForce::tune().
cbpow()
__forceinline__ __device__ float cbpow (float x)
Definition at line 214 of file Mmm1dgpuForce_cuda.cu.
Referenced by forcesKernel().
dev_mod_psi_even()
__device__ float dev_mod_psi_even (int n, float x)
Definition at line 77 of file Mmm1dgpuForce_cuda.cu.
References device_linModPsi, device_linModPsi_lengths, device_linModPsi_offsets, and evaluateAsTaylorSeriesAt().
Referenced by energiesKernel(), and forcesKernel().
dev_mod_psi_odd()
__device__ float dev_mod_psi_odd (int n, float x)
Definition at line 83 of file Mmm1dgpuForce_cuda.cu.
References device_linModPsi, device_linModPsi_lengths, device_linModPsi_offsets, and evaluateAsTaylorSeriesAt().
Referenced by forcesKernel().
energiesKernel()
__global__ void energiesKernel (const float *__restrict__ r, const float *__restrict__ q, float *__restrict__ energy, std::size_t N, int pairs, std::size_t tStart)
Definition at line 458 of file Mmm1dgpuForce_cuda.cu.
References __syncthreads(), bessel_cutoff, boxz, coulomb_prefactor, dev_K0(), dev_mod_psi_even(), device_n_modPsi, far_switch_radius_2, maxPWerror, N, sqpow(), Utils::sqr(), Utils::sqrt(), sumReduction(), and uz.
Referenced by Mmm1dgpuForce::computeEnergy().
forcesKernel()
__global__ void forcesKernel (const float *__restrict__ r, const float *__restrict__ q, float *__restrict__ force, std::size_t N, int pairs, std::size_t tStart)
Definition at line 368 of file Mmm1dgpuForce_cuda.cu.
References bessel_cutoff, boxz, cbpow(), coulomb_prefactor, dev_K0(), dev_K1(), dev_mod_psi_even(), dev_mod_psi_odd(), device_n_modPsi, far_switch_radius_2, force, maxPWerror, N, sqpow(), Utils::sqr(), Utils::sqrt(), and uz.
Referenced by Mmm1dgpuForce::computeForces().
modpsi_init()
int modpsi_init ()
Definition at line 89 of file Mmm1dgpuForce_cuda.cu.
References create_mod_psi_up_to(), cuda_safe_mem, cudaSetDevice, device_linModPsi, device_linModPsi_lengths, device_linModPsi_offsets, device_n_modPsi, deviceCount, modPsi, modpsi_constant_size, and modpsi_order.
Referenced by Mmm1dgpuForce::Mmm1dgpuForce().
scaleAndAddKernel()
__global__ void scaleAndAddKernel (float * dst, float const * src, std::size_t N, float factor)
Definition at line 570 of file Mmm1dgpuForce_cuda.cu.
References N.
Referenced by Mmm1dgpuForce::computeEnergy().
sqpow()
__forceinline__ __device__ float sqpow (float x)
Definition at line 213 of file Mmm1dgpuForce_cuda.cu.
Referenced by energiesKernel(), and forcesKernel().
sumKernel()
__global__ void sumKernel (float * data, std::size_t N)
Definition at line 228 of file Mmm1dgpuForce_cuda.cu.
References N, and sumReduction().
Referenced by Mmm1dgpuForce::computeEnergy().
sumReduction()
__device__ void sumReduction (float * input, float * sum)
Definition at line 216 of file Mmm1dgpuForce_cuda.cu.
References __syncthreads(), and sum.
Referenced by energiesKernel(), and sumKernel().
vectorReductionKernel()
__global__ void vectorReductionKernel (float const * src, float * dst, std::size_t N, std::size_t tStart)
Definition at line 530 of file Mmm1dgpuForce_cuda.cu.
References N, and Utils::sqr().
Referenced by Mmm1dgpuForce::computeForces().
Variable Documentation
bessel_cutoff
__constant__ int bessel_cutoff[1] = {5}
Definition at line 62 of file Mmm1dgpuForce_cuda.cu.
Referenced by energiesKernel(), forcesKernel(), and Mmm1dgpuForce::tune().
boxz
__constant__ float boxz[1]
Definition at line 59 of file Mmm1dgpuForce_cuda.cu.
Referenced by energiesKernel(), forcesKernel(), and Mmm1dgpuForce::set_params().
coulomb_prefactor
__constant__ float coulomb_prefactor[1] = {1.0f}
Definition at line 61 of file Mmm1dgpuForce_cuda.cu.
Referenced by energiesKernel(), and forcesKernel().
device_linModPsi
__constant__ float device_linModPsi[modpsi_constant_size]
Definition at line 75 of file Mmm1dgpuForce_cuda.cu.
Referenced by dev_mod_psi_even(), dev_mod_psi_odd(), and modpsi_init().
device_linModPsi_lengths
__constant__ unsigned int device_linModPsi_lengths[2 *modpsi_order]
Definition at line 74 of file Mmm1dgpuForce_cuda.cu.
Referenced by dev_mod_psi_even(), dev_mod_psi_odd(), and modpsi_init().
device_linModPsi_offsets
__constant__ unsigned int device_linModPsi_offsets[2 *modpsi_order]
Definition at line 73 of file Mmm1dgpuForce_cuda.cu.
Referenced by dev_mod_psi_even(), dev_mod_psi_odd(), and modpsi_init().
device_n_modPsi
__constant__ int device_n_modPsi[1] = {0}
Definition at line 72 of file Mmm1dgpuForce_cuda.cu.
Referenced by energiesKernel(), forcesKernel(), and modpsi_init().
deviceCount
constexpr int deviceCount = 1 constexpr
Definition at line 53 of file Mmm1dgpuForce_cuda.cu.
Referenced by cuda_get_n_gpus(), modpsi_init(), Mmm1dgpuForce::set_params(), and Mmm1dgpuForce::setup().
far_switch_radius_2
__constant__ float far_switch_radius_2[1] = {0.05f * 0.05f}
Definition at line 58 of file Mmm1dgpuForce_cuda.cu.
Referenced by energiesKernel(), forcesKernel(), and Mmm1dgpuForce::set_params().
maxPWerror
__constant__ float maxPWerror[1] = {1e-5f}
Definition at line 63 of file Mmm1dgpuForce_cuda.cu.
Referenced by besselTuneKernel(), determine_bessel_radii(), determine_minrad(), ELC_set_params(), energiesKernel(), forcesKernel(), mdlc_set_params(), MMM1D_set_params(), and prepare_polygamma_series().
modpsi_constant_size
constexpr int modpsi_constant_size = modpsi_order * modpsi_order * 2 constexpr
Definition at line 69 of file Mmm1dgpuForce_cuda.cu.
Referenced by modpsi_init().
modpsi_order
constexpr int modpsi_order = 30 constexpr
Definition at line 68 of file Mmm1dgpuForce_cuda.cu.
Referenced by modpsi_init().
uz
__constant__ float uz[1]
Definition at line 60 of file Mmm1dgpuForce_cuda.cu.
Referenced by besselTuneKernel(), energiesKernel(), forcesKernel(), and Mmm1dgpuForce::set_params().