ESPResSo: Scafacos Namespace Reference
Scafacos Namespace Reference
Namespaces
anonymous_namespace{scafacos.cpp}
Classes
struct Scafacos
Abstraction of a method from the scafacos library.
struct ScafacosContext
Encapsulation for the particle data needed by ScaFaCoS.
struct ScafacosContextBase
Public interface to the ScaFaCoS context.
struct ScafacosContextCoulomb
struct ScafacosContextDipoles
Functions
std::list< std::string > available_methods ()
Get available ScaFaCoS methods.
ScafacosContextBase * fcs_dipoles ()
Access the per-MPI-node ScaFaCoS dipoles instance.
ScafacosContextBase * fcs_coulomb ()
Access the per-MPI-node ScaFaCoS Coulomb instance.
static void set_parameters_dipoles_worker (const std::string &method, const std::string &params)
static void set_parameters_coulomb_worker (const std::string &method, const std::string &params)
void set_r_cut_and_tune_local (double r_cut)
void free_handle (bool dipolar)
void set_parameters (const std::string &method, const std::string &params, bool dipolar)
std::string get_method_and_parameters (bool dipolar)
static void set_r_cut_and_tune_local_worker (double r_cut)
static double time_r_cut (double r_cut)
Determine runtime for a specific cutoff.
static void tune_r_cut ()
Determine the optimal cutoff by bisection.
Function Documentation
available_methods()
std::list< std::string > Scafacos::available_methods ()
Get available ScaFaCoS methods.
Definition at line 47 of file scafacos.cpp.
fcs_coulomb()
ScafacosContextBase * Scafacos::Scafacos::fcs_coulomb ()
Access the per-MPI-node ScaFaCoS Coulomb instance.
Definition at line 68 of file scafacos.cpp.
References Scafacos::anonymous_namespace{scafacos.cpp}::coulomb_instance.
Referenced by Coulomb::calc_energy_long_range(), Coulomb::calc_long_range_force(), Coulomb::central_force(), Coulomb::cutoff(), get_method_and_parameters(), Coulomb::on_boxl_change(), on_periodicity_change(), and Coulomb::pair_energy().
fcs_dipoles()
ScafacosContextBase * Scafacos::Scafacos::fcs_dipoles ()
Access the per-MPI-node ScaFaCoS dipoles instance.
Definition at line 59 of file scafacos.cpp.
References Scafacos::anonymous_namespace{scafacos.cpp}::dipoles_instance.
Referenced by Dipole::calc_energy_long_range(), Dipole::calc_long_range_force(), get_method_and_parameters(), Dipole::on_boxl_change(), and on_periodicity_change().
free_handle()
void Scafacos::free_handle (bool dipolar)
Definition at line 125 of file scafacos.cpp.
References Scafacos::anonymous_namespace{scafacos.cpp}::coulomb_instance, Scafacos::anonymous_namespace{scafacos.cpp}::dipoles_instance, mpi_call(), and this_node.
get_method_and_parameters()
std::string Scafacos::get_method_and_parameters (bool dipolar)
Definition at line 152 of file scafacos.cpp.
References fcs_coulomb(), fcs_dipoles(), and Scafacos::ScafacosContextBase::get_method_and_parameters().
set_parameters()
void Scafacos::set_parameters (const std::string & method, const std::string & params, bool dipolar)
Definition at line 141 of file scafacos.cpp.
References mpi_call_all(), params, set_parameters_coulomb_worker(), and set_parameters_dipoles_worker().
set_parameters_coulomb_worker()
static void Scafacos::set_parameters_coulomb_worker (const std::string & method, const std::string & params) static
Definition at line 99 of file scafacos.cpp.
References comm_cart, coulomb, Scafacos::anonymous_namespace{scafacos.cpp}::coulomb_instance, COULOMB_SCAFACOS, Coulomb_parameters::method, Coulomb::on_coulomb_change(), params, runtimeErrorMsg, and Scafacos::Scafacos::set_dipolar().
Referenced by set_parameters().
set_parameters_dipoles_worker()
static void Scafacos::set_parameters_dipoles_worker (const std::string & method, const std::string & params) static
Definition at line 77 of file scafacos.cpp.
References comm_cart, DIPOLAR_SCAFACOS, dipole, Scafacos::anonymous_namespace{scafacos.cpp}::dipoles_instance, Dipole_parameters::method, Coulomb::on_coulomb_change(), params, runtimeErrorMsg, and Scafacos::Scafacos::set_dipolar().
Referenced by set_parameters().
set_r_cut_and_tune_local()
void Scafacos::set_r_cut_and_tune_local (double r_cut)
Definition at line 121 of file scafacos.cpp.
References Scafacos::anonymous_namespace{scafacos.cpp}::coulomb_instance, and Scafacos::ScafacosContextCoulomb::set_r_cut_and_tune_local().
Referenced by set_r_cut_and_tune_local_worker().
set_r_cut_and_tune_local_worker()
static void Scafacos::set_r_cut_and_tune_local_worker (double r_cut) static
Definition at line 179 of file ScafacosContext.cpp.
References set_r_cut_and_tune_local().
Referenced by time_r_cut().
time_r_cut()
static double Scafacos::time_r_cut (double r_cut) static
Determine runtime for a specific cutoff.
Definition at line 186 of file ScafacosContext.cpp.
References mpi_call_all(), set_r_cut_and_tune_local_worker(), and time_force_calc().
Referenced by tune_r_cut().
tune_r_cut()
static void Scafacos::tune_r_cut () static
Determine the optimal cutoff by bisection.
Definition at line 194 of file ScafacosContext.cpp.
References box_geo, dr, LocalBox< T >::length(), BoxGeometry::length(), local_geo, anonymous_namespace{Correlator.cpp}::min(), skin, and time_r_cut().
Referenced by Scafacos::ScafacosContextCoulomb::tune().