ESPResSo: anonymous_namespace{DomainDecomposition.cpp} Namespace Reference
anonymous_namespace{DomainDecomposition.cpp} Namespace Reference
Functions
void fold_and_reset (Particle &p, BoxGeometry const &box_geo)
Fold coordinates to box and reset the old position.
void revert_comm_order (GhostCommunicator &comm)
Revert the order of a communicator: After calling this the communicator is working in reverted order with exchanged communication types GHOST_SEND <-> GHOST_RECV.
void assign_prefetches (GhostCommunicator &comm)
Of every two communication rounds, set the first receivers to prefetch and poststore.
Utils::Vector3d shift (BoxGeometry const &box, LocalBox< double > const &local_box, int dir, int lr)
Function Documentation
assign_prefetches()
void anonymous_namespace{DomainDecomposition.cpp}::assign_prefetches (GhostCommunicator & comm)
Of every two communication rounds, set the first receivers to prefetch and poststore.
Definition at line 445 of file DomainDecomposition.cpp.
References GhostCommunicator::communications, GHOST_PREFETCH, GHOST_PSTSTORE, GHOST_RECV, and GHOST_SEND.
Referenced by DomainDecomposition::DomainDecomposition().
fold_and_reset()
void anonymous_namespace{DomainDecomposition.cpp}::fold_and_reset (Particle & p, BoxGeometry const & box_geo)
Fold coordinates to box and reset the old position.
Definition at line 164 of file DomainDecomposition.cpp.
References box_geo, fold_position(), ParticleLocal::i, Particle::l, ParticlePosition::p, ParticleLocal::p_old, and Particle::r.
Referenced by DomainDecomposition::resort().
revert_comm_order()
void anonymous_namespace{DomainDecomposition.cpp}::revert_comm_order (GhostCommunicator & comm)
Revert the order of a communicator: After calling this the communicator is working in reverted order with exchanged communication types GHOST_SEND <-> GHOST_RECV.
Definition at line 426 of file DomainDecomposition.cpp.
References D3Q19::c, GhostCommunicator::communications, GHOST_LOCL, GHOST_RECV, and GHOST_SEND.
Referenced by DomainDecomposition::DomainDecomposition().
shift()
Utils::Vector3d anonymous_namespace{DomainDecomposition.cpp}::shift (BoxGeometry const & box, LocalBox< double > const & local_box, int dir, int lr)
Definition at line 457 of file DomainDecomposition.cpp.
References LocalBox< T >::boundary(), BoxGeometry::length(), and BoxGeometry::periodic().
Referenced by add_dipole_force(), BMHTF_set_params(), bounce_back_boundaries(), buck_energy_r(), buckingham_set_params(), dipole_energy(), G_opt_dipolar(), G_opt_dipolar_self_energy(), image_sum_b(), image_sum_t(), lennard_jones_set_params(), ljgen_set_params(), and z_energy().