ESPResSo: anonymous_namespace{lb_particle_coupling.cpp} Namespace Reference
anonymous_namespace{lb_particle_coupling.cpp} Namespace Reference
Typedefs
template<class T , std::size_t N>
using Box = std::pair< Vector< T, N >, Vector< T, N > >
Functions
void add_md_force (Utils::Vector3d const &pos, Utils::Vector3d const &force, double time_step)
Add a force to the lattice force density.
template<class T , std::size_t N>
bool in_box (Vector< T, N > const &pos, Box< T, N > const &box)
Check if a position is in a box.
template<class T >
bool in_local_domain (Vector< T, 3 > const &pos, LocalBox< T > const &local_box, T const &halo={})
Check if a position is within the local box + halo.
bool in_local_halo (Vector3d const &pos)
Check if a position is within the local LB domain plus halo.
void add_swimmer_force (Particle const &p, double time_step)
Typedef Documentation
Box
template<class T , std::size_t N> using anonymous_namespace{lb_particle_coupling.cpp}::Box = typedef std::pair<Vector<T, N>, Vector<T, N> >
Definition at line 179 of file lb_particle_coupling.cpp.
Function Documentation
add_md_force()
void anonymous_namespace{lb_particle_coupling.cpp}::add_md_force (Utils::Vector3d const & pos, Utils::Vector3d const & force, double time_step)
Add a force to the lattice force density.
Parameters
pos Position of the force
force Force in MD units.
time_step MD time step.
Definition at line 127 of file lb_particle_coupling.cpp.
References force, lb_lbfluid_get_lattice_speed(), lb_lbinterpolation_add_force_density(), pos, and time_step.
Referenced by add_swimmer_force(), and lb_viscous_coupling().
add_swimmer_force()
void anonymous_namespace{lb_particle_coupling.cpp}::add_swimmer_force (Particle const & p, double time_step)
Definition at line 231 of file lb_particle_coupling.cpp.
References add_md_force(), ParticlePosition::calc_director(), ParticleParametersSwimming::dipole_length, ParticleParametersSwimming::f_swim, in_local_halo(), ParticlePosition::p, Particle::p, ParticleParametersSwimming::push_pull, Particle::r, ParticleProperties::swim, ParticleParametersSwimming::swimming, and time_step.
Referenced by lb_lbcoupling_calc_particle_lattice_ia().
in_box()
template<class T , std::size_t N> bool anonymous_namespace{lb_particle_coupling.cpp}::in_box (Vector< T, N > const & pos, Box< T, N > const & box)
Check if a position is in a box.
The left boundary belong to the box, the right one does not. Periodic boundaries are not considered.
Parameters
pos Position to check
box Box to check
Returns
True iff the point is inside of the box.
Definition at line 194 of file lb_particle_coupling.cpp.
References pos.
in_local_domain()
template<class T > bool anonymous_namespace{lb_particle_coupling.cpp}::in_local_domain (Vector< T, 3 > const & pos, LocalBox< T > const & local_box, T const & halo = {})
Check if a position is within the local box + halo.
Parameters
pos Position to check
local_box Geometry to check
halo Halo
Returns
True iff the point is inside of the box up to halo.
Definition at line 208 of file lb_particle_coupling.cpp.
Referenced by in_local_halo(), and lb_lbcoupling_calc_particle_lattice_ia().
in_local_halo()
bool anonymous_namespace{lb_particle_coupling.cpp}::in_local_halo (Vector3d const & pos)
Check if a position is within the local LB domain plus halo.
Parameters
pos Position to check
Returns
True iff the point is inside of the domain.
Definition at line 224 of file lb_particle_coupling.cpp.
References in_local_domain(), lb_lbfluid_get_agrid(), local_geo, and pos.
Referenced by add_swimmer_force(), and lb_lbcoupling_calc_particle_lattice_ia().