ESPResSo: Mpiio Namespace Reference
Mpiio Namespace Reference
Enumerations
enum MPIIOOutputFields : unsigned int { MPIIO_OUT_POS = 1u, MPIIO_OUT_VEL = 2u, MPIIO_OUT_TYP = 4u, MPIIO_OUT_BND = 8u }
Constants which indicate what to output.
Functions
template<typename T >
static void mpiio_dump_array (const std::string &fn, T *arr, std::size_t len, std::size_t pref, MPI_Datatype MPI_T)
Dumps arr of size len starting from prefix pref of type T using MPI_T as MPI datatype.
static void dump_info (const std::string &fn, unsigned fields)
Dumps some generic infos like the dumped fields and info to process the bond information offline (without ESPResSo).
void mpi_mpiio_common_write (const char *filename, unsigned fields, const ParticleRange &particles)
Parallel binary output using MPI-IO.
static int get_num_elem (const std::string &fn, std::size_t elem_sz)
Get the number of elements in a file by its file size and elem_sz.
template<typename T >
static void mpiio_read_array (const std::string &fn, T *arr, std::size_t len, std::size_t pref, MPI_Datatype MPI_T)
Reads a previously dumped array of size len starting from prefix pref of type T using MPI_T as MPI datatype.
static void read_head (const std::string &fn, int rank, unsigned *fields)
Read the header file and store the information in the pointer "field".
static void read_prefs (const std::string &fn, int rank, int size, int nglobalpart, int *pref, int *nlocalpart)
Reads the pref file and fills pref and nlocalpart with their corresponding values.
void mpi_mpiio_common_read (const char *filename, unsigned fields)
Parallel binary input using MPI-IO.
Enumeration Type Documentation
MPIIOOutputFields
enum Mpiio::MPIIOOutputFields : unsigned int
Constants which indicate what to output.
To indicate the output of multiple fields, OR the corresponding values.
Enumerator
MPIIO_OUT_POS
MPIIO_OUT_VEL
MPIIO_OUT_TYP
MPIIO_OUT_BND
Definition at line 35 of file mpiio.hpp.
Function Documentation
dump_info()
static void Mpiio::dump_info (const std::string & fn, unsigned fields) static
Dumps some generic infos like the dumped fields and info to process the bond information offline (without ESPResSo).
To be called by the master node only.
Parameters
fn The filename to write to
fields The dumped fields
Definition at line 125 of file mpiio.cpp.
References bonded_ia_params, errexit(), f, and number_of_partners().
Referenced by mpi_mpiio_common_write().
get_num_elem()
static int Mpiio::get_num_elem (const std::string & fn, std::size_t elem_sz) static
Get the number of elements in a file by its file size and elem_sz.
I.e. query the file size using stat(2) and divide it by elem_sz.
Parameters
fn The filename
elem_sz Sizeof a single element
Returns
The number of elements stored binary in the file
Definition at line 250 of file mpiio.cpp.
References errexit().
Referenced by mpi_mpiio_common_read().
mpi_mpiio_common_read()
void Mpiio::mpi_mpiio_common_read (const char * filename, unsigned fields)
Parallel binary input using MPI-IO.
To be called by all MPI processes. Aborts ESPResSo if an error occurs.
Parameters
filename A null-terminated filename prefix.
fields Specifier which fields to read.
Definition at line 344 of file mpiio.cpp.
References cell_structure, errexit(), get_num_elem(), MPIIO_OUT_POS, MPIIO_OUT_TYP, MPIIO_OUT_VEL, Cells::particles(), pos, read_head(), read_prefs(), and CellStructure::remove_all_particles().
Referenced by ScriptInterface::MPIIO::MPIIOScript::do_call_method().
mpi_mpiio_common_write()
void Mpiio::mpi_mpiio_common_write (const char * filename, unsigned fields, const ParticleRange & particles)
Parallel binary output using MPI-IO.
To be called by all MPI processes. Aborts ESPResSo if an error occurs.
Parameters
filename A null-terminated filename prefix.
fields Output specifier which fields to dump.
particles range of particles to serialize.
Definition at line 155 of file mpiio.cpp.
References dump_info(), MPIIO_OUT_BND, MPIIO_OUT_POS, MPIIO_OUT_TYP, MPIIO_OUT_VEL, Cells::particles(), pos, and ParticleRange::size().
Referenced by ScriptInterface::MPIIO::MPIIOScript::do_call_method().
mpiio_dump_array()
template<typename T > static void Mpiio::mpiio_dump_array (const std::string & fn, T * arr, std::size_t len, std::size_t pref, MPI_Datatype MPI_T) static
Dumps arr of size len starting from prefix pref of type T using MPI_T as MPI datatype.
Beware, that T and MPI_T have to match!
Parameters
fn The file name to dump to. Must not exist already
arr The array to dump
len The number of elements to dump
pref The prefix for this process
MPI_T The MPI_Datatype corresponding to the template parameter T.
Definition at line 90 of file mpiio.cpp.
References errexit(), and f.
mpiio_read_array()
template<typename T > static void Mpiio::mpiio_read_array (const std::string & fn, T * arr, std::size_t len, std::size_t pref, MPI_Datatype MPI_T) static
Reads a previously dumped array of size len starting from prefix pref of type T using MPI_T as MPI datatype.
Beware, that T and MPI_T have to match!
Definition at line 268 of file mpiio.cpp.
References errexit(), and f.
read_head()
static void Mpiio::read_head (const std::string & fn, int rank, unsigned * fields) static
Read the header file and store the information in the pointer "field".
To be called by all processes.
Parameters
fn Filename of the head file
rank The rank of the current process in MPI_COMM_WORLD
fields Pointer to store the fields to
Definition at line 303 of file mpiio.cpp.
References errexit(), and f.
Referenced by mpi_mpiio_common_read().
read_prefs()
static void Mpiio::read_prefs (const std::string & fn, int rank, int size, int nglobalpart, int * pref, int * nlocalpart) static
Reads the pref file and fills pref and nlocalpart with their corresponding values.
Needs to be called by all processes.
Parameters
fn The file name of the prefs file
rank The rank of the current process in MPI_COMM_WORLD
size The size of MPI_COMM_WORLD
nglobalpart The global amount of particles
pref Pointer to store the prefix to
nlocalpart Pointer to store the amount of local particles to
Definition at line 331 of file mpiio.cpp.
Referenced by mpi_mpiio_common_read().