ESPResSo: Dipole Namespace Reference
Dipole Namespace Reference
Functions
void calc_pressure_long_range ()
void nonbonded_sanity_check (int &state)
double cutoff (const Utils::Vector3d &box_l)
void on_observable_calc ()
called before calculating observables, i.e.
void on_coulomb_change ()
called every time the Coulomb parameters are changed.
void on_boxl_change ()
void init ()
void calc_long_range_force (const ParticleRange &particles)
double calc_energy_long_range (const ParticleRange &particles)
void bcast_params (const boost::mpi::communicator &comm)
void set_Dprefactor (double prefactor)
Set the dipolar prefactor.
void set_method_local (DipolarInteraction method)
ParticleForce pair_force (Particle const &p1, Particle const &p2, Utils::Vector3d const &d, double dist, double dist2)
double pair_energy (Particle const &p1, Particle const &p2, Utils::Vector3d const &d, double dist, double dist2)
Function Documentation
bcast_params()
void Dipole::bcast_params (const boost::mpi::communicator & comm)
Definition at line 269 of file dipole.cpp.
References DIPOLAR_MDLC_P3M, DIPOLAR_P3M, dipole, dlc_params, dp3m, Dipole_parameters::method, and p3m_data_struct_base::params.
Referenced by mpi_bcast_coulomb_params_local().
calc_energy_long_range()
double Dipole::calc_energy_long_range (const ParticleRange & particles)
Definition at line 220 of file dipole.cpp.
References add_mdlc_energy_corrections(), dawaanr_calculations(), DIPOLAR_ALL_WITH_ALL_AND_NO_REPLICA, DIPOLAR_BH_GPU, DIPOLAR_DS, DIPOLAR_DS_GPU, DIPOLAR_MDLC_DS, DIPOLAR_MDLC_P3M, DIPOLAR_NONE, DIPOLAR_P3M, DIPOLAR_SCAFACOS, dipole, dp3m_calc_kspace_forces(), dp3m_dipole_assign(), Scafacos::fcs_dipoles(), Scafacos::ScafacosContextBase::long_range_energy(), magnetic_dipolar_direct_sum_calculations(), Dipole_parameters::method, Cells::particles(), and runtimeErrorMsg.
Referenced by calculate_energy_local().
calc_long_range_force()
void Dipole::calc_long_range_force (const ParticleRange & particles)
Definition at line 170 of file dipole.cpp.
References Scafacos::ScafacosContextBase::add_long_range_force(), add_mdlc_force_corrections(), dawaanr_calculations(), DIPOLAR_ALL_WITH_ALL_AND_NO_REPLICA, DIPOLAR_BH_GPU, DIPOLAR_DS, DIPOLAR_DS_GPU, DIPOLAR_MDLC_DS, DIPOLAR_MDLC_P3M, DIPOLAR_NONE, DIPOLAR_P3M, DIPOLAR_SCAFACOS, dipole, dp3m_calc_kspace_forces(), dp3m_dipole_assign(), Scafacos::fcs_dipoles(), INTEG_METHOD_NPT_ISO, integ_switch, magnetic_dipolar_direct_sum_calculations(), Dipole_parameters::method, npt_add_virial_contribution(), Cells::particles(), and runtimeErrorMsg.
Referenced by calc_long_range_forces().
calc_pressure_long_range()
void Dipole::calc_pressure_long_range ()
Definition at line 56 of file dipole.cpp.
References DIPOLAR_NONE, dipole, Dipole_parameters::method, and runtimeWarningMsg.
Referenced by calculate_pressure_local().
cutoff()
double Dipole::cutoff (const Utils::Vector3d & box_l)
Definition at line 94 of file dipole.cpp.
References DIPOLAR_MDLC_P3M, DIPOLAR_P3M, dipole, dp3m, Dipole_parameters::method, p3m_data_struct_base::params, and P3MParameters::r_cut_iL.
Referenced by force_calc(), and recalc_long_range_cutoff().
init()
void Dipole::init ()
Definition at line 156 of file dipole.cpp.
References DIPOLAR_MDLC_P3M, DIPOLAR_P3M, dipole, dp3m_init(), and Dipole_parameters::method.
Referenced by on_cell_structure_change().
nonbonded_sanity_check()
void Dipole::nonbonded_sanity_check (int & state)
Definition at line 67 of file dipole.cpp.
References DIPOLAR_DS, DIPOLAR_MDLC_DS, DIPOLAR_MDLC_P3M, DIPOLAR_P3M, dipole, dp3m_sanity_checks(), mdds_n_replica, mdds_sanity_checks(), mdlc_sanity_checks(), Dipole_parameters::method, node_grid, and runtimeErrorMsg.
Referenced by interactions_sanity_checks().
on_boxl_change()
void Dipole::on_boxl_change ()
Definition at line 137 of file dipole.cpp.
References DIPOLAR_MDLC_P3M, DIPOLAR_P3M, DIPOLAR_SCAFACOS, dipole, dp3m_scaleby_box_l(), Scafacos::fcs_dipoles(), Dipole_parameters::method, and Scafacos::ScafacosContextBase::update_system_params().
Referenced by on_boxl_change().
on_coulomb_change()
void Dipole::on_coulomb_change ()
called every time the Coulomb parameters are changed.
Definition at line 123 of file dipole.cpp.
References DIPOLAR_MDLC_P3M, DIPOLAR_P3M, dipole, dp3m_init(), and Dipole_parameters::method.
Referenced by on_coulomb_change().
on_observable_calc()
void Dipole::on_observable_calc ()
called before calculating observables, i.e.
energy, pressure or the integrator (forces). Initialize any methods here which are not initialized immediately (P3M etc.).
Definition at line 109 of file dipole.cpp.
References DIPOLAR_MDLC_P3M, DIPOLAR_P3M, dipole, dp3m_count_magnetic_particles(), and Dipole_parameters::method.
Referenced by on_observable_calc().
pair_energy()
double Dipole::pair_energy (Particle const & p1, Particle const & p2, Utils::Vector3d const & d, double dist, double dist2) inline
Definition at line 48 of file dipole_inline.hpp.
References DIPOLAR_MDLC_P3M, DIPOLAR_NONE, DIPOLAR_P3M, dipole, dp3m_pair_energy(), and Dipole_parameters::method.
Referenced by add_non_bonded_pair_energy().
pair_force()
ParticleForce Dipole::pair_force (Particle const & p1, Particle const & p2, Utils::Vector3d const & d, double dist, double dist2) inline
Definition at line 28 of file dipole_inline.hpp.
References DIPOLAR_MDLC_P3M, DIPOLAR_P3M, dipole, dp3m_pair_force(), and Dipole_parameters::method.
Referenced by add_non_bonded_pair_force().
set_Dprefactor()
void Dipole::set_Dprefactor (double prefactor)
Set the dipolar prefactor.
Definition at line 286 of file dipole.cpp.
References dipole, mpi_bcast_coulomb_params(), and Dipole_parameters::prefactor.
set_method_local()
void Dipole::set_method_local (DipolarInteraction method)
Definition at line 296 of file dipole.cpp.
References deactivate_dipolar_barnes_hut(), deactivate_dipolar_direct_sum_gpu(), DIPOLAR_BH_GPU, DIPOLAR_DS_GPU, dipole, and Dipole_parameters::method.
Referenced by dawaanr_set_params(), dp3m_mcr_time(), dp3m_set_params(), mdds_set_params(), mdlc_set_params(), and mpi_bcast_coulomb_params_local().