ESPResSo: ScriptInterface Namespace Reference
ScriptInterface Namespace Reference
Namespaces
Accumulators
ClusterAnalysis
CollisionDetection
Constraints
LBBoundaries
MPIIO
Observables
PairCriteria
Shapes
VirtualSites
Writer
Classes
struct AutoParameter
Description and getter/setter for a parameter.
class AutoParameters
Bind parameters in the script interface.
class ComFixed
class Context
Context of an object handle.
class ContextManager
Manage object contexts.
class CylindricalTransformationParameters
struct Exception
class GlobalContext
Global synchronizing context.
class LocalContext
Trivial context.
class None
Type to indicate no value in Variant.
class ObjectHandle
Base class for interface handles.
class ObjectList
Owning list of ObjectHandles.
struct ObjectState
State of an object ready for serialization.
struct PackVisitor
Visitor that converts a Variant to a PackedVariant.
struct UnpackVisitor
Visitor that converts a PackedVariant to a Variant.
Typedefs
using ObjectId = std::size_t
using PackedVariant = boost::make_recursive_variant< None, bool, int, double, std::string, std::vector< int >, std::vector< double >, ObjectId, std::vector< boost::recursive_variant_ >, Utils::Vector2d, Utils::Vector3d, Utils::Vector4d, std::unordered_map< int, boost::recursive_variant_ > >::type
Packed version of Variant.
using PackedMap = std::vector< std::pair< std::string, PackedVariant > >
using ObjectRef = std::shared_ptr< ObjectHandle >
using Variant = boost::make_recursive_variant< None, bool, int, std::size_t, double, std::string, std::vector< int >, std::vector< double >, ObjectRef, std::vector< boost::recursive_variant_ >, Utils::Vector2d, Utils::Vector3d, Utils::Vector4d, std::unordered_map< int, boost::recursive_variant_ > >::type
Possible types for parameters.
using VariantMap = std::unordered_map< std::string, Variant >
Functions
template<typename T >
T get_value (Variant const &v)
Extract value of specific type T from a Variant.
template<typename K , typename V >
std::unordered_map< K, V > get_map (std::unordered_map< K, Variant > const &v)
template<typename K , typename V >
std::unordered_map< K, Variant > make_map (std::unordered_map< K, V > const &v)
template<typename T >
T get_value (VariantMap const &vals, std::string const &name)
Get a value from a VariantMap by name, or throw if it does not exist or is not convertible to the target type.
template<typename T >
T get_value_or (VariantMap const &vals, std::string const &name, T const &default_)
Get a value from a VariantMap by name, or return a default value if it does not exist.
template<typename T , typename... Types, typename... ArgNames>
std::shared_ptr< T > make_shared_from_args (VariantMap const &vals, ArgNames &&... args)
Make a new std::shared_ptr<T> with arguments extracted from a VariantMap.
template<typename T >
void set_from_args (T &dst, VariantMap const &vals, const char *name)
void initialize (Utils::Factory< ObjectHandle > *f)
ObjectId object_id (const ObjectHandle *p)
Id for object.
PackedVariant pack (const Variant &v)
Transform a Variant to a PackedVariant.
Variant unpack (const PackedVariant &v, std::unordered_map< ObjectId, ObjectRef > const &objects)
Unpack a PackedVariant.
PackedMap pack (const VariantMap &v)
Pack a VariantMap.
VariantMap unpack (const PackedMap &v, std::unordered_map< ObjectId, ObjectRef > const &objects)
Unpack a PackedMap.
template<typename T >
Variant make_variant (const T &x)
Make a Variant from argument.
template<class T >
bool is_type (Variant const &v)
Check is a Variant holds a specific type.
bool is_none (Variant const &v)
Variables
constexpr const None none {}
None-"literal".
Typedef Documentation
ObjectId
using ScriptInterface::ObjectId = typedef std::size_t
Definition at line 32 of file packed_variant.hpp.
ObjectRef
using ScriptInterface::ObjectRef = typedef std::shared_ptr<ObjectHandle>
Definition at line 55 of file Variant.hpp.
PackedMap
using ScriptInterface::PackedMap = typedef std::vector<std::pair<std::string, PackedVariant> >
Definition at line 60 of file packed_variant.hpp.
PackedVariant
using ScriptInterface::PackedVariant = typedef boost::make_recursive_variant< None, bool, int, double, std::string, std::vector<int>, std::vector<double>, ObjectId, std::vector<boost::recursive_variant_>, Utils::Vector2d, Utils::Vector3d, Utils::Vector4d, std::unordered_map<int, boost::recursive_variant_> >::type
Packed version of Variant.
When packing variants by PackVisitor, objects of type ObjectRef are packed as ObjectId. Other than that, all other types allowed in Variant must appear here.
Definition at line 58 of file packed_variant.hpp.
Variant
using ScriptInterface::Variant = typedef boost::make_recursive_variant< None, bool, int, std::size_t, double, std::string, std::vector<int>, std::vector<double>, ObjectRef, std::vector<boost::recursive_variant_>, Utils::Vector2d, Utils::Vector3d, Utils::Vector4d, std::unordered_map<int, boost::recursive_variant_> >::type
Possible types for parameters.
The visitors and packing functions need to be adapted accordingly when extending this variant with new types. For the exact details, see commit b48ab62. The number of types is limited by macro BOOST_MPL_LIMIT_LIST_SIZE (defaults to 20).
Definition at line 74 of file Variant.hpp.
VariantMap
using ScriptInterface::VariantMap = typedef std::unordered_map<std::string, Variant>
Definition at line 76 of file Variant.hpp.
Function Documentation
get_map()
template<typename K , typename V > std::unordered_map<K, V> ScriptInterface::get_map (std::unordered_map< K, Variant > const & v)
Definition at line 229 of file get_value.hpp.
get_value() [1/2]
template<typename T > T ScriptInterface::get_value (Variant const & v)
Extract value of specific type T from a Variant.
This is a wrapper around boost::get that allows us to customize the behavior for different types. This is needed e.g. to deal with Vector types that are not explicitly contained in Variant, but can easily be converted.
Definition at line 219 of file get_value.hpp.
Referenced by ScriptInterface::ComFixed::ComFixed(), and ScriptInterface::Observables::CylindricalPidProfileObservable< CoreObs >::do_construct().
get_value() [2/2]
template<typename T > T ScriptInterface::get_value (VariantMap const & vals, std::string const & name)
Get a value from a VariantMap by name, or throw if it does not exist or is not convertible to the target type.
Definition at line 262 of file get_value.hpp.
get_value_or()
template<typename T > T ScriptInterface::get_value_or (VariantMap const & vals, std::string const & name, T const & default_)
Get a value from a VariantMap by name, or return a default value if it does not exist.
Definition at line 275 of file get_value.hpp.
initialize()
void ScriptInterface::initialize (Utils::Factory< ObjectHandle > * f)
Definition at line 41 of file initialize.cpp.
References f, ScriptInterface::PairCriteria::initialize(), ScriptInterface::MPIIO::initialize(), ScriptInterface::ClusterAnalysis::initialize(), ScriptInterface::Writer::initialize(), ScriptInterface::LBBoundaries::initialize(), ScriptInterface::Accumulators::initialize(), ScriptInterface::CollisionDetection::initialize(), ScriptInterface::VirtualSites::initialize(), ScriptInterface::Shapes::initialize(), ScriptInterface::Constraints::initialize(), and ScriptInterface::Observables::initialize().
is_none()
bool ScriptInterface::is_none (Variant const & v) inline
Definition at line 105 of file Variant.hpp.
is_type()
template<class T > bool ScriptInterface::is_type (Variant const & v)
Check is a Variant holds a specific type.
Template Parameters
T type to check for
Parameters
v Variant to check in
Returns
true, if v holds a T.
Definition at line 101 of file Variant.hpp.
make_map()
template<typename K , typename V > std::unordered_map<K, Variant> ScriptInterface::make_map (std::unordered_map< K, V > const & v)
Definition at line 247 of file get_value.hpp.
make_shared_from_args()
template<typename T , typename... Types, typename... ArgNames> std::shared_ptr<T> ScriptInterface::make_shared_from_args (VariantMap const & vals, ArgNames &&... args)
Make a new std::shared_ptr<T> with arguments extracted from a VariantMap.
Definition at line 288 of file get_value.hpp.
Referenced by ScriptInterface::Observables::LBProfileObservable< CoreLBObs >::do_construct().
make_variant()
template<typename T > Variant ScriptInterface::make_variant (const T & x)
Make a Variant from argument.
This is a convenience function, so that rather involved constructors from boost::variant are not needed in the script interfaces.
Definition at line 84 of file Variant.hpp.
object_id()
ObjectId ScriptInterface::object_id (const ObjectHandle * p) inline
Id for object.
This assigns every ObjectHandle a unique id.
Definition at line 39 of file packed_variant.hpp.
Referenced by ScriptInterface::GlobalContext::make_shared(), ScriptInterface::GlobalContext::notify_call_method(), ScriptInterface::GlobalContext::notify_set_parameter(), and ScriptInterface::PackVisitor::operator()().
pack() [1/2]
PackedVariant ScriptInterface::pack (const Variant & v) inline
Transform a Variant to a PackedVariant.
Applies PackVisitor to a Variant.
Parameters
v Input Variant
Returns
Packed variant.
Definition at line 164 of file packed_variant.hpp.
Referenced by ScriptInterface::GlobalContext::notify_call_method(), and ScriptInterface::GlobalContext::notify_set_parameter().
pack() [2/2]
PackedMap ScriptInterface::pack (const VariantMap & v) inline
Pack a VariantMap.
Applies pack to every value in the input map.
Definition at line 188 of file packed_variant.hpp.
set_from_args()
template<typename T > void ScriptInterface::set_from_args (T & dst, VariantMap const & vals, const char * name)
Definition at line 295 of file get_value.hpp.
Referenced by ScriptInterface::Accumulators::TimeSeries::do_construct(), ScriptInterface::Accumulators::MeanVarianceCalculator::do_construct(), ScriptInterface::Accumulators::Correlator::do_construct(), ScriptInterface::Shapes::HollowConicalFrustum::do_construct(), ScriptInterface::Observables::CylindricalPidProfileObservable< CoreObs >::do_construct(), and ScriptInterface::Observables::CylindricalLBProfileObservable< CoreCylLBObs >::do_construct().
unpack() [1/2]
VariantMap ScriptInterface::unpack (const PackedMap & v, std::unordered_map< ObjectId, ObjectRef > const & objects) inline
Unpack a PackedMap.
Applies unpack to every value in the input map.
Definition at line 205 of file packed_variant.hpp.
unpack() [2/2]
Variant ScriptInterface::unpack (const PackedVariant & v, std::unordered_map< ObjectId, ObjectRef > const & objects) inline
Unpack a PackedVariant.
Applies UnpackVisitor to a Variant.
Parameters
v Packed Variant.
objects Map of ids to reference.
Returns
Transformed variant.
Definition at line 177 of file packed_variant.hpp.
Variable Documentation
none
constexpr const None ScriptInterface::none {} constexpr
None-"literal".
Definition at line 59 of file Variant.hpp.
Referenced by ScriptInterface::Constraints::ExternalPotential< Coupling, Field >::do_call_method(), ScriptInterface::Constraints::ExternalField< Coupling, Field >::do_call_method(), ScriptInterface::CollisionDetection::CollisionDetection::do_call_method(), ScriptInterface::Constraints::ShapeBasedConstraint::do_call_method(), ScriptInterface::LBBoundaries::LBBoundary::do_call_method(), ScriptInterface::ObjectList< Constraint >::do_call_method(), ScriptInterface::ObjectHandle::do_call_method(), anonymous_namespace{fft.cpp}::find_comm_groups(), and p3m_calc_kspace_forces().