ESPResSo: Coulomb Namespace Reference
Coulomb Namespace Reference
Functions
Utils::Vector9d calc_pressure_long_range (const ParticleRange &particles)
void sanity_checks (int &state)
double cutoff (const Utils::Vector3d &box_l)
void deactivate ()
void update_dependent_particles ()
Update particles with properties depending on other particles, namely ICC charges.
void on_observable_calc ()
called before calculating observables, i.e.
void on_coulomb_change ()
called every time the Coulomb parameters are changed.
void on_boxl_change ()
void init ()
void calc_long_range_force (const ParticleRange &particles)
double calc_energy_long_range (const ParticleRange &particles)
int icc_sanity_check ()
void bcast_coulomb_params ()
void set_prefactor (double prefactor)
Set the electrostatics prefactor.
void deactivate_method ()
Deactivates the current Coulomb method.
Utils::Vector3d central_force (double const q1q2, Utils::Vector3d const &d, double dist)
std::tuple< Utils::Vector3d, Utils::Vector3d, Utils::Vector3d > pair_force (Particle const &p1, Particle const &p2, Utils::Vector3d const &d, double dist)
Utils::Matrix< double, 3, 3 > pair_pressure (Particle const &p1, Particle const &p2, Utils::Vector3d const &d, double dist)
Pair contribution to the pressure tensor.
double pair_energy (Particle const &p1, Particle const &p2, double const q1q2, Utils::Vector3d const &d, double dist, double dist2)
Function Documentation
bcast_coulomb_params()
void Coulomb::bcast_coulomb_params ()
Definition at line 400 of file coulomb.cpp.
References comm_cart, coulomb, COULOMB_DH, COULOMB_ELC_P3M, COULOMB_MMM1D, COULOMB_MMM1D_GPU, COULOMB_NONE, COULOMB_P3M, COULOMB_P3M_GPU, COULOMB_RF, COULOMB_SCAFACOS, dh_params, elc_params, Coulomb_parameters::method, mmm1d_params, p3m, p3m_data_struct_base::params, and rf_params.
Referenced by mpi_bcast_coulomb_params_local().
calc_energy_long_range()
double Coulomb::calc_energy_long_range (const ParticleRange & particles)
Definition at line 315 of file coulomb.cpp.
References coulomb, COULOMB_ELC_P3M, COULOMB_P3M, COULOMB_P3M_GPU, COULOMB_SCAFACOS, ELCParameters::dielectric_contrast_on, ELC_energy(), ELC_p3m_charge_assign_both(), ELC_p3m_charge_assign_image(), ELC_P3M_dielectric_layers_energy_self(), ELC_P3M_modify_p3m_sums_both(), ELC_P3M_modify_p3m_sums_image(), ELC_P3M_restore_p3m_sums(), elc_params, Scafacos::fcs_coulomb(), Scafacos::ScafacosContextBase::long_range_energy(), Coulomb_parameters::method, p3m_calc_kspace_forces(), p3m_charge_assign(), Cells::particles(), Coulomb_parameters::prefactor, and runtimeWarningMsg.
Referenced by calculate_energy_local().
calc_long_range_force()
void Coulomb::calc_long_range_force (const ParticleRange & particles)
Definition at line 256 of file coulomb.cpp.
References Scafacos::ScafacosContextBase::add_long_range_force(), coulomb, COULOMB_ELC_P3M, COULOMB_P3M, COULOMB_P3M_GPU, COULOMB_SCAFACOS, ELCParameters::dielectric_contrast_on, ek_calculate_electrostatic_coupling(), ELC_add_force(), ELC_p3m_charge_assign_both(), ELC_P3M_modify_p3m_sums_both(), ELC_P3M_restore_p3m_sums(), ELC_P3M_self_forces(), elc_params, Scafacos::fcs_coulomb(), INTEG_METHOD_NPT_ISO, integ_switch, Coulomb_parameters::method, npt_add_virial_contribution(), p3m_calc_kspace_forces(), p3m_charge_assign(), p3m_gpu_add_farfield_force(), Cells::particles(), and this_node.
Referenced by calc_long_range_forces(), and force_calc_icc().
calc_pressure_long_range()
Utils::Vector9d Coulomb::calc_pressure_long_range (const ParticleRange & particles)
Definition at line 58 of file coulomb.cpp.
References coulomb, COULOMB_ELC_P3M, COULOMB_MMM1D, COULOMB_MMM1D_GPU, COULOMB_P3M, COULOMB_P3M_GPU, Coulomb_parameters::method, p3m_calc_kspace_pressure_tensor(), p3m_charge_assign(), and Cells::particles().
Referenced by calculate_pressure_local().
central_force()
Utils::Vector3d Coulomb::central_force (double const q1q2, Utils::Vector3d const & d, double dist) inline
Definition at line 41 of file coulomb_inline.hpp.
References add_dh_coulomb_pair_force(), add_mmm1d_coulomb_pair_force(), Scafacos::ScafacosContextBase::add_pair_force(), add_rf_coulomb_pair_force(), coulomb, COULOMB_DH, COULOMB_ELC_P3M, COULOMB_MMM1D, COULOMB_P3M, COULOMB_P3M_GPU, COULOMB_RF, COULOMB_SCAFACOS, f, Scafacos::fcs_coulomb(), Coulomb_parameters::method, p3m_add_pair_force(), and Coulomb_parameters::prefactor.
Referenced by BondedCoulombSR::force(), pair_force(), pair_pressure(), and thole_pair_force().
cutoff()
double Coulomb::cutoff (const Utils::Vector3d & box_l)
Definition at line 113 of file coulomb.cpp.
References coulomb, COULOMB_DH, COULOMB_ELC_P3M, COULOMB_MMM1D, COULOMB_P3M, COULOMB_P3M_GPU, COULOMB_RF, COULOMB_SCAFACOS, dh_params, elc_params, Scafacos::fcs_coulomb(), Scafacos::ScafacosContextBase::get_r_cut(), Coulomb_parameters::method, p3m, p3m_data_struct_base::params, DebyeHueckelParameters::r_cut, ReactionFieldParameters::r_cut, P3MParameters::r_cut_iL, rf_params, and ELCParameters::space_layer.
Referenced by force_calc(), recalc_long_range_cutoff(), recalc_maximal_cutoff(), and thole_pair_energy().
deactivate()
void Coulomb::deactivate ()
Definition at line 138 of file coulomb.cpp.
References coulomb, COULOMB_DH, COULOMB_ELC_P3M, COULOMB_MMM1D, COULOMB_P3M, COULOMB_P3M_GPU, COULOMB_RF, dh_params, MMM1DParameters::maxPWerror, Coulomb_parameters::method, mmm1d_params, and rf_params.
Referenced by deactivate_method().
deactivate_method()
void Coulomb::deactivate_method ()
Deactivates the current Coulomb method.
Definition at line 440 of file coulomb.cpp.
References coulomb, COULOMB_NONE, deactivate(), Coulomb_parameters::method, mpi_bcast_coulomb_params(), and Coulomb_parameters::prefactor.
icc_sanity_check()
int Coulomb::icc_sanity_check ()
Definition at line 367 of file coulomb.cpp.
References coulomb, COULOMB_DH, COULOMB_ELC_P3M, COULOMB_RF, ELCParameters::dielectric_contrast_on, elc_params, INTEG_METHOD_NPT_ISO, integ_switch, Coulomb_parameters::method, and runtimeErrorMsg.
Referenced by icc_iteration().
init()
void Coulomb::init ()
Definition at line 234 of file coulomb.cpp.
References coulomb, COULOMB_DH, COULOMB_ELC_P3M, COULOMB_MMM1D, COULOMB_P3M, COULOMB_P3M_GPU, ELC_init(), Coulomb_parameters::method, MMM1D_init(), and p3m_init().
Referenced by on_cell_structure_change().
on_boxl_change()
void Coulomb::on_boxl_change ()
Definition at line 210 of file coulomb.cpp.
References coulomb, COULOMB_ELC_P3M, COULOMB_MMM1D, COULOMB_P3M, COULOMB_P3M_GPU, COULOMB_SCAFACOS, ELC_init(), Scafacos::fcs_coulomb(), Coulomb_parameters::method, MMM1D_init(), p3m_scaleby_box_l(), and Scafacos::ScafacosContextBase::update_system_params().
Referenced by mpi_set_box_length_local(), on_boxl_change(), and velocity_verlet_npt_propagate_pos().
on_coulomb_change()
void Coulomb::on_coulomb_change ()
called every time the Coulomb parameters are changed.
Definition at line 179 of file coulomb.cpp.
Referenced by mpi_bcast_coulomb_params_local(), on_coulomb_change(), Scafacos::set_parameters_coulomb_worker(), and Scafacos::set_parameters_dipoles_worker().
on_observable_calc()
void Coulomb::on_observable_calc ()
called before calculating observables, i.e.
energy, pressure or the integrator (forces). Initialize any methods here which are not initialized immediately (P3M etc.).
Definition at line 165 of file coulomb.cpp.
Referenced by calculate_energy_local(), calculate_pressure_local(), dpd_viscous_stress_local(), get_pairs_filtered(), and on_observable_calc().
pair_energy()
double Coulomb::pair_energy (Particle const & p1, Particle const & p2, double const q1q2, Utils::Vector3d const & d, double dist, double dist2) inline
Definition at line 143 of file coulomb_inline.hpp.
References coulomb, COULOMB_DH, COULOMB_ELC_P3M, COULOMB_MMM1D, COULOMB_P3M, COULOMB_P3M_GPU, COULOMB_RF, COULOMB_SCAFACOS, dh_coulomb_pair_energy(), ELCParameters::dielectric_contrast_on, ELC_P3M_dielectric_layers_energy_contribution(), elc_params, Scafacos::fcs_coulomb(), Coulomb_parameters::method, mmm1d_coulomb_pair_energy(), p3m_pair_energy(), Scafacos::ScafacosContextBase::pair_energy(), Coulomb_parameters::prefactor, and rf_coulomb_pair_energy().
Referenced by add_non_bonded_pair_energy(), BondedCoulombSR::energy(), and thole_pair_energy().
pair_force()
std::tuple<Utils::Vector3d, Utils::Vector3d, Utils::Vector3d> Coulomb::pair_force (Particle const & p1, Particle const & p2, Utils::Vector3d const & d, double dist) inline
Definition at line 75 of file coulomb_inline.hpp.
References central_force(), coulomb, COULOMB_ELC_P3M, ELCParameters::dielectric_contrast_on, ELC_P3M_dielectric_layers_force_contribution(), elc_params, force, Coulomb_parameters::method, ParticlePosition::p, Particle::p, Coulomb_parameters::prefactor, ParticleProperties::q, and Particle::r.
Referenced by add_non_bonded_pair_force(), and add_non_bonded_pair_force_icc().
pair_pressure()
Utils::Matrix<double, 3, 3> Coulomb::pair_pressure (Particle const & p1, Particle const & p2, Utils::Vector3d const & d, double dist) inline
Pair contribution to the pressure tensor.
If supported by the method, this returns the virial contribution to the pressure tensor for this pair.
Parameters
p1 particle
p2 particle
d distance vector
dist distance norm
Returns
Contribution to the pressure tensor.
Definition at line 115 of file coulomb_inline.hpp.
References central_force(), coulomb, COULOMB_DH, COULOMB_MMM1D, COULOMB_NONE, COULOMB_P3M, COULOMB_P3M_GPU, COULOMB_RF, force, Coulomb_parameters::method, Particle::p, ParticleProperties::q, and Utils::tensor_product().
Referenced by add_non_bonded_pair_virials().
sanity_checks()
void Coulomb::sanity_checks (int & state)
Definition at line 87 of file coulomb.cpp.
References coulomb, COULOMB_ELC_P3M, COULOMB_MMM1D, COULOMB_P3M, COULOMB_P3M_GPU, elc_params, ELC_sanity_checks(), Coulomb_parameters::method, MMM1D_sanity_checks(), p3m_sanity_checks(), and runtimeErrorMsg.
Referenced by interactions_sanity_checks().
set_prefactor()
void Coulomb::set_prefactor (double prefactor)
Set the electrostatics prefactor.
Definition at line 431 of file coulomb.cpp.
References coulomb, mpi_bcast_coulomb_params(), and Coulomb_parameters::prefactor.
update_dependent_particles()
void Coulomb::update_dependent_particles ()
Update particles with properties depending on other particles, namely ICC charges.
Update particles with properties depending on other particles, namely virtual sites and ICC charges.
Definition at line 160 of file coulomb.cpp.
Referenced by local_rotate_system(), and update_dependent_particles().