ESPResSo: Cells Namespace Reference
Cells Namespace Reference
Enumerations
enum Resort : unsigned { RESORT_NONE = 0u, RESORT_LOCAL = 1u, RESORT_GLOBAL = 2u }
enum DataPart : unsigned {
DATA_PART_NONE = 0u, DATA_PART_PROPERTIES = 1u, DATA_PART_POSITION = 2u, DATA_PART_MOMENTUM = 8u,
DATA_PART_FORCE = 16u, DATA_PART_RATTLE = 32u, DATA_PART_BONDS = 64u
}
Flags to select particle parts for communication.
Functions
ParticleRange particles (Utils::Span< Cell * > cells)
Enumeration Type Documentation
DataPart
enum Cells::DataPart : unsigned
Flags to select particle parts for communication.
Enumerator
DATA_PART_NONE
Nothing.
DATA_PART_PROPERTIES
Particle::p.
DATA_PART_POSITION
Particle::r.
DATA_PART_MOMENTUM
Particle::m.
DATA_PART_FORCE
Particle::f.
DATA_PART_RATTLE
Particle::rattle.
DATA_PART_BONDS
Particle::bonds.
Definition at line 67 of file CellStructure.hpp.
Resort
enum Cells::Resort : unsigned
Enumerator
RESORT_NONE
RESORT_LOCAL
RESORT_GLOBAL
Definition at line 58 of file CellStructure.hpp.
Function Documentation
particles()
ParticleRange Cells::particles (Utils::Span< Cell * > cells) inline
Definition at line 81 of file CellStructure.hpp.
References Utils::Span< T >::begin(), D3Q19::c, Utils::Span< T >::end(), and Utils::find_if().
Referenced by anonymous_namespace{p3m.cpp}::add_dipole_correction(), add_dipole_force(), Constraints::Constraints< ParticleRange, Constraint >::add_energy(), Constraints::Constraints< ParticleRange, Constraint >::add_forces(), add_forces_and_torques(), add_mdlc_energy_corrections(), add_mdlc_force_corrections(), add_PoQ_force(), add_PQ_force(), add_z_force(), ComFixed< ParticleRange >::apply(), apply_positional_correction(), apply_velocity_correction(), brownian_dynamics_propagator(), anonymous_namespace{p3m.cpp}::calc_dipole_moment(), Dipole::calc_energy_long_range(), Coulomb::calc_energy_long_range(), Dipole::calc_long_range_force(), Coulomb::calc_long_range_force(), calc_long_range_forces(), Coulomb::calc_pressure_long_range(), calc_sc_cache(), calc_slab_dipole(), calc_surface_term(), convert_initial_torques(), convert_torques_propagate_omega(), copy_forces_from_GPU(), copy_part_data_to_gpu(), correct_position_shake(), correct_velocity_shake(), cuda_mpi_get_particles(), cuda_mpi_send_forces(), dawaanr_calculations(), dipole_energy(), dp3m_calc_kspace_forces(), dp3m_dipole_assign(), ELC_add_force(), ELC_energy(), ELC_p3m_charge_assign_both(), ELC_p3m_charge_assign_image(), ELC_P3M_dielectric_layers_energy_self(), ELC_P3M_modify_p3m_sums_both(), ELC_P3M_modify_p3m_sums_image(), ELC_P3M_restore_p3m_sums(), ELC_P3M_self_forces(), Observables::TotalForce::evaluate(), Observables::ParticleBodyAngularVelocities::evaluate(), Observables::ParticleAngularVelocities::evaluate(), Observables::ParticleBodyVelocities::evaluate(), Observables::ParticleForces::evaluate(), Observables::CylindricalDensityProfile::evaluate(), Observables::DensityProfile::evaluate(), Observables::CylindricalFluxDensityProfile::evaluate(), Observables::CylindricalLBFluxDensityProfileAtParticlePositions::evaluate(), Observables::CylindricalLBVelocityProfileAtParticlePositions::evaluate(), Observables::CylindricalVelocityProfile::evaluate(), Observables::FluxDensityProfile::evaluate(), Observables::ForceDensityProfile::evaluate(), Observables::BondAngles::evaluate(), Observables::ParticleDistances::evaluate(), Observables::CosPersistenceAngles::evaluate(), Observables::BondDihedrals::evaluate(), Observables::ParticleObservable< ObsType >::evaluate(), fetch_particles(), force_calc(), force_calc_icc(), forcecap_cap(), get_DLC_dipolar(), get_DLC_energy_dipolar(), CellStructure::ghost_particles(), IBM_cuda_mpi_get_particles(), IBM_cuda_mpi_send_velocities(), IBM_ForcesIntoFluid_GPU(), IBM_UpdateParticlePositions(), icc_iteration(), init_correction_vector(), init_forces(), init_forces_ghosts(), init_forces_icc(), integrate(), integrator_step_1(), integrator_step_2(), lb_lbcoupling_calc_particle_lattice_ia(), local_kill_particle_forces(), local_kill_particle_motion(), local_particle_momentum(), CellStructure::local_particles(), local_rotate_system(), magnetic_dipolar_direct_sum_calculations(), Constraints::ShapeBasedConstraint::min_dist(), Mpiio::mpi_mpiio_common_read(), Mpiio::mpi_mpiio_common_write(), ParticleObservables::WeightedSum< ValueOp, WeightOp >::operator()(), Observables::PidObservable::operator()(), ParticleObservables::Sum< ValueOp >::operator()(), ParticleObservables::WeightedAverage< ValueOp, WeightOp >::operator()(), ParticleObservables::Average< ValueOp >::operator()(), ParticleObservables::Map< ValueOp >::operator()(), p3m_calc_kspace_forces(), p3m_charge_assign(), pack_particles(), ParticleVelocitiesFromLB_GPU(), prepare_sc_cache(), propagate_vel_pos_sd(), AtomDecomposition::resort(), save_old_position(), set_velocities(), setup_PoQ(), setup_PQ(), split_kernel_dip(), split_kernel_director(), split_kernel_q(), split_kernel_r(), split_kernel_rq(), split_kernel_v(), steepest_descent_step(), stokesian_dynamics_propagate_vel_pos(), stokesian_dynamics_step_1(), velocity_verlet_npt_propagate_pos(), velocity_verlet_npt_propagate_vel(), velocity_verlet_npt_propagate_vel_final(), velocity_verlet_npt_step_1(), velocity_verlet_npt_step_2(), velocity_verlet_propagate_vel_final(), velocity_verlet_propagate_vel_pos(), velocity_verlet_step_1(), velocity_verlet_step_2(), Writer::H5md::File::write(), Writer::H5md::write_td_particle_property(), and z_energy().