ESPResSo: anonymous_namespace{VirtualSitesRelative.cpp} Namespace Reference
anonymous_namespace{VirtualSitesRelative.cpp} Namespace Reference
Functions
Utils::Quaternion< double > orientation (Particle const *p_ref, const ParticleProperties::VirtualSitesRelativeParameters &vs_rel)
Orientation of the virtual site.
Utils::Vector3d connection_vector (Particle const *p_ref, const ParticleProperties::VirtualSitesRelativeParameters &vs_rel)
Vector pointing from the real particle to the virtual site.
Utils::Vector3d position (Particle const *p_ref, const ParticleProperties::VirtualSitesRelativeParameters &vs_rel)
Position of the virtual site.
Utils::Vector3d velocity (const Particle *p_ref, const ParticleProperties::VirtualSitesRelativeParameters &vs_rel)
Velocity of the virtual site.
Particle * get_reference_particle (const ParticleProperties::VirtualSitesRelativeParameters &vs_rel)
Get reference particle.
ParticleForce constraint_force (const ParticleForce &f, const Particle *p_ref, const ParticleProperties::VirtualSitesRelativeParameters &vs_rel)
Constraint force on the real particle.
auto constraint_stress (const Utils::Vector3d &f, const Particle *p_ref, const ParticleProperties::VirtualSitesRelativeParameters &vs_rel)
Constraint force to hold the particles at its prescribed position.
Function Documentation
connection_vector()
Utils::Vector3d anonymous_namespace{VirtualSitesRelative.cpp}::connection_vector (Particle const * p_ref, const ParticleProperties::VirtualSitesRelativeParameters & vs_rel) inline
Vector pointing from the real particle to the virtual site.
Returns
Relative distance.
Definition at line 58 of file VirtualSitesRelative.cpp.
References Utils::convert_quaternion_to_director(), ParticleProperties::VirtualSitesRelativeParameters::distance, Utils::Vector< T, N >::normalize(), ParticlePosition::quat, Particle::r, and ParticleProperties::VirtualSitesRelativeParameters::rel_orientation.
Referenced by constraint_force(), constraint_stress(), position(), and velocity().
constraint_force()
ParticleForce anonymous_namespace{VirtualSitesRelative.cpp}::constraint_force (const ParticleForce & f, const Particle * p_ref, const ParticleProperties::VirtualSitesRelativeParameters & vs_rel)
Constraint force on the real particle.
Calculates the force exerted by the constraint on the reference particle.
Definition at line 127 of file VirtualSitesRelative.cpp.
References connection_vector(), f, and Utils::vector_product().
Referenced by VirtualSitesRelative::back_transfer_forces_and_torques().
constraint_stress()
auto anonymous_namespace{VirtualSitesRelative.cpp}::constraint_stress (const Utils::Vector3d & f, const Particle * p_ref, const ParticleProperties::VirtualSitesRelativeParameters & vs_rel)
Constraint force to hold the particles at its prescribed position.
Parameters
f Force on the virtual site.
p_ref Reference particle.
vs_rel Parameters.
Returns
Constraint force.
Definition at line 142 of file VirtualSitesRelative.cpp.
References connection_vector(), f, and Accumulators::tensor_product().
Referenced by VirtualSitesRelative::pressure_tensor().
get_reference_particle()
Particle* anonymous_namespace{VirtualSitesRelative.cpp}::get_reference_particle (const ParticleProperties::VirtualSitesRelativeParameters & vs_rel)
Get reference particle.
Parameters
vs_rel Parameters to get the reference particle for.
Returns
Pointer to reference particle.
Definition at line 111 of file VirtualSitesRelative.cpp.
References cell_structure, CellStructure::get_local_particle(), and ParticleProperties::VirtualSitesRelativeParameters::to_particle_id.
Referenced by VirtualSitesRelative::back_transfer_forces_and_torques(), VirtualSitesRelative::pressure_tensor(), and VirtualSitesRelative::update().
orientation()
Utils::Quaternion<double> anonymous_namespace{VirtualSitesRelative.cpp}::orientation (Particle const * p_ref, const ParticleProperties::VirtualSitesRelativeParameters & vs_rel)
Orientation of the virtual site.
Parameters
p_ref Reference particle for the virtual site.
vs_rel Parameters for the virtual site.
Returns
Orientation quaternion of the virtual site.
Definition at line 47 of file VirtualSitesRelative.cpp.
References ParticleProperties::VirtualSitesRelativeParameters::quat, ParticlePosition::quat, and Particle::r.
Referenced by Utils::transform_coordinate_cartesian_to_cylinder(), Utils::transform_coordinate_cylinder_to_cartesian(), and VirtualSitesRelative::update().
position()
Utils::Vector3d anonymous_namespace{VirtualSitesRelative.cpp}::position (Particle const * p_ref, const ParticleProperties::VirtualSitesRelativeParameters & vs_rel)
Position of the virtual site.
Parameters
p_ref Reference particle for the virtual site.
vs_rel Parameters for the virtual site.
Returns
Position of the virtual site.
Definition at line 81 of file VirtualSitesRelative.cpp.
References connection_vector(), ParticlePosition::p, and Particle::r.
Referenced by bd_drag(), bd_random_walk(), calc_viscous_force(), interpolation< no_of_neighbours >::operator()(), p3m_calculate_interpolation_weights(), and VirtualSitesRelative::update().
velocity()
Utils::Vector3d anonymous_namespace{VirtualSitesRelative.cpp}::velocity (const Particle * p_ref, const ParticleProperties::VirtualSitesRelativeParameters & vs_rel)
Velocity of the virtual site.
Parameters
p_ref Reference particle for the virtual site.
vs_rel Parameters for the virtual site.
Returns
Velocity of the virtual site.
Definition at line 93 of file VirtualSitesRelative.cpp.
References connection_vector(), convert_vector_body_to_space(), Particle::m, ParticleMomentum::omega, ParticleMomentum::v, and Utils::vector_product().
Referenced by bd_drag_vel(), bd_random_walk_vel(), calc_viscous_force(), friction_thermo_langevin(), GetIBMInterpolatedVelocity(), Observables::CylindricalLBVelocityProfile::operator()(), set_u_from_rho_v_pi(), and VirtualSitesRelative::update().