ESPResSo: nonbonded_interaction_data.hpp File Reference
nonbonded_interaction_data.hpp File Reference
#include "TabulatedPotential.hpp"
#include "config.hpp"
#include <utils/index.hpp>
#include <MpiCallbacks.hpp>
#include <algorithm>
#include <cassert>
#include <communication.hpp>
#include <event.hpp>
#include <string>
#include <vector>
Classes
struct LJ_Parameters
Lennard-Jones with shift.
struct WCA_Parameters
WCA potential.
struct LJGen_Parameters
Generic Lennard-Jones with shift.
struct SmoothStep_Parameters
smooth step potential
struct Hertzian_Parameters
Hertzian potential.
struct Gaussian_Parameters
Gaussian potential.
struct BMHTF_Parameters
BMHTF NaCl potential.
struct Morse_Parameters
Morse potential.
struct Buckingham_Parameters
Buckingham potential.
struct SoftSphere_Parameters
soft-sphere potential
struct Hat_Parameters
hat potential
struct LJcos_Parameters
Lennard-Jones+Cos potential.
struct LJcos2_Parameters
Lennard-Jones with a different Cos potential.
struct GayBerne_Parameters
Gay-Berne potential.
struct Thole_Parameters
Thole potential.
struct DPDParameters
DPD potential.
struct IA_parameters
Data structure containing the interaction parameters for non-bonded interactions.
Functions
double maximal_cutoff_nonbonded ()
Maximal interaction cutoff (real space/short range non-bonded interactions).
double maximal_cutoff_bonded ()
Maximal interaction cutoff (bonded interactions).
IA_parameters * get_ia_param (int i, int j)
Get interaction parameters between particle types i and j.
IA_parameters * get_ia_param_safe (int i, int j)
Get interaction parameters between particle types i and j.
std::string ia_params_get_state ()
Get the state of all non-bonded interactions.
void ia_params_set_state (std::string const &)
Set the state of all non-bonded interactions.
bool is_new_particle_type (int type)
void make_particle_type_exist (int type)
Make sure that ia_params is large enough to cover interactions for this particle type.
void make_particle_type_exist_local (int type)
void realloc_ia_params (int nsize)
This function increases the LOCAL ia_params field to the given size.
double maximal_cutoff ()
Calculate the maximal cutoff of all pair interactions.
void reset_ia_params ()
Reset all interaction parameters to their defaults.
int interactions_sanity_checks ()
Check whether all force calculation routines are properly initialized.
bool checkIfInteraction (IA_parameters const &data)
Check if a non-bonded interaction is defined.
void mpi_set_min_global_cut (double min_global_cut)
Set and broadcast the min_global_cut.
Variables
constexpr double INACTIVE_CUTOFF = -1.
Cutoff for deactivated interactions.
std::vector< IA_parameters > ia_params
int max_seen_particle_type
Maximal particle type seen so far.
double min_global_cut
Minimal global interaction cutoff.
Detailed Description
Various procedures concerning interactions between particles.
Definition in file nonbonded_interaction_data.hpp.
Function Documentation
checkIfInteraction()
bool checkIfInteraction (IA_parameters const & data) inline
Check if a non-bonded interaction is defined.
Definition at line 361 of file nonbonded_interaction_data.hpp.
References INACTIVE_CUTOFF, and IA_parameters::max_cut.
Referenced by Constraints::ShapeBasedConstraint::add_energy(), and Constraints::ShapeBasedConstraint::force().
get_ia_param()
IA_parameters* get_ia_param (int i, int j) inline
Get interaction parameters between particle types i and j.
This is symmetric, e.g. it holds that get_ia_param(i, j) and get_ia_param(j, i) point to the same data.
Parameters
i First type, has to be smaller than max_seen_particle_type.
j Second type, has to be smaller than max_seen_particle_type.
Returns
Pointer to interaction parameters for the type pair.
Definition at line 311 of file nonbonded_interaction_data.hpp.
References ia_params, max_seen_particle_type, anonymous_namespace{Correlator.cpp}::min(), and Utils::upper_triangular().
Referenced by Constraints::ShapeBasedConstraint::add_energy(), add_non_bonded_pair_energy(), add_non_bonded_pair_force(), add_non_bonded_pair_virials(), PairCriteria::EnergyCriterion::decide(), dpd_init(), dpd_viscous_stress_local(), Constraints::ShapeBasedConstraint::force(), get_ia_param_safe(), mpi_bcast_ia_params_local(), VerletCriterion::operator()(), and realloc_ia_params().
get_ia_param_safe()
IA_parameters* get_ia_param_safe (int i, int j)
Get interaction parameters between particle types i and j.
Slower than get_ia_param, but can also be used on not yet present particle types
Definition at line 62 of file nonbonded_interaction_data.cpp.
References get_ia_param(), and make_particle_type_exist().
Referenced by BMHTF_set_params(), buckingham_set_params(), dpd_set_params(), gaussian_set_params(), gay_berne_set_params(), hat_set_params(), hertzian_set_params(), lennard_jones_set_params(), ljcos2_set_params(), ljcos_set_params(), ljgen_set_params(), morse_set_params(), smooth_step_set_params(), soft_sphere_set_params(), tabulated_set_params(), thole_set_params(), and wca_set_params().
ia_params_get_state()
std::string ia_params_get_state ()
Get the state of all non-bonded interactions.
Definition at line 67 of file nonbonded_interaction_data.cpp.
References ia_params, and max_seen_particle_type.
ia_params_set_state()
void ia_params_set_state (std::string const &)
Set the state of all non-bonded interactions.
Definition at line 75 of file nonbonded_interaction_data.cpp.
References ia_params, max_seen_particle_type, mpi_bcast_all_ia_params(), and mpi_realloc_ia_params().
interactions_sanity_checks()
int interactions_sanity_checks ()
Check whether all force calculation routines are properly initialized.
Definition at line 249 of file nonbonded_interaction_data.cpp.
References Dipole::nonbonded_sanity_check(), and Coulomb::sanity_checks().
Referenced by calculate_energy_local(), calculate_pressure_local(), and on_integration_start().
is_new_particle_type()
bool is_new_particle_type (int type)
Definition at line 235 of file nonbonded_interaction_data.cpp.
References max_seen_particle_type.
Referenced by make_particle_type_exist(), and make_particle_type_exist_local().
make_particle_type_exist()
void make_particle_type_exist (int type)
Make sure that ia_params is large enough to cover interactions for this particle type.
The interactions are initialized with values such that no physical interaction occurs.
Definition at line 239 of file nonbonded_interaction_data.cpp.
References is_new_particle_type(), and mpi_realloc_ia_params().
Referenced by get_ia_param_safe(), on_program_start(), set_particle_type(), and validate_collision_parameters().
make_particle_type_exist_local()
void make_particle_type_exist_local (int type)
Definition at line 244 of file nonbonded_interaction_data.cpp.
References is_new_particle_type(), and realloc_ia_params().
Referenced by Constraints::ShapeBasedConstraint::set_type().
maximal_cutoff()
double maximal_cutoff ()
Calculate the maximal cutoff of all pair interactions.
Definition at line 195 of file nonbonded_interaction_data.cpp.
References collision_detection_cutoff(), maximal_cutoff_bonded(), maximal_cutoff_nonbonded(), min_global_cut, and recalc_long_range_cutoff().
Referenced by calculate_energy_local(), calculate_pressure_local(), force_calc(), interaction_range(), python_integrate(), and tune_skin().
maximal_cutoff_bonded()
double maximal_cutoff_bonded ()
Maximal interaction cutoff (bonded interactions).
Maximal interaction cutoff (bonded interactions).
Bond angle and dihedral potentials do not contain a cutoff intrinsically. The cutoff for these potentials depends on the bond length potentials (it is assumed that particles participating in a bond angle or dihedral potential are bound to each other by some bond length potential). For bond angle potentials nothing has to be done. For dihedral potentials the cutoff is set to twice the maximal cutoff because the particle in which the bond is stored is only bonded to the first two partners, one of which has an additional bond to the third partner.
Definition at line 41 of file bonded_interaction_data.cpp.
References bonded_ia_params, and BONDED_INACTIVE_CUTOFF.
Referenced by calculate_energy_local(), calculate_pressure_local(), force_calc(), and maximal_cutoff().
maximal_cutoff_nonbonded()
double maximal_cutoff_nonbonded ()
Maximal interaction cutoff (real space/short range non-bonded interactions).
Definition at line 184 of file nonbonded_interaction_data.cpp.
References ia_params, INACTIVE_CUTOFF, and recalc_maximal_cutoff().
Referenced by maximal_cutoff().
mpi_set_min_global_cut()
void mpi_set_min_global_cut (double min_global_cut)
Set and broadcast the min_global_cut.
Parameters
min_global_cut minimum global cutoff
Definition at line 271 of file nonbonded_interaction_data.cpp.
References min_global_cut, mpi_call_all(), and mpi_set_min_global_cut_local().
realloc_ia_params()
void realloc_ia_params (int nsize)
This function increases the LOCAL ia_params field to the given size.
Better use make_particle_type_exist since it takes care of the other nodes.
This function increases the LOCAL ia_params field to the given size.
This function is not exported since it does not do this on all nodes. Use make_particle_type_exist for that.
Definition at line 213 of file nonbonded_interaction_data.cpp.
References get_ia_param(), ia_params, max_seen_particle_type, and Utils::upper_triangular().
Referenced by make_particle_type_exist_local(), and mpi_realloc_ia_params().
reset_ia_params()
void reset_ia_params ()
Reset all interaction parameters to their defaults.
Definition at line 230 of file nonbonded_interaction_data.cpp.
References ia_params, and mpi_bcast_all_ia_params().
Variable Documentation
ia_params
std::vector<IA_parameters> ia_params
Definition at line 54 of file nonbonded_interaction_data.cpp.
Referenced by Constraints::ShapeBasedConstraint::add_energy(), add_non_bonded_pair_energy(), add_non_bonded_pair_force(), add_non_bonded_pair_virials(), BMHTF_pair_energy(), BMHTF_pair_force_factor(), buck_pair_energy(), buck_pair_force_factor(), calc_non_bonded_pair_energy(), calc_non_bonded_pair_force(), calculate_positional_correction(), calculate_velocity_correction(), PairCriteria::EnergyCriterion::decide(), dpd_init(), dpd_pair_force(), dpd_set_params(), dpd_viscous_stress_local(), Constraints::ShapeBasedConstraint::force(), gaussian_pair_energy(), gaussian_pair_force_factor(), gb_pair_energy(), gb_pair_force(), get_ia_param(), hat_pair_energy(), hat_pair_force_factor(), hertzian_pair_energy(), hertzian_pair_force_factor(), ia_params_get_state(), ia_params_set_state(), lj_pair_energy(), lj_pair_force_factor(), ljcos2_pair_energy(), ljcos2_pair_force_factor(), ljcos_pair_energy(), ljcos_pair_force_factor(), ljgen_pair_energy(), ljgen_pair_force_factor(), maximal_cutoff_nonbonded(), morse_pair_energy(), morse_pair_force_factor(), mpi_bcast_all_ia_params_local(), realloc_ia_params(), reset_ia_params(), SmSt_pair_energy(), SmSt_pair_force_factor(), soft_pair_energy(), soft_pair_force_factor(), tabulated_pair_energy(), tabulated_pair_force_factor(), thole_pair_energy(), thole_pair_force(), wca_pair_energy(), and wca_pair_force_factor().
INACTIVE_CUTOFF
constexpr double INACTIVE_CUTOFF = -1. constexpr
Cutoff for deactivated interactions.
Must be negative, so that even particles on top of each other don't interact by chance.
Definition at line 43 of file nonbonded_interaction_data.hpp.
Referenced by checkIfInteraction(), force_calc(), interaction_range(), maximal_cutoff_nonbonded(), VerletCriterion::operator()(), recalc_long_range_cutoff(), and recalc_maximal_cutoff().
max_seen_particle_type
int max_seen_particle_type
Maximal particle type seen so far.
Definition at line 53 of file nonbonded_interaction_data.cpp.
Referenced by dpd_init(), get_ia_param(), ia_params_get_state(), ia_params_set_state(), is_new_particle_type(), max_non_bonded_pairs(), and realloc_ia_params().
min_global_cut
double min_global_cut
Minimal global interaction cutoff.
Particles with a distance smaller than this are guaranteed to be available on the same node (through ghosts).
Definition at line 56 of file nonbonded_interaction_data.cpp.
Referenced by calculate_vs_relate_to_params(), maximal_cutoff(), mpi_set_min_global_cut(), and mpi_set_min_global_cut_local().