ESPResSo: nonbonded_interaction_data.cpp File Reference
nonbonded_interaction_data.cpp File Reference
#include "nonbonded_interactions/nonbonded_interaction_data.hpp"
#include "bonded_interactions/bonded_interaction_data.hpp"
#include "collision.hpp"
#include "electrostatics_magnetostatics/coulomb.hpp"
#include "electrostatics_magnetostatics/dipole.hpp"
#include "grid.hpp"
#include "interactions.hpp"
#include "serialization/IA_parameters.hpp"
#include <boost/archive/binary_iarchive.hpp>
#include <boost/archive/binary_oarchive.hpp>
#include <boost/iostreams/device/array.hpp>
#include <boost/iostreams/stream.hpp>
#include <boost/range/algorithm/fill.hpp>
#include <boost/serialization/string.hpp>
#include <boost/serialization/vector.hpp>
#include <utils/index.hpp>
#include <algorithm>
#include <sstream>
#include <string>
#include <utility>
#include <vector>
Functions
IA_parameters * get_ia_param_safe (int i, int j)
Get interaction parameters between particle types i and j.
std::string ia_params_get_state ()
Get the state of all non-bonded interactions.
void ia_params_set_state (std::string const &state)
Set the state of all non-bonded interactions.
static double recalc_long_range_cutoff ()
static double recalc_maximal_cutoff (const IA_parameters &data)
double maximal_cutoff_nonbonded ()
Maximal interaction cutoff (real space/short range non-bonded interactions).
double maximal_cutoff ()
Calculate the maximal cutoff of all pair interactions.
void realloc_ia_params (int nsize)
Increase the LOCAL ia_params field for non-bonded interactions to the given size.
void reset_ia_params ()
Reset all interaction parameters to their defaults.
bool is_new_particle_type (int type)
void make_particle_type_exist (int type)
Make sure that ia_params is large enough to cover interactions for this particle type.
void make_particle_type_exist_local (int type)
int interactions_sanity_checks ()
Check whether all force calculation routines are properly initialized.
void mpi_set_min_global_cut_local (double min_global_cut)
void mpi_set_min_global_cut (double min_global_cut)
Set and broadcast the min_global_cut.
Variables
int max_seen_particle_type = 0
Maximal particle type seen so far.
std::vector< IA_parameters > ia_params
double min_global_cut = INACTIVE_CUTOFF
Minimal global interaction cutoff.
Detailed Description
Implementation of nonbonded_interaction_data.hpp
Definition in file nonbonded_interaction_data.cpp.
Function Documentation
get_ia_param_safe()
IA_parameters* get_ia_param_safe (int i, int j)
Get interaction parameters between particle types i and j.
Slower than get_ia_param, but can also be used on not yet present particle types
Definition at line 62 of file nonbonded_interaction_data.cpp.
References get_ia_param(), and make_particle_type_exist().
Referenced by BMHTF_set_params(), buckingham_set_params(), dpd_set_params(), gaussian_set_params(), gay_berne_set_params(), hat_set_params(), hertzian_set_params(), lennard_jones_set_params(), ljcos2_set_params(), ljcos_set_params(), ljgen_set_params(), morse_set_params(), smooth_step_set_params(), soft_sphere_set_params(), tabulated_set_params(), thole_set_params(), and wca_set_params().
ia_params_get_state()
std::string ia_params_get_state ()
Get the state of all non-bonded interactions.
Definition at line 67 of file nonbonded_interaction_data.cpp.
References ia_params, and max_seen_particle_type.
ia_params_set_state()
void ia_params_set_state (std::string const & state)
Set the state of all non-bonded interactions.
Definition at line 75 of file nonbonded_interaction_data.cpp.
References ia_params, max_seen_particle_type, mpi_bcast_all_ia_params(), and mpi_realloc_ia_params().
interactions_sanity_checks()
int interactions_sanity_checks ()
Check whether all force calculation routines are properly initialized.
Definition at line 249 of file nonbonded_interaction_data.cpp.
References Dipole::nonbonded_sanity_check(), and Coulomb::sanity_checks().
Referenced by calculate_energy_local(), calculate_pressure_local(), and on_integration_start().
is_new_particle_type()
bool is_new_particle_type (int type)
Definition at line 235 of file nonbonded_interaction_data.cpp.
References max_seen_particle_type.
Referenced by make_particle_type_exist(), and make_particle_type_exist_local().
make_particle_type_exist()
void make_particle_type_exist (int type)
Make sure that ia_params is large enough to cover interactions for this particle type.
The interactions are initialized with values such that no physical interaction occurs.
Definition at line 239 of file nonbonded_interaction_data.cpp.
References is_new_particle_type(), and mpi_realloc_ia_params().
Referenced by get_ia_param_safe(), on_program_start(), set_particle_type(), and validate_collision_parameters().
make_particle_type_exist_local()
void make_particle_type_exist_local (int type)
Definition at line 244 of file nonbonded_interaction_data.cpp.
References is_new_particle_type(), and realloc_ia_params().
Referenced by Constraints::ShapeBasedConstraint::set_type().
maximal_cutoff()
double maximal_cutoff ()
Calculate the maximal cutoff of all pair interactions.
Definition at line 195 of file nonbonded_interaction_data.cpp.
References collision_detection_cutoff(), maximal_cutoff_bonded(), maximal_cutoff_nonbonded(), min_global_cut, and recalc_long_range_cutoff().
Referenced by calculate_energy_local(), calculate_pressure_local(), force_calc(), interaction_range(), python_integrate(), and tune_skin().
maximal_cutoff_nonbonded()
double maximal_cutoff_nonbonded ()
Maximal interaction cutoff (real space/short range non-bonded interactions).
Definition at line 184 of file nonbonded_interaction_data.cpp.
References ia_params, INACTIVE_CUTOFF, and recalc_maximal_cutoff().
Referenced by maximal_cutoff().
mpi_set_min_global_cut()
void mpi_set_min_global_cut (double min_global_cut)
Set and broadcast the min_global_cut.
Parameters
min_global_cut minimum global cutoff
Definition at line 271 of file nonbonded_interaction_data.cpp.
References min_global_cut, mpi_call_all(), and mpi_set_min_global_cut_local().
mpi_set_min_global_cut_local()
void mpi_set_min_global_cut_local (double min_global_cut)
Definition at line 264 of file nonbonded_interaction_data.cpp.
References min_global_cut, and on_skin_change().
Referenced by mpi_set_min_global_cut().
realloc_ia_params()
void realloc_ia_params (int nsize)
Increase the LOCAL ia_params field for non-bonded interactions to the given size.
This function increases the LOCAL ia_params field to the given size.
This function is not exported since it does not do this on all nodes. Use make_particle_type_exist for that.
Definition at line 213 of file nonbonded_interaction_data.cpp.
References get_ia_param(), ia_params, max_seen_particle_type, and Utils::upper_triangular().
Referenced by make_particle_type_exist_local(), and mpi_realloc_ia_params().
recalc_long_range_cutoff()
static double recalc_long_range_cutoff () static
Definition at line 87 of file nonbonded_interaction_data.cpp.
References box_geo, Dipole::cutoff(), Coulomb::cutoff(), INACTIVE_CUTOFF, and BoxGeometry::length().
Referenced by maximal_cutoff().
recalc_maximal_cutoff()
static double recalc_maximal_cutoff (const IA_parameters & data) static
Definition at line 102 of file nonbonded_interaction_data.cpp.
References IA_parameters::bmhtf, box_geo, IA_parameters::buckingham, LJ_Parameters::cut, WCA_Parameters::cut, LJGen_Parameters::cut, SmoothStep_Parameters::cut, Gaussian_Parameters::cut, BMHTF_Parameters::cut, Morse_Parameters::cut, Buckingham_Parameters::cut, SoftSphere_Parameters::cut, LJcos_Parameters::cut, LJcos2_Parameters::cut, GayBerne_Parameters::cut, TabulatedPotential::cutoff(), Coulomb::cutoff(), DPDParameters::cutoff, IA_parameters::dpd_radial, IA_parameters::dpd_trans, IA_parameters::gaussian, IA_parameters::gay_berne, IA_parameters::hat, IA_parameters::hertzian, INACTIVE_CUTOFF, BoxGeometry::length(), IA_parameters::lj, IA_parameters::ljcos, IA_parameters::ljcos2, IA_parameters::ljgen, IA_parameters::morse, LJ_Parameters::offset, LJGen_Parameters::offset, SoftSphere_Parameters::offset, LJcos_Parameters::offset, LJcos2_Parameters::offset, Hat_Parameters::r, Thole_Parameters::scaling_coeff, Hertzian_Parameters::sig, IA_parameters::smooth_step, IA_parameters::soft_sphere, IA_parameters::tab, IA_parameters::thole, and IA_parameters::wca.
Referenced by maximal_cutoff_nonbonded().
reset_ia_params()
void reset_ia_params ()
Reset all interaction parameters to their defaults.
Definition at line 230 of file nonbonded_interaction_data.cpp.
References ia_params, and mpi_bcast_all_ia_params().
Variable Documentation
ia_params
std::vector<IA_parameters> ia_params
Definition at line 54 of file nonbonded_interaction_data.cpp.
Referenced by Constraints::ShapeBasedConstraint::add_energy(), add_non_bonded_pair_energy(), add_non_bonded_pair_force(), add_non_bonded_pair_virials(), BMHTF_pair_energy(), BMHTF_pair_force_factor(), buck_pair_energy(), buck_pair_force_factor(), calc_non_bonded_pair_energy(), calc_non_bonded_pair_force(), calculate_positional_correction(), calculate_velocity_correction(), PairCriteria::EnergyCriterion::decide(), dpd_init(), dpd_pair_force(), dpd_set_params(), dpd_viscous_stress_local(), Constraints::ShapeBasedConstraint::force(), gaussian_pair_energy(), gaussian_pair_force_factor(), gb_pair_energy(), gb_pair_force(), get_ia_param(), hat_pair_energy(), hat_pair_force_factor(), hertzian_pair_energy(), hertzian_pair_force_factor(), ia_params_get_state(), ia_params_set_state(), lj_pair_energy(), lj_pair_force_factor(), ljcos2_pair_energy(), ljcos2_pair_force_factor(), ljcos_pair_energy(), ljcos_pair_force_factor(), ljgen_pair_energy(), ljgen_pair_force_factor(), maximal_cutoff_nonbonded(), morse_pair_energy(), morse_pair_force_factor(), mpi_bcast_all_ia_params_local(), realloc_ia_params(), reset_ia_params(), SmSt_pair_energy(), SmSt_pair_force_factor(), soft_pair_energy(), soft_pair_force_factor(), tabulated_pair_energy(), tabulated_pair_force_factor(), thole_pair_energy(), thole_pair_force(), wca_pair_energy(), and wca_pair_force_factor().
max_seen_particle_type
int max_seen_particle_type = 0
Maximal particle type seen so far.
Definition at line 53 of file nonbonded_interaction_data.cpp.
Referenced by dpd_init(), get_ia_param(), ia_params_get_state(), ia_params_set_state(), is_new_particle_type(), max_non_bonded_pairs(), and realloc_ia_params().
min_global_cut
double min_global_cut = INACTIVE_CUTOFF
Minimal global interaction cutoff.
Particles with a distance smaller than this are guaranteed to be available on the same node (through ghosts).
Definition at line 56 of file nonbonded_interaction_data.cpp.
Referenced by calculate_vs_relate_to_params(), maximal_cutoff(), mpi_set_min_global_cut(), and mpi_set_min_global_cut_local().