ESPResSo: p3m-dipolar.hpp File Reference
p3m-dipolar.hpp File Reference
#include "config.hpp"
#include "electrostatics_magnetostatics/dipole.hpp"
#include "electrostatics_magnetostatics/fft.hpp"
#include "electrostatics_magnetostatics/p3m-common.hpp"
#include "electrostatics_magnetostatics/p3m-data_struct.hpp"
#include "electrostatics_magnetostatics/p3m_interpolation.hpp"
#include "electrostatics_magnetostatics/p3m_send_mesh.hpp"
#include "Particle.hpp"
#include "ParticleRange.hpp"
#include <utils/Vector.hpp>
#include <utils/constants.hpp>
#include <utils/math/AS_erfc_part.hpp>
#include <array>
#include <cmath>
#include <vector>
Classes
struct dp3m_data_struct
Functions
void dp3m_set_tune_params (double r_cut, int mesh, int cao, double accuracy)
Set initial values for p3m_adaptive_tune()
void dp3m_set_params (double r_cut, int mesh, int cao, double alpha, double accuracy)
Set custom parameters.
void dp3m_set_mesh_offset (double x, double y, double z)
Set mesh offset.
void dp3m_set_eps (double eps)
Set epsilon parameter.
void dp3m_init ()
Initialize all structures, parameters and arrays needed for the P3M algorithm for dipole-dipole interactions.
void dp3m_scaleby_box_l ()
Update alpha and r_cut if box length changed.
bool dp3m_sanity_checks (const Utils::Vector3i &grid)
Sanity checks.
void dp3m_dipole_assign (const ParticleRange &particles)
Assign the physical dipoles using the tabulated assignment function.
void dp3m_deactivate ()
Reset dp3m core parameters.
int dp3m_adaptive_tune (int timings, bool verbose)
Tune dipolar P3M parameters to desired accuracy.
double dp3m_calc_kspace_forces (bool force_flag, bool energy_flag, ParticleRange const &particles)
Compute the k-space part of forces and energies for the magnetic dipole-dipole interaction.
void dp3m_count_magnetic_particles ()
Calculate number of magnetic particles, the sum of the squared charges and the squared sum of the charges.
void npt_add_virial_magnetic_contribution (double energy)
Update the NpT virial.
ParticleForce dp3m_pair_force (Particle const &p1, Particle const &p2, Utils::Vector3d const &d, double dist2, double dist)
Calculate real space contribution of p3m dipolar pair forces and torques.
double dp3m_pair_energy (Particle const &p1, Particle const &p2, Utils::Vector3d const &d, double dist2, double dist)
Calculate real space contribution of dipolar pair energy.
Variables
dp3m_data_struct dp3m
dipolar P3M parameters.
Detailed Description
P3M algorithm for long range magnetic dipole-dipole interaction.
We use here a P3M (Particle-Particle Particle-Mesh) method based on the dipolar Ewald summation. Details of the used method can be found in [27] and [11] [12]. The file p3m contains only the Particle-Mesh part.
Further reading: [10]
Implementation in p3m-dipolar.cpp.
Definition in file p3m-dipolar.hpp.
Function Documentation
dp3m_adaptive_tune()
int dp3m_adaptive_tune (int timings, bool verbose)
Tune dipolar P3M parameters to desired accuracy.
The parameters mesh, cao, r_cut_iL and alpha_L are tuned to obtain the target accuracy (initially stored in accuracy) in optimal time. These parameters are stored in the dp3m object.
The function utilizes the analytic expression of the error estimate for the dipolar P3M method in the paper of [10] in order to obtain the rms error in the force for a system of N randomly distributed particles in a cubic box. For the real space error, the estimate in [29] is used.
Parameter ranges if not given explicit values via dp3m_set_tune_params():
mesh is set up such that the number of mesh points is equal to the number of magnetic dipolar particles
cao explores all possible values
alpha_L is tuned for each tuple (r_cut_iL, mesh, cao) and calculated assuming that the error contributions of real and reciprocal space should be equal
After checking if the total error lies below the target accuracy, the time needed for one force calculation (including Verlet list update) is measured via time_force_calc().
The function generates a log of the performed tuning.
The function is based on routines of the program HE_Q.cpp for charges written by M. Deserno.
Parameters
verbose printf output
timings Number of test force calculations
Return values
ES_OK
ES_ERROR
Tuning of dipolar P3M. The algorithm basically determines the mesh, cao and then the real space cutoff, in this nested order.
For each mesh, the cao optimal for the mesh tested previously is used as an initial guess, and the algorithm tries whether increasing or decreasing it leads to a better solution. This is efficient, since the optimal cao only changes little with the meshes in general.
The real space cutoff for a given mesh and cao is determined via a bisection on the error estimate, which determines where the error estimate equals the required accuracy. Therefore the smallest possible, i.e. fastest real space cutoff is determined.
Both the search over mesh and cao stop to search in a specific direction once the computation time is significantly higher than the currently known optimum.
Definition at line 1079 of file p3m-dipolar.cpp.
References P3MParameters::accuracy, P3MParameters::alpha_L, box_geo, P3MParameters::cao, dipole, dp3m, dp3m_count_magnetic_particles(), dp3m_m_time(), DP3M_RTBISECTION_ERROR, ES_ERROR, ES_OK, LocalBox< T >::length(), BoxGeometry::length(), BoxGeometry::length_inv(), local_geo, P3MParameters::mesh, anonymous_namespace{Correlator.cpp}::min(), mpi_bcast_coulomb_params(), mpi_call_all(), P3M_MAX_MESH, P3M_TIME_GRAN, P3M_TUNE_FAIL, p3m_data_struct_base::params, Dipole_parameters::prefactor, P3MParameters::r_cut_iL, runtimeErrorMsg, skin, dp3m_data_struct::sum_dip_part, and dp3m_data_struct::sum_mu2.
dp3m_calc_kspace_forces()
double dp3m_calc_kspace_forces (bool force_flag, bool energy_flag, ParticleRange const & particles)
Compute the k-space part of forces and energies for the magnetic dipole-dipole interaction.
Definition at line 381 of file p3m-dipolar.cpp.
References P3MParameters::alpha_L, box_geo, calc_surface_term(), P3MParameters::cao, comm_cart, p3m_data_struct_base::d_op, P3MLocalMesh::dim, dipole, dp3m, dp3m_compute_constants_energy_dipolar(), dp3m_data_struct::energy_correction, P3MParameters::epsilon, dp3m_data_struct::fft, fft_perform_back(), fft_perform_forw(), p3m_data_struct_base::g_energy, p3m_data_struct_base::g_force, p3m_send_mesh::gather_grid(), dp3m_data_struct::ks_mesh, p3m_data_struct_base::ks_pnum, BoxGeometry::length_inv(), dp3m_data_struct::local_mesh, Utils::make_span(), P3MParameters::mesh, fft_forw_plan::new_mesh, P3M_EPSILON_METALLIC, p3m_data_struct_base::params, Cells::particles(), Utils::pi(), fft_data_struct::plan, Dipole_parameters::prefactor, dp3m_data_struct::rs_mesh, dp3m_data_struct::rs_mesh_dip, dp3m_data_struct::sm, p3m_send_mesh::spread_grid(), Utils::sqr(), Utils::sqrt_pi_i(), fft_forw_plan::start, dp3m_data_struct::sum_mu2, this_node, and BoxGeometry::volume().
Referenced by Dipole::calc_energy_long_range(), and Dipole::calc_long_range_force().
dp3m_count_magnetic_particles()
void dp3m_count_magnetic_particles ()
Calculate number of magnetic particles, the sum of the squared charges and the squared sum of the charges.
Definition at line 1230 of file p3m-dipolar.cpp.
References cell_structure, comm_cart, dp3m, CellStructure::local_particles(), dp3m_data_struct::sum_dip_part, and dp3m_data_struct::sum_mu2.
Referenced by dp3m_adaptive_tune(), dp3m_init(), and Dipole::on_observable_calc().
dp3m_deactivate()
void dp3m_deactivate ()
Reset dp3m core parameters.
Definition at line 174 of file p3m-dipolar.cpp.
References P3MParameters::alpha, P3MParameters::alpha_L, P3MParameters::cao, dp3m, P3MParameters::mesh, p3m_data_struct_base::params, P3MParameters::r_cut, and P3MParameters::r_cut_iL.
dp3m_dipole_assign()
void dp3m_dipole_assign (const ParticleRange & particles)
Assign the physical dipoles using the tabulated assignment function.
Definition at line 322 of file p3m-dipolar.cpp.
References P3MParameters::cao, dp3m, dp3m_data_struct::inter_weights, dp3m_data_struct::local_mesh, p3m_data_struct_base::params, Cells::particles(), p3m_interpolation_cache::reset(), dp3m_data_struct::rs_mesh_dip, and P3MLocalMesh::size.
Referenced by Dipole::calc_energy_long_range(), and Dipole::calc_long_range_force().
dp3m_init()
void dp3m_init ()
Initialize all structures, parameters and arrays needed for the P3M algorithm for dipole-dipole interactions.
Definition at line 185 of file p3m-dipolar.cpp.
References p3m_data_struct_base::calc_differential_operator(), P3MParameters::cao, P3MParameters::cao3, comm_cart, P3MLocalMesh::dim, dipole, dp3m, dp3m_count_magnetic_particles(), dp3m_init_a_ai_cao_cut(), dp3m_sanity_checks(), dp3m_scaleby_box_l(), dp3m_data_struct::fft, fft_init(), dp3m_data_struct::ks_mesh, p3m_data_struct_base::ks_pnum, local_geo, dp3m_data_struct::local_mesh, P3MLocalMesh::margin, P3MParameters::mesh, P3MParameters::mesh_off, node_grid, p3m_calc_local_ca_mesh(), p3m_data_struct_base::params, Dipole_parameters::prefactor, P3MParameters::r_cut, P3MParameters::r_cut_iL, p3m_send_mesh::resize(), dp3m_data_struct::rs_mesh, dp3m_data_struct::rs_mesh_dip, skin, and dp3m_data_struct::sm.
Referenced by Dipole::init(), and Dipole::on_coulomb_change().
dp3m_pair_energy()
double dp3m_pair_energy (Particle const & p1, Particle const & p2, Utils::Vector3d const & d, double dist2, double dist) inline
Calculate real space contribution of dipolar pair energy.
Definition at line 243 of file p3m-dipolar.hpp.
References P3MParameters::accuracy, P3MParameters::alpha, Utils::AS_erfc_part(), Particle::calc_dip(), ParticleProperties::dipm, dipole, dp3m, Particle::p, p3m_data_struct_base::params, Dipole_parameters::prefactor, P3MParameters::r_cut, and Utils::sqrt_pi_i().
Referenced by Dipole::pair_energy().
dp3m_pair_force()
ParticleForce dp3m_pair_force (Particle const & p1, Particle const & p2, Utils::Vector3d const & d, double dist2, double dist) inline
Calculate real space contribution of p3m dipolar pair forces and torques.
If NPT is compiled in, update the NpT virial.
Definition at line 183 of file p3m-dipolar.hpp.
References P3MParameters::accuracy, P3MParameters::alpha, Utils::AS_erfc_part(), Particle::calc_dip(), ParticleProperties::dipm, dipole, dp3m, force, npt_add_virial_magnetic_contribution(), Particle::p, p3m_data_struct_base::params, Dipole_parameters::prefactor, P3MParameters::r_cut, Utils::sqrt_pi_i(), torque, and Utils::vector_product().
Referenced by Dipole::pair_force().
dp3m_sanity_checks()
bool dp3m_sanity_checks (const Utils::Vector3i & grid)
Sanity checks.
Definition at line 1420 of file p3m-dipolar.cpp.
References box_geo, P3MParameters::cao, cell_structure, CELL_STRUCTURE_DOMDEC, CellStructure::decomposition_type(), dp3m, dp3m_sanity_checks_boxl(), BoxGeometry::length(), P3MParameters::mesh, p3m_data_struct_base::params, BoxGeometry::periodic(), and runtimeErrorMsg.
Referenced by dp3m_init(), and Dipole::nonbonded_sanity_check().
dp3m_scaleby_box_l()
void dp3m_scaleby_box_l ()
Update alpha and r_cut if box length changed.
Definition at line 1468 of file p3m-dipolar.cpp.
References P3MParameters::alpha, P3MParameters::alpha_L, box_geo, dipole, dp3m, dp3m_calc_influence_function_energy(), dp3m_calc_influence_function_force(), dp3m_init_a_ai_cao_cut(), dp3m_sanity_checks_boxl(), BoxGeometry::length(), BoxGeometry::length_inv(), dp3m_data_struct::local_mesh, p3m_calc_lm_ld_pos(), p3m_data_struct_base::params, Dipole_parameters::prefactor, P3MParameters::r_cut, P3MParameters::r_cut_iL, and runtimeErrorMsg.
Referenced by dp3m_init(), and Dipole::on_boxl_change().
dp3m_set_eps()
void dp3m_set_eps (double eps)
Set epsilon parameter.
Parameters
[in] eps epsilon of the "surrounding dielectric".
Set epsilon parameter.
Currently unused.
Definition at line 299 of file p3m-dipolar.cpp.
References dp3m, P3MParameters::epsilon, mpi_bcast_coulomb_params(), and p3m_data_struct_base::params.
dp3m_set_mesh_offset()
void dp3m_set_mesh_offset (double x, double y, double z)
Set mesh offset.
Parameters
[in] x,y,z Components of mesh_off
Definition at line 281 of file p3m-dipolar.cpp.
References dp3m, P3MParameters::mesh_off, mpi_bcast_coulomb_params(), and p3m_data_struct_base::params.
dp3m_set_params()
void dp3m_set_params (double r_cut, int mesh, int cao, double alpha, double accuracy)
Set custom parameters.
Parameters
[in] r_cut unscaled r_cut_iL for use with fast inline functions only
[in] mesh number of mesh points per coordinate direction (>0).
[in] cao charge assignment order ([0,7]).
[in] alpha unscaled alpha_L for use with fast inline functions only
[in] accuracy accuracy of the actual parameter set.
Definition at line 247 of file p3m-dipolar.cpp.
References P3MParameters::accuracy, P3MParameters::alpha, P3MParameters::alpha_L, box_geo, P3MParameters::cao, DIPOLAR_MDLC_P3M, DIPOLAR_P3M, dipole, dp3m, BoxGeometry::length(), BoxGeometry::length_inv(), P3MParameters::mesh, Dipole_parameters::method, mpi_bcast_coulomb_params(), p3m_data_struct_base::params, P3MParameters::r_cut, P3MParameters::r_cut_iL, and Dipole::set_method_local().
dp3m_set_tune_params()
void dp3m_set_tune_params (double r_cut, int mesh, int cao, double accuracy)
Set initial values for p3m_adaptive_tune()
Parameters
[in] r_cut unscaled r_cut_iL for use with fast inline functions only
[in] mesh number of mesh points per coordinate direction (>0).
[in] cao charge assignment order ([0,7]).
[in] accuracy accuracy of the actual parameter set.
Definition at line 229 of file p3m-dipolar.cpp.
References P3MParameters::accuracy, box_geo, P3MParameters::cao, dp3m, BoxGeometry::length_inv(), P3MParameters::mesh, p3m_data_struct_base::params, P3MParameters::r_cut, and P3MParameters::r_cut_iL.
npt_add_virial_magnetic_contribution()
void npt_add_virial_magnetic_contribution (double energy)
Update the NpT virial.
Definition at line 1499 of file p3m-dipolar.cpp.
References npt_add_virial_contribution().
Referenced by dp3m_pair_force().
Variable Documentation
dp3m
dp3m_data_struct dp3m
dipolar P3M parameters.
Definition at line 86 of file p3m-dipolar.cpp.
Referenced by add_mdlc_energy_corrections(), add_mdlc_force_corrections(), Dipole::bcast_params(), calc_surface_term(), Dipole::cutoff(), dp3m_adaptive_tune(), dp3m_average_dipolar_self_energy(), dp3m_calc_influence_function_energy(), dp3m_calc_influence_function_force(), dp3m_calc_kspace_forces(), dp3m_compute_constants_energy_dipolar(), dp3m_count_magnetic_particles(), dp3m_deactivate(), dp3m_dipole_assign(), dp3m_get_accuracy(), dp3m_init(), dp3m_init_a_ai_cao_cut(), dp3m_mc_time(), dp3m_mcr_time(), dp3m_pair_energy(), dp3m_pair_force(), dp3m_sanity_checks(), dp3m_sanity_checks_boxl(), dp3m_scaleby_box_l(), dp3m_set_eps(), dp3m_set_mesh_offset(), dp3m_set_params(), and dp3m_set_tune_params().