ESPResSo: p3m-common.hpp File Reference
p3m-common.hpp File Reference
#include "config.hpp"
#include <array>
#include <cstddef>
#include <vector>
#include "LocalBox.hpp"
#include <utils/Vector.hpp>
Classes
struct P3MLocalMesh
Structure for local mesh parameters.
struct P3MParameters
Structure to hold P3M parameters and some dependent variables.
Macros
#define P3M_EPSILON_METALLIC 0.0
This value indicates metallic boundary conditions.
#define P3M_RCUT_PREC 1e-3
precision limit for the r_cut zero
#define P3M_TIME_GRAN 2
granularity of the time measurement
Enumerations
enum P3M_TUNE_ERROR {
P3M_TUNE_FAIL = 1, P3M_TUNE_NOCUTOFF = 2, P3M_TUNE_CAO_TOO_LARGE = 4, P3M_TUNE_ELCTEST = 8,
P3M_TUNE_CUTOFF_TOO_LARGE = 16, P3M_TUNE_ACCURACY_TOO_LARGE = 32
}
Error Codes for p3m tuning (version 2)
Functions
void p3m_add_block (double const *in, double *out, int const start[3], int const size[3], int const dim[3])
Add values of a 3d-grid input block (size[3]) to values of 3d-grid output array with dimension dim[3] at start position start[3].
double p3m_analytic_cotangent_sum (int n, double mesh_i, int cao)
One of the aliasing sums used by p3m_k_space_error.
void p3m_calc_local_ca_mesh (P3MLocalMesh &local_mesh, const P3MParameters &params, const LocalBox< double > &local_geo, double skin, double space_layer)
Calculate properties of the local FFT mesh for the charge assignment process.
void p3m_calc_lm_ld_pos (P3MLocalMesh &local_mesh, const P3MParameters &params)
Calculate the spatial position of the left down mesh point of the local mesh, to be stored in ld_pos.
Detailed Description
Common functions for dipolar and charge P3M.
We use here a P3M (Particle-Particle Particle-Mesh) method based on the Ewald summation. Details of the used method can be found in [27] and [11] [12]. The file p3m contains only the Particle-Mesh part.
Further reading: [22], [27], [11], [12], [13], [14], [10]
Definition in file p3m-common.hpp.
Macro Definition Documentation
P3M_EPSILON_METALLIC
#define P3M_EPSILON_METALLIC 0.0
This value indicates metallic boundary conditions.
Definition at line 74 of file p3m-common.hpp.
P3M_RCUT_PREC
#define P3M_RCUT_PREC 1e-3
precision limit for the r_cut zero
Definition at line 77 of file p3m-common.hpp.
P3M_TIME_GRAN
#define P3M_TIME_GRAN 2
granularity of the time measurement
Definition at line 79 of file p3m-common.hpp.
Enumeration Type Documentation
P3M_TUNE_ERROR
enum P3M_TUNE_ERROR
Error Codes for p3m tuning (version 2)
Enumerator
P3M_TUNE_FAIL
force evaluation failed
P3M_TUNE_NOCUTOFF
could not find a valid realspace cutoff radius
P3M_TUNE_CAO_TOO_LARGE
charge assignment order too large for mesh size
P3M_TUNE_ELCTEST
conflict with ELC gap size
P3M_TUNE_CUTOFF_TOO_LARGE
P3M_TUNE_ACCURACY_TOO_LARGE
could not achieve target accuracy
Definition at line 48 of file p3m-common.hpp.
Function Documentation
p3m_add_block()
void p3m_add_block (double const * in, double * out, int const start[3], int const size[3], int const dim[3])
Add values of a 3d-grid input block (size[3]) to values of 3d-grid output array with dimension dim[3] at start position start[3].
Parameters
in Pointer to first element of input block data.
out Pointer to first element of output grid.
start Start position of block in output grid.
size Dimensions of the block
dim Dimensions of the output grid.
Definition at line 39 of file p3m-common.cpp.
References f.
Referenced by p3m_send_mesh::gather_grid().
p3m_analytic_cotangent_sum()
double p3m_analytic_cotangent_sum (int n, double mesh_i, int cao)
One of the aliasing sums used by p3m_k_space_error.
Fortunately the one which is most important (because it converges most slowly, since it is not damped exponentially) can be calculated analytically. The result (which depends on the order of the spline interpolation) can be written as an even trigonometric polynomial. The results are tabulated here (the employed formula is eq. (7.66) in [27]).
Definition at line 63 of file p3m-common.cpp.
References D3Q19::c, errexit(), Utils::pi(), res, Utils::sqr(), and this_node.
Referenced by dp3m_k_space_error(), and p3m_k_space_error().
p3m_calc_lm_ld_pos()
void p3m_calc_lm_ld_pos (P3MLocalMesh & local_mesh, const P3MParameters & params)
Calculate the spatial position of the left down mesh point of the local mesh, to be stored in ld_pos.
Function called by p3m_calc_local_ca_mesh() once and by p3m_scaleby_box_l() whenever the box size changes.
Definition at line 193 of file p3m-common.cpp.
References P3MLocalMesh::ld_ind, P3MLocalMesh::ld_pos, and params.
Referenced by dp3m_scaleby_box_l(), and p3m_scaleby_box_l().
p3m_calc_local_ca_mesh()
void p3m_calc_local_ca_mesh (P3MLocalMesh & local_mesh, const P3MParameters & params, const LocalBox< double > & local_geo, double skin, double space_layer)
Calculate properties of the local FFT mesh for the charge assignment process.
Definition at line 116 of file p3m-common.cpp.
References P3MLocalMesh::dim, P3MLocalMesh::in_ld, P3MLocalMesh::in_ur, P3MLocalMesh::inner, P3MLocalMesh::ld_ind, local_geo, P3MLocalMesh::margin, LocalBox< T >::my_left(), LocalBox< T >::my_right(), params, P3MLocalMesh::q_21_off, P3MLocalMesh::q_2_off, ROUND_ERROR_PREC, P3MLocalMesh::size, and skin.
Referenced by dp3m_init(), and p3m_init().