ESPResSo: p3m-common.cpp File Reference
p3m-common.cpp File Reference
#include "p3m-common.hpp"
#include "errorhandling.hpp"
#include <utils/Vector.hpp>
#include <utils/constants.hpp>
#include <utils/math/sqr.hpp>
#include <cmath>
#include <cstdio>
Functions
void p3m_add_block (double const *in, double *out, int const start[3], int const size[3], int const dim[3])
Add values of a 3d-grid input block (size[3]) to values of 3d-grid output array with dimension dim[3] at start position start[3].
double p3m_analytic_cotangent_sum (int n, double mesh_i, int cao)
One of the aliasing sums used by p3m_k_space_error.
void p3m_calc_local_ca_mesh (P3MLocalMesh &local_mesh, const P3MParameters &params, const LocalBox< double > &local_geo, double skin, double space_layer)
Calculate properties of the local FFT mesh for the charge assignment process.
void p3m_calc_lm_ld_pos (P3MLocalMesh &local_mesh, const P3MParameters &params)
Calculate the spatial position of the left down mesh point of the local mesh, to be stored in ld_pos.
Variables
int this_node
The number of this node.
Detailed Description
P3M main file.
Definition in file p3m-common.cpp.
Function Documentation
p3m_add_block()
void p3m_add_block (double const * in, double * out, int const start[3], int const size[3], int const dim[3])
Add values of a 3d-grid input block (size[3]) to values of 3d-grid output array with dimension dim[3] at start position start[3].
Parameters
in Pointer to first element of input block data.
out Pointer to first element of output grid.
start Start position of block in output grid.
size Dimensions of the block
dim Dimensions of the output grid.
Definition at line 39 of file p3m-common.cpp.
References f.
Referenced by p3m_send_mesh::gather_grid().
p3m_analytic_cotangent_sum()
double p3m_analytic_cotangent_sum (int n, double mesh_i, int cao)
One of the aliasing sums used by p3m_k_space_error.
Fortunately the one which is most important (because it converges most slowly, since it is not damped exponentially) can be calculated analytically. The result (which depends on the order of the spline interpolation) can be written as an even trigonometric polynomial. The results are tabulated here (the employed formula is eq. (7.66) in [27]).
Definition at line 63 of file p3m-common.cpp.
References D3Q19::c, errexit(), Utils::pi(), res, Utils::sqr(), and this_node.
Referenced by dp3m_k_space_error(), and p3m_k_space_error().
p3m_calc_lm_ld_pos()
void p3m_calc_lm_ld_pos (P3MLocalMesh & local_mesh, const P3MParameters & params)
Calculate the spatial position of the left down mesh point of the local mesh, to be stored in ld_pos.
Function called by p3m_calc_local_ca_mesh() once and by p3m_scaleby_box_l() whenever the box size changes.
Definition at line 193 of file p3m-common.cpp.
References P3MLocalMesh::ld_ind, P3MLocalMesh::ld_pos, and params.
Referenced by dp3m_scaleby_box_l(), and p3m_scaleby_box_l().
p3m_calc_local_ca_mesh()
void p3m_calc_local_ca_mesh (P3MLocalMesh & local_mesh, const P3MParameters & params, const LocalBox< double > & local_geo, double skin, double space_layer)
Calculate properties of the local FFT mesh for the charge assignment process.
Definition at line 116 of file p3m-common.cpp.
References P3MLocalMesh::dim, P3MLocalMesh::in_ld, P3MLocalMesh::in_ur, P3MLocalMesh::inner, P3MLocalMesh::ld_ind, local_geo, P3MLocalMesh::margin, LocalBox< T >::my_left(), LocalBox< T >::my_right(), params, P3MLocalMesh::q_21_off, P3MLocalMesh::q_2_off, ROUND_ERROR_PREC, P3MLocalMesh::size, and skin.
Referenced by dp3m_init(), and p3m_init().
Variable Documentation
this_node
int this_node
The number of this node.
Definition at line 62 of file communication.cpp.
Referenced by p3m_analytic_cotangent_sum().