ESPResSo: p3m-dipolar.cpp File Reference
p3m-dipolar.cpp File Reference
#include "config.hpp"
#include "electrostatics_magnetostatics/p3m-dipolar.hpp"
#include "electrostatics_magnetostatics/common.hpp"
#include "electrostatics_magnetostatics/dp3m_influence_function.hpp"
#include "electrostatics_magnetostatics/fft.hpp"
#include "electrostatics_magnetostatics/p3m-common.hpp"
#include "electrostatics_magnetostatics/p3m_interpolation.hpp"
#include "electrostatics_magnetostatics/p3m_send_mesh.hpp"
#include "Particle.hpp"
#include "ParticleRange.hpp"
#include "cells.hpp"
#include "communication.hpp"
#include "errorhandling.hpp"
#include "grid.hpp"
#include "integrate.hpp"
#include "npt.hpp"
#include "tuning.hpp"
#include <utils/Vector.hpp>
#include <utils/constants.hpp>
#include <utils/integral_parameter.hpp>
#include <utils/math/int_pow.hpp>
#include <utils/math/sinc.hpp>
#include <utils/math/sqr.hpp>
#include <boost/mpi/collectives/all_reduce.hpp>
#include <boost/mpi/collectives/reduce.hpp>
#include <boost/range/algorithm/min_element.hpp>
#include <algorithm>
#include <array>
#include <cstdio>
#include <functional>
#include <stdexcept>
#include <vector>
Namespaces
anonymous_namespace{p3m-dipolar.cpp}
Macros
#define DP3M_RTBISECTION_ERROR 9999999
Functions
static double calc_surface_term (bool force_flag, bool energy_flag, ParticleRange const &particles)
Compute the dipolar surface terms.
double dp3m_average_dipolar_self_energy ()
Correction of the dipolar p3m-energy.
void dp3m_deactivate ()
Reset dp3m core parameters.
void dp3m_init ()
Initialize all structures, parameters and arrays needed for the P3M algorithm for dipole-dipole interactions.
void dp3m_set_tune_params (double r_cut, int mesh, int cao, double accuracy)
Set initial values for p3m_adaptive_tune()
void dp3m_set_params (double r_cut, int mesh, int cao, double alpha, double accuracy)
Set custom parameters.
void dp3m_set_mesh_offset (double x, double y, double z)
Set mesh offset.
void dp3m_set_eps (double eps)
We left the handling of the epsilon, due to portability reasons in the future for the electrical dipoles, or if people want to do electrical dipoles alone using the magnetic code.
void dp3m_dipole_assign (const ParticleRange &particles)
Assign the physical dipoles using the tabulated assignment function.
double dp3m_calc_kspace_forces (bool force_flag, bool energy_flag, const ParticleRange &particles)
Compute the k-space part of forces and energies for the magnetic dipole-dipole interaction.
double dp3m_get_accuracy (int mesh, int cao, double r_cut_iL, double *_alpha_L, double *_rs_err, double *_ks_err)
Get the minimal error for this combination of parameters.
static double dp3m_mcr_time (int mesh, int cao, double r_cut_iL, double alpha_L, int timings)
Get the computation time for some mesh, cao, r_cut and alpha.
static double dp3m_mc_time (int mesh, int cao, double r_cut_iL_min, double r_cut_iL_max, double *_r_cut_iL, double *_alpha_L, double *_accuracy, int timings, bool verbose)
Get the optimal alpha and the corresponding computation time for a fixed mesh and cao.
static double dp3m_m_time (int mesh, int cao_min, int cao_max, int *_cao, double r_cut_iL_min, double r_cut_iL_max, double *_r_cut_iL, double *_alpha_L, double *_accuracy, int timings, bool verbose)
Get the optimal alpha and the corresponding computation time for a fixed mesh.
int dp3m_adaptive_tune (int timings, bool verbose)
Tune dipolar P3M parameters to desired accuracy.
void dp3m_count_magnetic_particles ()
Calculate number of magnetic particles, the sum of the squared charges and the squared sum of the charges.
bool dp3m_sanity_checks (const Utils::Vector3i &grid)
Sanity checks.
void dp3m_scaleby_box_l ()
Update alpha and r_cut if box length changed.
void npt_add_virial_magnetic_contribution (double energy)
Update the NpT virial.
Private Functions
static void dp3m_init_a_ai_cao_cut ()
Initialize for magnetic dipoles the (inverse) mesh constant a (ai) and the cutoff for charge assignment cao_cut.
static bool dp3m_sanity_checks_boxl ()
Checks for correctness for magnetic dipoles in P3M of the cao_cut, necessary when the box length changes.
static void dp3m_calc_influence_function_force ()
Calculate the influence function optimized for the dipolar forces.
static void dp3m_calc_influence_function_energy ()
Calculate the influence function optimized for the dipolar energy and torques.
static void dp3m_compute_constants_energy_dipolar ()
Calculate the constants necessary to correct the dipolar energy to minimize the error.
static double dp3m_k_space_error (double box_size, double prefac, int mesh, int cao, int n_c_part, double sum_q2, double alpha_L)
Calculate the k-space error of dipolar-P3M.
P3M Tuning Functions
double dp3m_real_space_error (double box_size, double prefac, double r_cut_iL, int n_c_part, double sum_q2, double alpha_L)
Calculate the value of the errors for the REAL part of the force in terms of the splitting parameter alpha of Ewald.
static void dp3m_tune_aliasing_sums (int nx, int ny, int nz, int mesh, double mesh_i, int cao, double alpha_L_i, double *alias1, double *alias2)
Tuning dipolar-P3M.
double dp3m_rtbisection (double box_size, double prefac, double r_cut_iL, int n_c_part, double sum_q2, double x1, double x2, double xacc, double tuned_accuracy)
Compute the value of alpha through a bisection method.
Variables
dp3m_data_struct dp3m
dipolar P3M parameters.
Detailed Description
P3M algorithm for long range magnetic dipole-dipole interaction.
Note
In general the magnetic dipole-dipole functions bear the same name than the charge-charge, but adding a "D" in front of the name and replacing "charge" by "dipole". In this way one can recognize the similarity of the functions while avoiding nasty confusions in their use.
By default the magnetic epsilon is metallic = 0.
The corresponding header file is p3m-dipolar.hpp.
Definition in file p3m-dipolar.cpp.
Macro Definition Documentation
DP3M_RTBISECTION_ERROR
#define DP3M_RTBISECTION_ERROR 9999999
Definition at line 80 of file p3m-dipolar.cpp.
Function Documentation
calc_surface_term()
double calc_surface_term (bool force_flag, bool energy_flag, ParticleRange const & particles) static
Compute the dipolar surface terms.
Definition at line 644 of file p3m-dipolar.cpp.
References box_geo, comm_cart, dipole, dp3m, P3MParameters::epsilon, p3m_data_struct_base::params, Cells::particles(), Utils::pi(), Dipole_parameters::prefactor, ParticleRange::size(), and BoxGeometry::volume().
Referenced by dp3m_calc_kspace_forces().
dp3m_adaptive_tune()
int dp3m_adaptive_tune (int timings, bool verbose)
Tune dipolar P3M parameters to desired accuracy.
The parameters mesh, cao, r_cut_iL and alpha_L are tuned to obtain the target accuracy (initially stored in accuracy) in optimal time. These parameters are stored in the dp3m object.
The function utilizes the analytic expression of the error estimate for the dipolar P3M method in the paper of [10] in order to obtain the rms error in the force for a system of N randomly distributed particles in a cubic box. For the real space error, the estimate in [29] is used.
Parameter ranges if not given explicit values via dp3m_set_tune_params():
mesh is set up such that the number of mesh points is equal to the number of magnetic dipolar particles
cao explores all possible values
alpha_L is tuned for each tuple (r_cut_iL, mesh, cao) and calculated assuming that the error contributions of real and reciprocal space should be equal
After checking if the total error lies below the target accuracy, the time needed for one force calculation (including Verlet list update) is measured via time_force_calc().
The function generates a log of the performed tuning.
The function is based on routines of the program HE_Q.cpp for charges written by M. Deserno.
Parameters
verbose printf output
timings Number of test force calculations
Return values
ES_OK
ES_ERROR
Tuning of dipolar P3M. The algorithm basically determines the mesh, cao and then the real space cutoff, in this nested order.
For each mesh, the cao optimal for the mesh tested previously is used as an initial guess, and the algorithm tries whether increasing or decreasing it leads to a better solution. This is efficient, since the optimal cao only changes little with the meshes in general.
The real space cutoff for a given mesh and cao is determined via a bisection on the error estimate, which determines where the error estimate equals the required accuracy. Therefore the smallest possible, i.e. fastest real space cutoff is determined.
Both the search over mesh and cao stop to search in a specific direction once the computation time is significantly higher than the currently known optimum.
Definition at line 1079 of file p3m-dipolar.cpp.
References P3MParameters::accuracy, P3MParameters::alpha_L, box_geo, P3MParameters::cao, dipole, dp3m, dp3m_count_magnetic_particles(), dp3m_m_time(), DP3M_RTBISECTION_ERROR, ES_ERROR, ES_OK, LocalBox< T >::length(), BoxGeometry::length(), BoxGeometry::length_inv(), local_geo, P3MParameters::mesh, anonymous_namespace{Correlator.cpp}::min(), mpi_bcast_coulomb_params(), mpi_call_all(), P3M_MAX_MESH, P3M_TIME_GRAN, P3M_TUNE_FAIL, p3m_data_struct_base::params, Dipole_parameters::prefactor, P3MParameters::r_cut_iL, runtimeErrorMsg, skin, dp3m_data_struct::sum_dip_part, and dp3m_data_struct::sum_mu2.
dp3m_average_dipolar_self_energy()
double dp3m_average_dipolar_self_energy ()
Correction of the dipolar p3m-energy.
Definition at line 147 of file p3m-dipolar.cpp.
References box_geo, comm_cart, dp3m, dp3m_data_struct::fft, p3m_data_struct_base::g_energy, grid_influence_function_self_energy(), BoxGeometry::length(), P3MParameters::mesh, fft_forw_plan::new_mesh, p3m_data_struct_base::params, Utils::pi(), fft_data_struct::plan, and fft_forw_plan::start.
Referenced by dp3m_compute_constants_energy_dipolar().
dp3m_calc_influence_function_energy()
void dp3m_calc_influence_function_energy () static
Calculate the influence function optimized for the dipolar energy and torques.
Definition at line 719 of file p3m-dipolar.cpp.
References box_geo, dp3m, dp3m_data_struct::fft, p3m_data_struct_base::g_energy, BoxGeometry::length(), fft_forw_plan::new_mesh, p3m_data_struct_base::params, fft_data_struct::plan, and fft_forw_plan::start.
Referenced by dp3m_scaleby_box_l().
dp3m_calc_influence_function_force()
void dp3m_calc_influence_function_force () static
Calculate the influence function optimized for the dipolar forces.
Definition at line 711 of file p3m-dipolar.cpp.
References box_geo, dp3m, dp3m_data_struct::fft, p3m_data_struct_base::g_force, BoxGeometry::length(), fft_forw_plan::new_mesh, p3m_data_struct_base::params, fft_data_struct::plan, and fft_forw_plan::start.
Referenced by dp3m_scaleby_box_l().
dp3m_calc_kspace_forces()
double dp3m_calc_kspace_forces (bool force_flag, bool energy_flag, const ParticleRange & particles)
Compute the k-space part of forces and energies for the magnetic dipole-dipole interaction.
Definition at line 381 of file p3m-dipolar.cpp.
References P3MParameters::alpha_L, box_geo, calc_surface_term(), P3MParameters::cao, comm_cart, p3m_data_struct_base::d_op, P3MLocalMesh::dim, dipole, dp3m, dp3m_compute_constants_energy_dipolar(), dp3m_data_struct::energy_correction, P3MParameters::epsilon, dp3m_data_struct::fft, fft_perform_back(), fft_perform_forw(), p3m_data_struct_base::g_energy, p3m_data_struct_base::g_force, p3m_send_mesh::gather_grid(), dp3m_data_struct::ks_mesh, p3m_data_struct_base::ks_pnum, BoxGeometry::length_inv(), dp3m_data_struct::local_mesh, Utils::make_span(), P3MParameters::mesh, fft_forw_plan::new_mesh, P3M_EPSILON_METALLIC, p3m_data_struct_base::params, Cells::particles(), Utils::pi(), fft_data_struct::plan, Dipole_parameters::prefactor, dp3m_data_struct::rs_mesh, dp3m_data_struct::rs_mesh_dip, dp3m_data_struct::sm, p3m_send_mesh::spread_grid(), Utils::sqr(), Utils::sqrt_pi_i(), fft_forw_plan::start, dp3m_data_struct::sum_mu2, this_node, and BoxGeometry::volume().
Referenced by Dipole::calc_energy_long_range(), and Dipole::calc_long_range_force().
dp3m_compute_constants_energy_dipolar()
void dp3m_compute_constants_energy_dipolar () static
Calculate the constants necessary to correct the dipolar energy to minimize the error.
Calculate the dipolar-P3M energy correction.
Definition at line 1485 of file p3m-dipolar.cpp.
References P3MParameters::alpha_L, box_geo, dp3m, dp3m_average_dipolar_self_energy(), dp3m_data_struct::energy_correction, p3m_data_struct_base::params, Utils::pi(), Utils::sqrt_pi_i(), dp3m_data_struct::sum_mu2, and BoxGeometry::volume().
Referenced by dp3m_calc_kspace_forces().
dp3m_count_magnetic_particles()
void dp3m_count_magnetic_particles ()
Calculate number of magnetic particles, the sum of the squared charges and the squared sum of the charges.
Definition at line 1230 of file p3m-dipolar.cpp.
References cell_structure, comm_cart, dp3m, CellStructure::local_particles(), dp3m_data_struct::sum_dip_part, and dp3m_data_struct::sum_mu2.
Referenced by dp3m_adaptive_tune(), dp3m_init(), and Dipole::on_observable_calc().
dp3m_deactivate()
void dp3m_deactivate ()
Reset dp3m core parameters.
Definition at line 174 of file p3m-dipolar.cpp.
References P3MParameters::alpha, P3MParameters::alpha_L, P3MParameters::cao, dp3m, P3MParameters::mesh, p3m_data_struct_base::params, P3MParameters::r_cut, and P3MParameters::r_cut_iL.
dp3m_dipole_assign()
void dp3m_dipole_assign (const ParticleRange & particles)
Assign the physical dipoles using the tabulated assignment function.
Definition at line 322 of file p3m-dipolar.cpp.
References P3MParameters::cao, dp3m, dp3m_data_struct::inter_weights, dp3m_data_struct::local_mesh, p3m_data_struct_base::params, Cells::particles(), p3m_interpolation_cache::reset(), dp3m_data_struct::rs_mesh_dip, and P3MLocalMesh::size.
Referenced by Dipole::calc_energy_long_range(), and Dipole::calc_long_range_force().
dp3m_get_accuracy()
double dp3m_get_accuracy (int mesh, int cao, double r_cut_iL, double * _alpha_L, double * _rs_err, double * _ks_err)
Get the minimal error for this combination of parameters.
The real space error is tuned such that it contributes half of the total error, and then the Fourier space error is calculated. If an optimal alpha is not found, the value 0.1 is used as fallback.
Parameters
[in] mesh number of mesh points per coordinate direction (>0).
[in] cao charge assignment order ([0,7]).
[in] r_cut_iL cutoff radius for real space electrostatics (>0), rescaled to r_cut_iL = r_cut * box_l_i.
[out] _alpha_L Ewald splitting parameter (0<alpha<1), rescaled to alpha_L = alpha * box_l.
[out] _rs_err real space error
[out] _ks_err Fourier space error
Returns
Error magnitude
Definition at line 742 of file p3m-dipolar.cpp.
References P3MParameters::accuracy, box_geo, dipole, dp3m, dp3m_k_space_error(), dp3m_real_space_error(), dp3m_rtbisection(), DP3M_RTBISECTION_ERROR, BoxGeometry::length(), p3m_data_struct_base::params, Dipole_parameters::prefactor, Utils::sqr(), Utils::sqrt(), Utils::sqrt_2(), dp3m_data_struct::sum_dip_part, and dp3m_data_struct::sum_mu2.
Referenced by dp3m_mc_time().
dp3m_init()
void dp3m_init ()
Initialize all structures, parameters and arrays needed for the P3M algorithm for dipole-dipole interactions.
Definition at line 185 of file p3m-dipolar.cpp.
References p3m_data_struct_base::calc_differential_operator(), P3MParameters::cao, P3MParameters::cao3, comm_cart, P3MLocalMesh::dim, dipole, dp3m, dp3m_count_magnetic_particles(), dp3m_init_a_ai_cao_cut(), dp3m_sanity_checks(), dp3m_scaleby_box_l(), dp3m_data_struct::fft, fft_init(), dp3m_data_struct::ks_mesh, p3m_data_struct_base::ks_pnum, local_geo, dp3m_data_struct::local_mesh, P3MLocalMesh::margin, P3MParameters::mesh, P3MParameters::mesh_off, node_grid, p3m_calc_local_ca_mesh(), p3m_data_struct_base::params, Dipole_parameters::prefactor, P3MParameters::r_cut, P3MParameters::r_cut_iL, p3m_send_mesh::resize(), dp3m_data_struct::rs_mesh, dp3m_data_struct::rs_mesh_dip, skin, and dp3m_data_struct::sm.
Referenced by Dipole::init(), and Dipole::on_coulomb_change().
dp3m_init_a_ai_cao_cut()
void dp3m_init_a_ai_cao_cut () static
Initialize for magnetic dipoles the (inverse) mesh constant a (ai) and the cutoff for charge assignment cao_cut.
Function called by dp3m_init() once and by dp3m_scaleby_box_l() whenever the box_length changes.
Definition at line 1386 of file p3m-dipolar.cpp.
References P3MParameters::a, P3MParameters::ai, box_geo, P3MParameters::cao, P3MParameters::cao_cut, dp3m, BoxGeometry::length_inv(), P3MParameters::mesh, and p3m_data_struct_base::params.
Referenced by dp3m_init(), and dp3m_scaleby_box_l().
dp3m_k_space_error()
static double dp3m_k_space_error (double box_size, double prefac, int mesh, int cao, int n_c_part, double sum_q2, double alpha_L) static
Calculate the k-space error of dipolar-P3M.
Definition at line 1249 of file p3m-dipolar.cpp.
References dp3m_tune_aliasing_sums(), p3m_analytic_cotangent_sum(), Utils::pi(), ROUND_ERROR_PREC, Utils::sqr(), and Utils::sqrt().
Referenced by dp3m_get_accuracy().
dp3m_m_time()
static double dp3m_m_time (int mesh, int cao_min, int cao_max, int * _cao, double r_cut_iL_min, double r_cut_iL_max, double * _r_cut_iL, double * _alpha_L, double * _accuracy, int timings, bool verbose) static
Get the optimal alpha and the corresponding computation time for a fixed mesh.
_cao should contain an initial guess, which is then adapted by stepping up and down.
Parameters
[in] mesh number of mesh points per coordinate direction (>0).
[in] cao_min lower bound for _cao
[in] cao_max upper bound for _cao
[in,out] _cao initial guess for the charge assignment order ([0,7]).
[in] r_cut_iL_min lower bound for _r_cut_iL
[in] r_cut_iL_max upper bound for _r_cut_iL
[out] _r_cut_iL cutoff radius for real space electrostatics (>0), rescaled to r_cut_iL = r_cut * box_l_i.
[out] _alpha_L Ewald splitting parameter (0<alpha<1), rescaled to alpha_L = alpha * box_l.
[out] _accuracy accuracy of the actual parameter set.
[in] timings Number of test force calculations
[in] verbose printf output
Returns
The integration time in case of success, otherwise -P3M_TUNE_FAIL or -P3M_TUNE_CAO_TOO_LARGE
Definition at line 947 of file p3m-dipolar.cpp.
References dp3m_mc_time(), DP3M_RTBISECTION_ERROR, P3M_TIME_GRAN, P3M_TUNE_CAO_TOO_LARGE, and P3M_TUNE_FAIL.
Referenced by dp3m_adaptive_tune().
dp3m_mc_time()
static double dp3m_mc_time (int mesh, int cao, double r_cut_iL_min, double r_cut_iL_max, double * _r_cut_iL, double * _alpha_L, double * _accuracy, int timings, bool verbose) static
Get the optimal alpha and the corresponding computation time for a fixed mesh and cao.
The _r_cut_iL is determined via a simple bisection.
Parameters
[in] mesh number of mesh points per coordinate direction (>0).
[in] cao charge assignment order ([0,7]).
[in] r_cut_iL_min lower bound for _r_cut_iL
[in] r_cut_iL_max upper bound for _r_cut_iL
[out] _r_cut_iL cutoff radius for real space electrostatics (>0), rescaled to r_cut_iL = r_cut * box_l_i.
[out] _alpha_L Ewald splitting parameter (0<alpha<1), rescaled to alpha_L = alpha * box_l.
[out] _accuracy accuracy of the actual parameter set.
[in] timings Number of test force calculations
[in] verbose printf output
Returns
The integration time in case of success, otherwise -P3M_TUNE_FAIL, -P3M_TUNE_ACCURACY_TOO_LARGE, -P3M_TUNE_CAO_TOO_LARGE, -P3M_TUNE_ELCTEST, or -P3M_TUNE_CUTOFF_TOO_LARGE
Definition at line 838 of file p3m-dipolar.cpp.
References P3MParameters::accuracy, box_geo, DIPOLAR_MDLC_P3M, dipole, dp3m, dp3m_get_accuracy(), dp3m_mcr_time(), DP3M_RTBISECTION_ERROR, LocalBox< T >::length(), BoxGeometry::length(), local_geo, Dipole_parameters::method, anonymous_namespace{Correlator.cpp}::min(), P3M_RCUT_PREC, P3M_TUNE_ACCURACY_TOO_LARGE, P3M_TUNE_CAO_TOO_LARGE, P3M_TUNE_FAIL, p3m_data_struct_base::params, runtimeErrorMsg, and skin.
Referenced by dp3m_m_time().
dp3m_mcr_time()
static double dp3m_mcr_time (int mesh, int cao, double r_cut_iL, double alpha_L, int timings) static
Get the computation time for some mesh, cao, r_cut and alpha.
Parameters
[in] mesh number of mesh points per coordinate direction (>0).
[in] cao charge assignment order ([0,7]).
[in] r_cut_iL cutoff radius for real space electrostatics (>0), rescaled to r_cut_iL = r_cut * box_l_i.
[in] alpha_L Ewald splitting parameter (0<alpha<1), rescaled to alpha_L = alpha * box_l.
[in] timings Number of test force calculations
Returns
The integration time in case of success, otherwise -P3M_TUNE_FAIL
Definition at line 799 of file p3m-dipolar.cpp.
References P3MParameters::alpha_L, P3MParameters::cao, DIPOLAR_MDLC_P3M, DIPOLAR_P3M, dipole, dp3m, P3MParameters::mesh, Dipole_parameters::method, mpi_bcast_coulomb_params(), P3M_TUNE_FAIL, p3m_data_struct_base::params, P3MParameters::r_cut_iL, Dipole::set_method_local(), and time_force_calc().
Referenced by dp3m_mc_time().
dp3m_real_space_error()
double dp3m_real_space_error (double box_size, double prefac, double r_cut_iL, int n_c_part, double sum_q2, double alpha_L)
Calculate the value of the errors for the REAL part of the force in terms of the splitting parameter alpha of Ewald.
Based on eq. (33) [52].
Please note that in this more refined approach we don't use eq. (37), but eq. (33) which maintains all the powers in alpha.
Definition at line 1316 of file p3m-dipolar.cpp.
References Utils::sqr(), and Utils::sqrt().
Referenced by dp3m_get_accuracy(), and dp3m_rtbisection().
dp3m_rtbisection()
double dp3m_rtbisection (double box_size, double prefac, double r_cut_iL, int n_c_part, double sum_q2, double x1, double x2, double xacc, double tuned_accuracy)
Compute the value of alpha through a bisection method.
Using bisection, find the root of a function "func-tuned_accuracy/sqrt(2.)" known to lie between x1 and x2.
Based on eq. (33) [52].
The root, returned as rtbis, will be refined until its accuracy is \(\pm\) xacc.
Definition at line 1349 of file p3m-dipolar.cpp.
References dp3m_real_space_error(), DP3M_RTBISECTION_ERROR, runtimeErrorMsg, and Utils::sqrt_2().
Referenced by dp3m_get_accuracy().
dp3m_sanity_checks()
bool dp3m_sanity_checks (const Utils::Vector3i & grid)
Sanity checks.
Definition at line 1420 of file p3m-dipolar.cpp.
References box_geo, P3MParameters::cao, cell_structure, CELL_STRUCTURE_DOMDEC, CellStructure::decomposition_type(), dp3m, dp3m_sanity_checks_boxl(), BoxGeometry::length(), P3MParameters::mesh, p3m_data_struct_base::params, BoxGeometry::periodic(), and runtimeErrorMsg.
Referenced by dp3m_init(), and Dipole::nonbonded_sanity_check().
dp3m_sanity_checks_boxl()
bool dp3m_sanity_checks_boxl () static
Checks for correctness for magnetic dipoles in P3M of the cao_cut, necessary when the box length changes.
Definition at line 1396 of file p3m-dipolar.cpp.
References box_geo, P3MParameters::cao_cut, dp3m, LocalBox< T >::length(), BoxGeometry::length(), BoxGeometry::length_half(), local_geo, p3m_data_struct_base::params, and runtimeErrorMsg.
Referenced by dp3m_sanity_checks(), and dp3m_scaleby_box_l().
dp3m_scaleby_box_l()
void dp3m_scaleby_box_l ()
Update alpha and r_cut if box length changed.
Definition at line 1468 of file p3m-dipolar.cpp.
References P3MParameters::alpha, P3MParameters::alpha_L, box_geo, dipole, dp3m, dp3m_calc_influence_function_energy(), dp3m_calc_influence_function_force(), dp3m_init_a_ai_cao_cut(), dp3m_sanity_checks_boxl(), BoxGeometry::length(), BoxGeometry::length_inv(), dp3m_data_struct::local_mesh, p3m_calc_lm_ld_pos(), p3m_data_struct_base::params, Dipole_parameters::prefactor, P3MParameters::r_cut, P3MParameters::r_cut_iL, and runtimeErrorMsg.
Referenced by dp3m_init(), and Dipole::on_boxl_change().
dp3m_set_eps()
void dp3m_set_eps (double eps)
We left the handling of the epsilon, due to portability reasons in the future for the electrical dipoles, or if people want to do electrical dipoles alone using the magnetic code.
Set epsilon parameter.
Currently unused.
Definition at line 299 of file p3m-dipolar.cpp.
References dp3m, P3MParameters::epsilon, mpi_bcast_coulomb_params(), and p3m_data_struct_base::params.
dp3m_set_mesh_offset()
void dp3m_set_mesh_offset (double x, double y, double z)
Set mesh offset.
Parameters
[in] x,y,z Components of mesh_off
Definition at line 281 of file p3m-dipolar.cpp.
References dp3m, P3MParameters::mesh_off, mpi_bcast_coulomb_params(), and p3m_data_struct_base::params.
dp3m_set_params()
void dp3m_set_params (double r_cut, int mesh, int cao, double alpha, double accuracy)
Set custom parameters.
Parameters
[in] r_cut unscaled r_cut_iL for use with fast inline functions only
[in] mesh number of mesh points per coordinate direction (>0).
[in] cao charge assignment order ([0,7]).
[in] alpha unscaled alpha_L for use with fast inline functions only
[in] accuracy accuracy of the actual parameter set.
Definition at line 247 of file p3m-dipolar.cpp.
References P3MParameters::accuracy, P3MParameters::alpha, P3MParameters::alpha_L, box_geo, P3MParameters::cao, DIPOLAR_MDLC_P3M, DIPOLAR_P3M, dipole, dp3m, BoxGeometry::length(), BoxGeometry::length_inv(), P3MParameters::mesh, Dipole_parameters::method, mpi_bcast_coulomb_params(), p3m_data_struct_base::params, P3MParameters::r_cut, P3MParameters::r_cut_iL, and Dipole::set_method_local().
dp3m_set_tune_params()
void dp3m_set_tune_params (double r_cut, int mesh, int cao, double accuracy)
Set initial values for p3m_adaptive_tune()
Parameters
[in] r_cut unscaled r_cut_iL for use with fast inline functions only
[in] mesh number of mesh points per coordinate direction (>0).
[in] cao charge assignment order ([0,7]).
[in] accuracy accuracy of the actual parameter set.
Definition at line 229 of file p3m-dipolar.cpp.
References P3MParameters::accuracy, box_geo, P3MParameters::cao, dp3m, BoxGeometry::length_inv(), P3MParameters::mesh, p3m_data_struct_base::params, P3MParameters::r_cut, and P3MParameters::r_cut_iL.
dp3m_tune_aliasing_sums()
void dp3m_tune_aliasing_sums (int nx, int ny, int nz, int mesh, double mesh_i, int cao, double alpha_L_i, double * alias1, double * alias2) static
Tuning dipolar-P3M.
Definition at line 1280 of file p3m-dipolar.cpp.
References P3M_BRILLOUIN, Utils::pi(), Utils::sinc(), and Utils::sqr().
Referenced by dp3m_k_space_error().
npt_add_virial_magnetic_contribution()
void npt_add_virial_magnetic_contribution (double energy)
Update the NpT virial.
Definition at line 1499 of file p3m-dipolar.cpp.
References npt_add_virial_contribution().
Referenced by dp3m_pair_force().
Variable Documentation
dp3m
dp3m_data_struct dp3m
dipolar P3M parameters.
Definition at line 86 of file p3m-dipolar.cpp.
Referenced by add_mdlc_energy_corrections(), add_mdlc_force_corrections(), Dipole::bcast_params(), calc_surface_term(), Dipole::cutoff(), dp3m_adaptive_tune(), dp3m_average_dipolar_self_energy(), dp3m_calc_influence_function_energy(), dp3m_calc_influence_function_force(), dp3m_calc_kspace_forces(), dp3m_compute_constants_energy_dipolar(), dp3m_count_magnetic_particles(), dp3m_deactivate(), dp3m_dipole_assign(), dp3m_get_accuracy(), dp3m_init(), dp3m_init_a_ai_cao_cut(), dp3m_mc_time(), dp3m_mcr_time(), dp3m_pair_energy(), dp3m_pair_force(), dp3m_sanity_checks(), dp3m_sanity_checks_boxl(), dp3m_scaleby_box_l(), dp3m_set_eps(), dp3m_set_mesh_offset(), dp3m_set_params(), and dp3m_set_tune_params().