ESPResSo: p3m.cpp File Reference
p3m.cpp File Reference
#include "electrostatics_magnetostatics/p3m.hpp"
#include "electrostatics_magnetostatics/common.hpp"
#include "electrostatics_magnetostatics/coulomb.hpp"
#include "electrostatics_magnetostatics/elc.hpp"
#include "electrostatics_magnetostatics/p3m_influence_function.hpp"
#include "Particle.hpp"
#include "ParticleRange.hpp"
#include "cells.hpp"
#include "communication.hpp"
#include "errorhandling.hpp"
#include "fft.hpp"
#include "grid.hpp"
#include "integrate.hpp"
#include "tuning.hpp"
#include "p3m_gpu_error.hpp"
#include <utils/Span.hpp>
#include <utils/Vector.hpp>
#include <utils/constants.hpp>
#include <utils/integral_parameter.hpp>
#include <utils/math/int_pow.hpp>
#include <utils/math/sinc.hpp>
#include <utils/math/sqr.hpp>
#include <boost/mpi/collectives/all_reduce.hpp>
#include <boost/mpi/collectives/reduce.hpp>
#include <boost/mpi/communicator.hpp>
#include <boost/optional.hpp>
#include <boost/range/algorithm/min_element.hpp>
#include <boost/range/numeric.hpp>
#include <algorithm>
#include <array>
#include <cassert>
#include <complex>
#include <cstddef>
#include <cstdio>
#include <functional>
#include <stdexcept>
Namespaces
anonymous_namespace{p3m.cpp}
Functions
void p3m_init ()
Initialize all structures, parameters and arrays needed for the P3M algorithm for charge-charge interactions.
void p3m_set_tune_params (double r_cut, const int mesh[3], int cao, double accuracy)
Set initial values for p3m_adaptive_tune()
void p3m_set_params (double r_cut, const int *mesh, int cao, double alpha, double accuracy)
Set custom parameters.
void p3m_set_mesh_offset (double x, double y, double z)
Set mesh offset.
void p3m_set_eps (double eps)
Set epsilon parameter.
void p3m_charge_assign (const ParticleRange &particles)
Assign the physical charges using the tabulated charge assignment function.
void p3m_assign_charge (double q, const Utils::Vector3d &real_pos, p3m_interpolation_cache &inter_weights)
Assign a single charge into the current charge grid.
void p3m_assign_charge (double q, const Utils::Vector3d &real_pos)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
auto anonymous_namespace{p3m.cpp}::dipole_moment (Particle const &p, BoxGeometry const &box)
auto anonymous_namespace{p3m.cpp}::calc_dipole_moment (boost::mpi::communicator const &comm, const ParticleRange &particles, BoxGeometry const &box)
void anonymous_namespace{p3m.cpp}::add_dipole_correction (Utils::Vector3d const &box_dipole, const ParticleRange &particles)
double anonymous_namespace{p3m.cpp}::dipole_correction_energy (Utils::Vector3d const &box_dipole)
Utils::Vector9d p3m_calc_kspace_pressure_tensor ()
Compute the k-space part of the pressure tensor.
double p3m_calc_kspace_forces (bool force_flag, bool energy_flag, const ParticleRange &particles)
Compute the k-space part of forces and energies for the charge-charge interaction.
static double p3m_get_accuracy (const int mesh[3], int cao, double r_cut_iL, double *_alpha_L, double *_rs_err, double *_ks_err)
Get the minimal error for this combination of parameters.
static double p3m_mcr_time (const int mesh[3], int cao, double r_cut_iL, double alpha_L, int timings)
Get the computation time for some mesh, cao, r_cut and alpha.
static double p3m_mc_time (const int mesh[3], int cao, double r_cut_iL_min, double r_cut_iL_max, double *_r_cut_iL, double *_alpha_L, double *_accuracy, int timings, bool verbose)
Get the optimal alpha and the corresponding computation time for a fixed mesh and cao.
static double p3m_m_time (const int mesh[3], int cao_min, int cao_max, int *_cao, double r_cut_iL_min, double r_cut_iL_max, double *_r_cut_iL, double *_alpha_L, double *_accuracy, int timings, bool verbose)
Get the optimal alpha and the corresponding computation time for a fixed mesh.
int p3m_adaptive_tune (int timings, bool verbose)
Tune P3M parameters to desired accuracy.
void p3m_count_charged_particles ()
Calculate number of charged particles, the sum of the squared charges and the squared sum of the charges.
bool p3m_sanity_checks ()
Sanity checks.
void p3m_scaleby_box_l ()
Update alpha and r_cut if box length changed.
Private Functions
static void p3m_init_a_ai_cao_cut ()
Initialize the (inverse) mesh constant a (ai) and the cutoff for charge assignment cao_cut.
static bool p3m_sanity_checks_system (const Utils::Vector3i &grid)
General sanity checks independent of p3m parameters.
static bool p3m_sanity_checks_boxl ()
Checks for correctness for charges in P3M of the cao_cut, necessary when the box length changes.
static bool p3m_sanity_checks_parameters ()
Checks that necessary parameters are set.
static void p3m_calc_influence_function_force ()
Calculate the optimal influence function of [27].
static void p3m_calc_influence_function_energy ()
Calculate the influence function optimized for the energy and the self energy correction.
P3M tuning helper functions
static double p3m_real_space_error (double prefac, double r_cut_iL, int n_c_part, double sum_q2, double alpha_L)
Calculate the real space contribution to the rms error in the force (as described by Kolafa and Perram).
static double p3m_k_space_error (double prefac, const int mesh[3], int cao, int n_c_part, double sum_q2, double alpha_L)
Calculate the analytic expression of the error estimate for the P3M method in [27] (eq.
static void p3m_tune_aliasing_sums (int nx, int ny, int nz, const int mesh[3], const double mesh_i[3], int cao, double alpha_L_i, double *alias1, double *alias2)
Aliasing sum used by p3m_k_space_error.
Variables
p3m_data_struct p3m
P3M parameters.
Detailed Description
The corresponding header file is p3m.hpp.
Definition in file p3m.cpp.
Function Documentation
p3m_adaptive_tune()
int p3m_adaptive_tune (int timings, bool verbose)
Tune P3M parameters to desired accuracy.
The parameters mesh, cao, r_cut_iL and alpha_L are tuned to obtain the target accuracy (initially stored in accuracy) in optimal time. These parameters are stored in the p3m object.
The function utilizes the analytic expression of the error estimate for the P3M method in [27] (eq. (8.23)) in order to obtain the rms error in the force for a system of N randomly distributed particles in a cubic box. For the real space error the estimate of Kolafa/Perram is used.
Parameter ranges if not given explicit values via p3m_set_tune_params():
mesh is set up such that the number of mesh points is equal to the number of charged particles
cao explores all possible values
alpha_L is tuned for each tuple (r_cut_iL, mesh, cao) and calculated assuming that the error contributions of real and reciprocal space should be equal
After checking if the total error lies below the target accuracy, the time needed for one force calculation (including Verlet list update) is measured via time_force_calc().
The function generates a log of the performed tuning.
The function is based on routines of the program HE_Q.cpp written by M. Deserno.
Parameters
timings Number of test force calculations
verbose printf output
Return values
ES_OK
ES_ERROR
Definition at line 954 of file p3m.cpp.
References P3MParameters::accuracy, P3MParameters::alpha, P3MParameters::alpha_L, box_geo, P3MParameters::cao, coulomb, COULOMB_P3M, P3MParameters::epsilon, ES_ERROR, ES_OK, LocalBox< T >::length(), BoxGeometry::length(), BoxGeometry::length_inv(), local_geo, P3MParameters::mesh, Coulomb_parameters::method, anonymous_namespace{Correlator.cpp}::min(), mpi_bcast_coulomb_params(), mpi_call_all(), node_grid, p3m, p3m_count_charged_particles(), P3M_EPSILON_METALLIC, p3m_m_time(), p3m_sanity_checks_system(), P3M_TIME_GRAN, P3M_TUNE_FAIL, p3m_data_struct_base::params, Coulomb_parameters::prefactor, P3MParameters::r_cut, P3MParameters::r_cut_iL, runtimeErrorMsg, skin, p3m_data_struct::sum_q2, p3m_data_struct::sum_qpart, P3MParameters::tuning, and BoxGeometry::volume().
p3m_assign_charge() [1/2]
void p3m_assign_charge (double q, const Utils::Vector3d & real_pos)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 346 of file p3m.cpp.
References P3MParameters::ai, P3MParameters::cao, p3m_data_struct::local_mesh, p3m, and p3m_data_struct_base::params.
p3m_assign_charge() [2/2]
void p3m_assign_charge (double q, const Utils::Vector3d & real_pos, p3m_interpolation_cache & inter_weights)
Assign a single charge into the current charge grid.
Parameters
[in] q Particle charge
[in] real_pos Particle position in real space
[in] inter_weights Cached interpolation weights to be used.
Definition at line 339 of file p3m.cpp.
References P3MParameters::ai, P3MParameters::cao, p3m_data_struct::local_mesh, p3m, and p3m_data_struct_base::params.
Referenced by anonymous_namespace{elc.cpp}::assign_image_charge(), and ELC_p3m_charge_assign_both().
p3m_calc_influence_function_energy()
void p3m_calc_influence_function_energy () static
Calculate the influence function optimized for the energy and the self energy correction.
Definition at line 591 of file p3m.cpp.
References box_geo, p3m_data_struct::fft, p3m_data_struct_base::g_energy, BoxGeometry::length(), fft_forw_plan::new_mesh, p3m, p3m_data_struct_base::params, fft_data_struct::plan, and fft_forw_plan::start.
Referenced by p3m_scaleby_box_l().
p3m_calc_influence_function_force()
void p3m_calc_influence_function_force () static
Calculate the optimal influence function of [27].
(optimised for force calculations)
Each node calculates only the values for its domain in k-space (see fft.plan[3].mesh and fft.plan[3].start).
See also: [27] eq. 8-22 (p. 275). Note the somewhat different convention for the prefactors, which is described in [11] [12].
Definition at line 583 of file p3m.cpp.
References box_geo, p3m_data_struct::fft, p3m_data_struct_base::g_force, BoxGeometry::length(), fft_forw_plan::new_mesh, p3m, p3m_data_struct_base::params, fft_data_struct::plan, and fft_forw_plan::start.
Referenced by p3m_scaleby_box_l().
p3m_calc_kspace_forces()
double p3m_calc_kspace_forces (bool force_flag, bool energy_flag, const ParticleRange & particles)
Compute the k-space part of forces and energies for the charge-charge interaction.
Definition at line 481 of file p3m.cpp.
References anonymous_namespace{p3m.cpp}::add_dipole_correction(), P3MParameters::alpha, box_geo, anonymous_namespace{p3m.cpp}::calc_dipole_moment(), P3MParameters::cao, comm_cart, coulomb, p3m_data_struct_base::d_op, P3MLocalMesh::dim, anonymous_namespace{p3m.cpp}::dipole_correction_energy(), p3m_data_struct::E_mesh, P3MParameters::epsilon, p3m_data_struct::fft, fft_perform_back(), fft_perform_forw(), p3m_data_struct_base::g_energy, p3m_data_struct_base::g_force, p3m_send_mesh::gather_grid(), p3m_data_struct_base::ks_pnum, BoxGeometry::length_inv(), p3m_data_struct::local_mesh, Utils::make_span(), fft_forw_plan::new_mesh, fft_forw_plan::new_size, ScriptInterface::none, p3m, P3M_EPSILON_METALLIC, p3m_data_struct_base::params, Cells::particles(), Utils::pi(), fft_data_struct::plan, Coulomb_parameters::prefactor, p3m_data_struct::rs_mesh, p3m_data_struct::sm, p3m_send_mesh::spread_grid(), Utils::sqr(), Utils::sqrt_pi_i(), p3m_data_struct::square_sum_q, fft_forw_plan::start, p3m_data_struct::sum_q2, this_node, P3MParameters::tuning, and BoxGeometry::volume().
Referenced by Coulomb::calc_energy_long_range(), and Coulomb::calc_long_range_force().
p3m_calc_kspace_pressure_tensor()
Utils::Vector9d p3m_calc_kspace_pressure_tensor ()
Compute the k-space part of the pressure tensor.
Calculate the long range electrostatics part of the pressure tensor. This is part \(\Pi_{\textrm{dir}, \alpha, \beta}\) eq. (2.6) in [21]. The part \(\Pi_{\textrm{corr}, \alpha, \beta}\) eq. (2.8) is not present here since M is the empty set in our simulations.
Definition at line 421 of file p3m.cpp.
References P3MParameters::alpha, comm_cart, P3MLocalMesh::dim, p3m_data_struct::fft, fft_perform_forw(), p3m_send_mesh::gather_grid(), p3m_data_struct::local_mesh, fft_forw_plan::new_mesh, p3m, p3m_data_struct_base::params, fft_data_struct::plan, p3m_data_struct::rs_mesh, p3m_data_struct::sm, Utils::sqr(), and p3m_data_struct::sum_q2.
Referenced by Coulomb::calc_pressure_long_range().
p3m_charge_assign()
void p3m_charge_assign (const ParticleRange & particles)
Assign the physical charges using the tabulated charge assignment function.
Definition at line 329 of file p3m.cpp.
References P3MParameters::cao, p3m_data_struct::inter_weights, p3m_data_struct::local_mesh, p3m, p3m_data_struct_base::params, Cells::particles(), p3m_interpolation_cache::reset(), p3m_data_struct::rs_mesh, and P3MLocalMesh::size.
Referenced by Coulomb::calc_energy_long_range(), Coulomb::calc_long_range_force(), and Coulomb::calc_pressure_long_range().
p3m_count_charged_particles()
void p3m_count_charged_particles ()
Calculate number of charged particles, the sum of the squared charges and the squared sum of the charges.
Definition at line 1157 of file p3m.cpp.
References cell_structure, comm_cart, CellStructure::local_particles(), p3m, Utils::sqr(), p3m_data_struct::square_sum_q, p3m_data_struct::sum_q2, and p3m_data_struct::sum_qpart.
Referenced by on_observable_calc(), p3m_adaptive_tune(), and p3m_init().
p3m_get_accuracy()
static double p3m_get_accuracy (const int mesh[3], int cao, double r_cut_iL, double * _alpha_L, double * _rs_err, double * _ks_err) static
Get the minimal error for this combination of parameters.
The real space error is tuned such that it contributes half of the total error, and then the Fourier space error is calculated. If an optimal alpha is not found, the value 0.1 is used as fallback.
Parameters
[in] mesh number of mesh points per coordinate direction (>0).
[in] cao charge assignment order ([0,7]).
[in] r_cut_iL cutoff radius for real space electrostatics (>0), rescaled to r_cut_iL = r_cut * box_l_i.
[out] _alpha_L Ewald splitting parameter (0<alpha<1), rescaled to alpha_L = alpha * box_l.
[out] _rs_err real space error
[out] _ks_err Fourier space error
Returns
Error magnitude
Definition at line 612 of file p3m.cpp.
References P3MParameters::accuracy, box_geo, coulomb, COULOMB_P3M_GPU, Utils::Array< T, N >::data(), BoxGeometry::length(), Coulomb_parameters::method, p3m, p3m_k_space_error(), p3m_k_space_error_gpu(), p3m_real_space_error(), p3m_data_struct_base::params, Coulomb_parameters::prefactor, Utils::sqr(), Utils::sqrt(), Utils::sqrt_2(), p3m_data_struct::sum_q2, and p3m_data_struct::sum_qpart.
Referenced by p3m_mc_time().
p3m_init()
void p3m_init ()
Initialize all structures, parameters and arrays needed for the P3M algorithm for charge-charge interactions.
Definition at line 167 of file p3m.cpp.
References p3m_data_struct_base::calc_differential_operator(), P3MParameters::cao, P3MParameters::cao3, comm_cart, coulomb, COULOMB_ELC_P3M, P3MLocalMesh::dim, p3m_data_struct::E_mesh, elc_params, p3m_data_struct::fft, fft_init(), p3m_data_struct_base::ks_pnum, local_geo, p3m_data_struct::local_mesh, P3MLocalMesh::margin, P3MParameters::mesh, P3MParameters::mesh_off, Coulomb_parameters::method, node_grid, p3m, p3m_calc_local_ca_mesh(), p3m_count_charged_particles(), p3m_init_a_ai_cao_cut(), p3m_sanity_checks(), p3m_sanity_checks_parameters(), p3m_scaleby_box_l(), p3m_data_struct_base::params, Coulomb_parameters::prefactor, P3MParameters::r_cut, P3MParameters::r_cut_iL, p3m_send_mesh::resize(), p3m_data_struct::rs_mesh, skin, p3m_data_struct::sm, and ELCParameters::space_layer.
Referenced by Coulomb::init(), and on_coulomb_change().
p3m_init_a_ai_cao_cut()
void p3m_init_a_ai_cao_cut () static
Initialize the (inverse) mesh constant a (ai) and the cutoff for charge assignment cao_cut.
Function called by p3m_init() once and by p3m_scaleby_box_l() whenever the box length changes.
Definition at line 1248 of file p3m.cpp.
References P3MParameters::a, P3MParameters::ai, box_geo, P3MParameters::cao, P3MParameters::cao_cut, BoxGeometry::length_inv(), P3MParameters::mesh, p3m, and p3m_data_struct_base::params.
Referenced by p3m_init(), and p3m_scaleby_box_l().
p3m_k_space_error()
double p3m_k_space_error (double prefac, const int mesh[3], int cao, int n_c_part, double sum_q2, double alpha_L) static
Calculate the analytic expression of the error estimate for the P3M method in [27] (eq.
8-23 p. 275) in order to obtain the rms error in the force for a system of N randomly distributed particles in a cubic box (k-space part).
Parameters
prefac Prefactor of Coulomb interaction.
mesh number of mesh points in one direction.
cao charge assignment order.
n_c_part number of charged particles in the system.
sum_q2 sum of square of charges in the system
alpha_L rescaled Ewald splitting parameter.
Returns
reciprocal (k) space error
Definition at line 1185 of file p3m.cpp.
References box_geo, BoxGeometry::length(), p3m_analytic_cotangent_sum(), p3m_tune_aliasing_sums(), ROUND_ERROR_PREC, Utils::sqr(), and Utils::sqrt().
Referenced by p3m_get_accuracy().
p3m_m_time()
static double p3m_m_time (const int mesh[3], int cao_min, int cao_max, int * _cao, double r_cut_iL_min, double r_cut_iL_max, double * _r_cut_iL, double * _alpha_L, double * _accuracy, int timings, bool verbose) static
Get the optimal alpha and the corresponding computation time for a fixed mesh.
_cao should contain an initial guess, which is then adapted by stepping up and down.
Parameters
[in] mesh number of mesh points per coordinate direction (>0).
[in] cao_min lower bound for _cao
[in] cao_max upper bound for _cao
[in,out] _cao initial guess for the charge assignment order ([0,7]).
[in] r_cut_iL_min lower bound for _r_cut_iL
[in] r_cut_iL_max upper bound for _r_cut_iL
[out] _r_cut_iL cutoff radius for real space electrostatics (>0), rescaled to r_cut_iL = r_cut * box_l_i.
[out] _alpha_L Ewald splitting parameter (0<alpha<1), rescaled to alpha_L = alpha * box_l.
[out] _accuracy accuracy of the actual parameter set.
[in] timings Number of test force calculations
[in] verbose printf output
Returns
The integration time in case of success, otherwise -P3M_TUNE_FAIL or -P3M_TUNE_CAO_TOO_LARGE
Definition at line 821 of file p3m.cpp.
References p3m_mc_time(), P3M_TIME_GRAN, P3M_TUNE_CAO_TOO_LARGE, and P3M_TUNE_FAIL.
Referenced by p3m_adaptive_tune().
p3m_mc_time()
static double p3m_mc_time (const int mesh[3], int cao, double r_cut_iL_min, double r_cut_iL_max, double * _r_cut_iL, double * _alpha_L, double * _accuracy, int timings, bool verbose) static
Get the optimal alpha and the corresponding computation time for a fixed mesh and cao.
The _r_cut_iL is determined via a simple bisection.
Parameters
[in] mesh number of mesh points per coordinate direction (>0).
[in] cao charge assignment order ([0,7]).
[in] r_cut_iL_min lower bound for _r_cut_iL
[in] r_cut_iL_max upper bound for _r_cut_iL
[out] _r_cut_iL cutoff radius for real space electrostatics (>0), rescaled to r_cut_iL = r_cut * box_l_i.
[out] _alpha_L Ewald splitting parameter (0<alpha<1), rescaled to alpha_L = alpha * box_l.
[out] _accuracy accuracy of the actual parameter set.
[in] timings Number of test force calculations
[in] verbose printf output
Returns
The integration time in case of success, otherwise -P3M_TUNE_FAIL, -P3M_TUNE_ACCURACY_TOO_LARGE, -P3M_TUNE_CAO_TOO_LARGE, or -P3M_TUNE_ELCTEST
Definition at line 709 of file p3m.cpp.
References P3MParameters::accuracy, box_geo, coulomb, COULOMB_ELC_P3M, elc_params, ELCParameters::gap_size, LocalBox< T >::length(), BoxGeometry::length(), local_geo, Coulomb_parameters::method, anonymous_namespace{Correlator.cpp}::min(), p3m, p3m_get_accuracy(), p3m_mcr_time(), P3M_RCUT_PREC, P3M_TUNE_ACCURACY_TOO_LARGE, P3M_TUNE_CAO_TOO_LARGE, P3M_TUNE_ELCTEST, P3M_TUNE_FAIL, p3m_data_struct_base::params, and skin.
Referenced by p3m_m_time().
p3m_mcr_time()
static double p3m_mcr_time (const int mesh[3], int cao, double r_cut_iL, double alpha_L, int timings) static
Get the computation time for some mesh, cao, r_cut and alpha.
Parameters
[in] mesh number of mesh points per coordinate direction (>0).
[in] cao charge assignment order ([0,7]).
[in] r_cut_iL cutoff radius for real space electrostatics (>0), rescaled to r_cut_iL = r_cut * box_l_i.
[in] alpha_L Ewald splitting parameter (0<alpha<1), rescaled to alpha_L = alpha * box_l.
[in] timings Number of test force calculations
Returns
The integration time in case of success, otherwise -P3M_TUNE_FAIL
Definition at line 663 of file p3m.cpp.
References P3MParameters::alpha, P3MParameters::alpha_L, box_geo, P3MParameters::cao, coulomb, COULOMB_ELC_P3M, COULOMB_P3M, COULOMB_P3M_GPU, BoxGeometry::length(), BoxGeometry::length_inv(), P3MParameters::mesh, Coulomb_parameters::method, mpi_bcast_coulomb_params(), p3m, P3M_TUNE_FAIL, p3m_data_struct_base::params, P3MParameters::r_cut, P3MParameters::r_cut_iL, and time_force_calc().
Referenced by p3m_mc_time().
p3m_real_space_error()
double p3m_real_space_error (double prefac, double r_cut_iL, int n_c_part, double sum_q2, double alpha_L) static
Calculate the real space contribution to the rms error in the force (as described by Kolafa and Perram).
Parameters
prefac Prefactor of Coulomb interaction.
r_cut_iL rescaled real space cutoff for p3m method.
n_c_part number of charged particles in the system.
sum_q2 sum of square of charges in the system
alpha_L rescaled Ewald splitting parameter.
Returns
real space error
Definition at line 1178 of file p3m.cpp.
References box_geo, BoxGeometry::length(), Utils::sqr(), Utils::sqrt(), and BoxGeometry::volume().
Referenced by p3m_get_accuracy().
p3m_sanity_checks()
bool p3m_sanity_checks ()
Sanity checks.
Definition at line 1330 of file p3m.cpp.
References node_grid, p3m_sanity_checks_boxl(), p3m_sanity_checks_parameters(), and p3m_sanity_checks_system().
Referenced by p3m_init(), and Coulomb::sanity_checks().
p3m_sanity_checks_boxl()
bool p3m_sanity_checks_boxl () static
Checks for correctness for charges in P3M of the cao_cut, necessary when the box length changes.
Definition at line 1256 of file p3m.cpp.
References box_geo, P3MParameters::cao_cut, LocalBox< T >::length(), BoxGeometry::length(), BoxGeometry::length_half(), local_geo, p3m, p3m_data_struct_base::params, and runtimeErrorMsg.
Referenced by p3m_sanity_checks(), and p3m_scaleby_box_l().
p3m_sanity_checks_parameters()
bool p3m_sanity_checks_parameters () static
Checks that necessary parameters are set.
Definition at line 1312 of file p3m.cpp.
References P3MParameters::alpha, P3MParameters::cao, P3MParameters::mesh, p3m, p3m_data_struct_base::params, and runtimeErrorMsg.
Referenced by p3m_init(), and p3m_sanity_checks().
p3m_sanity_checks_system()
bool p3m_sanity_checks_system (const Utils::Vector3i & grid) static
General sanity checks independent of p3m parameters.
Returns
false if ok, true on error.
Definition at line 1282 of file p3m.cpp.
References box_geo, cell_structure, CELL_STRUCTURE_DOMDEC, CellStructure::decomposition_type(), P3MParameters::epsilon, P3MParameters::mesh, p3m, P3M_EPSILON_METALLIC, p3m_data_struct_base::params, BoxGeometry::periodic(), and runtimeErrorMsg.
Referenced by p3m_adaptive_tune(), and p3m_sanity_checks().
p3m_scaleby_box_l()
void p3m_scaleby_box_l ()
Update alpha and r_cut if box length changed.
Definition at line 1345 of file p3m.cpp.
References P3MParameters::alpha, P3MParameters::alpha_L, box_geo, coulomb, BoxGeometry::length(), BoxGeometry::length_inv(), p3m_data_struct::local_mesh, p3m, p3m_calc_influence_function_energy(), p3m_calc_influence_function_force(), p3m_calc_lm_ld_pos(), p3m_init_a_ai_cao_cut(), p3m_sanity_checks_boxl(), p3m_data_struct_base::params, Coulomb_parameters::prefactor, P3MParameters::r_cut, P3MParameters::r_cut_iL, and runtimeErrorMsg.
Referenced by Coulomb::on_boxl_change(), and p3m_init().
p3m_set_eps()
void p3m_set_eps (double eps)
Set epsilon parameter.
Parameters
[in] eps epsilon of the "surrounding dielectric".
Definition at line 290 of file p3m.cpp.
References P3MParameters::epsilon, mpi_bcast_coulomb_params(), p3m, and p3m_data_struct_base::params.
p3m_set_mesh_offset()
void p3m_set_mesh_offset (double x, double y, double z)
Set mesh offset.
Parameters
[in] x,y,z Components of mesh_off
Definition at line 276 of file p3m.cpp.
References P3MParameters::mesh_off, mpi_bcast_coulomb_params(), p3m, and p3m_data_struct_base::params.
p3m_set_params()
void p3m_set_params (double r_cut, const int * mesh, int cao, double alpha, double accuracy)
Set custom parameters.
Parameters
[in] r_cut unscaled r_cut_iL for use with fast inline functions only
[in] mesh number of mesh points per coordinate direction (>0).
[in] cao charge assignment order ([0,7]).
[in] alpha unscaled alpha_L for use with fast inline functions only
[in] accuracy accuracy of the actual parameter set.
Definition at line 239 of file p3m.cpp.
References P3MParameters::accuracy, P3MParameters::alpha, P3MParameters::alpha_L, box_geo, P3MParameters::cao, coulomb, COULOMB_ELC_P3M, COULOMB_P3M, COULOMB_P3M_GPU, BoxGeometry::length(), BoxGeometry::length_inv(), P3MParameters::mesh, Coulomb_parameters::method, mpi_bcast_coulomb_params(), p3m, p3m_data_struct_base::params, P3MParameters::r_cut, and P3MParameters::r_cut_iL.
p3m_set_tune_params()
void p3m_set_tune_params (double r_cut, const int mesh[3], int cao, double accuracy)
Set initial values for p3m_adaptive_tune()
Parameters
[in] r_cut unscaled r_cut_iL for use with fast inline functions only
[in] mesh number of mesh points per coordinate direction (>0).
[in] cao charge assignment order ([0,7]).
[in] accuracy accuracy of the actual parameter set.
Definition at line 216 of file p3m.cpp.
References P3MParameters::accuracy, box_geo, P3MParameters::cao, BoxGeometry::length_inv(), P3MParameters::mesh, p3m, p3m_data_struct_base::params, P3MParameters::r_cut, and P3MParameters::r_cut_iL.
p3m_tune_aliasing_sums()
void p3m_tune_aliasing_sums (int nx, int ny, int nz, const int mesh[3], const double mesh_i[3], int cao, double alpha_L_i, double * alias1, double * alias2) static
Aliasing sum used by p3m_k_space_error.
Definition at line 1218 of file p3m.cpp.
References P3M_BRILLOUIN, Utils::pi(), Utils::sinc(), and Utils::sqr().
Referenced by p3m_k_space_error().
Variable Documentation
p3m
p3m_data_struct p3m
P3M parameters.
Definition at line 74 of file p3m.cpp.
Referenced by anonymous_namespace{p3m.cpp}::add_dipole_correction(), Coulomb::bcast_coulomb_params(), Coulomb::cutoff(), anonymous_namespace{p3m.cpp}::dipole_correction_energy(), ELC_init(), ELC_p3m_charge_assign_both(), ELC_p3m_charge_assign_image(), ELC_P3M_modify_p3m_sums_both(), ELC_P3M_modify_p3m_sums_image(), ELC_P3M_restore_p3m_sums(), ELC_sanity_checks(), ELC_set_params(), on_coulomb_change(), p3m_adaptive_tune(), p3m_add_pair_force(), p3m_assign_charge(), p3m_calc_influence_function_energy(), p3m_calc_influence_function_force(), p3m_calc_kspace_forces(), p3m_calc_kspace_pressure_tensor(), p3m_charge_assign(), p3m_count_charged_particles(), p3m_get_accuracy(), p3m_init(), p3m_init_a_ai_cao_cut(), p3m_mc_time(), p3m_mcr_time(), p3m_pair_energy(), p3m_sanity_checks_boxl(), p3m_sanity_checks_parameters(), p3m_sanity_checks_system(), p3m_scaleby_box_l(), p3m_set_eps(), p3m_set_mesh_offset(), p3m_set_params(), and p3m_set_tune_params().