ESPResSo: p3m_gpu.hpp File Reference
p3m_gpu.hpp File Reference
Functions
void p3m_gpu_init (int cao, const int mesh[3], double alpha)
void p3m_gpu_add_farfield_force ()
The long range part of the P3M algorithm.
Detailed Description
P3M electrostatics on GPU.
Implementation in p3m_gpu_cuda.cu.
Definition in file p3m_gpu.hpp.
Function Documentation
p3m_gpu_add_farfield_force()
void p3m_gpu_add_farfield_force ()
The long range part of the P3M algorithm.
Definition at line 695 of file p3m_gpu_cuda.cu.
References apply_diff_op(), apply_influence_function(), assign_charges(), assign_forces(), p3m_gpu_fft_plans_t::back_plan, P3MGpuData::box, P3MGpuData::charge_mesh, coulomb, cuda_safe_mem, FFT_BACK_FFT, FFT_FORW_FFT, P3MGpuData::force_mesh_x, P3MGpuData::force_mesh_y, P3MGpuData::force_mesh_z, p3m_gpu_fft_plans_t::forw_plan, gpu_get_particle_force_pointer(), gpu_get_particle_pointer(), KERNELCALL, P3MGpuData::mesh, P3MGpuData::mesh_size, P3MGpuData::n_part, p3m_gpu_data, p3m_gpu_fft_plans, Coulomb_parameters::prefactor, and REAL_TYPE.
Referenced by Coulomb::calc_long_range_force().
p3m_gpu_init()
void p3m_gpu_init (int cao, const int mesh[3], double alpha)
Definition at line 561 of file p3m_gpu_cuda.cu.
References P3MGpuData::alpha, p3m_gpu_fft_plans_t::back_plan, block(), P3MGpuData::box, box_geo, P3MGpuData::cao, P3MGpuData::charge_mesh, cuda_safe_mem, espressoSystemInterface, FFT_PLAN_BACK_FLAG, FFT_PLAN_FORW_FLAG, FFT_TYPE_COMPLEX, P3MGpuData::force_mesh_x, P3MGpuData::force_mesh_y, P3MGpuData::force_mesh_z, p3m_gpu_fft_plans_t::forw_plan, P3MGpuData::G_hat, gpu_get_particle_pointer(), P3MGpuData::hi, KERNELCALL, BoxGeometry::length(), P3MGpuData::mesh, P3MGpuData::mesh_size, P3MGpuData::mesh_z_padded, P3MGpuData::n_part, p3m_gpu_data, p3m_gpu_data_initialized, p3m_gpu_fft_plans, P3MGpuData::pos_shift, and REAL_TYPE.
Referenced by on_coulomb_change().