ESPResSo: p3m.hpp File Reference
p3m.hpp File Reference
#include "config.hpp"
#include "electrostatics_magnetostatics/fft.hpp"
#include "electrostatics_magnetostatics/p3m-common.hpp"
#include "electrostatics_magnetostatics/p3m-data_struct.hpp"
#include "electrostatics_magnetostatics/p3m_interpolation.hpp"
#include "electrostatics_magnetostatics/p3m_send_mesh.hpp"
#include "ParticleRange.hpp"
#include <utils/Vector.hpp>
#include <utils/constants.hpp>
#include <utils/math/AS_erfc_part.hpp>
#include <array>
#include <cmath>
Classes
struct p3m_data_struct
Functions
int p3m_adaptive_tune (int timings, bool verbose)
Tune P3M parameters to desired accuracy.
void p3m_init ()
Initialize all structures, parameters and arrays needed for the P3M algorithm for charge-charge interactions.
void p3m_scaleby_box_l ()
Update alpha and r_cut if box length changed.
double p3m_calc_kspace_forces (bool force_flag, bool energy_flag, const ParticleRange &particles)
Compute the k-space part of forces and energies for the charge-charge interaction.
Utils::Vector9d p3m_calc_kspace_pressure_tensor ()
Compute the k-space part of the pressure tensor.
bool p3m_sanity_checks ()
Sanity checks.
void p3m_count_charged_particles ()
Calculate number of charged particles, the sum of the squared charges and the squared sum of the charges.
void p3m_charge_assign (const ParticleRange &particles)
Assign the physical charges using the tabulated charge assignment function.
void p3m_assign_charge (double q, const Utils::Vector3d &real_pos, p3m_interpolation_cache &inter_weights)
Assign a single charge into the current charge grid.
void p3m_assign_charge (double q, const Utils::Vector3d &real_pos)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
void p3m_add_pair_force (double q1q2, Utils::Vector3d const &d, double dist, Utils::Vector3d &force)
Calculate real space contribution of Coulomb pair forces.
void p3m_set_tune_params (double r_cut, const int mesh[3], int cao, double accuracy)
Set initial values for p3m_adaptive_tune()
void p3m_set_params (double r_cut, const int *mesh, int cao, double alpha, double accuracy)
Set custom parameters.
void p3m_set_mesh_offset (double x, double y, double z)
Set mesh offset.
void p3m_set_eps (double eps)
Set epsilon parameter.
double p3m_pair_energy (double chgfac, double dist)
Calculate real space contribution of Coulomb pair energy.
Variables
p3m_data_struct p3m
P3M parameters.
Detailed Description
P3M algorithm for long range Coulomb interaction.
We use a P3M (Particle-Particle Particle-Mesh) method based on the Ewald summation. Details of the used method can be found in [27] and [11] [12].
Further reading: [22], [27], [11], [12], [13], [14], [10].
Implementation in p3m.cpp.
Definition in file p3m.hpp.
Function Documentation
p3m_adaptive_tune()
int p3m_adaptive_tune (int timings, bool verbose)
Tune P3M parameters to desired accuracy.
The parameters mesh, cao, r_cut_iL and alpha_L are tuned to obtain the target accuracy (initially stored in accuracy) in optimal time. These parameters are stored in the p3m object.
The function utilizes the analytic expression of the error estimate for the P3M method in [27] (eq. (8.23)) in order to obtain the rms error in the force for a system of N randomly distributed particles in a cubic box. For the real space error the estimate of Kolafa/Perram is used.
Parameter ranges if not given explicit values via p3m_set_tune_params():
mesh is set up such that the number of mesh points is equal to the number of charged particles
cao explores all possible values
alpha_L is tuned for each tuple (r_cut_iL, mesh, cao) and calculated assuming that the error contributions of real and reciprocal space should be equal
After checking if the total error lies below the target accuracy, the time needed for one force calculation (including Verlet list update) is measured via time_force_calc().
The function generates a log of the performed tuning.
The function is based on routines of the program HE_Q.cpp written by M. Deserno.
Parameters
timings Number of test force calculations
verbose printf output
Return values
ES_OK
ES_ERROR
Definition at line 954 of file p3m.cpp.
References P3MParameters::accuracy, P3MParameters::alpha, P3MParameters::alpha_L, box_geo, P3MParameters::cao, coulomb, COULOMB_P3M, P3MParameters::epsilon, ES_ERROR, ES_OK, LocalBox< T >::length(), BoxGeometry::length(), BoxGeometry::length_inv(), local_geo, P3MParameters::mesh, Coulomb_parameters::method, anonymous_namespace{Correlator.cpp}::min(), mpi_bcast_coulomb_params(), mpi_call_all(), node_grid, p3m, p3m_count_charged_particles(), P3M_EPSILON_METALLIC, p3m_m_time(), p3m_sanity_checks_system(), P3M_TIME_GRAN, P3M_TUNE_FAIL, p3m_data_struct_base::params, Coulomb_parameters::prefactor, P3MParameters::r_cut, P3MParameters::r_cut_iL, runtimeErrorMsg, skin, p3m_data_struct::sum_q2, p3m_data_struct::sum_qpart, P3MParameters::tuning, and BoxGeometry::volume().
p3m_add_pair_force()
void p3m_add_pair_force (double q1q2, Utils::Vector3d const & d, double dist, Utils::Vector3d & force) inline
Calculate real space contribution of Coulomb pair forces.
Definition at line 171 of file p3m.hpp.
References P3MParameters::alpha, Utils::AS_erfc_part(), force, p3m, p3m_data_struct_base::params, P3MParameters::r_cut, and Utils::sqrt_pi_i().
Referenced by Coulomb::central_force(), and ELC_P3M_dielectric_layers_force_contribution().
p3m_assign_charge() [1/2]
void p3m_assign_charge (double q, const Utils::Vector3d & real_pos)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 346 of file p3m.cpp.
References P3MParameters::ai, P3MParameters::cao, p3m_data_struct::local_mesh, p3m, and p3m_data_struct_base::params.
p3m_assign_charge() [2/2]
void p3m_assign_charge (double q, const Utils::Vector3d & real_pos, p3m_interpolation_cache & inter_weights)
Assign a single charge into the current charge grid.
Parameters
[in] q Particle charge
[in] real_pos Particle position in real space
[in] inter_weights Cached interpolation weights to be used.
Definition at line 339 of file p3m.cpp.
References P3MParameters::ai, P3MParameters::cao, p3m_data_struct::local_mesh, p3m, and p3m_data_struct_base::params.
Referenced by anonymous_namespace{elc.cpp}::assign_image_charge(), and ELC_p3m_charge_assign_both().
p3m_calc_kspace_forces()
double p3m_calc_kspace_forces (bool force_flag, bool energy_flag, const ParticleRange & particles)
Compute the k-space part of forces and energies for the charge-charge interaction.
Definition at line 481 of file p3m.cpp.
References anonymous_namespace{p3m.cpp}::add_dipole_correction(), P3MParameters::alpha, box_geo, anonymous_namespace{p3m.cpp}::calc_dipole_moment(), P3MParameters::cao, comm_cart, coulomb, p3m_data_struct_base::d_op, P3MLocalMesh::dim, anonymous_namespace{p3m.cpp}::dipole_correction_energy(), p3m_data_struct::E_mesh, P3MParameters::epsilon, p3m_data_struct::fft, fft_perform_back(), fft_perform_forw(), p3m_data_struct_base::g_energy, p3m_data_struct_base::g_force, p3m_send_mesh::gather_grid(), p3m_data_struct_base::ks_pnum, BoxGeometry::length_inv(), p3m_data_struct::local_mesh, Utils::make_span(), fft_forw_plan::new_mesh, fft_forw_plan::new_size, ScriptInterface::none, p3m, P3M_EPSILON_METALLIC, p3m_data_struct_base::params, Cells::particles(), Utils::pi(), fft_data_struct::plan, Coulomb_parameters::prefactor, p3m_data_struct::rs_mesh, p3m_data_struct::sm, p3m_send_mesh::spread_grid(), Utils::sqr(), Utils::sqrt_pi_i(), p3m_data_struct::square_sum_q, fft_forw_plan::start, p3m_data_struct::sum_q2, this_node, P3MParameters::tuning, and BoxGeometry::volume().
Referenced by Coulomb::calc_energy_long_range(), and Coulomb::calc_long_range_force().
p3m_calc_kspace_pressure_tensor()
Utils::Vector9d p3m_calc_kspace_pressure_tensor ()
Compute the k-space part of the pressure tensor.
Calculate the long range electrostatics part of the pressure tensor. This is part \(\Pi_{\textrm{dir}, \alpha, \beta}\) eq. (2.6) in [21]. The part \(\Pi_{\textrm{corr}, \alpha, \beta}\) eq. (2.8) is not present here since M is the empty set in our simulations.
Definition at line 421 of file p3m.cpp.
References P3MParameters::alpha, comm_cart, P3MLocalMesh::dim, p3m_data_struct::fft, fft_perform_forw(), p3m_send_mesh::gather_grid(), p3m_data_struct::local_mesh, fft_forw_plan::new_mesh, p3m, p3m_data_struct_base::params, fft_data_struct::plan, p3m_data_struct::rs_mesh, p3m_data_struct::sm, Utils::sqr(), and p3m_data_struct::sum_q2.
Referenced by Coulomb::calc_pressure_long_range().
p3m_charge_assign()
void p3m_charge_assign (const ParticleRange & particles)
Assign the physical charges using the tabulated charge assignment function.
Definition at line 329 of file p3m.cpp.
References P3MParameters::cao, p3m_data_struct::inter_weights, p3m_data_struct::local_mesh, p3m, p3m_data_struct_base::params, Cells::particles(), p3m_interpolation_cache::reset(), p3m_data_struct::rs_mesh, and P3MLocalMesh::size.
Referenced by Coulomb::calc_energy_long_range(), Coulomb::calc_long_range_force(), and Coulomb::calc_pressure_long_range().
p3m_count_charged_particles()
void p3m_count_charged_particles ()
Calculate number of charged particles, the sum of the squared charges and the squared sum of the charges.
Definition at line 1157 of file p3m.cpp.
References cell_structure, comm_cart, CellStructure::local_particles(), p3m, Utils::sqr(), p3m_data_struct::square_sum_q, p3m_data_struct::sum_q2, and p3m_data_struct::sum_qpart.
Referenced by on_observable_calc(), p3m_adaptive_tune(), and p3m_init().
p3m_init()
void p3m_init ()
Initialize all structures, parameters and arrays needed for the P3M algorithm for charge-charge interactions.
Definition at line 167 of file p3m.cpp.
References p3m_data_struct_base::calc_differential_operator(), P3MParameters::cao, P3MParameters::cao3, comm_cart, coulomb, COULOMB_ELC_P3M, P3MLocalMesh::dim, p3m_data_struct::E_mesh, elc_params, p3m_data_struct::fft, fft_init(), p3m_data_struct_base::ks_pnum, local_geo, p3m_data_struct::local_mesh, P3MLocalMesh::margin, P3MParameters::mesh, P3MParameters::mesh_off, Coulomb_parameters::method, node_grid, p3m, p3m_calc_local_ca_mesh(), p3m_count_charged_particles(), p3m_init_a_ai_cao_cut(), p3m_sanity_checks(), p3m_sanity_checks_parameters(), p3m_scaleby_box_l(), p3m_data_struct_base::params, Coulomb_parameters::prefactor, P3MParameters::r_cut, P3MParameters::r_cut_iL, p3m_send_mesh::resize(), p3m_data_struct::rs_mesh, skin, p3m_data_struct::sm, and ELCParameters::space_layer.
Referenced by Coulomb::init(), and on_coulomb_change().
p3m_pair_energy()
double p3m_pair_energy (double chgfac, double dist) inline
Calculate real space contribution of Coulomb pair energy.
Definition at line 231 of file p3m.hpp.
References P3MParameters::alpha, Utils::AS_erfc_part(), p3m, p3m_data_struct_base::params, and P3MParameters::r_cut.
Referenced by ELC_P3M_dielectric_layers_energy_contribution(), and Coulomb::pair_energy().
p3m_sanity_checks()
bool p3m_sanity_checks ()
Sanity checks.
Definition at line 1330 of file p3m.cpp.
References node_grid, p3m_sanity_checks_boxl(), p3m_sanity_checks_parameters(), and p3m_sanity_checks_system().
Referenced by p3m_init(), and Coulomb::sanity_checks().
p3m_scaleby_box_l()
void p3m_scaleby_box_l ()
Update alpha and r_cut if box length changed.
Definition at line 1345 of file p3m.cpp.
References P3MParameters::alpha, P3MParameters::alpha_L, box_geo, coulomb, BoxGeometry::length(), BoxGeometry::length_inv(), p3m_data_struct::local_mesh, p3m, p3m_calc_influence_function_energy(), p3m_calc_influence_function_force(), p3m_calc_lm_ld_pos(), p3m_init_a_ai_cao_cut(), p3m_sanity_checks_boxl(), p3m_data_struct_base::params, Coulomb_parameters::prefactor, P3MParameters::r_cut, P3MParameters::r_cut_iL, and runtimeErrorMsg.
Referenced by Coulomb::on_boxl_change(), and p3m_init().
p3m_set_eps()
void p3m_set_eps (double eps)
Set epsilon parameter.
Parameters
[in] eps epsilon of the "surrounding dielectric".
Definition at line 290 of file p3m.cpp.
References P3MParameters::epsilon, mpi_bcast_coulomb_params(), p3m, and p3m_data_struct_base::params.
p3m_set_mesh_offset()
void p3m_set_mesh_offset (double x, double y, double z)
Set mesh offset.
Parameters
[in] x,y,z Components of mesh_off
Definition at line 276 of file p3m.cpp.
References P3MParameters::mesh_off, mpi_bcast_coulomb_params(), p3m, and p3m_data_struct_base::params.
p3m_set_params()
void p3m_set_params (double r_cut, const int * mesh, int cao, double alpha, double accuracy)
Set custom parameters.
Parameters
[in] r_cut unscaled r_cut_iL for use with fast inline functions only
[in] mesh number of mesh points per coordinate direction (>0).
[in] cao charge assignment order ([0,7]).
[in] alpha unscaled alpha_L for use with fast inline functions only
[in] accuracy accuracy of the actual parameter set.
Definition at line 239 of file p3m.cpp.
References P3MParameters::accuracy, P3MParameters::alpha, P3MParameters::alpha_L, box_geo, P3MParameters::cao, coulomb, COULOMB_ELC_P3M, COULOMB_P3M, COULOMB_P3M_GPU, BoxGeometry::length(), BoxGeometry::length_inv(), P3MParameters::mesh, Coulomb_parameters::method, mpi_bcast_coulomb_params(), p3m, p3m_data_struct_base::params, P3MParameters::r_cut, and P3MParameters::r_cut_iL.
p3m_set_tune_params()
void p3m_set_tune_params (double r_cut, const int mesh[3], int cao, double accuracy)
Set initial values for p3m_adaptive_tune()
Parameters
[in] r_cut unscaled r_cut_iL for use with fast inline functions only
[in] mesh number of mesh points per coordinate direction (>0).
[in] cao charge assignment order ([0,7]).
[in] accuracy accuracy of the actual parameter set.
Definition at line 216 of file p3m.cpp.
References P3MParameters::accuracy, box_geo, P3MParameters::cao, BoxGeometry::length_inv(), P3MParameters::mesh, p3m, p3m_data_struct_base::params, P3MParameters::r_cut, and P3MParameters::r_cut_iL.
Variable Documentation
p3m
p3m_data_struct p3m
P3M parameters.
Definition at line 74 of file p3m.cpp.
Referenced by anonymous_namespace{p3m.cpp}::add_dipole_correction(), Coulomb::bcast_coulomb_params(), Coulomb::cutoff(), anonymous_namespace{p3m.cpp}::dipole_correction_energy(), ELC_init(), ELC_p3m_charge_assign_both(), ELC_p3m_charge_assign_image(), ELC_P3M_modify_p3m_sums_both(), ELC_P3M_modify_p3m_sums_image(), ELC_P3M_restore_p3m_sums(), ELC_sanity_checks(), ELC_set_params(), on_coulomb_change(), p3m_adaptive_tune(), p3m_add_pair_force(), p3m_assign_charge(), p3m_calc_influence_function_energy(), p3m_calc_influence_function_force(), p3m_calc_kspace_forces(), p3m_calc_kspace_pressure_tensor(), p3m_charge_assign(), p3m_count_charged_particles(), p3m_get_accuracy(), p3m_init(), p3m_init_a_ai_cao_cut(), p3m_mc_time(), p3m_mcr_time(), p3m_pair_energy(), p3m_sanity_checks_boxl(), p3m_sanity_checks_parameters(), p3m_sanity_checks_system(), p3m_scaleby_box_l(), p3m_set_eps(), p3m_set_mesh_offset(), p3m_set_params(), and p3m_set_tune_params().