ESPResSo: particle_data.hpp File Reference
particle_data.hpp File Reference
#include "config.hpp"
#include "Particle.hpp"
#include "ParticleList.hpp"
#include <utils/Span.hpp>
#include <utils/Vector.hpp>
#include <utils/quaternion.hpp>
#include <cstddef>
#include <vector>
Enumerations
enum { ES_PART_OK = 0, ES_PART_ERROR = -1, ES_PART_CREATED = 1 }
Functions
void clear_particle_node ()
Invalidate particle_node.
const Particle & get_particle_data (int part)
Get particle data.
void prefetch_particle_data (Utils::Span< const int > ids)
Fetch a range of particle into the fetch cache.
void invalidate_fetch_cache ()
Invalidate the fetch cache for get_particle_data.
std::size_t fetch_cache_max_size ()
Return the maximal number of particles that are kept in the fetch cache.
int place_particle (int part, Utils::Vector3d const &p)
Call only on the master node.
void set_particle_v (int part, Utils::Vector3d const &v)
Call only on the master node: set particle velocity.
void set_particle_swimming (int part, ParticleParametersSwimming swim)
Call only on the master node: set particle velocity.
void set_particle_f (int part, const Utils::Vector3d &F)
Call only on the master node: set particle force.
void set_particle_mass (int part, double mass)
Call only on the master node: set particle mass.
void set_particle_rotational_inertia (int part, Utils::Vector3d const &rinertia)
Call only on the master node: set particle rotational inertia.
void set_particle_rotation (int part, int rot)
Call only on the master node: Specifies whether a particle's rotational degrees of freedom are integrated or not.
void rotate_particle (int part, const Utils::Vector3d &axis, double angle)
rotate a particle around an axis
void set_particle_q (int part, double q)
Call only on the master node: set particle charge.
void set_particle_mu_E (int part, Utils::Vector3d const &mu_E)
Call only on the master node: set particle electrophoretic mobility.
Utils::Vector3d get_particle_mu_E (int part)
void set_particle_type (int p_id, int type)
Call only on the master node: set particle type.
void set_particle_mol_id (int part, int mid)
Call only on the master node: set particle's molecule id.
void set_particle_quat (int part, double *quat)
Call only on the master node: set particle orientation using quaternions.
void set_particle_director (int part, const Utils::Vector3d &director)
Call only on the master node: set particle orientation using director.
void set_particle_omega_lab (int part, const Utils::Vector3d &omega_lab)
Call only on the master node: set particle angular velocity from lab frame.
void set_particle_omega_body (int part, const Utils::Vector3d &omega)
Call only on the master node: set particle angular velocity in body frame.
void set_particle_torque_lab (int part, const Utils::Vector3d &torque_lab)
Call only on the master node: set particle torque from lab frame.
void set_particle_dip (int part, Utils::Vector3d const &dip)
Call only on the master node: set particle dipole orientation.
void set_particle_dipm (int part, double dipm)
Call only on the master node: set particle dipole moment (absolute value).
void set_particle_virtual (int part, bool is_virtual)
Call only on the master node: set particle virtual flag.
void set_particle_vs_quat (int part, Utils::Quaternion< double > const &vs_relative_quat)
void set_particle_vs_relative (int part, int vs_relative_to, double vs_distance, Utils::Quaternion< double > const &rel_ori)
void set_particle_gamma (int part, Utils::Vector3d const &gamma)
Call only on the master node: set particle frictional coefficient.
void set_particle_gamma_rot (int part, Utils::Vector3d const &gamma_rot)
void set_particle_ext_torque (int part, const Utils::Vector3d &torque)
Call only on the master node: set particle external torque.
void set_particle_ext_force (int part, const Utils::Vector3d &force)
Call only on the master node: set particle external force.
void set_particle_fix (int part, uint8_t flag)
Call only on the master node: set coordinate axes for which the particles motion is fixed.
void delete_particle_bond (int part, Utils::Span< const int > bond)
Call only on the master node: remove bond from particle.
void delete_particle_bonds (int part)
Call only on the master node: remove all bonds from particle.
void add_particle_bond (int part, Utils::Span< const int > bond)
Call only on the master node: Add bond to particle.
const std::vector< BondView > & get_particle_bonds (int part)
int change_exclusion (int part, int part2, int _delete)
Call only on the master node: change particle constraints.
int remove_particle (int part)
Remove particle with a given identity.
void remove_all_particles ()
Remove all particles.
void mpi_rescale_particles (int dir, double scale)
Rescale all particle positions in direction dir by a factor scale.
void auto_exclusions (int distance)
Automatically add the next <distance> neighbors in each molecule to the exclusion list.
void init_type_map (int type)
int get_random_p_id (int type, int random_index_in_type_map)
Find a particle of given type and return its id.
int number_of_particles_with_type (int type)
void pointer_to_omega_body (Particle const *p, double const *&res)
Utils::Vector3d get_torque_body (const Particle &p)
void pointer_to_quat (Particle const *p, double const *&res)
void pointer_to_q (Particle const *p, double const *&res)
void pointer_to_virtual (Particle const *p, bool const *&res)
void pointer_to_vs_quat (Particle const *p, double const *&res)
void pointer_to_vs_relative (Particle const *p, int const *&res1, double const *&res2, double const *&res3)
void pointer_to_dipm (Particle const *P, double const *&res)
void pointer_to_ext_force (Particle const *p, double const *&res2)
void pointer_to_ext_torque (Particle const *p, double const *&res2)
void pointer_to_fix (Particle const *p, const uint8_t *&res)
void pointer_to_gamma (Particle const *p, double const *&res)
void pointer_to_gamma_rot (Particle const *p, double const *&res)
void pointer_to_swimming (Particle const *p, ParticleParametersSwimming const *&swim)
void pointer_to_rotational_inertia (Particle const *p, double const *&res)
bool particle_exists (int part)
Check if particle exists.
int get_particle_node (int id)
Get the mpi rank which owns the particle with id.
std::vector< int > get_particle_ids ()
Get all particle ids.
int get_maximal_particle_id ()
Get maximal particle id.
int get_n_part ()
Get number of particles.
Detailed Description
Particles and particle lists.
This file contains everything related to particle storage. If you want to add a new property to the particles, it is probably a good idea to modify Particle to give scripts access to that property. You always have to modify two positions: first the print section, where you should add your new data at the end, and second the read section where you have to find a nice and short name for your property to appear in the Python code. Then you just parse your part out of argc and argv.
Implementation in particle_data.cpp.
Definition in file particle_data.hpp.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
ES_PART_OK
ok code for place_particle
ES_PART_ERROR
error code for place_particle
ES_PART_CREATED
ok code for place_particle, particle is new
Definition at line 53 of file particle_data.hpp.
Function Documentation
add_particle_bond()
void add_particle_bond (int part, Utils::Span< const int > bond)
Call only on the master node: Add bond to particle.
Parameters
part identity of principal atom of the bond.
bond field containing the bond type number and the identity of all bond partners (secondary atoms of the bond).
Definition at line 932 of file particle_data.cpp.
References Utils::Span< T >::begin(), Utils::Span< T >::end(), and mpi_send_update_message().
auto_exclusions()
void auto_exclusions (int distance)
Automatically add the next <distance> neighbors in each molecule to the exclusion list.
This uses the bond topology obtained directly from the particles. To easily setup the bonds, all data should be on a single node, therefore the partCfg array is used. With large amounts of particles, you should avoid this function and setup exclusions manually.
Definition at line 1087 of file particle_data.cpp.
References anonymous_namespace{particle_data.cpp}::add_partner(), change_exclusion(), Particle::identity(), and partCfg().
change_exclusion()
int change_exclusion (int part, int part2, int _delete)
Call only on the master node: change particle constraints.
Parameters
part identity of particle for which the exclusion is set.
part2 identity of particle for which the exclusion is set. If -1, delete all exclusions.
_delete if true, do not add the exclusion, rather delete it if found
Return values
ES_OK on success
ES_ERROR on failure (e.g. particles do not exist / did not have exclusion set)
Definition at line 1079 of file particle_data.cpp.
References ES_ERROR, ES_OK, mpi_send_exclusion(), and particle_exists().
Referenced by auto_exclusions().
clear_particle_node()
void clear_particle_node ()
Invalidate particle_node.
This has to be done at the beginning of the integration.
Definition at line 476 of file particle_data.cpp.
References particle_node.
Referenced by mpi_resort_particles(), on_cell_structure_change(), on_observable_calc(), and remove_all_particles().
delete_particle_bond()
void delete_particle_bond (int part, Utils::Span< const int > bond)
Call only on the master node: remove bond from particle.
Parameters
part identity of principal atom of the bond.
bond field containing the bond type number and the identity of all bond partners (secondary atoms of the bond).
Definition at line 923 of file particle_data.cpp.
References Utils::Span< T >::begin(), Utils::Span< T >::end(), and mpi_send_update_message().
delete_particle_bonds()
void delete_particle_bonds (int part)
Call only on the master node: remove all bonds from particle.
Parameters
part identity of principal atom of the bond.
Definition at line 928 of file particle_data.cpp.
References mpi_send_update_message().
fetch_cache_max_size()
std::size_t fetch_cache_max_size ()
Return the maximal number of particles that are kept in the fetch cache.
Definition at line 485 of file particle_data.cpp.
References anonymous_namespace{particle_data.cpp}::particle_fetch_cache.
Referenced by fetch_particles().
get_maximal_particle_id()
int get_maximal_particle_id ()
Get maximal particle id.
Definition at line 1301 of file particle_data.cpp.
References build_particle_node(), and particle_node.
Referenced by ReactionMethods::ReactionAlgorithm::delete_particle().
get_n_part()
int get_n_part ()
Get number of particles.
Definition at line 1311 of file particle_data.cpp.
References build_particle_node(), and particle_node.
Referenced by mdlc_tune_far_cut().
get_particle_bonds()
const std::vector<BondView>& get_particle_bonds (int part)
Definition at line 937 of file particle_data.cpp.
References get_particle_data().
get_particle_data()
const Particle& get_particle_data (int part)
Get particle data.
Parameters
part the identity of the particle to fetch
Returns
Pointer to copy of particle if it exists, nullptr otherwise;
Definition at line 499 of file particle_data.cpp.
References cell_structure, CellStructure::get_local_particle(), get_particle_data_local(), get_particle_node(), Communication::mpiCallbacks(), Communication::Result::one_rank, anonymous_namespace{particle_data.cpp}::particle_fetch_cache, and this_node.
Referenced by calc_re(), calc_rg(), calc_rh(), ClusterAnalysis::Cluster::center_of_mass_subcluster(), PairCriteria::PairCriterion::decide(), fetch_particles(), ClusterAnalysis::Cluster::fractal_dimension(), ReactionMethods::ReactionAlgorithm::generate_new_particle_positions(), get_particle_bonds(), get_particle_mu_E(), IBMTribend::IBMTribend(), IBMTriel::IBMTriel(), ClusterAnalysis::Cluster::longest_distance(), ClusterAnalysis::Cluster::radius_of_gyration_subcluster(), remove_particle(), ClusterAnalysis::ClusterStructure::run_for_bonded_particles(), set_particle_omega_lab(), set_particle_torque_lab(), set_particle_type(), set_particle_vs_quat(), and vs_relate_to().
get_particle_ids()
std::vector<int> get_particle_ids ()
Get all particle ids.
Returns
Sorted ids of all existing particles.
Definition at line 1291 of file particle_data.cpp.
References build_particle_node(), Utils::keys(), and particle_node.
get_particle_mu_E()
Utils::Vector3d get_particle_mu_E (int part)
Definition at line 814 of file particle_data.cpp.
References get_particle_data(), ParticleProperties::mu_E, and Particle::p.
get_particle_node()
int get_particle_node (int id)
Get the mpi rank which owns the particle with id.
Parameters
id Id of the particle
Returns
The MPI rank the particle is on.
Definition at line 459 of file particle_data.cpp.
References build_particle_node(), and particle_node.
Referenced by get_particle_data(), mpi_get_particles(), mpi_send_update_message(), place_particle(), and prefetch_particle_data().
get_random_p_id()
int get_random_p_id (int type, int random_index_in_type_map)
Find a particle of given type and return its id.
Definition at line 1163 of file particle_data.cpp.
References particle_type_map.
Referenced by ReactionMethods::ReactionAlgorithm::generate_new_particle_positions().
get_torque_body()
Utils::Vector3d get_torque_body (const Particle & p) inline
Definition at line 363 of file particle_data.hpp.
References Particle::f, and ParticleForce::torque.
init_type_map()
void init_type_map (int type)
Definition at line 1144 of file particle_data.cpp.
References ParticleProperties::identity, Particle::p, partCfg(), particle_type_map, ParticleProperties::type, and type_list_enable.
Referenced by ReactionMethods::ReactionAlgorithm::add_reaction().
invalidate_fetch_cache()
void invalidate_fetch_cache ()
Invalidate the fetch cache for get_particle_data.
Definition at line 484 of file particle_data.cpp.
References anonymous_namespace{particle_data.cpp}::particle_fetch_cache.
Referenced by on_integration_start(), and on_particle_change().
mpi_rescale_particles()
void mpi_rescale_particles (int dir, double scale)
Rescale all particle positions in direction dir by a factor scale.
Definition at line 1009 of file particle_data.cpp.
References comm_cart, local_rescale_particles(), mpi_call(), mpi_rescale_particles_local(), n_nodes, on_particle_change(), SOME_TAG, and this_node.
Referenced by rescale_boxl().
number_of_particles_with_type()
int number_of_particles_with_type (int type)
Definition at line 1183 of file particle_data.cpp.
References particle_type_map.
Referenced by ReactionMethods::ReactionAlgorithm::all_reactant_particles_exist(), ReactionMethods::ReactionAlgorithm::do_global_mc_move_for_particles_of_type(), and ReactionMethods::ReactionAlgorithm::generate_new_particle_positions().
particle_exists()
bool particle_exists (int part)
Check if particle exists.
Parameters
part Id of the particle
Returns
True iff the particle exists.
Definition at line 1285 of file particle_data.cpp.
References build_particle_node(), and particle_node.
Referenced by change_exclusion(), and place_particle().
place_particle()
int place_particle (int part, Utils::Vector3d const & p)
Call only on the master node.
Move a particle to a new position. If it does not exist, it is created.
Parameters
part the identity of the particle to move
p its new position
Return values
ES_PART_OK if particle existed
ES_PART_CREATED if created
ES_PART_ERROR if id is illegal
Definition at line 695 of file particle_data.cpp.
References ES_PART_CREATED, ES_PART_OK, get_particle_node(), mpi_place_new_particle(), mpi_place_particle(), particle_exists(), particle_node, and pos.
Referenced by ReactionMethods::ReactionAlgorithm::do_global_mc_move_for_particles_of_type().
pointer_to_dipm()
void pointer_to_dipm (Particle const * P, double const *& res)
Definition at line 1232 of file particle_data.cpp.
References ParticleProperties::dipm, Particle::p, and res.
pointer_to_ext_force()
void pointer_to_ext_force (Particle const * p, double const *& res2)
Definition at line 1238 of file particle_data.cpp.
References Utils::Array< T, N >::data(), ParticleProperties::ext_force, and Particle::p.
pointer_to_ext_torque()
void pointer_to_ext_torque (Particle const * p, double const *& res2)
Definition at line 1242 of file particle_data.cpp.
References Utils::Array< T, N >::data(), ParticleProperties::ext_torque, and Particle::p.
pointer_to_fix()
void pointer_to_fix (Particle const * p, const uint8_t *& res)
Definition at line 1246 of file particle_data.cpp.
References ParticleProperties::ext_flag, Particle::p, and res.
pointer_to_gamma()
void pointer_to_gamma (Particle const * p, double const *& res)
Definition at line 1252 of file particle_data.cpp.
References Utils::Array< T, N >::data(), ParticleProperties::gamma, Particle::p, and res.
pointer_to_gamma_rot()
void pointer_to_gamma_rot (Particle const * p, double const *& res)
Definition at line 1261 of file particle_data.cpp.
References Utils::Array< T, N >::data(), ParticleProperties::gamma_rot, Particle::p, and res.
pointer_to_omega_body()
void pointer_to_omega_body (Particle const * p, double const *& res)
Definition at line 1200 of file particle_data.cpp.
References Utils::Array< T, N >::data(), Particle::m, ParticleMomentum::omega, and res.
pointer_to_q()
void pointer_to_q (Particle const * p, double const *& res)
Definition at line 1209 of file particle_data.cpp.
References Particle::p, ParticleProperties::q, and res.
pointer_to_quat()
void pointer_to_quat (Particle const * p, double const *& res)
Definition at line 1204 of file particle_data.cpp.
References Utils::Quaternion< T >::data(), ParticlePosition::quat, Particle::r, and res.
pointer_to_rotational_inertia()
void pointer_to_rotational_inertia (Particle const * p, double const *& res)
Definition at line 1280 of file particle_data.cpp.
References Utils::Array< T, N >::data(), Particle::p, res, and ParticleProperties::rinertia.
pointer_to_swimming()
void pointer_to_swimming (Particle const * p, ParticleParametersSwimming const *& swim)
Definition at line 1273 of file particle_data.cpp.
References Particle::p, and ParticleProperties::swim.
pointer_to_virtual()
void pointer_to_virtual (Particle const * p, bool const *& res)
Definition at line 1212 of file particle_data.cpp.
References ParticleProperties::is_virtual, Particle::p, and res.
pointer_to_vs_quat()
void pointer_to_vs_quat (Particle const * p, double const *& res)
Definition at line 1218 of file particle_data.cpp.
References Utils::Quaternion< T >::data(), Particle::p, ParticleProperties::VirtualSitesRelativeParameters::quat, res, and ParticleProperties::vs_relative.
pointer_to_vs_relative()
void pointer_to_vs_relative (Particle const * p, int const *& res1, double const *& res2, double const *& res3)
Definition at line 1222 of file particle_data.cpp.
References Utils::Quaternion< T >::data(), ParticleProperties::VirtualSitesRelativeParameters::distance, Particle::p, ParticleProperties::VirtualSitesRelativeParameters::rel_orientation, ParticleProperties::VirtualSitesRelativeParameters::to_particle_id, and ParticleProperties::vs_relative.
prefetch_particle_data()
void prefetch_particle_data (Utils::Span< const int > ids)
Fetch a range of particle into the fetch cache.
If the range is larger than the cache size, only the particle that fit into the cache are fetched.
The particles have to exist, an exception it throw if one of the the particles can not be found.
Parameters
ids Ids of the particles that should be fetched.
Definition at line 587 of file particle_data.cpp.
References comm_cart, get_particle_node(), Particle::identity(), mpi_get_particles(), anonymous_namespace{particle_data.cpp}::particle_fetch_cache, and this_node.
Referenced by fetch_particles().
remove_all_particles()
void remove_all_particles ()
Remove all particles.
Definition at line 965 of file particle_data.cpp.
References clear_particle_node(), and mpi_remove_particle().
remove_particle()
int remove_particle (int part)
Remove particle with a given identity.
Also removes all bonds to the particle.
Parameters
part identity of the particle to remove
Return values
ES_OK on success
ES_ERROR if particle does not exist
Definition at line 970 of file particle_data.cpp.
References ES_OK, get_particle_data(), mpi_remove_particle(), particle_node, remove_id_from_map(), and type_list_enable.
Referenced by ReactionMethods::ReactionAlgorithm::delete_particle().
rotate_particle()
void rotate_particle (int part, const Utils::Vector3d & axis, double angle)
rotate a particle around an axis
Parameters
part particle id
axis rotation axis
angle rotation angle
Definition at line 747 of file particle_data.cpp.
References mpi_send_update_message().
set_particle_dip()
void set_particle_dip (int part, Utils::Vector3d const & dip)
Call only on the master node: set particle dipole orientation.
Parameters
part the particle.
dip its new dipole orientation.
Definition at line 757 of file particle_data.cpp.
References convert_dip_to_quat(), Utils::Quaternion< T >::data(), set_particle_dipm(), and set_particle_quat().
set_particle_dipm()
void set_particle_dipm (int part, double dipm)
Call only on the master node: set particle dipole moment (absolute value).
Parameters
part the particle.
dipm its new dipole moment.
Definition at line 753 of file particle_data.cpp.
Referenced by set_particle_dip().
set_particle_director()
void set_particle_director (int part, const Utils::Vector3d & director)
Call only on the master node: set particle orientation using director.
The particle director defines the z-axis in the body-fixed frame.
Parameters
part the particle.
director its new director vector (will be normalized if necessary)
Definition at line 849 of file particle_data.cpp.
References Utils::convert_director_to_quaternion(), Utils::Quaternion< T >::data(), Utils::Vector< T, N >::normalized(), and set_particle_quat().
set_particle_ext_force()
void set_particle_ext_force (int part, const Utils::Vector3d & force)
Call only on the master node: set particle external force.
Parameters
part the particle.
force new value for ext_force.
Definition at line 912 of file particle_data.cpp.
References force.
set_particle_ext_torque()
void set_particle_ext_torque (int part, const Utils::Vector3d & torque)
Call only on the master node: set particle external torque.
Parameters
part the particle.
torque new value for ext_torque.
Definition at line 906 of file particle_data.cpp.
References ParticleProperties::ext_torque, mpi_update_particle_property(), and torque.
set_particle_f()
void set_particle_f (int part, const Utils::Vector3d & F)
Call only on the master node: set particle force.
Parameters
part the particle.
F its new force.
Definition at line 718 of file particle_data.cpp.
References ParticleForce::f, Particle::f, f, and mpi_update_particle().
set_particle_fix()
void set_particle_fix (int part, uint8_t flag)
Call only on the master node: set coordinate axes for which the particles motion is fixed.
Parameters
part the particle.
flag new value for flagged coordinate axes to be fixed
Definition at line 917 of file particle_data.cpp.
set_particle_gamma()
void set_particle_gamma (int part, Utils::Vector3d const & gamma)
Call only on the master node: set particle frictional coefficient.
Parameters
part the particle.
gamma its new frictional coefficient.
Definition at line 883 of file particle_data.cpp.
References Utils::gamma().
set_particle_gamma_rot()
void set_particle_gamma_rot (int part, Utils::Vector3d const & gamma_rot)
Definition at line 896 of file particle_data.cpp.
set_particle_mass()
void set_particle_mass (int part, double mass)
Call only on the master node: set particle mass.
Parameters
part the particle.
mass its new mass.
Definition at line 724 of file particle_data.cpp.
set_particle_mol_id()
void set_particle_mol_id (int part, int mid)
Call only on the master node: set particle's molecule id.
Parameters
part the particle.
mid its new mol id.
Definition at line 838 of file particle_data.cpp.
set_particle_mu_E()
void set_particle_mu_E (int part, Utils::Vector3d const & mu_E)
Call only on the master node: set particle electrophoretic mobility.
Parameters
part the particle.
mu_E its new mobility.
Definition at line 809 of file particle_data.cpp.
set_particle_omega_body()
void set_particle_omega_body (int part, const Utils::Vector3d & omega)
Call only on the master node: set particle angular velocity in body frame.
Parameters
part the particle.
omega its new angular velocity.
Definition at line 863 of file particle_data.cpp.
References Particle::m, mpi_update_particle(), and ParticleMomentum::omega.
set_particle_omega_lab()
void set_particle_omega_lab (int part, const Utils::Vector3d & omega_lab)
Call only on the master node: set particle angular velocity from lab frame.
Parameters
part the particle.
omega_lab its new angular velocity.
Definition at line 855 of file particle_data.cpp.
References convert_vector_space_to_body(), get_particle_data(), Particle::m, mpi_update_particle(), and ParticleMomentum::omega.
set_particle_q()
void set_particle_q (int part, double q)
Call only on the master node: set particle charge.
Parameters
part the particle.
q its new charge.
Definition at line 798 of file particle_data.cpp.
Referenced by ReactionMethods::ReactionAlgorithm::restore_properties().
set_particle_quat()
void set_particle_quat (int part, double * quat)
Call only on the master node: set particle orientation using quaternions.
Parameters
part the particle.
quat its new value for quaternions.
Definition at line 843 of file particle_data.cpp.
References ParticlePosition::quat.
Referenced by set_particle_dip(), and set_particle_director().
set_particle_rotation()
void set_particle_rotation (int part, int rot)
Call only on the master node: Specifies whether a particle's rotational degrees of freedom are integrated or not.
If set to zero, the content of the torque and omega variables are meaningless
Parameters
part the particle.
rot the degrees of freedom flag.
Definition at line 742 of file particle_data.cpp.
set_particle_rotational_inertia()
void set_particle_rotational_inertia (int part, Utils::Vector3d const & rinertia)
Call only on the master node: set particle rotational inertia.
Parameters
part the particle.
rinertia its new inertia.
Definition at line 732 of file particle_data.cpp.
set_particle_swimming()
void set_particle_swimming (int part, ParticleParametersSwimming swim)
Call only on the master node: set particle velocity.
Parameters
part the particle.
swim struct containing swimming parameters
Definition at line 712 of file particle_data.cpp.
References mpi_update_particle_property(), and ParticleProperties::swim.
set_particle_torque_lab()
void set_particle_torque_lab (int part, const Utils::Vector3d & torque_lab)
Call only on the master node: set particle torque from lab frame.
Parameters
part the particle.
torque_lab its new torque.
Definition at line 868 of file particle_data.cpp.
References convert_vector_space_to_body(), Particle::f, get_particle_data(), mpi_update_particle(), and ParticleForce::torque.
set_particle_type()
void set_particle_type (int p_id, int type)
Call only on the master node: set particle type.
Parameters
p_id the particle.
type its new type.
Definition at line 820 of file particle_data.cpp.
References add_id_to_type_map(), get_particle_data(), make_particle_type_exist(), remove_id_from_map(), and type_list_enable.
Referenced by ReactionMethods::ReactionAlgorithm::generic_oneway_reaction(), and ReactionMethods::ReactionAlgorithm::restore_properties().
set_particle_v()
void set_particle_v (int part, Utils::Vector3d const & v)
Call only on the master node: set particle velocity.
Parameters
part the particle.
v its new velocity.
Definition at line 706 of file particle_data.cpp.
References Particle::m, mpi_update_particle(), and ParticleMomentum::v.
set_particle_virtual()
void set_particle_virtual (int part, bool is_virtual)
Call only on the master node: set particle virtual flag.
Parameters
part the particle.
is_virtual new is_virtual flag.
Definition at line 768 of file particle_data.cpp.
Referenced by vs_relate_to().
set_particle_vs_quat()
void set_particle_vs_quat (int part, Utils::Quaternion< double > const & vs_relative_quat)
Definition at line 775 of file particle_data.cpp.
References get_particle_data(), mpi_update_particle_property(), Particle::p, ParticleProperties::VirtualSitesRelativeParameters::quat, and ParticleProperties::vs_relative.
set_particle_vs_relative()
void set_particle_vs_relative (int part, int vs_relative_to, double vs_distance, Utils::Quaternion< double > const & rel_ori)
Definition at line 785 of file particle_data.cpp.
References ParticleProperties::VirtualSitesRelativeParameters::distance, mpi_update_particle_property(), ParticleProperties::VirtualSitesRelativeParameters::rel_orientation, ParticleProperties::VirtualSitesRelativeParameters::to_particle_id, and ParticleProperties::vs_relative.
Referenced by vs_relate_to().