ESPResSo: particle_data.cpp File Reference
particle_data.cpp File Reference
#include "particle_data.hpp"
#include "Particle.hpp"
#include "cells.hpp"
#include "communication.hpp"
#include "event.hpp"
#include "grid.hpp"
#include "nonbonded_interactions/nonbonded_interaction_data.hpp"
#include "partCfg_global.hpp"
#include "rotation.hpp"
#include <string>
#include <utils/Cache.hpp>
#include <utils/constants.hpp>
#include <utils/keys.hpp>
#include <utils/mpi/gatherv.hpp>
#include <boost/algorithm/cxx11/copy_if.hpp>
#include <boost/mpi/collectives/gather.hpp>
#include <boost/mpi/collectives/scatter.hpp>
#include <boost/optional.hpp>
#include <boost/range/algorithm.hpp>
#include <boost/range/numeric.hpp>
#include <boost/serialization/variant.hpp>
#include <boost/serialization/vector.hpp>
#include <boost/variant.hpp>
#include <algorithm>
#include <cassert>
#include <cmath>
#include <cstddef>
#include <stdexcept>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <vector>
Namespaces
anonymous_namespace{particle_data.cpp}
Typedefs
template<typename T , T ParticleProperties::* m>
using anonymous_namespace{particle_data.cpp}::UpdateProperty = UpdateParticle< ParticleProperties, &Particle::p, T, m >
template<typename T , T ParticlePosition ::* m>
using anonymous_namespace{particle_data.cpp}::UpdatePosition = UpdateParticle< ParticlePosition, &Particle::r, T, m >
template<typename T , T ParticleMomentum ::* m>
using anonymous_namespace{particle_data.cpp}::UpdateMomentum = UpdateParticle< ParticleMomentum, &Particle::m, T, m >
template<typename T , T ParticleForce ::* m>
using anonymous_namespace{particle_data.cpp}::UpdateForce = UpdateParticle< ParticleForce, &Particle::f, T, m >
using anonymous_namespace{particle_data.cpp}::Prop = ParticleProperties
using anonymous_namespace{particle_data.cpp}::UpdatePropertyMessage = boost::variant< UpdateProperty< int, &Prop::type >, UpdateProperty< int, &Prop::mol_id >, UpdateProperty< double, &Prop::mass >, UpdateProperty< Utils::Vector3d, &Prop::rinertia >, UpdateProperty< uint8_t, &Prop::rotation >, UpdateProperty< double, &Prop::q >, UpdateProperty< Utils::Vector3d, &Prop::mu_E >, UpdateProperty< ParticleParametersSwimming, &Prop::swim >, UpdateProperty< double, &Prop::dipm >, UpdateProperty< bool, &Prop::is_virtual >, UpdateProperty< ParticleProperties::VirtualSitesRelativeParameters, &Prop::vs_relative >, UpdateProperty< Utils::Vector3d, &Prop::gamma >, UpdateProperty< Utils::Vector3d, &Prop::gamma_rot >, UpdateProperty< uint8_t, &Prop::ext_flag >, UpdateProperty< Utils::Vector3d, &Prop::ext_force >, UpdateProperty< Utils::Vector3d, &Prop::ext_torque > >
using anonymous_namespace{particle_data.cpp}::UpdatePositionMessage = boost::variant< UpdatePosition< Utils::Vector3d, &ParticlePosition::p >, UpdatePosition< Utils::Quaternion< double >, &ParticlePosition::quat > >
using anonymous_namespace{particle_data.cpp}::UpdateMomentumMessage = boost::variant< UpdateMomentum< Utils::Vector3d, &ParticleMomentum::v >, UpdateMomentum< Utils::Vector3d, &ParticleMomentum::omega > >
using anonymous_namespace{particle_data.cpp}::UpdateForceMessage = boost::variant< UpdateForce< Utils::Vector3d, &ParticleForce::f >, UpdateForce< Utils::Vector3d, &ParticleForce::torque > >
using anonymous_namespace{particle_data.cpp}::UpdateBondMessage = boost::variant< RemoveBond, RemoveBonds, AddBond >
using anonymous_namespace{particle_data.cpp}::UpdateMessage = boost::variant< UpdatePropertyMessage, UpdatePositionMessage, UpdateMomentumMessage, UpdateForceMessage, UpdateBondMessage, UpdateOrientation >
Top-level message.
template<typename S , S Particle::* s>
using anonymous_namespace{particle_data.cpp}::message_type_t = typename message_type< S, s >::type
Functions
void mpi_send_update_message_local (int node, int id)
void mpi_send_update_message (int id, const UpdateMessage &msg)
Send a particle update message.
template<typename S , S Particle::* s, typename T , T S::* m>
void mpi_update_particle (int id, const T &value)
template<typename T , T ParticleProperties::* m>
void mpi_update_particle_property (int id, const T &value)
void remove_id_from_map (int part_id, int type)
void add_id_to_type_map (int part_id, int type)
void delete_exclusion (Particle *part, int part2)
Remove exclusion from particle if possible.
void add_exclusion (Particle *part, int part2)
Insert an exclusion if not already set.
void auto_exclusion (int distance)
void mpi_who_has_local (int, int)
void mpi_who_has ()
void build_particle_node ()
Rebuild the particle index.
int get_particle_node (int id)
Get the mpi rank which owns the particle with id.
void clear_particle_node ()
Invalidate particle_node.
void invalidate_fetch_cache ()
Invalidate the fetch cache for get_particle_data.
std::size_t fetch_cache_max_size ()
Return the maximal number of particles that are kept in the fetch cache.
boost::optional< const Particle & > get_particle_data_local (int id)
const Particle & get_particle_data (int part)
Get particle data.
void mpi_get_particles_local (int, int)
std::vector< Particle > mpi_get_particles (Utils::Span< const int > ids)
Get multiple particles at once.
void prefetch_particle_data (Utils::Span< const int > in_ids)
Fetch a range of particle into the fetch cache.
Particle * local_place_particle (int id, const Utils::Vector3d &pos, int _new)
Move a particle to a new position.
boost::optional< int > mpi_place_new_particle_local (int p_id, Utils::Vector3d const &pos)
int mpi_place_new_particle (int p_id, const Utils::Vector3d &pos)
Create particle at a position on a node.
void mpi_place_particle_local (int pnode, int p_id)
void mpi_place_particle (int node, int p_id, const Utils::Vector3d &pos)
Move particle to a position on a node.
int place_particle (int p_id, Utils::Vector3d const &pos)
Call only on the master node.
void set_particle_v (int part, Utils::Vector3d const &v)
Call only on the master node: set particle velocity.
void set_particle_swimming (int part, ParticleParametersSwimming swim)
Call only on the master node: set particle velocity.
void set_particle_f (int part, const Utils::Vector3d &f)
Call only on the master node: set particle force.
void set_particle_mass (int part, double mass)
Call only on the master node: set particle mass.
void set_particle_rotational_inertia (int part, Utils::Vector3d const &rinertia)
Call only on the master node: set particle rotational inertia.
void set_particle_rotation (int part, int rot)
Call only on the master node: Specifies whether a particle's rotational degrees of freedom are integrated or not.
void rotate_particle (int part, const Utils::Vector3d &axis, double angle)
rotate a particle around an axis
void set_particle_dipm (int part, double dipm)
Call only on the master node: set particle dipole moment (absolute value).
void set_particle_dip (int part, Utils::Vector3d const &dip)
Call only on the master node: set particle dipole orientation.
void set_particle_virtual (int part, bool is_virtual)
Call only on the master node: set particle virtual flag.
void set_particle_vs_quat (int part, Utils::Quaternion< double > const &vs_relative_quat)
void set_particle_vs_relative (int part, int vs_relative_to, double vs_distance, Utils::Quaternion< double > const &rel_ori)
void set_particle_q (int part, double q)
Call only on the master node: set particle charge.
void set_particle_mu_E (int part, Utils::Vector3d const &mu_E)
Call only on the master node: set particle electrophoretic mobility.
Utils::Vector3d get_particle_mu_E (int part)
void set_particle_type (int p_id, int type)
Call only on the master node: set particle type.
void set_particle_mol_id (int part, int mid)
Call only on the master node: set particle's molecule id.
void set_particle_quat (int part, double *const quat)
Call only on the master node: set particle orientation using quaternions.
void set_particle_director (int part, const Utils::Vector3d &director)
Call only on the master node: set particle orientation using director.
void set_particle_omega_lab (int part, const Utils::Vector3d &omega_lab)
Call only on the master node: set particle angular velocity from lab frame.
void set_particle_omega_body (int part, const Utils::Vector3d &omega)
Call only on the master node: set particle angular velocity in body frame.
void set_particle_torque_lab (int part, const Utils::Vector3d &torque_lab)
Call only on the master node: set particle torque from lab frame.
void set_particle_gamma (int part, Utils::Vector3d const &gamma)
Call only on the master node: set particle frictional coefficient.
void set_particle_gamma_rot (int part, Utils::Vector3d const &gamma_rot)
void set_particle_ext_torque (int part, const Utils::Vector3d &torque)
Call only on the master node: set particle external torque.
void set_particle_ext_force (int part, const Utils::Vector3d &force)
Call only on the master node: set particle external force.
void set_particle_fix (int part, uint8_t flag)
Call only on the master node: set coordinate axes for which the particles motion is fixed.
void delete_particle_bond (int part, Utils::Span< const int > bond)
Call only on the master node: remove bond from particle.
void delete_particle_bonds (int part)
Call only on the master node: remove all bonds from particle.
void add_particle_bond (int part, Utils::Span< const int > bond)
Call only on the master node: Add bond to particle.
const std::vector< BondView > & get_particle_bonds (int part)
void mpi_remove_particle_local (int, int part)
void mpi_remove_particle (int, int p_id)
Remove a particle.
void remove_all_particles ()
Remove all particles.
int remove_particle (int p_id)
Remove particle with a given identity.
void local_rescale_particles (int dir, double scale)
Locally rescale all particles on current node.
void mpi_rescale_particles_local (int, int dir)
void mpi_rescale_particles (int dir, double scale)
Rescale all particle positions in direction dir by a factor scale.
void local_change_exclusion (int part1, int part2, int _delete)
Locally add an exclusion to a particle.
void anonymous_namespace{particle_data.cpp}::add_partner (std::vector< int > &il, int i, int j, int distance)
void mpi_send_exclusion_local (int part1, int part2, int _delete)
void mpi_send_exclusion (int part1, int part2, int _delete)
Send exclusions.
int change_exclusion (int part1, int part2, int _delete)
Call only on the master node: change particle constraints.
void auto_exclusions (int distance)
Automatically add the next <distance> neighbors in each molecule to the exclusion list.
void init_type_map (int type)
int get_random_p_id (int type, int random_index_in_type_map)
Find a particle of given type and return its id.
int number_of_particles_with_type (int type)
void pointer_to_omega_body (Particle const *p, double const *&res)
void pointer_to_quat (Particle const *p, double const *&res)
void pointer_to_q (Particle const *p, double const *&res)
void pointer_to_virtual (Particle const *p, bool const *&res)
void pointer_to_vs_quat (Particle const *p, double const *&res)
void pointer_to_vs_relative (Particle const *p, int const *&res1, double const *&res2, double const *&res3)
void pointer_to_dipm (Particle const *p, double const *&res)
void pointer_to_ext_force (Particle const *p, double const *&res2)
void pointer_to_ext_torque (Particle const *p, double const *&res2)
void pointer_to_fix (Particle const *p, const uint8_t *&res)
void pointer_to_gamma (Particle const *p, double const *&res)
void pointer_to_gamma_rot (Particle const *p, double const *&res)
void pointer_to_swimming (Particle const *p, ParticleParametersSwimming const *&swim)
void pointer_to_rotational_inertia (Particle const *p, double const *&res)
bool particle_exists (int part_id)
Check if particle exists.
std::vector< int > get_particle_ids ()
Get all particle ids.
int get_maximal_particle_id ()
Get maximal particle id.
int get_n_part ()
Get number of particles.
Variables
bool type_list_enable
std::unordered_map< int, std::unordered_set< int > > particle_type_map {}
std::unordered_map< int, int > particle_node
id -> rank
const std::size_t anonymous_namespace{particle_data.cpp}::max_cache_size = (100ul * 1048576ul) / sizeof(Particle)
Utils::Cache< int, Particle > anonymous_namespace{particle_data.cpp}::particle_fetch_cache (max_cache_size)
Detailed Description
Particles and particle lists.
The corresponding header file is particle_data.hpp.
Definition in file particle_data.cpp.
Function Documentation
add_exclusion()
void add_exclusion (Particle * part, int part2)
Insert an exclusion if not already set.
Definition at line 32 of file exclusions.cpp.
References Utils::contains(), and Particle::exclusions().
Referenced by local_change_exclusion().
add_id_to_type_map()
void add_id_to_type_map (int part_id, int type)
Definition at line 1177 of file particle_data.cpp.
References particle_type_map.
Referenced by set_particle_type().
add_particle_bond()
void add_particle_bond (int part, Utils::Span< const int > bond)
Call only on the master node: Add bond to particle.
Parameters
part identity of principal atom of the bond.
bond field containing the bond type number and the identity of all bond partners (secondary atoms of the bond).
Definition at line 932 of file particle_data.cpp.
References Utils::Span< T >::begin(), Utils::Span< T >::end(), and mpi_send_update_message().
auto_exclusion()
void auto_exclusion (int distance)
auto_exclusions()
void auto_exclusions (int distance)
Automatically add the next <distance> neighbors in each molecule to the exclusion list.
This uses the bond topology obtained directly from the particles. To easily setup the bonds, all data should be on a single node, therefore the partCfg array is used. With large amounts of particles, you should avoid this function and setup exclusions manually.
Definition at line 1087 of file particle_data.cpp.
References anonymous_namespace{particle_data.cpp}::add_partner(), change_exclusion(), Particle::identity(), and partCfg().
build_particle_node()
void build_particle_node ()
Rebuild the particle index.
Definition at line 454 of file particle_data.cpp.
References mpi_who_has().
Referenced by get_maximal_particle_id(), get_n_part(), get_particle_ids(), get_particle_node(), and particle_exists().
change_exclusion()
int change_exclusion (int part, int part2, int _delete)
Call only on the master node: change particle constraints.
Parameters
part identity of particle for which the exclusion is set.
part2 identity of particle for which the exclusion is set. If -1, delete all exclusions.
_delete if true, do not add the exclusion, rather delete it if found
Return values
ES_OK on success
ES_ERROR on failure (e.g. particles do not exist / did not have exclusion set)
Definition at line 1079 of file particle_data.cpp.
References ES_ERROR, ES_OK, mpi_send_exclusion(), and particle_exists().
Referenced by auto_exclusions().
clear_particle_node()
void clear_particle_node ()
Invalidate particle_node.
This has to be done at the beginning of the integration.
Definition at line 476 of file particle_data.cpp.
References particle_node.
Referenced by mpi_resort_particles(), on_cell_structure_change(), on_observable_calc(), and remove_all_particles().
delete_exclusion()
void delete_exclusion (Particle * part, int part2)
Remove exclusion from particle if possible.
Definition at line 39 of file exclusions.cpp.
References Particle::exclusions(), and LBBoundaries::remove().
Referenced by local_change_exclusion().
delete_particle_bond()
void delete_particle_bond (int part, Utils::Span< const int > bond)
Call only on the master node: remove bond from particle.
Parameters
part identity of principal atom of the bond.
bond field containing the bond type number and the identity of all bond partners (secondary atoms of the bond).
Definition at line 923 of file particle_data.cpp.
References Utils::Span< T >::begin(), Utils::Span< T >::end(), and mpi_send_update_message().
delete_particle_bonds()
void delete_particle_bonds (int part)
Call only on the master node: remove all bonds from particle.
Parameters
part identity of principal atom of the bond.
Definition at line 928 of file particle_data.cpp.
References mpi_send_update_message().
fetch_cache_max_size()
std::size_t fetch_cache_max_size ()
Return the maximal number of particles that are kept in the fetch cache.
Definition at line 485 of file particle_data.cpp.
References anonymous_namespace{particle_data.cpp}::particle_fetch_cache.
Referenced by fetch_particles().
get_maximal_particle_id()
int get_maximal_particle_id ()
Get maximal particle id.
Definition at line 1301 of file particle_data.cpp.
References build_particle_node(), and particle_node.
Referenced by ReactionMethods::ReactionAlgorithm::delete_particle().
get_n_part()
int get_n_part ()
Get number of particles.
Definition at line 1311 of file particle_data.cpp.
References build_particle_node(), and particle_node.
Referenced by mdlc_tune_far_cut().
get_particle_bonds()
const std::vector<BondView>& get_particle_bonds (int part)
Definition at line 937 of file particle_data.cpp.
References get_particle_data().
get_particle_data()
const Particle& get_particle_data (int part)
Get particle data.
Parameters
part the identity of the particle to fetch
Returns
Pointer to copy of particle if it exists, nullptr otherwise;
Definition at line 499 of file particle_data.cpp.
References cell_structure, CellStructure::get_local_particle(), get_particle_data_local(), get_particle_node(), Communication::mpiCallbacks(), Communication::Result::one_rank, anonymous_namespace{particle_data.cpp}::particle_fetch_cache, and this_node.
Referenced by calc_re(), calc_rg(), calc_rh(), ClusterAnalysis::Cluster::center_of_mass_subcluster(), PairCriteria::PairCriterion::decide(), fetch_particles(), ClusterAnalysis::Cluster::fractal_dimension(), ReactionMethods::ReactionAlgorithm::generate_new_particle_positions(), get_particle_bonds(), get_particle_mu_E(), IBMTribend::IBMTribend(), IBMTriel::IBMTriel(), ClusterAnalysis::Cluster::longest_distance(), ClusterAnalysis::Cluster::radius_of_gyration_subcluster(), remove_particle(), ClusterAnalysis::ClusterStructure::run_for_bonded_particles(), set_particle_omega_lab(), set_particle_torque_lab(), set_particle_type(), set_particle_vs_quat(), and vs_relate_to().
get_particle_data_local()
boost::optional<const Particle &> get_particle_data_local (int id)
Definition at line 487 of file particle_data.cpp.
References cell_structure, CellStructure::get_local_particle(), ParticleLocal::ghost, and Particle::l.
Referenced by get_particle_data().
get_particle_ids()
std::vector<int> get_particle_ids ()
Get all particle ids.
Returns
Sorted ids of all existing particles.
Definition at line 1291 of file particle_data.cpp.
References build_particle_node(), Utils::keys(), and particle_node.
get_particle_mu_E()
Utils::Vector3d get_particle_mu_E (int part)
Definition at line 814 of file particle_data.cpp.
References get_particle_data(), ParticleProperties::mu_E, and Particle::p.
get_particle_node()
int get_particle_node (int id)
Get the mpi rank which owns the particle with id.
Parameters
id Id of the particle
Returns
The MPI rank the particle is on.
Definition at line 459 of file particle_data.cpp.
References build_particle_node(), and particle_node.
Referenced by get_particle_data(), mpi_get_particles(), mpi_send_update_message(), place_particle(), and prefetch_particle_data().
get_random_p_id()
int get_random_p_id (int type, int random_index_in_type_map)
Find a particle of given type and return its id.
Definition at line 1163 of file particle_data.cpp.
References particle_type_map.
Referenced by ReactionMethods::ReactionAlgorithm::generate_new_particle_positions().
init_type_map()
void init_type_map (int type)
Definition at line 1144 of file particle_data.cpp.
References ParticleProperties::identity, Particle::p, partCfg(), particle_type_map, ParticleProperties::type, and type_list_enable.
Referenced by ReactionMethods::ReactionAlgorithm::add_reaction().
invalidate_fetch_cache()
void invalidate_fetch_cache ()
Invalidate the fetch cache for get_particle_data.
Definition at line 484 of file particle_data.cpp.
References anonymous_namespace{particle_data.cpp}::particle_fetch_cache.
Referenced by on_integration_start(), and on_particle_change().
local_change_exclusion()
void local_change_exclusion (int part1, int part2, int _delete)
Locally add an exclusion to a particle.
Parameters
part1 the identity of the first exclusion partner
part2 the identity of the second exclusion partner
_delete if true, delete the exclusion instead of add
Definition at line 1027 of file particle_data.cpp.
References add_exclusion(), cell_structure, delete_exclusion(), and CellStructure::get_local_particle().
Referenced by mpi_send_exclusion_local().
local_place_particle()
Particle* local_place_particle (int id, const Utils::Vector3d & pos, int _new)
Move a particle to a new position.
If it does not exist, it is created. The position must be on the local node!
Parameters
id the identity of the particle to move
pos its new position
_new if true, the particle is allocated, else has to exists already
Returns
Pointer to the particle.
Definition at line 620 of file particle_data.cpp.
References CellStructure::add_local_particle(), box_geo, cell_structure, fold_position(), CellStructure::get_local_particle(), ParticleLocal::i, ParticleProperties::identity, Particle::l, ParticlePosition::p, Particle::p, pos, and Particle::r.
Referenced by mpi_place_new_particle_local(), mpi_place_particle(), and mpi_place_particle_local().
local_rescale_particles()
void local_rescale_particles (int dir, double scale)
Locally rescale all particles on current node.
Parameters
dir direction to scale (0/1/2 = x/y/z, 3 = x+y+z isotropically)
scale factor by which to rescale (>1: stretch, <1: contract)
Definition at line 990 of file particle_data.cpp.
References cell_structure, CellStructure::local_particles(), ParticlePosition::p, and Particle::r.
Referenced by mpi_rescale_particles(), and mpi_rescale_particles_local().
mpi_get_particles()
std::vector<Particle> mpi_get_particles (Utils::Span< const int > ids)
Get multiple particles at once.
WARNING Particles are returned in an arbitrary order.
Parameters
ids The ids of the particles that should be returned.
Returns
The particle list.
Definition at line 545 of file particle_data.cpp.
References comm_cart, Utils::Mpi::gatherv(), get_particle_node(), Communication::Result::ignore, mpi_call(), mpi_get_particles_local(), and this_node.
Referenced by prefetch_particle_data().
mpi_get_particles_local()
void mpi_get_particles_local (int , int)
Definition at line 521 of file particle_data.cpp.
References comm_cart, and Utils::Mpi::gatherv().
Referenced by mpi_get_particles().
mpi_place_new_particle()
int mpi_place_new_particle (int p_id, const Utils::Vector3d & pos)
Create particle at a position on a node.
Also calls on_particle_change.
Parameters
p_id the particle to create.
pos the particles position.
Definition at line 658 of file particle_data.cpp.
References mpi_call(), mpi_place_new_particle_local(), Communication::Result::one_rank, and pos.
Referenced by place_particle().
mpi_place_new_particle_local()
boost::optional<int> mpi_place_new_particle_local (int p_id, Utils::Vector3d const & pos)
Definition at line 641 of file particle_data.cpp.
References comm_cart, local_place_particle(), on_particle_change(), and pos.
Referenced by mpi_place_new_particle().
mpi_place_particle()
void mpi_place_particle (int node, int p_id, const Utils::Vector3d & pos)
Move particle to a position on a node.
Also calls on_particle_change.
Parameters
node the node to attach it to.
p_id the particle to move.
pos the particles position.
Definition at line 682 of file particle_data.cpp.
References cell_structure, comm_cart, local_place_particle(), mpi_call(), mpi_place_particle_local(), node, on_particle_change(), pos, Cells::RESORT_GLOBAL, CellStructure::set_resort_particles(), SOME_TAG, and this_node.
Referenced by place_particle().
mpi_place_particle_local()
void mpi_place_particle_local (int pnode, int p_id)
Definition at line 663 of file particle_data.cpp.
References cell_structure, comm_cart, local_place_particle(), on_particle_change(), pos, Cells::RESORT_GLOBAL, CellStructure::set_resort_particles(), SOME_TAG, and this_node.
Referenced by mpi_place_particle().
mpi_remove_particle()
void mpi_remove_particle (int , int p_id)
Remove a particle.
Also calls on_particle_change.
Parameters
p_id the particle to remove, use -1 to remove all particles.
Definition at line 961 of file particle_data.cpp.
References mpi_call_all(), and mpi_remove_particle_local().
Referenced by remove_all_particles(), and remove_particle().
mpi_remove_particle_local()
void mpi_remove_particle_local (int , int part)
Definition at line 946 of file particle_data.cpp.
References cell_structure, on_particle_change(), CellStructure::remove_all_particles(), and CellStructure::remove_particle().
Referenced by mpi_remove_particle().
mpi_rescale_particles()
void mpi_rescale_particles (int dir, double scale)
Rescale all particle positions in direction dir by a factor scale.
Definition at line 1009 of file particle_data.cpp.
References comm_cart, local_rescale_particles(), mpi_call(), mpi_rescale_particles_local(), n_nodes, on_particle_change(), SOME_TAG, and this_node.
Referenced by rescale_boxl().
mpi_rescale_particles_local()
void mpi_rescale_particles_local (int , int dir)
Definition at line 1000 of file particle_data.cpp.
References comm_cart, local_rescale_particles(), on_particle_change(), and SOME_TAG.
Referenced by mpi_rescale_particles().
mpi_send_exclusion()
void mpi_send_exclusion (int part1, int part2, int _delete)
Send exclusions.
Also calls on_particle_change.
Parameters
part1 identity of first particle of the exclusion.
part2 identity of second particle of the exclusion.
_delete if true, do not add the exclusion, rather delete it if found
Definition at line 1075 of file particle_data.cpp.
References mpi_call_all(), and mpi_send_exclusion_local().
Referenced by change_exclusion().
mpi_send_exclusion_local()
void mpi_send_exclusion_local (int part1, int part2, int _delete)
Definition at line 1062 of file particle_data.cpp.
References local_change_exclusion(), and on_particle_change().
Referenced by mpi_send_exclusion().
mpi_send_update_message()
void mpi_send_update_message (int id, const UpdateMessage & msg)
Send a particle update message.
This sends the message to the node that is responsible for the particle, where msg is called with the particle as argument. The message then performs the change to the particle that is encoded in it. The mechanism to call a functor based on the active type of a variant is called visitation. Here we can use UpdateVisitor with a single templated call operator on the visitor because all message (eventually) provide the same interface. Overall this is logically equivalent to nested switch statements over the message types, where the case statements play the role of the call of the messages in our case. A general introduction can be found in the documentation of boost::variant.
Parameters
id Id of the particle to update
msg The message
Definition at line 355 of file particle_data.cpp.
References comm_cart, get_particle_node(), mpi_call(), mpi_send_update_message_local(), on_particle_change(), and SOME_TAG.
Referenced by add_particle_bond(), delete_particle_bond(), delete_particle_bonds(), mpi_update_particle(), and rotate_particle().
mpi_send_update_message_local()
void mpi_send_update_message_local (int node, int id)
Definition at line 325 of file particle_data.cpp.
References comm_cart, node, on_particle_change(), and SOME_TAG.
Referenced by mpi_send_update_message().
mpi_update_particle()
template<typename S , S Particle::* s, typename T , T S::* m> void mpi_update_particle (int id, const T & value)
Definition at line 373 of file particle_data.cpp.
References mpi_send_update_message().
Referenced by set_particle_f(), set_particle_omega_body(), set_particle_omega_lab(), set_particle_torque_lab(), and set_particle_v().
mpi_update_particle_property()
template<typename T , T ParticleProperties::* m> void mpi_update_particle_property (int id, const T & value)
Definition at line 380 of file particle_data.cpp.
Referenced by set_particle_ext_torque(), set_particle_swimming(), set_particle_vs_quat(), and set_particle_vs_relative().
mpi_who_has()
void mpi_who_has ()
Definition at line 424 of file particle_data.cpp.
References cell_structure, comm_cart, ParticleProperties::identity, CellStructure::local_particles(), mpi_call(), mpi_who_has_local(), n_nodes, Particle::p, particle_node, SOME_TAG, and this_node.
Referenced by build_particle_node().
mpi_who_has_local()
void mpi_who_has_local (int , int)
Definition at line 403 of file particle_data.cpp.
References cell_structure, comm_cart, CellStructure::local_particles(), and SOME_TAG.
Referenced by mpi_who_has().
number_of_particles_with_type()
int number_of_particles_with_type (int type)
Definition at line 1183 of file particle_data.cpp.
References particle_type_map.
Referenced by ReactionMethods::ReactionAlgorithm::all_reactant_particles_exist(), ReactionMethods::ReactionAlgorithm::do_global_mc_move_for_particles_of_type(), and ReactionMethods::ReactionAlgorithm::generate_new_particle_positions().
particle_exists()
bool particle_exists (int part)
Check if particle exists.
Parameters
part Id of the particle
Returns
True iff the particle exists.
Definition at line 1285 of file particle_data.cpp.
References build_particle_node(), and particle_node.
Referenced by change_exclusion(), and place_particle().
place_particle()
int place_particle (int part, Utils::Vector3d const & p)
Call only on the master node.
Move a particle to a new position. If it does not exist, it is created.
Parameters
part the identity of the particle to move
p its new position
Return values
ES_PART_OK if particle existed
ES_PART_CREATED if created
ES_PART_ERROR if id is illegal
Definition at line 695 of file particle_data.cpp.
References ES_PART_CREATED, ES_PART_OK, get_particle_node(), mpi_place_new_particle(), mpi_place_particle(), particle_exists(), particle_node, and pos.
Referenced by ReactionMethods::ReactionAlgorithm::do_global_mc_move_for_particles_of_type().
pointer_to_dipm()
void pointer_to_dipm (Particle const * p, double const *& res)
Definition at line 1232 of file particle_data.cpp.
References ParticleProperties::dipm, Particle::p, and res.
pointer_to_ext_force()
void pointer_to_ext_force (Particle const * p, double const *& res2)
Definition at line 1238 of file particle_data.cpp.
References Utils::Array< T, N >::data(), ParticleProperties::ext_force, and Particle::p.
pointer_to_ext_torque()
void pointer_to_ext_torque (Particle const * p, double const *& res2)
Definition at line 1242 of file particle_data.cpp.
References Utils::Array< T, N >::data(), ParticleProperties::ext_torque, and Particle::p.
pointer_to_fix()
void pointer_to_fix (Particle const * p, const uint8_t *& res)
Definition at line 1246 of file particle_data.cpp.
References ParticleProperties::ext_flag, Particle::p, and res.
pointer_to_gamma()
void pointer_to_gamma (Particle const * p, double const *& res)
Definition at line 1252 of file particle_data.cpp.
References Utils::Array< T, N >::data(), ParticleProperties::gamma, Particle::p, and res.
pointer_to_gamma_rot()
void pointer_to_gamma_rot (Particle const * p, double const *& res)
Definition at line 1261 of file particle_data.cpp.
References Utils::Array< T, N >::data(), ParticleProperties::gamma_rot, Particle::p, and res.
pointer_to_omega_body()
void pointer_to_omega_body (Particle const * p, double const *& res)
Definition at line 1200 of file particle_data.cpp.
References Utils::Array< T, N >::data(), Particle::m, ParticleMomentum::omega, and res.
pointer_to_q()
void pointer_to_q (Particle const * p, double const *& res)
Definition at line 1209 of file particle_data.cpp.
References Particle::p, ParticleProperties::q, and res.
pointer_to_quat()
void pointer_to_quat (Particle const * p, double const *& res)
Definition at line 1204 of file particle_data.cpp.
References Utils::Quaternion< T >::data(), ParticlePosition::quat, Particle::r, and res.
pointer_to_rotational_inertia()
void pointer_to_rotational_inertia (Particle const * p, double const *& res)
Definition at line 1280 of file particle_data.cpp.
References Utils::Array< T, N >::data(), Particle::p, res, and ParticleProperties::rinertia.
pointer_to_swimming()
void pointer_to_swimming (Particle const * p, ParticleParametersSwimming const *& swim)
Definition at line 1273 of file particle_data.cpp.
References Particle::p, and ParticleProperties::swim.
pointer_to_virtual()
void pointer_to_virtual (Particle const * p, bool const *& res)
Definition at line 1212 of file particle_data.cpp.
References ParticleProperties::is_virtual, Particle::p, and res.
pointer_to_vs_quat()
void pointer_to_vs_quat (Particle const * p, double const *& res)
Definition at line 1218 of file particle_data.cpp.
References Utils::Quaternion< T >::data(), Particle::p, ParticleProperties::VirtualSitesRelativeParameters::quat, res, and ParticleProperties::vs_relative.
pointer_to_vs_relative()
void pointer_to_vs_relative (Particle const * p, int const *& res1, double const *& res2, double const *& res3)
Definition at line 1222 of file particle_data.cpp.
References Utils::Quaternion< T >::data(), ParticleProperties::VirtualSitesRelativeParameters::distance, Particle::p, ParticleProperties::VirtualSitesRelativeParameters::rel_orientation, ParticleProperties::VirtualSitesRelativeParameters::to_particle_id, and ParticleProperties::vs_relative.
prefetch_particle_data()
void prefetch_particle_data (Utils::Span< const int > ids)
Fetch a range of particle into the fetch cache.
If the range is larger than the cache size, only the particle that fit into the cache are fetched.
The particles have to exist, an exception it throw if one of the the particles can not be found.
Parameters
ids Ids of the particles that should be fetched.
Definition at line 587 of file particle_data.cpp.
References comm_cart, get_particle_node(), Particle::identity(), mpi_get_particles(), anonymous_namespace{particle_data.cpp}::particle_fetch_cache, and this_node.
Referenced by fetch_particles().
remove_all_particles()
void remove_all_particles ()
Remove all particles.
Definition at line 965 of file particle_data.cpp.
References clear_particle_node(), and mpi_remove_particle().
remove_id_from_map()
void remove_id_from_map (int part_id, int type)
Definition at line 1157 of file particle_data.cpp.
References particle_type_map.
Referenced by remove_particle(), and set_particle_type().
remove_particle()
int remove_particle (int part)
Remove particle with a given identity.
Also removes all bonds to the particle.
Parameters
part identity of the particle to remove
Return values
ES_OK on success
ES_ERROR if particle does not exist
Definition at line 970 of file particle_data.cpp.
References ES_OK, get_particle_data(), mpi_remove_particle(), particle_node, remove_id_from_map(), and type_list_enable.
Referenced by ReactionMethods::ReactionAlgorithm::delete_particle().
rotate_particle()
void rotate_particle (int part, const Utils::Vector3d & axis, double angle)
rotate a particle around an axis
Parameters
part particle id
axis rotation axis
angle rotation angle
Definition at line 747 of file particle_data.cpp.
References mpi_send_update_message().
set_particle_dip()
void set_particle_dip (int part, Utils::Vector3d const & dip)
Call only on the master node: set particle dipole orientation.
Parameters
part the particle.
dip its new dipole orientation.
Definition at line 757 of file particle_data.cpp.
References convert_dip_to_quat(), Utils::Quaternion< T >::data(), set_particle_dipm(), and set_particle_quat().
set_particle_dipm()
void set_particle_dipm (int part, double dipm)
Call only on the master node: set particle dipole moment (absolute value).
Parameters
part the particle.
dipm its new dipole moment.
Definition at line 753 of file particle_data.cpp.
Referenced by set_particle_dip().
set_particle_director()
void set_particle_director (int part, const Utils::Vector3d & director)
Call only on the master node: set particle orientation using director.
The particle director defines the z-axis in the body-fixed frame.
Parameters
part the particle.
director its new director vector (will be normalized if necessary)
Definition at line 849 of file particle_data.cpp.
References Utils::convert_director_to_quaternion(), Utils::Quaternion< T >::data(), Utils::Vector< T, N >::normalized(), and set_particle_quat().
set_particle_ext_force()
void set_particle_ext_force (int part, const Utils::Vector3d & force)
Call only on the master node: set particle external force.
Parameters
part the particle.
force new value for ext_force.
Definition at line 912 of file particle_data.cpp.
References force.
set_particle_ext_torque()
void set_particle_ext_torque (int part, const Utils::Vector3d & torque)
Call only on the master node: set particle external torque.
Parameters
part the particle.
torque new value for ext_torque.
Definition at line 906 of file particle_data.cpp.
References ParticleProperties::ext_torque, mpi_update_particle_property(), and torque.
set_particle_f()
void set_particle_f (int part, const Utils::Vector3d & F)
Call only on the master node: set particle force.
Parameters
part the particle.
F its new force.
Definition at line 718 of file particle_data.cpp.
References ParticleForce::f, Particle::f, f, and mpi_update_particle().
set_particle_fix()
void set_particle_fix (int part, uint8_t flag)
Call only on the master node: set coordinate axes for which the particles motion is fixed.
Parameters
part the particle.
flag new value for flagged coordinate axes to be fixed
Definition at line 917 of file particle_data.cpp.
set_particle_gamma()
void set_particle_gamma (int part, Utils::Vector3d const & gamma)
Call only on the master node: set particle frictional coefficient.
Parameters
part the particle.
gamma its new frictional coefficient.
Definition at line 883 of file particle_data.cpp.
References Utils::gamma().
set_particle_gamma_rot()
void set_particle_gamma_rot (int part, Utils::Vector3d const & gamma_rot)
Definition at line 896 of file particle_data.cpp.
set_particle_mass()
void set_particle_mass (int part, double mass)
Call only on the master node: set particle mass.
Parameters
part the particle.
mass its new mass.
Definition at line 724 of file particle_data.cpp.
set_particle_mol_id()
void set_particle_mol_id (int part, int mid)
Call only on the master node: set particle's molecule id.
Parameters
part the particle.
mid its new mol id.
Definition at line 838 of file particle_data.cpp.
set_particle_mu_E()
void set_particle_mu_E (int part, Utils::Vector3d const & mu_E)
Call only on the master node: set particle electrophoretic mobility.
Parameters
part the particle.
mu_E its new mobility.
Definition at line 809 of file particle_data.cpp.
set_particle_omega_body()
void set_particle_omega_body (int part, const Utils::Vector3d & omega)
Call only on the master node: set particle angular velocity in body frame.
Parameters
part the particle.
omega its new angular velocity.
Definition at line 863 of file particle_data.cpp.
References Particle::m, mpi_update_particle(), and ParticleMomentum::omega.
set_particle_omega_lab()
void set_particle_omega_lab (int part, const Utils::Vector3d & omega_lab)
Call only on the master node: set particle angular velocity from lab frame.
Parameters
part the particle.
omega_lab its new angular velocity.
Definition at line 855 of file particle_data.cpp.
References convert_vector_space_to_body(), get_particle_data(), Particle::m, mpi_update_particle(), and ParticleMomentum::omega.
set_particle_q()
void set_particle_q (int part, double q)
Call only on the master node: set particle charge.
Parameters
part the particle.
q its new charge.
Definition at line 798 of file particle_data.cpp.
Referenced by ReactionMethods::ReactionAlgorithm::restore_properties().
set_particle_quat()
void set_particle_quat (int part, double * quat)
Call only on the master node: set particle orientation using quaternions.
Parameters
part the particle.
quat its new value for quaternions.
Definition at line 843 of file particle_data.cpp.
References ParticlePosition::quat.
Referenced by set_particle_dip(), and set_particle_director().
set_particle_rotation()
void set_particle_rotation (int part, int rot)
Call only on the master node: Specifies whether a particle's rotational degrees of freedom are integrated or not.
If set to zero, the content of the torque and omega variables are meaningless
Parameters
part the particle.
rot the degrees of freedom flag.
Definition at line 742 of file particle_data.cpp.
set_particle_rotational_inertia()
void set_particle_rotational_inertia (int part, Utils::Vector3d const & rinertia)
Call only on the master node: set particle rotational inertia.
Parameters
part the particle.
rinertia its new inertia.
Definition at line 732 of file particle_data.cpp.
set_particle_swimming()
void set_particle_swimming (int part, ParticleParametersSwimming swim)
Call only on the master node: set particle velocity.
Parameters
part the particle.
swim struct containing swimming parameters
Definition at line 712 of file particle_data.cpp.
References mpi_update_particle_property(), and ParticleProperties::swim.
set_particle_torque_lab()
void set_particle_torque_lab (int part, const Utils::Vector3d & torque_lab)
Call only on the master node: set particle torque from lab frame.
Parameters
part the particle.
torque_lab its new torque.
Definition at line 868 of file particle_data.cpp.
References convert_vector_space_to_body(), Particle::f, get_particle_data(), mpi_update_particle(), and ParticleForce::torque.
set_particle_type()
void set_particle_type (int p_id, int type)
Call only on the master node: set particle type.
Parameters
p_id the particle.
type its new type.
Definition at line 820 of file particle_data.cpp.
References add_id_to_type_map(), get_particle_data(), make_particle_type_exist(), remove_id_from_map(), and type_list_enable.
Referenced by ReactionMethods::ReactionAlgorithm::generic_oneway_reaction(), and ReactionMethods::ReactionAlgorithm::restore_properties().
set_particle_v()
void set_particle_v (int part, Utils::Vector3d const & v)
Call only on the master node: set particle velocity.
Parameters
part the particle.
v its new velocity.
Definition at line 706 of file particle_data.cpp.
References Particle::m, mpi_update_particle(), and ParticleMomentum::v.
set_particle_virtual()
void set_particle_virtual (int part, bool is_virtual)
Call only on the master node: set particle virtual flag.
Parameters
part the particle.
is_virtual new is_virtual flag.
Definition at line 768 of file particle_data.cpp.
Referenced by vs_relate_to().
set_particle_vs_quat()
void set_particle_vs_quat (int part, Utils::Quaternion< double > const & vs_relative_quat)
Definition at line 775 of file particle_data.cpp.
References get_particle_data(), mpi_update_particle_property(), Particle::p, ParticleProperties::VirtualSitesRelativeParameters::quat, and ParticleProperties::vs_relative.
set_particle_vs_relative()
void set_particle_vs_relative (int part, int vs_relative_to, double vs_distance, Utils::Quaternion< double > const & rel_ori)
Definition at line 785 of file particle_data.cpp.
References ParticleProperties::VirtualSitesRelativeParameters::distance, mpi_update_particle_property(), ParticleProperties::VirtualSitesRelativeParameters::rel_orientation, ParticleProperties::VirtualSitesRelativeParameters::to_particle_id, and ParticleProperties::vs_relative.
Referenced by vs_relate_to().
Variable Documentation
particle_node
std::unordered_map<int, int> particle_node
id -> rank
Definition at line 395 of file particle_data.cpp.
Referenced by clear_particle_node(), get_maximal_particle_id(), get_n_part(), get_particle_ids(), get_particle_node(), mpi_who_has(), particle_exists(), place_particle(), and remove_particle().
particle_type_map
std::unordered_map<int, std::unordered_set<int> > particle_type_map {}
Definition at line 388 of file particle_data.cpp.
Referenced by add_id_to_type_map(), get_random_p_id(), init_type_map(), number_of_particles_with_type(), and remove_id_from_map().
type_list_enable
bool type_list_enable
Definition at line 387 of file particle_data.cpp.
Referenced by init_type_map(), remove_particle(), and set_particle_type().