ESPResSo: rattle.hpp File Reference
rattle.hpp File Reference
#include "bonded_interactions/bonded_interaction_data.hpp"
#include "bonded_interactions/rigid_bond.hpp"
#include "cells.hpp"
#include "config.hpp"
Functions
void save_old_position (const ParticleRange &particles, const ParticleRange &ghost_particles)
Transfer the current particle positions from Particle::r::p to Particle::r::p_last_timestep.
void correct_position_shake (CellStructure &cs)
Propagate velocity and position while using SHAKE algorithm for bond constraint.
void correct_velocity_shake (CellStructure &cs)
Correction of current velocities using RATTLE algorithm.
Detailed Description
RATTLE algorithm ([4]).
For more information see rattle.cpp.
Definition in file rattle.hpp.
Function Documentation
correct_position_shake()
void correct_position_shake (CellStructure & cs)
Propagate velocity and position while using SHAKE algorithm for bond constraint.
Parameters
cs cell structure
Definition at line 132 of file rattle.cpp.
References apply_positional_correction(), calculate_positional_correction(), cell_structure, cells_update_ghosts(), check_resort_particles(), comm_cart, compute_correction_vector(), Cells::DATA_PART_MOMENTUM, Cells::DATA_PART_POSITION, Cells::DATA_PART_PROPERTIES, CellStructure::ghost_particles(), CellStructure::ghosts_reduce_rattle_correction(), CellStructure::ghosts_update(), init_correction_vector(), CellStructure::local_particles(), Cells::particles(), runtimeErrorMsg, and SHAKE_MAX_ITERATIONS.
Referenced by integrate().
correct_velocity_shake()
void correct_velocity_shake (CellStructure & cs)
Correction of current velocities using RATTLE algorithm.
Parameters
cs cell structure
Definition at line 203 of file rattle.cpp.
References apply_velocity_correction(), calculate_velocity_correction(), cell_structure, comm_cart, compute_correction_vector(), Cells::DATA_PART_MOMENTUM, Cells::DATA_PART_POSITION, CellStructure::ghost_particles(), CellStructure::ghosts_reduce_rattle_correction(), CellStructure::ghosts_update(), init_correction_vector(), CellStructure::local_particles(), Cells::particles(), runtimeErrorMsg, and SHAKE_MAX_ITERATIONS.
Referenced by integrate().
save_old_position()
void save_old_position (const ParticleRange & particles, const ParticleRange & ghost_particles)
Transfer the current particle positions from Particle::r::p to Particle::r::p_last_timestep.
Transfer the current particle positions from Particle::r::p to Particle::r::p_last_timestep.
Parameters
particles particle range
ghost_particles ghost particle range
Definition at line 41 of file rattle.cpp.
References Utils::for_each(), and Cells::particles().
Referenced by integrate().