ESPResSo: reaction_field.hpp File Reference
reaction_field.hpp File Reference
#include "config.hpp"
#include <utils/Vector.hpp>
#include <utils/math/int_pow.hpp>
Classes
struct ReactionFieldParameters
Reaction Field parameters.
Functions
void rf_set_params (double kappa, double epsilon1, double epsilon2, double r_cut)
void add_rf_coulomb_pair_force (double const q1q2, Utils::Vector3d const &d, double const dist, Utils::Vector3d &force)
Compute the Reaction Field pair force.
double rf_coulomb_pair_energy (double const q1q2, double const dist)
Compute the Reaction Field pair energy.
Variables
ReactionFieldParameters rf_params
Global state of the Reaction Field method.
Detailed Description
Routines to calculate the Reaction Field energy or/and force for a particle pair [37], [49].
Implementation in reaction_field.cpp
Definition in file reaction_field.hpp.
Function Documentation
add_rf_coulomb_pair_force()
void add_rf_coulomb_pair_force (double const q1q2, Utils::Vector3d const & d, double const dist, Utils::Vector3d & force) inline
Compute the Reaction Field pair force.
Parameters
[in] q1q2 Product of the charges on p1 and p2.
[in] d Vector pointing from p1 to p2.
[in] dist Distance between p1 and p2.
[out] force Calculated force on p1.
Definition at line 65 of file reaction_field.hpp.
References ReactionFieldParameters::B, force, ReactionFieldParameters::r_cut, and rf_params.
Referenced by Coulomb::central_force().
rf_coulomb_pair_energy()
double rf_coulomb_pair_energy (double const q1q2, double const dist) inline
Compute the Reaction Field pair energy.
Parameters
q1q2 Product of the charges on p1 and p2.
dist Distance between p1 and p2.
Definition at line 81 of file reaction_field.hpp.
References ReactionFieldParameters::B, ReactionFieldParameters::r_cut, and rf_params.
Referenced by Coulomb::pair_energy().
rf_set_params()
void rf_set_params (double kappa, double epsilon1, double epsilon2, double r_cut)
Definition at line 32 of file reaction_field.cpp.
References mpi_bcast_coulomb_params(), and rf_params.
Variable Documentation
rf_params
ReactionFieldParameters rf_params
Global state of the Reaction Field method.
Definition at line 30 of file reaction_field.cpp.
Referenced by add_rf_coulomb_pair_force(), Coulomb::bcast_coulomb_params(), Coulomb::cutoff(), Coulomb::deactivate(), rf_coulomb_pair_energy(), and rf_set_params().