ESPResSo: CellStructure Struct Reference
CellStructure Struct Reference
Describes a cell structure / cell system.
#include <CellStructure.hpp>
Public Member Functions
void update_particle_index (int id, Particle *p)
Update local particle index.
void update_particle_index (Particle &p)
Update local particle index.
void update_particle_index (ParticleList &pl)
Update local particle index.
void clear_particle_index ()
Clear the particles index.
Particle * get_local_particle (int id)
Get a local particle by id.
const Particle * get_local_particle (int id) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
template<class InputRange , class OutputIterator >
void get_local_particles (InputRange ids, OutputIterator out)
int decomposition_type () const
Utils::Vector3d max_cutoff () const
Maximal cutoff supported by current cell system.
Utils::Vector3d max_range () const
Maximal pair range supported by current cell system.
ParticleRange local_particles ()
ParticleRange ghost_particles ()
Particle * add_particle (Particle &&p)
Add a particle.
Particle * add_local_particle (Particle &&p)
Add a particle.
void remove_particle (int id)
Remove a particle.
int get_max_local_particle_id () const
Get the maximal particle id on this node.
void remove_all_particles ()
Remove all particles from the cell system.
const ParticleDecomposition & decomposition () const
Get the underlying particle decomposition.
void set_resort_particles (Cells::Resort level)
Increase the local resort level at least to level.
unsigned get_resort_particles () const
Get the currently scheduled resort level.
void clear_resort_particles ()
Set the resort level to sorted.
void ghosts_count ()
Synchronize number of ghosts.
void ghosts_update (unsigned data_parts)
Update ghost particles.
void ghosts_reduce_forces ()
Add forces from ghost particles to real particles.
void ghosts_reduce_rattle_correction ()
Add rattle corrections from ghost particles to real particles.
void resort_particles (int global_flag)
Resort particles.
void set_atom_decomposition (boost::mpi::communicator const &comm, BoxGeometry const &box)
Set the particle decomposition to AtomDecomposition.
void set_domain_decomposition (boost::mpi::communicator const &comm, double range, BoxGeometry const &box, LocalBox< double > const &local_geo)
Set the particle decomposition to DomainDecomposition.
template<class BondKernel >
void bond_loop (BondKernel const &bond_kernel)
template<class PairKernel >
void non_bonded_loop (PairKernel pair_kernel)
Non-bonded pair loop.
template<class PairKernel , class VerletCriterion >
void non_bonded_loop (PairKernel pair_kernel, const VerletCriterion &verlet_criterion)
Non-bonded pair loop with potential use of verlet lists.
Cell * find_current_cell (const Particle &p)
Find cell a particle is stored in.
Public Attributes
bool use_verlet_list = true
Detailed Description
Describes a cell structure / cell system.
Contains information about the communication of cell contents (particles, ghosts, ...) between different nodes and the relation between particle positions and the cell system. All other properties of the cell system which are not common between different cell systems have to be stored in separate structures.
Definition at line 125 of file CellStructure.hpp.
Member Function Documentation
add_local_particle()
Particle * CellStructure::add_local_particle (Particle && p)
Add a particle.
Moves a particle into the cell system, if it belongs to this node. Otherwise this does not have an effect and the particle is discarded. This can be used to add a particle without knowledge where it should be placed by calling the function on all nodes, it will then add the particle in exactly one place.
Parameters
p Particle to add.
Returns
Pointer to particle if it is local, null otherwise.
Definition at line 112 of file CellStructure.cpp.
Referenced by local_place_particle().
add_particle()
Particle * CellStructure::add_particle (Particle && p)
Add a particle.
Moves a particle into the cell system. This adds a particle to the local node, irrespective of where it belongs.
Parameters
p Particle to add.
Returns
Pointer to the particle in the cell system.
Definition at line 123 of file CellStructure.cpp.
References Cells::RESORT_GLOBAL, Cells::RESORT_LOCAL, and set_resort_particles().
Referenced by place_vs_and_relate_to_particle().
bond_loop()
template<class BondKernel > void CellStructure::bond_loop (BondKernel const & bond_kernel) inline
Definition at line 501 of file CellStructure.hpp.
References local_particles().
Referenced by add_oif_global_forces(), calc_oif_global(), and compute_correction_vector().
clear_particle_index()
void CellStructure::clear_particle_index () inline
Clear the particles index.
Definition at line 188 of file CellStructure.hpp.
clear_resort_particles()
void CellStructure::clear_resort_particles () inline
Set the resort level to sorted.
Definition at line 362 of file CellStructure.hpp.
References Cells::RESORT_NONE.
Referenced by cells_update_ghosts().
decomposition()
const ParticleDecomposition& CellStructure::decomposition () const inline
Get the underlying particle decomposition.
Should be used solely for informative purposes.
Returns
The active particle decomposition.
Definition at line 336 of file CellStructure.hpp.
Referenced by ghost_particles(), ghosts_count(), ghosts_reduce_forces(), ghosts_reduce_rattle_correction(), ghosts_update(), local_particles(), max_cutoff(), max_range(), remove_all_particles(), and remove_particle().
decomposition_type()
int CellStructure::decomposition_type () const inline
Definition at line 247 of file CellStructure.hpp.
Referenced by dp3m_sanity_checks(), lb_sanity_checks(), MMM1D_sanity_checks(), on_boxl_change(), on_nodegrid_change(), on_short_range_ia_change(), on_skin_change(), and p3m_sanity_checks_system().
find_current_cell()
Cell* CellStructure::find_current_cell (const Particle & p) inline
Find cell a particle is stored in.
For local particles, this returns the cell they are stored in, otherwise nullptr is returned.
Parameters
p Particle to find cell for
Returns
Cell for particle or nullptr.
Definition at line 627 of file CellStructure.hpp.
References get_resort_particles(), ParticleLocal::ghost, and Particle::l.
Referenced by find_current_cell().
get_local_particle() [1/2]
Particle* CellStructure::get_local_particle (int id) inline
Get a local particle by id.
Parameters
id Particle to get.
Returns
Pointer to particle if it is local, nullptr otherwise.
Definition at line 221 of file CellStructure.hpp.
Referenced by bind_at_poc_create_bond_between_vs(), cells_update_ghosts(), get_local_particles(), anonymous_namespace{collision.cpp}::get_part(), get_particle_data(), get_particle_data_local(), anonymous_namespace{VirtualSitesRelative.cpp}::get_reference_particle(), handle_collisions(), local_change_exclusion(), local_place_particle(), and three_particle_binding_domain_decomposition().
get_local_particle() [2/2]
const Particle* CellStructure::get_local_particle (int id) const inline
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 231 of file CellStructure.hpp.
get_local_particles()
template<class InputRange , class OutputIterator > void CellStructure::get_local_particles (InputRange ids, OutputIterator out) inline
Definition at line 241 of file CellStructure.hpp.
References get_local_particle().
get_max_local_particle_id()
int CellStructure::get_max_local_particle_id () const
Get the maximal particle id on this node.
This returns the highest particle id on this node, or -1 if there are no particles on this node.
Definition at line 137 of file CellStructure.cpp.
References Utils::find_if().
Referenced by handle_collisions().
get_resort_particles()
unsigned CellStructure::get_resort_particles () const inline
Get the currently scheduled resort level.
Definition at line 357 of file CellStructure.hpp.
Referenced by cells_update_ghosts(), find_current_cell(), and integrate().
ghost_particles()
ParticleRange CellStructure::ghost_particles ()
Definition at line 197 of file CellStructure.cpp.
References decomposition(), and Cells::particles().
Referenced by VirtualSitesRelative::back_transfer_forces_and_torques(), cells_update_ghosts(), correct_position_shake(), correct_velocity_shake(), force_calc(), IBM_ForcesIntoFluid_CPU(), init_forces(), integrate(), ParticleVelocitiesFromLB_CPU(), and update_dependent_particles().
ghosts_count()
void CellStructure::ghosts_count ()
Synchronize number of ghosts.
Definition at line 170 of file CellStructure.cpp.
References decomposition(), ghost_communicator(), and GHOSTTRANS_PARTNUM.
Referenced by cells_update_ghosts().
ghosts_reduce_forces()
void CellStructure::ghosts_reduce_forces ()
Add forces from ghost particles to real particles.
Definition at line 178 of file CellStructure.cpp.
References decomposition(), ghost_communicator(), and GHOSTTRANS_FORCE.
Referenced by VirtualSitesRelative::back_transfer_forces_and_torques(), force_calc(), icc_iteration(), and ParticleVelocitiesFromLB_CPU().
ghosts_reduce_rattle_correction()
void CellStructure::ghosts_reduce_rattle_correction ()
Add rattle corrections from ghost particles to real particles.
Definition at line 183 of file CellStructure.cpp.
References decomposition(), ghost_communicator(), and GHOSTTRANS_RATTLE.
Referenced by correct_position_shake(), and correct_velocity_shake().
ghosts_update()
void CellStructure::ghosts_update (unsigned data_parts)
Update ghost particles.
This function updates the ghost particles with data from the real particles.
Parameters
data_parts Particle parts to update, combination of Cells::DataPart
Definition at line 174 of file CellStructure.cpp.
References decomposition(), ghost_communicator(), and map_data_parts().
Referenced by cells_update_ghosts(), correct_position_shake(), correct_velocity_shake(), IBM_ForcesIntoFluid_CPU(), icc_iteration(), and VirtualSitesRelative::update().
local_particles()
ParticleRange CellStructure::local_particles ()
Definition at line 193 of file CellStructure.cpp.
References decomposition(), and Cells::particles().
Referenced by VirtualSitesRelative::back_transfer_forces_and_torques(), bond_loop(), calc_mu_max(), calculate_energy_local(), calculate_pressure_local(), check_resort_particles(), correct_position_shake(), correct_velocity_shake(), ScriptInterface::MPIIO::MPIIOScript::do_call_method(), ScriptInterface::Constraints::ShapeBasedConstraint::do_call_method(), dp3m_count_magnetic_particles(), force_calc(), EspressoSystemInterface::gatherParticles(), IBM_ForcesIntoFluid_CPU(), integrate(), local_galilei_transform(), local_particle_momentum(), local_rescale_particles(), local_system_CMS(), local_system_CMS_velocity(), mpi_kill_particle_forces_local(), mpi_kill_particle_motion_local(), mpi_resort_particles(), mpi_resort_particles_local(), mpi_rotate_system(), mpi_rotate_system_local(), mpi_who_has(), mpi_who_has_local(), p3m_count_charged_particles(), ParticleVelocitiesFromLB_CPU(), VirtualSitesRelative::pressure_tensor(), VirtualSitesRelative::update(), update_dependent_particles(), Scafacos::ScafacosContextCoulomb::update_particle_data(), Scafacos::ScafacosContextDipoles::update_particle_data(), Scafacos::ScafacosContextCoulomb::update_particle_forces(), Scafacos::ScafacosContextDipoles::update_particle_forces(), and Scafacos::ScafacosContext::update_system_params().
max_cutoff()
Utils::Vector3d CellStructure::max_cutoff () const
Maximal cutoff supported by current cell system.
Definition at line 201 of file CellStructure.cpp.
References decomposition(), and ParticleDecomposition::max_cutoff().
Referenced by python_integrate(), and tune_skin().
max_range()
Utils::Vector3d CellStructure::max_range () const
Maximal pair range supported by current cell system.
Definition at line 205 of file CellStructure.cpp.
References decomposition(), and ParticleDecomposition::max_range().
non_bonded_loop() [1/2]
template<class PairKernel > void CellStructure::non_bonded_loop (PairKernel pair_kernel) inline
Non-bonded pair loop.
Parameters
pair_kernel Kernel to apply
Definition at line 577 of file CellStructure.hpp.
Referenced by dpd_viscous_stress_local(), force_calc_icc(), get_pairs_filtered(), and non_bonded_loop_trace().
non_bonded_loop() [2/2]
template<class PairKernel , class VerletCriterion > void CellStructure::non_bonded_loop (PairKernel pair_kernel, const VerletCriterion & verlet_criterion) inline
Non-bonded pair loop with potential use of verlet lists.
Parameters
pair_kernel Kernel to apply
verlet_criterion Filter for verlet lists.
Definition at line 587 of file CellStructure.hpp.
References use_verlet_list.
remove_all_particles()
void CellStructure::remove_all_particles ()
Remove all particles from the cell system.
This allows linear time removal of all particles from the system, removing each particle individually would be quadratic.
Definition at line 144 of file CellStructure.cpp.
References D3Q19::c, and decomposition().
Referenced by Mpiio::mpi_mpiio_common_read(), and mpi_remove_particle_local().
remove_particle()
void CellStructure::remove_particle (int id)
Remove a particle.
Removes a particle and all bonds pointing to it. This is a collective call.
Parameters
id Id of particle to remove.
Definition at line 85 of file CellStructure.cpp.
References D3Q19::c, Utils::contains(), decomposition(), and update_particle_index().
Referenced by mpi_remove_particle_local().
resort_particles()
void CellStructure::resort_particles (int global_flag)
Resort particles.
Definition at line 223 of file CellStructure.cpp.
Referenced by cells_update_ghosts(), mpi_resort_particles(), and mpi_resort_particles_local().
set_atom_decomposition()
void CellStructure::set_atom_decomposition (boost::mpi::communicator const & comm, BoxGeometry const & box)
Set the particle decomposition to AtomDecomposition.
Parameters
comm Communicator to use.
box Box Geometry
Definition at line 243 of file CellStructure.cpp.
References CELL_STRUCTURE_NSQUARE.
Referenced by cells_re_init().
set_domain_decomposition()
void CellStructure::set_domain_decomposition (boost::mpi::communicator const & comm, double range, BoxGeometry const & box, LocalBox< double > const & local_geo)
Set the particle decomposition to DomainDecomposition.
Parameters
comm Cartesian communicator to use.
range Interaction range.
box Box Geometry
local_geo Geometry of the local box.
Definition at line 249 of file CellStructure.cpp.
References CELL_STRUCTURE_DOMDEC, and local_geo.
Referenced by cells_re_init().
set_resort_particles()
void CellStructure::set_resort_particles (Cells::Resort level) inline
Increase the local resort level at least to level.
Definition at line 349 of file CellStructure.hpp.
Referenced by add_particle(), brownian_dynamics_propagator(), check_resort_particles(), handle_collisions(), IBM_UpdateParticlePositions(), local_rotate_system(), mpi_place_particle(), mpi_place_particle_local(), on_particle_change(), steepest_descent_step(), stokesian_dynamics_propagate_vel_pos(), VirtualSitesRelative::update(), velocity_verlet_npt_propagate_pos(), and velocity_verlet_propagate_vel_pos().
update_particle_index() [1/3]
void CellStructure::update_particle_index (int id, Particle * p) inline
Update local particle index.
Update the entry for a particle in the local particle index.
Parameters
id Entry to update.
p Pointer to the particle.
Definition at line 152 of file CellStructure.hpp.
References Particle::identity().
Referenced by cells_update_ghosts(), remove_particle(), and update_particle_index().
update_particle_index() [2/3]
void CellStructure::update_particle_index (Particle & p) inline
Update local particle index.
Update the entry for a particle in the local particle index.
Parameters
p Pointer to the particle.
Definition at line 170 of file CellStructure.hpp.
References Particle::identity(), and update_particle_index().
update_particle_index() [3/3]
void CellStructure::update_particle_index (ParticleList & pl) inline
Update local particle index.
Parameters
pl List of particles whose index entries should be updated.
Definition at line 179 of file CellStructure.hpp.
References update_particle_index().
Member Data Documentation
use_verlet_list
bool CellStructure::use_verlet_list = true
Definition at line 141 of file CellStructure.hpp.
Referenced by mpi_set_use_verlet_lists_local(), non_bonded_loop(), and on_integration_start().
The documentation for this struct was generated from the following files:
CellStructure.hpp
CellStructure.cpp