ESPResSo: Scafacos::ScafacosContextCoulomb Struct Reference
Scafacos::ScafacosContextCoulomb Struct Reference
#include <ScafacosContext.hpp>
Public Member Functions
void update_particle_data () override
void update_particle_forces () const override
double long_range_energy () override
void add_long_range_force () override
void tune ()
void set_r_cut_and_tune_local (double r_cut)
Public Member Functions inherited from Scafacos::ScafacosContext
~ScafacosContext () override=default
void update_system_params () override
double get_pair_force (double dist) const override
double get_pair_energy (double dist) const override
std::string get_method_and_parameters () override
double get_r_cut () const override
Scafacos (std::string method, MPI_Comm comm, const std::string &parameters)
Public Member Functions inherited from Scafacos::ScafacosContextBase
virtual ~ScafacosContextBase ()=default
void add_pair_force (double q1q2, Utils::Vector3d const &d, double dist, Utils::Vector3d &force)
Add near-field pair force.
double pair_energy (double q1q2, double dist)
Calculate near-field pair energy.
Public Member Functions inherited from Scafacos::Scafacos
Scafacos (std::string method, MPI_Comm comm, const std::string &parameters)
~Scafacos ()
void parse_parameters (const std::string &s)
Parse parameter string.
std::string get_parameters ()
Get the parameters from the library.
std::string get_method ()
Get active method name.
void set_common_parameters (const double *box_l, const int *periodicity, int total_particles)
Set parameters common to all methods.
double pair_force (double dist) const
Calculate short range pair force if supported by the method.
double pair_energy (double dist) const
Get pair energy for near field contrib.
void run (std::vector< double > &charges, std::vector< double > &positions, std::vector< double > &fields, std::vector< double > &potentials)
Calculate the fields and potentials for charges.
void tune (std::vector< double > &charges, std::vector< double > &positions)
Tune parameters.
double r_cut () const
Get shortrange cutoff (0.0 if not supported)
void set_r_cut (double r_cut)
Set cutoff.
bool dipolar ()
Scafacos used for dipolar ia.
void set_dipolar (bool d)
Switch scafacos to dipolar ia.
Additional Inherited Members
Static Public Member Functions inherited from Scafacos::Scafacos
static std::list< std::string > available_methods ()
Get a list of methods supported by the library.
Public Attributes inherited from Scafacos::Scafacos
FCS handle
Handle from the library.
bool has_near
Whether the method supports near field delegation.
const std::string method
The scafacos method name of this instance.
std::string m_last_parameters
The last parameters set.
bool m_dipolar
Scafacos used for dipolar ia.
Protected Attributes inherited from Scafacos::ScafacosContext
std::vector< double > fields
Outputs.
std::vector< double > potentials
Detailed Description
Definition at line 69 of file ScafacosContext.hpp.
Member Function Documentation
add_long_range_force()
void Scafacos::ScafacosContextCoulomb::add_long_range_force () inline override virtual
Implements Scafacos::ScafacosContextBase.
Definition at line 74 of file ScafacosContext.hpp.
References Scafacos::ScafacosContext::fields, Scafacos::ScafacosContext::potentials, Scafacos::Scafacos::run(), update_particle_data(), and update_particle_forces().
long_range_energy()
double Scafacos::ScafacosContextCoulomb::long_range_energy () override virtual
Implements Scafacos::ScafacosContextBase.
Definition at line 163 of file ScafacosContext.cpp.
References coulomb, Scafacos::ScafacosContext::fields, Scafacos::ScafacosContext::potentials, Coulomb_parameters::prefactor, Scafacos::Scafacos::run(), and update_particle_data().
set_r_cut_and_tune_local()
void Scafacos::ScafacosContextCoulomb::set_r_cut_and_tune_local (double r_cut)
Definition at line 241 of file ScafacosContext.cpp.
References Scafacos::Scafacos::r_cut(), Scafacos::Scafacos::set_r_cut(), Scafacos::Scafacos::tune(), and update_particle_data().
Referenced by Scafacos::set_r_cut_and_tune_local().
tune()
void Scafacos::ScafacosContextCoulomb::tune ()
Definition at line 225 of file ScafacosContext.cpp.
References Scafacos::Scafacos::has_near, Scafacos::Scafacos::r_cut(), this_node, Scafacos::Scafacos::tune(), Scafacos::tune_r_cut(), and update_particle_data().
update_particle_data()
void Scafacos::ScafacosContextCoulomb::update_particle_data () override virtual
Implements Scafacos::ScafacosContextBase.
Definition at line 75 of file ScafacosContext.cpp.
References box_geo, cell_structure, folded_position(), CellStructure::local_particles(), and pos.
Referenced by add_long_range_force(), long_range_energy(), set_r_cut_and_tune_local(), and tune().
update_particle_forces()
void Scafacos::ScafacosContextCoulomb::update_particle_forces () const override virtual
Implements Scafacos::ScafacosContextBase.
Definition at line 106 of file ScafacosContext.cpp.
References cell_structure, coulomb, Scafacos::ScafacosContext::fields, CellStructure::local_particles(), and Coulomb_parameters::prefactor.
Referenced by add_long_range_force().
The documentation for this struct was generated from the following files:
ScafacosContext.hpp
ScafacosContext.cpp