ESPResSo: DomainDecomposition Struct Reference
DomainDecomposition Struct Reference
Structure containing the information about the cell grid used for domain decomposition.
#include <DomainDecomposition.hpp>
Public Member Functions
DomainDecomposition (boost::mpi::communicator comm, double range, const BoxGeometry &box_geo, const LocalBox< double > &local_geo)
const GhostCommunicator & exchange_ghosts_comm () const override
const GhostCommunicator & collect_ghost_force_comm () const override
Utils::Span< Cell * > local_cells () override
Utils::Span< Cell * > ghost_cells () override
Cell * particle_to_cell (Particle const &p) override
void resort (bool global, std::vector< ParticleChange > &diff) override
Utils::Vector3d max_cutoff () const override
Utils::Vector3d max_range () const override
boost::optional< BoxGeometry > minimum_image_distance () const override
Public Member Functions inherited from ParticleDecomposition
virtual ~ParticleDecomposition ()=default
Public Attributes
Utils::Vector3i cell_grid = {}
Grid dimensions per node.
Utils::Vector3d cell_size = {}
Cell size.
Utils::Vector3i cell_offset = {}
Offset in global grid.
Utils::Vector3i ghost_cell_grid = {}
linked cell grid with ghost frame.
Utils::Vector3d inv_cell_size = {}
inverse cell size =
boost::mpi::communicator m_comm
BoxGeometry m_box
LocalBox< double > m_local_box
std::vector< Cell > cells
std::vector< Cell * > m_local_cells
std::vector< Cell * > m_ghost_cells
GhostCommunicator m_exchange_ghosts_comm
GhostCommunicator m_collect_ghost_force_comm
Detailed Description
Structure containing the information about the cell grid used for domain decomposition.
The domain of a node is split into a 3D cell grid with dimension cell_grid. Together with one ghost cell layer on each side the overall dimension of the ghost cell grid is ghost_cell_grid. The domain decomposition enables one the use of the linked cell algorithm which is in turn used for setting up the Verlet list for the system. You can see a 2D graphical representation of the linked cell grid below.
Linked cells structure
2D representation of a linked cell grid: cell_grid = {4,4}, ghost_cell_grid = {6,6}
Each cell has 3^D neighbor cells. Since we deal with pair forces, it is sufficient to calculate only half of the interactions (Newton's law: action = reaction). We have chosen the upper half e.g. all neighbor cells with a higher linear index (for cell 14 they are marked in light blue). Caution: This implementation needs double sided ghost communication! For single sided ghost communication one would need some ghost-ghost cell interaction as well, which we do not need!
Definition at line 68 of file DomainDecomposition.hpp.
Constructor & Destructor Documentation
DomainDecomposition()
DomainDecomposition::DomainDecomposition (boost::mpi::communicator comm, double range, const BoxGeometry & box_geo, const LocalBox< double > & local_geo)
Definition at line 573 of file DomainDecomposition.cpp.
References anonymous_namespace{DomainDecomposition.cpp}::assign_prefetches(), m_collect_ghost_force_comm, m_exchange_ghosts_comm, and anonymous_namespace{DomainDecomposition.cpp}::revert_comm_order().
Member Function Documentation
collect_ghost_force_comm()
const GhostCommunicator& DomainDecomposition::collect_ghost_force_comm () const inline override virtual
Implements ParticleDecomposition.
Definition at line 97 of file DomainDecomposition.hpp.
References m_collect_ghost_force_comm.
exchange_ghosts_comm()
const GhostCommunicator& DomainDecomposition::exchange_ghosts_comm () const inline override virtual
Implements ParticleDecomposition.
Definition at line 94 of file DomainDecomposition.hpp.
References m_exchange_ghosts_comm.
ghost_cells()
Utils::Span<Cell *> DomainDecomposition::ghost_cells () inline override virtual
Implements ParticleDecomposition.
Definition at line 104 of file DomainDecomposition.hpp.
References m_ghost_cells, and Utils::make_span().
local_cells()
Utils::Span<Cell *> DomainDecomposition::local_cells () inline override virtual
Implements ParticleDecomposition.
Definition at line 101 of file DomainDecomposition.hpp.
References m_local_cells, and Utils::make_span().
Referenced by resort().
max_cutoff()
Utils::Vector3d DomainDecomposition::max_cutoff () const override virtual
Implements ParticleDecomposition.
Definition at line 265 of file DomainDecomposition.cpp.
References LocalBox< T >::length(), BoxGeometry::length(), m_box, m_local_box, and anonymous_namespace{Correlator.cpp}::min().
max_range()
Utils::Vector3d DomainDecomposition::max_range () const override virtual
Implements ParticleDecomposition.
Definition at line 273 of file DomainDecomposition.cpp.
References cell_size.
minimum_image_distance()
boost::optional<BoxGeometry> DomainDecomposition::minimum_image_distance () const inline override virtual
Implements ParticleDecomposition.
Definition at line 116 of file DomainDecomposition.hpp.
particle_to_cell()
Cell* DomainDecomposition::particle_to_cell (Particle const & p) inline override virtual
Implements ParticleDecomposition.
Definition at line 108 of file DomainDecomposition.hpp.
References ParticlePosition::p, and Particle::r.
Referenced by resort().
resort()
void DomainDecomposition::resort (bool global, std::vector< ParticleChange > & diff) override virtual
Implements ParticleDecomposition.
Definition at line 171 of file DomainDecomposition.cpp.
References D3Q19::c, Utils::Bag< T >::empty(), anonymous_namespace{DomainDecomposition.cpp}::fold_and_reset(), Utils::Bag< T >::insert(), local_cells(), m_box, m_comm, particle_to_cell(), runtimeErrorMsg, and Utils::Bag< T >::size().
Member Data Documentation
cell_grid
Utils::Vector3i DomainDecomposition::cell_grid = {}
Grid dimensions per node.
Definition at line 70 of file DomainDecomposition.hpp.
cell_offset
Utils::Vector3i DomainDecomposition::cell_offset = {}
Offset in global grid.
Definition at line 74 of file DomainDecomposition.hpp.
cell_size
Utils::Vector3d DomainDecomposition::cell_size = {}
Cell size.
Definition at line 72 of file DomainDecomposition.hpp.
Referenced by max_range().
cells
std::vector<Cell> DomainDecomposition::cells
Definition at line 83 of file DomainDecomposition.hpp.
ghost_cell_grid
Utils::Vector3i DomainDecomposition::ghost_cell_grid = {}
linked cell grid with ghost frame.
Definition at line 76 of file DomainDecomposition.hpp.
inv_cell_size
Utils::Vector3d DomainDecomposition::inv_cell_size = {}
inverse cell size =
See also
DomainDecomposition::cell_size ^ -1.
Definition at line 78 of file DomainDecomposition.hpp.
m_box
BoxGeometry DomainDecomposition::m_box
Definition at line 81 of file DomainDecomposition.hpp.
Referenced by max_cutoff(), and resort().
m_collect_ghost_force_comm
GhostCommunicator DomainDecomposition::m_collect_ghost_force_comm
Definition at line 87 of file DomainDecomposition.hpp.
Referenced by collect_ghost_force_comm(), and DomainDecomposition().
m_comm
boost::mpi::communicator DomainDecomposition::m_comm
Definition at line 80 of file DomainDecomposition.hpp.
Referenced by resort().
m_exchange_ghosts_comm
GhostCommunicator DomainDecomposition::m_exchange_ghosts_comm
Definition at line 86 of file DomainDecomposition.hpp.
Referenced by DomainDecomposition(), and exchange_ghosts_comm().
m_ghost_cells
std::vector<Cell *> DomainDecomposition::m_ghost_cells
Definition at line 85 of file DomainDecomposition.hpp.
Referenced by ghost_cells().
m_local_box
LocalBox<double> DomainDecomposition::m_local_box
Definition at line 82 of file DomainDecomposition.hpp.
Referenced by max_cutoff().
m_local_cells
std::vector<Cell *> DomainDecomposition::m_local_cells
Definition at line 84 of file DomainDecomposition.hpp.
Referenced by local_cells().
The documentation for this struct was generated from the following files:
DomainDecomposition.hpp
DomainDecomposition.cpp