ESPResSo: Scafacos::ScafacosContext Struct Reference
Scafacos::ScafacosContext Struct Reference
Encapsulation for the particle data needed by ScaFaCoS.
#include <ScafacosContext.hpp>
Public Member Functions
~ScafacosContext () override=default
void update_system_params () override
double get_pair_force (double dist) const override
double get_pair_energy (double dist) const override
std::string get_method_and_parameters () override
double get_r_cut () const override
Scafacos (std::string method, MPI_Comm comm, const std::string &parameters)
Public Member Functions inherited from Scafacos::ScafacosContextBase
virtual ~ScafacosContextBase ()=default
virtual void update_particle_data ()=0
Collect particle data in continuous arrays.
virtual void update_particle_forces () const =0
Write forces back to particles.
virtual double long_range_energy ()=0
Calculate long-range part of the energy.
virtual void add_long_range_force ()=0
Add long-range part of the forces to particles.
void add_pair_force (double q1q2, Utils::Vector3d const &d, double dist, Utils::Vector3d &force)
Add near-field pair force.
double pair_energy (double q1q2, double dist)
Calculate near-field pair energy.
Public Member Functions inherited from Scafacos::Scafacos
Scafacos (std::string method, MPI_Comm comm, const std::string &parameters)
~Scafacos ()
void parse_parameters (const std::string &s)
Parse parameter string.
std::string get_parameters ()
Get the parameters from the library.
std::string get_method ()
Get active method name.
void set_common_parameters (const double *box_l, const int *periodicity, int total_particles)
Set parameters common to all methods.
double pair_force (double dist) const
Calculate short range pair force if supported by the method.
double pair_energy (double dist) const
Get pair energy for near field contrib.
void run (std::vector< double > &charges, std::vector< double > &positions, std::vector< double > &fields, std::vector< double > &potentials)
Calculate the fields and potentials for charges.
void tune (std::vector< double > &charges, std::vector< double > &positions)
Tune parameters.
double r_cut () const
Get shortrange cutoff (0.0 if not supported)
void set_r_cut (double r_cut)
Set cutoff.
bool dipolar ()
Scafacos used for dipolar ia.
void set_dipolar (bool d)
Switch scafacos to dipolar ia.
Protected Attributes
std::vector< double > fields
Outputs.
std::vector< double > potentials
Additional Inherited Members
Static Public Member Functions inherited from Scafacos::Scafacos
static std::list< std::string > available_methods ()
Get a list of methods supported by the library.
Public Attributes inherited from Scafacos::Scafacos
FCS handle
Handle from the library.
bool has_near
Whether the method supports near field delegation.
const std::string method
The scafacos method name of this instance.
std::string m_last_parameters
The last parameters set.
bool m_dipolar
Scafacos used for dipolar ia.
Detailed Description
Encapsulation for the particle data needed by ScaFaCoS.
Definition at line 50 of file ScafacosContext.hpp.
Constructor & Destructor Documentation
~ScafacosContext()
Scafacos::ScafacosContext::~ScafacosContext () override default
Member Function Documentation
get_method_and_parameters()
std::string Scafacos::ScafacosContext::get_method_and_parameters () override virtual
Implements Scafacos::ScafacosContextBase.
Definition at line 60 of file ScafacosContext.cpp.
References Scafacos::Scafacos::get_method(), and Scafacos::Scafacos::get_parameters().
get_pair_energy()
double Scafacos::ScafacosContext::get_pair_energy (double dist) const inline override virtual
Implements Scafacos::ScafacosContextBase.
Definition at line 58 of file ScafacosContext.hpp.
References Scafacos::Scafacos::pair_energy().
get_pair_force()
double Scafacos::ScafacosContext::get_pair_force (double dist) const inline override virtual
Implements Scafacos::ScafacosContextBase.
Definition at line 55 of file ScafacosContext.hpp.
References Scafacos::Scafacos::pair_force().
get_r_cut()
double Scafacos::ScafacosContext::get_r_cut () const inline override virtual
Implements Scafacos::ScafacosContextBase.
Definition at line 62 of file ScafacosContext.hpp.
References Scafacos::Scafacos::r_cut().
Scafacos()
Scafacos::Scafacos::Scafacos
Definition at line 83 of file Scafacos.cpp.
update_system_params()
void Scafacos::ScafacosContext::update_system_params () override virtual
Implements Scafacos::ScafacosContextBase.
Definition at line 66 of file ScafacosContext.cpp.
References box_geo, cell_structure, comm_cart, Utils::Array< T, N >::data(), BoxGeometry::length(), CellStructure::local_particles(), BoxGeometry::periodic(), Scafacos::Scafacos::set_common_parameters(), and ParticleRange::size().
Member Data Documentation
fields
std::vector<double> Scafacos::ScafacosContext::fields protected
Outputs.
Definition at line 66 of file ScafacosContext.hpp.
Referenced by Scafacos::ScafacosContextCoulomb::add_long_range_force(), Scafacos::ScafacosContextDipoles::add_long_range_force(), Scafacos::ScafacosContextCoulomb::long_range_energy(), Scafacos::ScafacosContextDipoles::long_range_energy(), Scafacos::ScafacosContextCoulomb::update_particle_forces(), and Scafacos::ScafacosContextDipoles::update_particle_forces().
potentials
std::vector<double> Scafacos::ScafacosContext::potentials protected
Definition at line 66 of file ScafacosContext.hpp.
Referenced by Scafacos::ScafacosContextCoulomb::add_long_range_force(), Scafacos::ScafacosContextDipoles::add_long_range_force(), Scafacos::ScafacosContextCoulomb::long_range_energy(), Scafacos::ScafacosContextDipoles::long_range_energy(), and Scafacos::ScafacosContextDipoles::update_particle_forces().
The documentation for this struct was generated from the following files:
ScafacosContext.hpp
ScafacosContext.cpp