ESPResSo: ParticleObservables::traits< Particle > Struct Reference
ParticleObservables::traits< Particle > Struct Reference
Template specialization for Particle.
#include <ParticleTraits.hpp>
Public Member Functions
auto position (Particle const &p) const
auto velocity (Particle const &p) const
auto mass (Particle const &p) const
auto charge (Particle const &p) const
auto dipole_moment (Particle const &p) const
Detailed Description
Template specialization for Particle.
The traits mechanism is used to get indirect access to particle properties. This helps making the implementation of observables independent of the particle type.
Definition at line 31 of file ParticleTraits.hpp.
Member Function Documentation
charge()
auto ParticleObservables::traits< Particle >::charge (Particle const & p) const inline
Definition at line 42 of file ParticleTraits.hpp.
References Particle::p, and ParticleProperties::q.
dipole_moment()
auto ParticleObservables::traits< Particle >::dipole_moment (Particle const & p) const inline
Definition at line 43 of file ParticleTraits.hpp.
References Particle::calc_dip().
mass()
auto ParticleObservables::traits< Particle >::mass (Particle const & p) const inline
Definition at line 34 of file ParticleTraits.hpp.
References ParticleProperties::is_virtual, ParticleProperties::mass, and Particle::p.
position()
auto ParticleObservables::traits< Particle >::position (Particle const & p) const inline
Definition at line 32 of file ParticleTraits.hpp.
References ParticlePosition::p, and Particle::r.
Referenced by Observables::CylindricalDensityProfile::evaluate(), Observables::DensityProfile::evaluate(), Observables::CylindricalFluxDensityProfile::evaluate(), Observables::CylindricalLBFluxDensityProfileAtParticlePositions::evaluate(), Observables::CylindricalLBVelocityProfileAtParticlePositions::evaluate(), Observables::CylindricalVelocityProfile::evaluate(), Observables::FluxDensityProfile::evaluate(), Observables::BondAngles::evaluate(), Observables::ParticleDistances::evaluate(), Observables::CosPersistenceAngles::evaluate(), and Observables::BondDihedrals::evaluate().
velocity()
auto ParticleObservables::traits< Particle >::velocity (Particle const & p) const inline
Definition at line 33 of file ParticleTraits.hpp.
References Particle::m, and ParticleMomentum::v.
Referenced by Observables::ParticleBodyVelocities::evaluate(), Observables::CylindricalFluxDensityProfile::evaluate(), Observables::CylindricalVelocityProfile::evaluate(), and Observables::FluxDensityProfile::evaluate().
The documentation for this struct was generated from the following file:
ParticleTraits.hpp