ESPResSo: Scafacos::Scafacos Struct Reference
Scafacos::Scafacos Struct Reference
Abstraction of a method from the scafacos library.
#include <Scafacos.hpp>
Public Member Functions
Scafacos (std::string method, MPI_Comm comm, const std::string &parameters)
~Scafacos ()
void parse_parameters (const std::string &s)
Parse parameter string.
std::string get_parameters ()
Get the parameters from the library.
std::string get_method ()
Get active method name.
void set_common_parameters (const double *box_l, const int *periodicity, int total_particles)
Set parameters common to all methods.
double pair_force (double dist) const
Calculate short range pair force if supported by the method.
double pair_energy (double dist) const
Get pair energy for near field contrib.
void run (std::vector< double > &charges, std::vector< double > &positions, std::vector< double > &fields, std::vector< double > &potentials)
Calculate the fields and potentials for charges.
void tune (std::vector< double > &charges, std::vector< double > &positions)
Tune parameters.
double r_cut () const
Get shortrange cutoff (0.0 if not supported)
void set_r_cut (double r_cut)
Set cutoff.
bool dipolar ()
Scafacos used for dipolar ia.
void set_dipolar (bool d)
Switch scafacos to dipolar ia.
Static Public Member Functions
static std::list< std::string > available_methods ()
Get a list of methods supported by the library.
Public Attributes
FCS handle
Handle from the library.
bool has_near
Whether the method supports near field delegation.
const std::string method
The scafacos method name of this instance.
std::string m_last_parameters
The last parameters set.
bool m_dipolar
Scafacos used for dipolar ia.
Detailed Description
Abstraction of a method from the scafacos library.
Definition at line 34 of file Scafacos.hpp.
Constructor & Destructor Documentation
Scafacos()
Scafacos::Scafacos::Scafacos (std::string method, MPI_Comm comm, const std::string & parameters)
Definition at line 83 of file Scafacos.cpp.
References handle_error.
~Scafacos()
Scafacos::Scafacos::~Scafacos ()
Definition at line 97 of file Scafacos.cpp.
Member Function Documentation
available_methods()
std::list< std::string > Scafacos::Scafacos::available_methods () static
Get a list of methods supported by the library.
Definition at line 40 of file Scafacos.cpp.
dipolar()
bool Scafacos::Scafacos::dipolar () inline
Scafacos used for dipolar ia.
Definition at line 91 of file Scafacos.hpp.
get_method()
std::string Scafacos::Scafacos::get_method ()
Get active method name.
Definition at line 38 of file Scafacos.cpp.
Referenced by Scafacos::ScafacosContext::get_method_and_parameters().
get_parameters()
std::string Scafacos::Scafacos::get_parameters ()
Get the parameters from the library.
Definition at line 37 of file Scafacos.cpp.
Referenced by Scafacos::ScafacosContext::get_method_and_parameters().
pair_energy()
double Scafacos::Scafacos::pair_energy (double dist) const inline
Get pair energy for near field contrib.
Definition at line 59 of file Scafacos.hpp.
Referenced by Scafacos::ScafacosContext::get_pair_energy().
pair_force()
double Scafacos::Scafacos::pair_force (double dist) const inline
Calculate short range pair force if supported by the method.
Definition at line 48 of file Scafacos.hpp.
Referenced by Scafacos::ScafacosContext::get_pair_force().
parse_parameters()
void Scafacos::Scafacos::parse_parameters (const std::string & s)
Parse parameter string.
Definition at line 99 of file Scafacos.cpp.
References handle_error.
r_cut()
double Scafacos::Scafacos::r_cut () const
Get shortrange cutoff (0.0 if not supported)
Definition at line 104 of file Scafacos.cpp.
Referenced by Scafacos::ScafacosContext::get_r_cut(), Scafacos::ScafacosContextCoulomb::set_r_cut_and_tune_local(), and Scafacos::ScafacosContextCoulomb::tune().
run()
void Scafacos::Scafacos::run (std::vector< double > & charges, std::vector< double > & positions, std::vector< double > & fields, std::vector< double > & potentials)
Calculate the fields and potentials for charges.
Definition at line 119 of file Scafacos.cpp.
References handle_error.
Referenced by Scafacos::ScafacosContextCoulomb::add_long_range_force(), and Scafacos::ScafacosContextCoulomb::long_range_energy().
set_common_parameters()
void Scafacos::Scafacos::set_common_parameters (const double * box_l, const int * periodicity, int total_particles)
Set parameters common to all methods.
Definition at line 158 of file Scafacos.cpp.
References handle_error.
Referenced by Scafacos::ScafacosContext::update_system_params().
set_dipolar()
void Scafacos::Scafacos::set_dipolar (bool d)
Switch scafacos to dipolar ia.
Definition at line 178 of file Scafacos.cpp.
Referenced by Scafacos::set_parameters_coulomb_worker(), and Scafacos::set_parameters_dipoles_worker().
set_r_cut()
void Scafacos::Scafacos::set_r_cut (double r_cut)
Set cutoff.
Definition at line 113 of file Scafacos.cpp.
Referenced by Scafacos::ScafacosContextCoulomb::set_r_cut_and_tune_local().
tune()
void Scafacos::Scafacos::tune (std::vector< double > & charges, std::vector< double > & positions)
Tune parameters.
Definition at line 152 of file Scafacos.cpp.
References handle_error.
Referenced by Scafacos::ScafacosContextCoulomb::set_r_cut_and_tune_local(), and Scafacos::ScafacosContextCoulomb::tune().
Member Data Documentation
handle
FCS Scafacos::Scafacos::handle
Handle from the library.
Definition at line 97 of file Scafacos.hpp.
has_near
bool Scafacos::Scafacos::has_near
Whether the method supports near field delegation.
Definition at line 99 of file Scafacos.hpp.
Referenced by Scafacos::ScafacosContextCoulomb::tune().
m_dipolar
bool Scafacos::Scafacos::m_dipolar
Scafacos used for dipolar ia.
Definition at line 106 of file Scafacos.hpp.
m_last_parameters
std::string Scafacos::Scafacos::m_last_parameters
The last parameters set.
Definition at line 103 of file Scafacos.hpp.
method
const std::string Scafacos::Scafacos::method
The scafacos method name of this instance.
Definition at line 101 of file Scafacos.hpp.
The documentation for this struct was generated from the following files:
Scafacos.hpp
Scafacos.cpp