ESPResSo: Scafacos::ScafacosContextBase Struct Reference
Scafacos::ScafacosContextBase Struct Reference abstract
Public interface to the ScaFaCoS context.
#include <ScafacosContextBase.hpp>
Public Member Functions
virtual ~ScafacosContextBase ()=default
virtual void update_particle_data ()=0
Collect particle data in continuous arrays.
virtual void update_particle_forces () const =0
Write forces back to particles.
virtual double long_range_energy ()=0
Calculate long-range part of the energy.
virtual void add_long_range_force ()=0
Add long-range part of the forces to particles.
void add_pair_force (double q1q2, Utils::Vector3d const &d, double dist, Utils::Vector3d &force)
Add near-field pair force.
double pair_energy (double q1q2, double dist)
Calculate near-field pair energy.
virtual void update_system_params ()=0
Reinitialize number of particles, box shape and periodicity.
virtual double get_r_cut () const =0
virtual double get_pair_force (double dist) const =0
virtual double get_pair_energy (double dist) const =0
virtual std::string get_method_and_parameters ()=0
Detailed Description
Public interface to the ScaFaCoS context.
Implementations of this class will store particle positions and charges/dipoles in flat arrays, as required by ScaFaCoS, as well as the output arrays.
Definition at line 47 of file ScafacosContextBase.hpp.
Constructor & Destructor Documentation
~ScafacosContextBase()
virtual Scafacos::ScafacosContextBase::~ScafacosContextBase () virtual default
Member Function Documentation
add_long_range_force()
virtual void Scafacos::ScafacosContextBase::add_long_range_force () pure virtual
Add long-range part of the forces to particles.
Implemented in Scafacos::ScafacosContextDipoles, and Scafacos::ScafacosContextCoulomb.
Referenced by Dipole::calc_long_range_force(), and Coulomb::calc_long_range_force().
add_pair_force()
void Scafacos::ScafacosContextBase::add_pair_force (double q1q2, Utils::Vector3d const & d, double dist, Utils::Vector3d & force) inline
Add near-field pair force.
Definition at line 58 of file ScafacosContextBase.hpp.
References force, get_pair_force(), and get_r_cut().
Referenced by Coulomb::central_force().
get_method_and_parameters()
virtual std::string Scafacos::ScafacosContextBase::get_method_and_parameters () pure virtual
Implemented in Scafacos::ScafacosContext.
Referenced by Scafacos::get_method_and_parameters().
get_pair_energy()
virtual double Scafacos::ScafacosContextBase::get_pair_energy (double dist) const pure virtual
Implemented in Scafacos::ScafacosContext.
Referenced by pair_energy().
get_pair_force()
virtual double Scafacos::ScafacosContextBase::get_pair_force (double dist) const pure virtual
Implemented in Scafacos::ScafacosContext.
Referenced by add_pair_force().
get_r_cut()
virtual double Scafacos::ScafacosContextBase::get_r_cut () const pure virtual
Implemented in Scafacos::ScafacosContext.
Referenced by add_pair_force(), Coulomb::cutoff(), and pair_energy().
long_range_energy()
virtual double Scafacos::ScafacosContextBase::long_range_energy () pure virtual
Calculate long-range part of the energy.
Implemented in Scafacos::ScafacosContextDipoles, and Scafacos::ScafacosContextCoulomb.
Referenced by Dipole::calc_energy_long_range(), and Coulomb::calc_energy_long_range().
pair_energy()
double Scafacos::ScafacosContextBase::pair_energy (double q1q2, double dist) inline
Calculate near-field pair energy.
Definition at line 68 of file ScafacosContextBase.hpp.
References get_pair_energy(), and get_r_cut().
Referenced by Coulomb::pair_energy().
update_particle_data()
virtual void Scafacos::ScafacosContextBase::update_particle_data () pure virtual
Collect particle data in continuous arrays.
Implemented in Scafacos::ScafacosContextDipoles, and Scafacos::ScafacosContextCoulomb.
update_particle_forces()
virtual void Scafacos::ScafacosContextBase::update_particle_forces () const pure virtual
Write forces back to particles.
Implemented in Scafacos::ScafacosContextDipoles, and Scafacos::ScafacosContextCoulomb.
update_system_params()
virtual void Scafacos::ScafacosContextBase::update_system_params () pure virtual
Reinitialize number of particles, box shape and periodicity.
Implemented in Scafacos::ScafacosContext.
Referenced by Dipole::on_boxl_change(), Coulomb::on_boxl_change(), and on_periodicity_change().
The documentation for this struct was generated from the following file:
ScafacosContextBase.hpp