ESPResSo: tuning.hpp File Reference
tuning.hpp File Reference
Functions
double time_force_calc (int int_steps)
Measure the time for some force calculations.
void tune_skin (double min_skin, double max_skin, double tol, int int_steps, bool adjust_max_skin)
Set the optimal skin between min_skin and max_skin by bisection to tolerance tol.
Detailed Description
This contains a timing loop for the force calculation.
Implementation in tuning.cpp.
Definition in file tuning.hpp.
Function Documentation
time_force_calc()
double time_force_calc (int int_steps)
Measure the time for some force calculations.
Actually performs mpi_integrate (0). This times the force calculation without propagating the system. It therefore does not include e.g. Verlet list updates.
Parameters
int_steps Number of integration steps.
Returns
Time per integration in milliseconds.
Definition at line 42 of file tuning.cpp.
References Utils::Statistics::RunningAverage< Scalar >::add_sample(), Utils::Statistics::RunningAverage< Scalar >::avg(), mpi_integrate(), runtimeWarningMsg, and Utils::Statistics::RunningAverage< Scalar >::sig().
Referenced by dp3m_mcr_time(), mmm1d_tune(), p3m_mcr_time(), and Scafacos::time_r_cut().
tune_skin()
void tune_skin (double min_skin, double max_skin, double tol, int int_steps, bool adjust_max_skin)
Set the optimal skin between min_skin and max_skin by bisection to tolerance tol.
Definition at line 94 of file tuning.cpp.
References b, box_geo, cell_structure, BoxGeometry::length(), CellStructure::max_cutoff(), maximal_cutoff(), anonymous_namespace{Correlator.cpp}::min(), mpi_set_skin(), and time_calc().